.gitignore
Makefile.am
commands.c
configure.ac
dotlock.c
globals.h
init.c
muttlib.c
sendlib.c

The original Mutt version string came with only a version number.
However, in NeoMutt, the versioning is done solely on the release date.
Hence, change how the version string is printed to reflect this change.

Fix the NeoMutt version string

---

hook.c

Fixes #347
In both mutt_timeout_hook and mutt_startup_shutdown_hook, we iterate on
the list of hooks and try to execute the right ones, always using the
same buffer. The buffer must be free'd after all the hooks have been
checked and not after the first hook which fails. This also removes a
memory leak, because the buffer was never freed if no hook failed.

Remove two use-after free in global hooks

---

newsrc.c

When converting NNTP to use mutt_mkdir() a line of code got lost.
Commit: 6800b2a nntp: use mutt_mkdir
Closes #338

fix: bug introduced by mkdir changes

---

crypt-gpgme.c

This requires gpgme >= 1.8.1, which exposes a new "redraw" status flag.
On older versions, fallback to always redraw if pinentry was potentially called.
Thanks to Werner Koch for the hints!
Closes #333

If possible, only redraw after gpgme has invoked pinentry

---

curs_main.c
imap/imap.c
imap/imap.h
imap/imap_private.h
imap/message.c
imap/util.c
mx.c

1. introduce private `int imap_check (IMAP_DATA* idata, int force); `
2. turn `int imap_check_mailbox (CONTEXT* ctx, int* index_hint, int force);` into a wrapper around 1.
3. refactor and simplify `imap_keepalive`
4. remove some useless (and dangerous) casts
5. remove some unused parameters

Simplify imap_keepalive + some cleanup

---

imap/command.c
imap/imap_private.h

Try (once) to reconnect after an IMAP failure

---

alias.c
globals.h
init.c
init.h

Uses the first loaded muttrc file as default for alias file.
This partially reverts commit 83f7558efab3dcd7b7e227a727ef95f711363f50.
fixes #378
Signed-off-by: Guyzmo <guyzmo+github+pub@m0g.net>

Reverts making AliasFile into a list_t

---

hcache-kc.c

Obtained from https://dev.mutt.org/hg/mutt/rev/09bb4a62ceb1
Closes #383

Release KyotoCabinet data with kcfree()

---

globals.h
handler.c
init.c
init.h

This pull request adds an option to ignore the multipart/alternative flag in emails. The reason for that is that there exist a lot of mailers that misuse that flag and doesn't have the same contents in the "alternative" part. 
Thus, clients that make the "wrong" choice in the alternative will see unhelpful or incomplete data and may miss important informations if he doesn't think to look at the attachment part.
NB: Is the documentation automatically generated from the comments?

Add an option to show multipart/alternative

---

init.c
mutt_notmuch.c

Fixes crashes if the notmuch database has an empty tag. See #393

Notmuch sending bad info

---

attach.c
crypt-gpgme.c
edit.c
init.c
mbox.c
pgp.c
query.c
recvcmd.c
send.c
sendlib.c
smime.c

There are about 25 small changes to prevent resource leaks.
As an experiment, I've made two commits:
1. Fix leaks and add CID comments (d0699e9)
2. Remove the CID comments
If you'd like to reference the Coverity Defect ID you can look at just the first commit: d0699e9
The commits will be squashed before merging.
Coverity reports that the changes are successful :-)
@neomutt/reviewers Please Review.

Fix resource leaks on error paths (coverity)

---

menu.c

Hi,
This change allow to use untransformed tag for index-tag color.
Cheers,

notmuch: Allow to use untransformed tag for color

---

configure.ac
getdomain.c

When getaddrinfo_a is avialable we can use it to set a timeout for the
dns resolution. This avoid to have mutt that freeze on startup when the
network connection isn't working and the hosts/hostname misconfigured on
the system.
Closes #176

Use getaddrinfo_a if possible

---

mutt_socket.c

I extended my previous attempt by adding @guyzmo's suggestion for handling SigInt. I've tested this with a mock IMAP server written in Python. It works and is able to abort a slow IMAP fetch.

handle sigint within socket operations

---

.editorconfig

* Our code contains a lot of whitespace issues, so every commit is
polluted by whitespace changes with the current editorconfig. However, i'm not sure whether disabling `trim_trailing_whitespace` is the best way to go until the codebase has been formatted with clang-format (which will also fix trailing whitespace)
* Add support for Makefile.am, xml, vim and yml files.
@flatcap what do you think?

editorconfig: support for new files, fix whitespace

---

handler.c
muttlib.c

This change makes attachment view using mailcap for everything
not text/plain.
And in pager, don't assume text/* are human readable except text/plain.
This can still be overridable with auto_view.
Closes #430

attachment/pager: Use mailcap for test/* except plain

---

pager.c

In pager, the index refresher uses the current count as oldcount.
Closes #305

Fix uncollapse_new in pager

---

browser.c

I upgraded one of my stable systems to stretch and noticed that when
changing the directory with 'c', there was some garbage at the end of
the string in the prompt. I've not noticed that before on my main
amd64 system, but this stable system is i386, so different alignment
and word size that can affect this kind of thing.
I tracked it down to an unescaped string handling.
Debian [BTS#857433](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=857433)

fix: Garbage in chdir prompt due to unescaped string

---

hdrline.c
init.h

This PR adds a new sequence `%K` to `$index_format`.
It returns the list to which the letter was sent. But unlike `%B`, `%K` will remain empty if no list is present. The sequence supports conditional formatting (`%?K?...`).
* Are there points in the code the reviewer needs to double check?
* Why was this PR needed?
This PR allows the user to create a column dedicated to list name (_if any_) in `$index_format`.
* Screenshots (if relevant)
The following screenshot uses:
```
$index_format = "%4C (%4c) %Z %?GI?%GI& ? %[%d/%b]  %-20.19F %?K?%15.14K&               ? %?M?(%3M)&     ? %?X?¤& ? %s %> %?g?%g?"
```
* Does this PR meet the acceptance criteria?
[doc/manual.xml.head](https://www.neomutt.org/guide/) for that)
* What are the relevant issue numbers?
_N/A_

index_format: add support of %K

---

doc/manual.xml.head

At the moment, the documentation contains links to the mutt mailinglists. As we have our own, we should link to them, which is what this PR is fixing.
**Questions:**
* @flatcap Whats the command you've used to indent the docbook? (including all options)
* is there a command to subscribe to the mailinglist without using the [form on the website](http://mailman.neomutt.org/mailman/listinfo/neomutt-users-neomutt.org), like sending a mail to a request mail address?
* What are the relevant issue numbers?
[neomutt.github.io#30](https://github.com/neomutt/neomutt.github.io/issues/30)

doc: use neomutt mailinglist

---

doc/Makefile.am

The input for manual.txt is manual.html which is UTF8 encoded. Now
forcing manual.txt to be ascii leads to all sorts of "?" in the ascii
file, which is not nice. If we have UTF8 input we should also use UTF8
for the output.
Moved w3m to be the default to generate UTF8 manual.txt. If you prefer
manual.txt to be ascii the fallbacks lynx or elinks will still produce
plain ascii.
Signed-off-by: Stefan Assmann <sassmann@kpanic.de>
* Does this PR meet the acceptance criteria?
[doc/manual.xml.head](https://www.neomutt.org/guide/) for that)

use w3m as default for generating UTF8 manual.txt

---

init.c
pgp.c
protos.h

* **What does this PR do?** 
* the `overwrite` parameter only holds `1`/ `0`
* and has a boolean meaning in the context
Therefore i think changing the type makes sense.

change 1/0 int parameter to boolean

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md

* PR template:
* made structural questions bold to contrast it from the actual
PR description.
* add note that acceptance criteria can be removed when the PR is
submitted. Its only meant as a reminder.
* fixed manual link.
* CONTRIBUTING.md:
* ~~removed Note that the first line of git commits should be 50
characters or less - the consensus seems to not care about that.~~
* wrap text at 80 characters.
* Why was this PR needed?
* text boxes to click on are not useful when PR's are submitted (they are mostly empty)
* ~~Some of the git commits by active contributors exceed 50 characters, therefore I guess the consensus is rather to write clear commit messages than to keep the first line below 50 characters.~~
* there's no real reason (imho) to keep the acceptance …

github: improve PR template and CONTRIBUTING.md

---

Makefile.am
configure.ac
hdrline.c
imap/message.c
mutt_ssl_gnutls.c
nntp.c
version.c

Cleans up configure.ac to avoid messing with `MUTTLIBS` and `LIBS` in confusing ways, build notmuch the same way as other mutt's components, remove dead code related to configure symbols that are never defined.
* Are there points in the code the reviewer needs to double check?
Making sure that the `HAVE_` symbols are really not defined anywhere and that the changes to configure.ac don't break anything.
* Why was this PR needed?
Improve code readability by removing dead code and uniformize configure.ac and Makefile.am.

configure: uniformize notmuch and remove dead code

---

configure.ac
crypt_gpgme.c
crypt_mod_pgp_gpgme.c

RHEL6 is still using GPGME 1.1.8, which doesn't have the function
`gpgme_op_export_keys`.  Revert the GPGME requirement to 1.1.0 and put
back the #ifdef's around the missing function.
Note: The improvements to `configure.ac` are still there.
@neomutt/reviewers Please review

build: change gpgme requirement back to 1.1.0

---

configure.ac
version.c

* **What does this PR do?** Completely removes the `--enable-mailtool` configure flag.
* **Why was this PR needed?** It looks legacy. However I have not found much evidence about its legacy - still i doubt the contrary.
* **What are the relevant issue numbers?** #389 

remove --enable-mailtool configure option

---

configure.ac

Issue: #585
Adds a check to configure.ac so that if `waddnwstr` cannot be found, the configure phase fails and the user is not left with link errors.

Fail early if ncursesw cannot be found

---

doc/Makefile.am

Fix build issue caused by following commits:
https://github.com/neomutt/neomutt/commit/fce65a1fa5a6a55d58d6810c80c3782d5ec637a3#diff-8d3e8f7411beefc4b162f0d8a5622353L109
https://github.com/neomutt/neomutt/commit/3c3e57dca57cbc8f5c3c84779a77fd60b819b10d#diff-8d3e8f7411beefc4b162f0d8a5622353L126
* **Why was this PR needed?**
Build failed on OS X 10.6.
See: https://build.macports.org/builders/ports-10.6_i386_legacy-builder/builds/22817
With patch: https://build.macports.org/builders/ports-10.6_i386_legacy-builder/builds/22843
macports/macports-ports#498

build: allow xsltproc and w3m calls to fail

---

contrib/vim-keys/vim-keys.rc

Sets mappings to `noop` before overwriting them to prevent warnings.
No.
* **Why was this PR needed?**
Changes to key bindings in release 2017-06-02.
#583

unbind mappings before overwriting in vim-keys

---

ncrypt/crypt.c

On multi folder mailbox setup and without a set 'From:' line in
~/.muttrc the mutt crash with SIGSEGV on a NULL pointer at
msg->env->from
Fixes: #577
@neomutt/reviewers please review

Fix crash if no from is set or founds

---

INSTALL

In doc/, there is no file named devel-note.txt.Actually, this is  harmless.As @flatcap  said, we have't modify the INSTALL file yet.
It's aim to fix a doc bug.But it is only a small reference missing.
It is such small fix even i hesitate to pull request.I appreciate @flatcap help me to improve the commet
* **Why was this PR needed?**
Actually, i fix a reference missing in INSTALL, and i hope i can continue to improve it.
Details is displayed in my comment. …

docs: fix references in INSTALL

---

ncrypt/crypt.c
nntp.c
parse.c

ncrypt/crypt.c
CID 170494:  Resource leaks  (RESOURCE_LEAK)
Variable "from" going out of scope leaks the storage it points to.
nntp.c
CID 170495:  Uninitialized variables  (UNINIT)
Declaring variable "buf" without initializer.
parse.c
CID 76957:  Error handling issues  (NEGATIVE_RETURNS)
"loc" is passed to a parameter that cannot be negative.

Fix latest coverity issues

---

browser.c
buffy.c
buffy.h
init.c
init.h
mutt_notmuch.c
protos.h
sidebar.c

NotMuch kept its mailboxes in a separate list, `VirtIncoming` rather than `Incoming`.
This lead to some code duplication and complex logic in the sidebar.
1. be36e9f tidy some buffy code
2. c58c838 split mutt_parse_mailboxes into mutt_parse_unmailboxes
3. 5dca538 drop VirtIncoming
From a user's point-of-view nothing has changed, you still use `<sidebar-toggle-virtual>` to switch between normal and virtual mailboxes.  (For now)
I've tested:
- adding normal mailboxes
- removing a single normal mailbox by shortcut `=mailbox`
- removing a single normal mailbox by path `/home/user/mail/mailbox`
- removing all normal mailboxes `*`
- adding virtual mailboxes
- removing a single virtual mailbox by description `neomutt`
- removing a single virtual mailbox by short path `notmuch://?query=neomutt`
- …

notmuch: drop VirtIncoming

---

curs_main.c
mutt_notmuch.c
mutt_notmuch.h

If the message is no longer in the current query after modifying
the label it will be hidden as before, but if it is in the current
query (again), it will be unhidden.
Related to #601

make modify-labels-then-hide hide or unhide

---

ncrypt/crypt_gpgme.c

- gpgsm ends the session after the decrypt error, so restart gpgsm when retrying with "maybe_signed".
- evolution sends encrypted + signed S/MIME mails with non-detached signatures

fix gpgme S/MIME non-detached signature handling

---

mutt_notmuch.c
url.c
url.h

Encodes URIs created in nm_uri_from_query using url_pct_encode. This means url_pct_encode is no longer static. This violates the coding style, as this function is now global but doesn't start with 'mutt_'. However, leaving 'mutt_' off seems to be consistent with the other url functions. Can change this if desired.
`url_pct_encode` now also encodes ampersands (`&`s). As `url_pct_encode` is only used in two other places, where it encodes either usernames or passwords, this seems valid.
Addresses issue #603

Encode URIs created with nm_uri_from_query

---

curs_lib.c

This patch fixes the leak of index line attributes on the next line due to the truncation of the output buffer based on terminal number of columns, that forgets to include escape sequence from the end of the input buffer (#664). Characters from an escape sequence have w=0, so they'll continue to be added to the output buffer.

Fix truncated formating

---

hcache/mutt_md5.c

Fixes #706
Including `lib/lib.h` means we bring in dependency on gettext.

Fix includes for mutt_md5

---

color.c

we call use_default_colors() when parsing colors in rc files only, and unconditionally when defining the color of the tree element, because the foreground color of the tree element may be combined dynamically with the default background color of another element, not explicitely defined in a rc file. This patch fixes a bug visible with some versions of the ncurses library: use_default_colors() was used too late, and generated color leakage effects. (#689)

color: call use_default_colors() in a single location

---

color.c
curs_lib.c

#_mutt_enter_fname: verify that flag is not zero
The flag argument in the _mutt_enter_fname function might not be                                                                                                                          
zero (e.g. in the definition of the mutt_enter_vfolder function, see                                                                                                                      
protos.h:297).                                                                                                                                                                            
This fixes issue #707, the issue was introduced in 43b949fbafe2e08c0cb90e5bc39a730201b8a0c4

curs_lib.c: _mutt_enter_fname fix

---

configure.ac

* Remove old checks that are not relevant anymore
* Group some `AC_ARG_WITH` in the same section
* Document a bit `--with-slang` / `--with-ncurses` interaction
* Group the generation of `OPS` in one place

Small cleanups to configure.ac

---

alias.c
browser.c
commands.c
compose.c
curs_lib.c
curs_main.c
edit.c
handler.c
imap/browse.c
main.c
menu.c
muttlib.c
ncrypt/crypt_gpgme.c
ncrypt/pgp.c
ncrypt/smime.c
pager.c
pattern.c
query.c
recvattach.c

This fixes a compilation error because of missing libintl.h on systems
without gettext.

Only include libintl.h if ENABLE_NLS is defined

---

curs_main.c

Solaris needs `term.h` for `tigetstr()`, but `term.h` doesn't always live in `/usr/include`
The only tests that need to be done are:
- Does Ncurses compile?
- Does Slang compile?
It works in Fedora and Debian, but I'd appreciate feedback for any systems you can test.
/cc @0-wiz-0

include term.h from wherever we find ncurses.h

---

addrbook.c
alias.c
buffy.c
charset.c
commands.c
complete.c
copy.c
curs_lib.c
curs_main.c
doc/makedoc.c
edit.c
from.c
handler.c
hcache/hcache.c
headers.c
help.c
hook.c
imap/auth_gss.c
imap/message.c
imap/util.c
init.c
keymap.c
lib/date.c
lib/file.c
lib/string.c
mbox.c
menu.c
mh.c
mutt_sasl.h

When saving a email, selecting a maildir directory should override the setting of $mbox_type.
- default mailbox (`$mbox_type`) is set to `mbox`
- save an email to a **Maildir** directory with a trailing '/'
Before #551, NeoMutt would do the "right thing" and safe it in Maildir format.
Since, it complains: '=bar/' is a directory, need a filename for mbox.
By trimming the trailing '/' from the completed name, means:
- maildirs are selected correctly
- non-existent paths respect `$mbox_type`
Fixes #719

trim trailing slash from completed dirs

---

configure.ac

This fixes the build on NetBSD 7.1_RC2 with curses from base (no ncurses package).

Accept curses.h as a valid curses header

---

contrib/guix-neomutt.scm

guix-neomutt.scm can be used to build the git checkout of neomutt at HEAD without hash checking in the build environment of GNU Guix. This is similar to what other software packages already do, like Mediagoblin, GNUnet, etc. There's no formalized way how to do it yet, but it helps with development on those platforms.
for that)
- Added [doxygen code …

contrib: Add guix-neomutt.scm.

---

curs_main.c
imap/imap.c
mutt_notmuch.c
mutt_tags.c
mutt_tags.h
mx.h

In notmuch editor we was passing sizeof(buf) with buf a char* with an
unknown allocated size.
In imap, we have assumed/hardcoded LONGSTRING. That's true, but we
should not do that.
edit_msg_tags() now takes the buflen as parameter so the root caller
can pass the size of the buffer.

tags: always pass correct buffer length

---

imap/imap.c

In imap_commit_message_tags() cmd is not freed in case of error.

imap: fix memory leak

---

doc/manual.xml.head
init.c
muttlib.c

Some people are still using this dir.
It will be deprecated in the future.
Also, drop the dated/versioned config files.
Nobody was using them.
~/.mutt/neomutt-20170912
for that)
- Added [doxygen code documentation](https://www.neomutt.org/dev/doxygen)
- Code follows the [style …

restore ~/.config/mutt to config search path

---

browser.c
hdrline.c
imap/command.c
imap/imap.c
init.c
mh.c
pattern.c
po/fr.po
pop.c

There's an off-by-one buffer overflow in the `add_index_color()` function.
To reproduce, rebuild the package with `-fsanitize=address` and run:
```console
$ echo H4sIAAAAAAACA3Mrys9VCE9NUfDLL1MwUDCwUjDgCi5NykpNLrEywAa+jALqAS4AS4nUHH8BAAA= | base64 -d | gzip -d > overflow.822
$ neomutt -R -f overflow.822 2>&1 >/dev/null | cat
=================================================================
==7367==ERROR: AddressSanitizer: stack-buffer-overflow on address 0xbfea8870 at pc 0x80127ec4 bp 0xbfea78e8 sp 0xbfea78dc
WRITE of size 1 at 0xbfea8870 thread T0
#0 0x80127ec3 in add_index_color .../neomutt/hdrline.c:181
#1 0x8012d2db in hdr_format_str .../neomutt/hdrline.c:1058
#2 0x80199788 in mutt_expando_format .../neomutt/muttlib.c:1355
#3 0x80130e27 in _mutt_make_string .../neomutt/hdrline.c:1358 …
```

Fix off-by-one buffer overflow in add_index_color

---

browser.c
hdrline.c
imap/command.c
imap/imap.c
init.c
mh.c
mutt_idna.c
pattern.c
po/fr.po
pop.c

NeoMutt's getting confused when an `Address->mailbox` contains an empty string.
I'll see if I can find where that's happening.
This commit fixes the immediate problem.
This problem also occurs in mutt-1.9.0.
Fixes #778

fix: crash in mbox_to_udomain

---

browser.c
hdrline.c
imap/command.c
imap/imap.c
init.c
lib/string.c
mh.c
mutt_idna.c
pattern.c
po/fr.po
pop.c
sendlib.c

- Make `mutt_substrdup()` more robust
- Protect a few `printf`s against `NULL` args

fix: crash in mutt_substrdup

---

browser.c
globals.h
hdrline.c
imap/command.c
imap/imap.c
init.c
lib/string.c
mh.c
mutt_idna.c
pattern.c
po/fr.po
pop.c
sendlib.c

This is a buffer overrun.
The mime type was being looked up in the BodyTypes table, but there wasn't an entry for TYPEANY.
Fixes #784

fix: crash looking up mime body type

---

attach.h
compose.c
menu.c
mutt_menu.h
pager.c
recvattach.c
recvcmd.c

First PR of hopefully a series ;)
First commits are very granular, later ones are a bit more packed, please
tell which is more appropriate.
If rebasing is needed, e.g. unify more commits, just notify me.
Refactors `int -> bool` in `attach.h` and it's deps.
Strips leading space e.g. `foo ()` -> `foo()`, splits too long prototypes to match ~90 chars
Yes
* `struct Menu`s `tagprefix` changed from `int` to `bool`.
I checked all occurrences, and only found boolean uses of it.
* `static int can_print()` in `recvattach.c` now returns `bool`
* `static short check_can_decode()` in `recvcmd.c` now returns `bool`
#774

Devel/issue 774 attach.h

---

bcache.c
bcache.h
imap/message.c
nntp.c
pop.c

Next is `bcache.h`. This only affects `mutt_bcache_put()`s `tmp` flag.
Affected files
* `bcache.c` -> `mutt_bcache_put()`
* `bcache.h` -> `mutt_bcache_put();`
* `imap/message.c` -> `msg_cache_put()`
* `nntp.c` -> `nntp_open_message()`
* `pop.c` -> `pop_fetch_message()` -> if can use body cache
Refactors bcache.h to make use of `bool`
Probably not
#774
* **Further mentions**
`int mutt_bcache_exists()` may return `bool`, as it answers the question: "Does bcache exists? Y/N"

devel/issue 774 bcache.h transit to `bool`

---

Makefile.am
configure.ac
doc/Makefile.am

- 45994318 restore tabs in configure.ac
No functional changes
- 2d67eab8 fix out-of-tree build
Make sure the built items in /doc are installed
- 91837478 stop yes/no include dirs
Stop configure from suggesting '-Iyes/include' or '-Lno/lib'
I tested the last commit using:
- `./configure `
- `./configure --with-curses`
- `./configure --with-curses=yes`
- `./configure --with-curses=no`
- `./configure --with-curses=/usr/local`
- `./configure --without-curses`

Fix some problems with autoconf

---

init.h

Aligns all function prototypes of commands to make it more consistent.
No
None
* **Further proposal**
It may be nicer to break the Coding-Style-Rule "No space between function name and `(`" here,
as all prototypes only differ in the function name. It also fits, as all `struct`s and `#def`s are nicely aligned.

spacing: Align function prototypes in init.h

---

mutt_notmuch.c
mutt_notmuch.h

next up is `mutt_notmuch.h`
Affected prototypes
* nm_longrun_init()
Affected static functions in `mutt_notmuch.c`
* append_message()
* append_replies()
* append_thread()
* do_database_open()
* get_db()
* get_query()
* get_query_string()
* is_longrun()
* read_mesgs_query()
* read_threads_query()
Refactors `mutt_notmuch.h` to make use of `bool`
`nm_check_mailbox()` returns `false`
```
#if LIBNOTMUCH_CHECK_VERSION(5, 0, 0)
if (notmuch_query_search_messages(q, &msgs) != NOTMUCH_STATUS_SUCCESS)
return false;
```
I think it should be `-1` to indicate an error rather than a success == 0, but I'm not sure.
TODO: needs change
#774

bool: convert function parameters in mutt_notmuch.h

---

mutt_options.h

adds `#include <stdbool.h>` to satisfy the use of `bool` of return value of
`mutt_option_get()` in `mutt_options.h`.
Currently everybody who uses `mutt_options.h` already includes `stdbool.h`.
#774

bool: include missing stdbool.h header in mutt_options.h

---

pattern.c

The NotMuch code didn't check for a NotMuch mailbox when dereferencing Header->data.
Thanks to @xunam.
Fixes #805

fix: crash using notmuch expando with imap

---

imap/util.c

valgrind reports a memory leak in imap_get_parent_path due to no
free'ing mx.mbox. As described in imap_parse_path, the callee should
free mx.mbox.
Valgrind output:
```==24227== 13 bytes in 1 blocks are definitely lost in loss record 154 of 953
==24227==    at 0x4C2CE5F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==24227==    by 0x1DE1AF: safe_malloc (memory.c:113)
==24227==    by 0x1DE683: safe_strdup (string.c:175)
==24227==    by 0x1D7B19: imap_parse_path (util.c:332)
==24227==    by 0x1D84E6: imap_get_parent_path (util.c:148)
==24227==    by 0x144619: mutt_index_menu (curs_main.c:2046)
==24227==    by 0x120B68: main (main.c:936)
```

imap: Fix mx.mbox leak in imap_get_parent_path

---

pgpewrap.c

Although the wrapper probably won't cause a real memory leak, cleaning up all allocated memory when exiting could save time spend on debugging memory leaks. Apart from fixing a leak this also leads a small refactoring of the duplicate argc check.

Fix memory leaks in pgpewrap

---

from.c
lib/date.c

mutt_mktime() can overflow when used on 32-bit arches.
This was due to a bogus comparision.
Now, extreme future dates will be interpreted as 2038-01-19.
Fixes #794

fix: overflow in mutt_mktime()

---

auto.def

Issue #826
GPGMe gets configured a bit differently depending on whether LFS needs the `_FILE_OFFSET_BITS=64` define. This commit reinstates `cc-check-lfs` that might define  `_FILE_OFFSET_BITS`, and if defined, adds it to `CFLAGS` when checking for GPGMe

If set, use -D_FILE_OFFSET_BITS=64 when checking for GPGMe

---

browser.c

Issue #803
I don't remember why I put that call to `browser_sort` inside the else branch, which would mean it's called on an undefined `state` variable. Probably just an oversight not backed by any particular logic. Does anybody have an idea? ;)

Sort the folders list when browsing an IMAP server

---

color.c

Using 'uncolor' on the last 'color' added would cause a crash,
because `tmp` isn't defined the first time through the loop.
e.g.
```
color index red yellow ~U; uncolor index ~U
```
This also fixes the two new coverity bugs.

fix: crash using uncolor

---

doc/manual.xml.head

We remove keyword dead code in 5c600997cd0e028a237fe6847ddffa1f2c340ea6.
This change removes the memu entry in the doc.
Closes #836

keyword: remove doc menu entry

---

init.c
mutt_regex.h

next up is `mutt_regex.h`
changes `struct Regex`s not member to `bool`
Affected
* struct Regex
* restore_default()
no
#774

bool: convert struct member in mutt_regex.h

---

mutt_sasl.c

Changes sasl_done() to sasl_client_done(), as former is deprecated now.
no
#841

Deprecation: changed called function in mutt_sasl.c

---

lib/date.c

On 32-bit arches it's easy to over-/under-flow the date.
We replace these with the max/min values allowed in a time_t.
When we encounter one of these dates, pretend it's UTC to prevent another overflow.
Fixes #819
Fixes #820

fix: prevent timezone overflow

---

mutt_tunnel.c
mutt_tunnel.h

next up is `mutt_tunnel.h`
Changes the return type of `mutt_tunnel_socket_setup()` from `int` -> `void` as
it always returned `0`.
Added documentation.
No, it only gets called once, without using the return type

Refactor: Remove unused return type

---

copy.c

Tag header was shown with Notmuch but not with Imap. This change enables it for all backends.
Closes #864

tags: Show fake header for all backends

---

mutt_notmuch.c

nm_uri_from_query() checks if there is a custom limit and includes it
in the URI. This keeps the limit intact after nm_normalize_uri()
terminates. Otherwise, the limit is stored within nm_normalize_uri()'s
temporary NmCtxData struct and lost upon termination.
Additionally, nm_normalize_uri() properly initializes tmp_ctxdata, which
sets the default db_limit value. This ensures db_limit is either
NmDbLimit or the custom limit. My earlier attempt to resolve #849 did
not initialize db_limit and suffered from random db_limit values.
The url_parse_query() check was removed from nm_normalize_uri() as
new_ctxdata() contains the same block of code. Error message numbering
has been updated the reflect the change.
Fixes issue #849
* **Are there points in the code the …

Fix issue #849

---

browser.c
compose.c
curs_main.c
main.c
newsrc.c
nntp.c
nntp.h

next up is `nntp.h`
Converts:
* nntp_active_fetch()
* nntp_select_server()
to use `bool`
Checks callers of `NntpData`, `NntpServer` and `NntpHeaderData` to use `bool`
No
#774

bool: convert function parameters in nntp.h

---

pattern.c

This was reported by summit_ on IRC, who provided the following backtrace:
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000558864263662 in mutt_pattern_exec (pat=pat@entry=0x55886494f6f0, flags=flags@entry=MUTT_MATCH_FULL_ADDRESS, ctx=ctx@entry=0x5588648eacb0,
h=h@entry=0x5588649d5ec0, cache=cache@entry=0x7ffff5523340) at pattern.c:1689
1689              set_pattern_cache_value(cache_entry, match_user(pat->alladdr, h->env->from, NULL));
-------------
(gdb) p h->env
$2 = (struct Envelope *) 0x0
```
Steps to reproduce:
- '#' (break-thread)
- '\<enter\>' (view-message)
Crash occurred in `mutt_pattern_exec()` when `~P` pattern was evaluated.
A backtrace showed that `h->env` was NULL.
Thanks to summit_ for the bug report.

fix crash in mutt_pattern_exec()

---

hcache/lmdb.c
lib/memory.c

* Minor change in LMDB hcache driver to use `safe_calloc` instead of initializing the memory manually
* Simplify `safe_calloc`'s check for `size_t` overflow

Use safe_calloc to initialize memory, simplify size_t overflow check

---

Makefile.autosetup
auto.def

Use bundled wcscasecmp if an implementation is not found in libc

---

ChangeLog.md
hdrline.c
imap/util.c
keymap.c
lib/file.c
lib/lib.h
mh.c
mutt_notmuch.c
pager.c

* 6fecb921 minor code fixes
- Fix typos
- Fix function prototype
- Remove spurious semicolons
- Remove duplicate #include
* e511a0bb use mutt_array_size()
* 7b258d98 refactor out O_NOFOLLOW
O_NOFOLLOW is part of POSIX:2008 which isn't required for NeoMutt.
This refactoring streamlines the code.
* 150febe9 initialise variables
These variables were passed uninitialised to a function which increments them.
Discovered by Coverity after the 'if-assign' commits.

Trivial code fixes

---

doc/manual.xml.head

docs cleanup after [NeoMutt 2017-06-02](https://github.com/neomutt/neomutt/releases/tag/neomutt-20170602):
> Six features are now "always built" as part of NeoMutt: sidebar, imap, pop, smtp, compressed, nntp.
These features have no build dependencies and don't add much to the size.

docs: compressed and nntp features are now always built

---

doc/Makefile.autosetup

Now that makedoc is always built, alter the 'make clean' target to delete it.

autosetup: delete makedoc on 'make clean'

---

auto.def

GNU/Linux does not seem to define BYTE_ORDER in vanilla c99 mode.
Issue #883

Fixes for endianness detection

---

autosetup/system.tcl

This includes the fix for a more fine-grained interaction between $prefix, /etc, and /var.
See https://github.com/msteveb/autosetup/issues/31.

Update autosetup to latest master branch

---

commands.c
compose.c
curs_lib.c
curs_main.c
editmsg.c
flags.c
headers.c
imap/message.c
ncrypt/crypt.c
protos.h
send.c
sendlib.c
thread.c

Many actions aren't performed on all tagged messages if the messages are within a collapsed thread.
Fixes #697
The `Context` has two lists of emails:
- `struct Header **hdrs`
A list of all emails
- `int v2r []`
A lookup table of **visible** emails (what's seen in the index)
An email may be invisible if it's in a collapsed thread,
or if it doesn't match a `limit` pattern.
Actions aren't being applied to tagged, but collapsed, threads.
e.g.
- \<tag-thread\>\<collapse-thread\>\<tag-prefix\>\<flag-message\>
- Expected action: all the emails in the thread are flagged
- Actual action: only the parent email is flagged
A closer inspection showed the problem to be widespread.
The incorrect code was looping through the `v2r` table of visible emails looking
for those that were tagged.
1. Threads …

fix actions on tagged messages

---

hook.c
protos.h
sendlib.c

cli neomutt asks for a password when sending because the `folder-hook` isn't executed for the `$record` mailbox.
This problem was discovered in #877.
Thanks to @lrosenman for his help debugging.
Setup:
- IMAP server
- 'sent' mailbox
- Password that's set using a folder-hook
Here's a minimal config.
```
set smtp_url="smtp://example.com"
set folder="imaps://USER@example.org"
set record="=SENT"
set imap_check_subscribed=yes
set from = "flatcap"
set realname = "Richard Russon"
set spoolfile = "=INBOX"
folder-hook "imaps://USER@example.com" set imap_pass="PASSWORD"
```
Test, by sending an email from the command line:
```
neomutt -n -F test.rc user@example.com
```
Actions:
- Follow the prompts to the compose email
- Hit <kbd>y</kbd> to send the mail
Result:
- A prompt for the password
Expected …

call the folder-hook before saving to $record

---

init.h
pager.c

This commit addresses the issue of smart wrap not working if a line
started with whitespace.
This behavior was a result commit f5e472b where smart wrap was disabled
on lines beginning with a space or tab to prevent headers from having
weird wrapping.
This commit addresses this issue by only applying smart wrapping if the
pager is displaying a message body. This allows smart_wrap to work
inside of a message and preserves what commit f5e472b addressed.
I'm not the greatest with bitwise operations, but I based my change off of what I saw in pager.c and pager.h. I'm sure I didn't mess up the bitwise operations, but not entirely confident.
Issue #844

Fix smart wrap in pager without breaking header

---

configure.ac

With autoconf, `./configure --enable-everything` should include lua.
configure's summary says it does, but `config.h` disagrees.
Tested with:
- `./configure`
- `./configure --enable-lua`
- `./configure --disable-lua`
- `./configure --enable-everything`
Thanks to @tycho for the fix.
Fixes #855

build: --enable-everything includes lua

---

auto.def

`sys_siglist[]` is used in `exit_handler()` in signal.c

autosetup: check for sys_siglist[]

---

init.c
lib/file.c
lib/file.h
muttlib.c

This new function, opposite to the original dirname(3), does not modify its argument and can be passed a const char * argument. This means that callers mustn't copy their strings before calling dirname anymore.

Wrap dirname(3) inside a mutt_dirname() function

---

auto.def
conn/sasl.c

RHEL6 doesn't have the function sasl_client_done().

fix build for RHEL6

---

conn/conn_globals.c
globals.h

Fixed #907
This is a quick and dirty fix to make sure the linker sees the definitions of objects defined in the libraries. A nicer and longer-term solution might involve the use of the `-whole-archive` (respectively `-all_load`on OSX) linker flags, but this requires more investigation.

Move definition of conn/globals.h back into globals.h

---

auto.def
configure.ac

See https://lists.gnu.org/archive/html/qemu-devel/2017-06/msg00634.html for a discussion.
This might be a solution for #589.

Define NCURSES_WIDECHAR to require wide-char support from ncurses

---

auto.def

If sendmail wasn't on the path, then configure.autosetup defined
SENDMAIL=false
/cc @evgeni

autosetup: fix check for missing sendmail

---

.gitignore
addrbook.c
alias.c
alias.h
conn/sasl.c
conn/tunnel.c
copy.c
doc/manual.xml.head
doc/neomutt.pwl
handler.c
hcache/hcache.c
init.c
main.c
mbyte.c
mbyte.h
mh.c
mutt_notmuch.c
ncrypt/crypt.c
ncrypt/pgp.c
newsrc.c
pager.c
pattern.c
protos.h
rfc3676.c
send.c
sendlib.c

All these changes are small and simple.
- 9300ff9bb move test to the right place
- 48908f241 Remove unnecessary semicolon
- f0404ff60 build: fix shadow variable warning
- b6bfab9bc refactor malloc/calloc
- 9c6eaff7d ignore temporary build files
- fb086fb1a fix copyright messages
- 574826250 fix plain unsigned
- 14b2a1b2c unused prototypes, whitespace
- 6b8388608 Standardise spelling s/RfC/RFC/
- ed750e21f alias drop self
I cannot see a need for the `self` pointer in the current code.
I haven't investigated if it was ever needed.

trivial code fixes/changes

---

handler.c

Fixes #722
This stops the conversion from CRLF into LF when decoding a transfer-encoding=base64 message.
This works fine for me, on a text/plain message I found in my mailbox, but I am not sure this doesn't have any unwanted side-effects.
I would like this to be further discussed before merging.

Do not turn CRLF into LF when dealing with transfer-encoding=base64

---

imap/command.c
imap/imap_private.h

- 5ce778544 bug: imap gmail search
The order of strings in Capabilities should match the enums in ImapCaps.
- 9c179f960 fix: drop capability aliases
`CapabilityAliases` was a list of alternative names (just one) for IMAP capability strings.  This isn't necessary.  We can put the strings in `Capabilities` and fix the enumeration.
```c
enum ImapCaps
{   
...
X_GM_EXT1,
X_GM_ALT1 = X_GM_EXT1,
...
};  
```

A couple of fixes for the GMail searching

---

mutt_socket.c

- Remove the sleep
- Be more informative about the failed connection
Issue #934

Cleanup "SSL is unavailable" error in mutt_conn_find

---

auto.def

If configure.autosetup is called with `--everything`, this commit expands that to `--gpgme --pgp ...` for display purposes.
`$ ./neomutt -v | grep Configure`
**Before:**
Configure options: --everything
**After:**
Configure options:  --gpgme --pgp --smime --notmuch --lua --tokyocabinet --kyotocabinet --bdb --gdbm --qdbm --lmdb

autosetup: expand --everything in `neomutt -v`

---

attach.c
editmsg.c
mutt/file.c
mutt/file.h

As discussed in pull-request #948 this implements three functions to set, add, and remove file permissions.
**Notes**
* I followed flatcap's naming convention for the functions as suggested in #948.
* `mutt_file_chmod()` is really just a `chmod()`. I added it anyway to have a complete API in `file.c`.
* I copied the approach of `mutt_file_decrease_mtime()` and gave `mutt_file_chmod_add/remove()` an optional parameter `struct stat sb` through which the caller can pass the `struct stat` for the file. Theoretically this saves a systemcall, although I doubt its usefulness.
* I converted the three calls of `chmod()` to the new functions. Please double check that the use of `mutt_file_chmod_add/remove()` is correct and shouldn't be `mutt_file_chmod()`.
* I tested the code by saving an …

Add chmod like functions to mutt/file.[hc]

---

attach.h
buffy.c
compress.c
curs_main.c
enter.c
hcache/bdb.c
imap/imap.c
imap/imap.h
init.c
mbox.c
mutt/file.c
mutt/file.h
ncrypt/crypt_gpgme.c
newsrc.c
pager.c
protos.h
recvattach.c
recvcmd.c
send.c
sendlib.c

These 13 functions have unused parameters.
I suggest we remove them (and add them back _if_ we ever need them).
They're in separate commits for ease of review; I'll squash them all before merging.
| Commit   | File                 | Function(argument)                    |
| :------- | :------------------- | :------------------------------------ |
| 99a1c25d | curs_main.c          | main_change_folder(flags)             |
| ea00c482 | imap/imap.c          | imap_buffy_check(force)               |
| 58c295e6 | init.c               | mutt_nm_tag_complete(pos)             |
| fcbf897c | mutt/file.c          | mutt_file_lock(path)                  |
| 1b4ee25b | mutt/file.c          | mutt_file_unlock(path)                |
| 2c0e95df | ncrypt/crypt_gpgme.c | verify_sender(protocol) …

Unused parameters

---

conn/conn_globals.c
conn/conn_globals.h

The MacOS build failed, with linker errors for libconn's global variables.
By initialising them, we hope to force the linker to use them.
@lrosenman Please can you give this a try.

build: restore libconn's externs

---

curs_main.c

The **normal sequence** of events is this:
1. Startup
1. Folder hook is executed, causing:
1. OP_MAIN_COLLAPSE_ALL to be put in macro buffer 
1. Mailbox is opened
1. mutt_index_menu() starts
1. No SigWinch has occurred
1. km_do_key() called
1. OP_MAIN_COLLAPSE_ALL is performed
A **broken sequence** of events is this:
1. Startup
1. Folder hook is executed, causing:
1. OP_MAIN_COLLAPSE_ALL to be put in macro buffer 
1. Mailbox is opened, during which
1. SIGWINCH occurs (SigWinch = 1)
1. mutt_index_menu() starts
1. A SigWinch HAS occurred, causing
1. mutt_flushinp() to called
1. the macro buffer to be emptied
1. km_do_key() called
1. nothing is returned

Don't clear the macro buffer during startup

---

auto.def
configure.ac
conn/ssl.c
copy.c
globals.h
hcache/kc.c
hcache/tc.c
imap/auth_gss.c
imap/auth_login.c
imap/imap.c
init.c
init.h
main.c
mutt.h
mutt/debug.h
mutt_notmuch.c
muttlib.c
ncrypt/crypt.c
nntp.c
pop_auth.c
pop_lib.c
rfc3676.c
version.c

* removes `--enable-debug` compile option
* remove `#define` DEBUG and corresponding `#ifdef`. This is fine IMHO, because debugging code usually doesn't need to be refactored. Or more precisely: "making a tighter integration into the sidebar easier" was a reason to not touch `#ifdef` of e.g. IMAP. This doesn't apply to `DEBUG`.
* non-debug being the default is **not** changed.
* [imap/auth_gss.c](https://github.com/neomutt/neomutt/compare/master...devel/persistent-debug#diff-092fac0ebe696f5a8bd7856d7fba9621R82)
* [rfc3676.c](https://github.com/neomutt/neomutt/compare/master...devel/persistent-debug#diff-f0eb956c12d2e70484cf45af91dc0f5fR354)
* …

make +DEBUG persistent

---

contrib/gpg.rc

* renames `gpg.rc` to `gpg2.rc`
* introduces `gpg2_1.rc` which brings in a parameter that does not exist in older GPG versions
* places gpg commands at the end of the commandline, as required by the (often unenforced) syntax rules
* remove use of `--always-trust` in the new version (on the advice of GPG folks)
* ultimately fixes bug https://github.com/neomutt/neomutt/issues/944
I didn't do any testing on the removal of `--always-trust`.
I think so.  I do not believe this change requires any of the following.
[doc/manual.xml.head](https://www.github.com/neomutt/neomutt/blob/master/doc/manual.xml. …

Introduce GPG config file changes to accomodate gpg 2.1

---

curs_main.c

The code used to automatically handle setting the quasi delete
state to whether the message is still visible after performing
the change.
This was broken for the !tag case in
commit 7d151fd0919f6cc7ba9cdc1e7de90697c66dce43
Author: Mehdi Abaakouk <sileht@sileht.net>
Date:   Tue Feb 21 10:50:35 2017 +0100
Share label editing between imap/notmuch
Which replaced the !still_visible with simply true.

Fixup smart modify-labels-then-hide for !tag case

---

.github/ISSUE_TEMPLATE.md

When users remove the irrelevant things for their issue, they often
leave the indentation of the nested list. That causes github to render
those lines as code instead of markdown list items.

github: make removal of irrelevant sections easier

---

smtp.c

Add a `mutt_sleep(0)` after an SMTP error message to ensure that the user can read it.
Fixes #982

add sleep after SMTP error

---

configure.ac

Add a missing `-lidn` when building with `idn` support to fix neomutt on NixOS.
Neomutt didn't have access to `libidn.so` (during runtime) since it was not specified during linking.
It seems that https://github.com/neomutt/neomutt/commit/abfe0f14d2c98d17a2ce39e14a377782e1aa732d#diff-67e997bcfdac55191033d57a16d1408aL887 introduced that issue and only appeared when I did run the 20170912 release on my NixOS machine.

build: add -lidn when idn is enabled

---

smtp.c

Fix SMTP RET parameter which was substituted by rc

---

muttlib.c

Fixes the following GCC warnings:
muttlib.c: In function ‘mutt_pretty_size’:
config.h:55:19: warning: format ‘%lld’ expects argument of type ‘long long int’, but argument 4 has type ‘size_t {aka unsigned int}’ [-Wformat=]
#define OFF_T_FMT "%" PRId64
^
muttlib.c:614:22: note: in expansion of macro ‘OFF_T_FMT’
snprintf(s, len, OFF_T_FMT "K", (n + 51) / 1024);
^~~~~~~~~
config.h:55:19: warning: format ‘%lld’ expects argument of type ‘long long int’, but argument 4 has type ‘size_t {aka unsigned int}’ [-Wformat=]
#define OFF_T_FMT "%" PRId64
^
muttlib.c:621:22: note: in expansion of macro ‘OFF_T_FMT’
snprintf(s, len, OFF_T_FMT "M", (n + 52428) / 1048576);
^~~~~~~~~

Fix type mismatch in mutt_pretty_size()

---

curs_lib.c

Fixes the following GCC warning:
curs_lib.c: In function ‘mutt_progress_init’:
curs_lib.c:471:65: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 4 has type ‘size_t {aka unsigned int}’ [-Wformat=]
snprintf(progress->sizestr, sizeof(progress->sizestr), "%ld", progress->size);
^

Fix type mismatch in mutt_progress_init()

---

contrib/gpg.rc

I believe this fix an bug introduced by changes introduced in Commit 465fad6d21ac3b9d2ae5d12bae7705f5f04323e7 which makes a change to `contrib/gpg.rc` that breaks signed and encrypted mail. The issues is just a typo related to way that `pgpewrap` works. This should fix the bug discussed in issue #998 and seems to do so on my system.
**Please review this carefully.** This is my first commit to mutt/neomutt and I know nothing about `pgpewrap` other than I what I just figured by experimenting with it on the command line. Since this i just a change to a configuration, I've not tested this more carefully than running the new configuration in my version of neomutt (the most recent version in debian).

fix for pgpewrap in default gpg.rc

---

.gitignore
Makefile.autosetup
auto.def
test/Makefile.autosetup
test/acutest.h
test/base64.c
test/base64.h
test/main.c
test/rfc2047.c

This PR is a first step towards having our C library functions unit-tested.
A new binary `neomutt-test` is generated under the `test` directory. This directory contains a `main.c` function which lists the test cases, represented by `void(*)(void)` functions. Test cases are ran through [acutest](https://github.com/mity/acutest), which is a single-header unit-test framework. It provides the scaffolding for running tests, provides a report, and implements the test macros `TEST_CHECK` and `TEST_CHECK_`.
I have already added a couple of test suites for base64 and rfc2047, to give people a sense of how it looks like.

Unit test framework

---

init.h

Fixes the incorrectly formatted `reply_regexp` in `init.h`, and also adds the Swedish "Sv:" prefix to it.
That things still builds, I haven't set up the entire dev environment as this was such a simple fix. Perhaps also some documentation needs updating, e.g. Doxygen run or similar?
N/A
It should, as I expect it to build just fine. I couldn't find any places in the manual touching on this feature/setting. Doxygen format should be fine, just added some words.
None, AFAIK.
* **Other comments**
Please note that the regex still allows the following subject prefixes which …

Fix reply_regexp

---

conn/ssl_gnutls.c
mutt/date.c
mutt/date.h

This PR makes three arrays non-global and moves the only external function which used to use them into an API in date.h.

Make Weekdays, Months, and TimeZones statics, expose mutt_date_make_tls

---

mutt/string.c
mutt/string2.h
test/Makefile.autosetup
test/main.c
test/string.c

The idea is that the currently returned value is of little use, being it the same as the destination parameter. Let's return something useful instead, namely the length of the string which was copied.

Let mutt_str_str(n)fcpy return the string length, add tests

---

mutt/rfc2047.c
url.c

The URL schemes come in two patterns
- smtp://user:pass@host
- notmuch:///path?query
The 'host' types don't take a query string.
'notmuch' and 'mailto' don't use a 'user:pass' string.
This fix will still be confused by a notmuch URL that has a '?' in the path component, but no query string.  (but I don't think the code ever coped with that).  e.g.
- notmuch:///dir?name/
Fixes #1043

fix parsing of urls containing '?'

---

ChangeLog.md
contrib/sample.neomuttrc
contrib/sample.neomuttrc-tlr
doc/manual.xml.head
globals.h
init.c
init.h
pager.c
parse.c
send.c

- Rename config:
- `$quote_regexp` -> `$quote_regex`
- `$reply_regexp` -> `$reply_regex`
- Create synonyms, so old config works
In the past, the vast majority of the code referred to regular expressions as 'regex', not 'regexp'.
So, I renamed all the `regexp`s that I could.
The last exceptions were two config items.
The 'regexp' versions can be deprecated in the (far) future.

Replace two 'regexp' variables with 'regex'

---

auto.def

Run xsltproc with a minimal Docbook file.
If this succeeds, then the docs will probably build correctly.

configure: Check for Docbook DTDs

---

browser.c
imap/browse.c
init.c
mutt/regex.c
muttlib.c
ncrypt/pgp.c
pager.c
parse.c
send.c

The bug happened when setting a regex config to a bad string, or an empty string.
The code would only partially construct a Regex object.
- All-or-nothing construction of Regex objects
- Check all the regex pointers before calling external functions
- Fix cleanup routine (thanks @gahr)
Note: The construction code is much smaller than the original because the logic has been simplified.
The code used to have lots of special cases for certain variables.
These cases were changed into flags, e.g. `DT_REGEX_ALLOW_NOT` and added to `mutt_regex_create()`.

Fix regex issues

---

rfc2231.c

franks2 reported a crash on irc.
It looks like a typo from when `rfc2231_decode_parameters()` was converted to use TAILQ.
See this chunk in the diff: https://github.com/neomutt/neomutt/commit/2aa6bb0a3b#diff-4c6d574f56ae9eb69dc081817e58beecL285
```
#0  0x00007fb5ccba40bb in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007fb5ccba5f5d in __GI_abort () at abort.c:90
#2  0x00007fb5ccbee28d in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7fb5ccd15528 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007fb5ccbf564a in malloc_printerr (action=<optimized out>, str=0x7fb5ccd11e7c "free(): invalid size", ptr=<optimized out>, ar_ptr=<optimized out>) at malloc.c:5426
#4  0x00007fb5ccbf773e in _int_free …
```

fix crash when decoding parameters

---

Makefile.autosetup
auto.def
curs_lib.c
curs_main.c
enter.c
menu.c
mutt/signal.c
mutt_signal.c
pager.c
resize.c
signal.c
version.c

Issue #1057
While at it, dump a stringified version of slang's version in version.c (did I mention version?)

Ncurses always has resizeterm, remove unnecessary ifdefs

---

init.c

The flag, in `struct Option`, allowing a regex to use a '!' (not) is part of the type, not the flags field.
Fixes @hsanson's browser bug in #1060

fix regexes using '!' (not)

---

mutt/regex.c

A `!` was missing when checking regex pointers. This caused some regexes to be ignored.
#1067

fix: missing ! when checking regex pointer

---

doc/manual.xml.head

Adds a text explaining how settings in user config files takes precedence over settings in system config files.
No.
N/A
None created, quick fix. Discussed on the IRC.

Clarify precedence of settings in config files.

---

nntp.c

Avoid dumping `0....n/~0` when loading nntp cache.

Fix usage of mutt_progress_init after b310689

---

mutt_notmuch.c

* If the database open fails, stop
* Use the verbose version of open so we can catch the error message
When we started using the latest Notmuch API, we didn't check if `notmuch_database_open()` failed.
This put NeoMutt into an unbreakable loop.
Also, the new version `notmuch_database_open()` prints an error message to stderr.
Use `notmuch_database_open_verbose()` instead and capture the message.
fixes #1076

notmuch: stop if db open fails

---

test/rfc2047.c

 Fallback to C.UTF-8 if en_US.UTF-8 cannot be set

---

Makefile.autosetup

This fixes the generation part of `git_ver.h` not to eat away any `g`'s it finds in the output from `git describe`.
This is happening now on master:
```sh
% git describe --dirty --abbrev=6 --match "neomutt-*" | sed -e 's/^neomutt-[0-9]\{8\}//;'
-cygwin-100-gc95a13
% cat git_ver.h
const char *GitVer = "-cywin-100-gc95a13";
```

Make sure git_ver.h doesn't eat random 'g's out of tag names

---

init.c

Generally, for strings `Option.var` is a `char **` (a pointer to a string pointer).
The Lua setting code uses it differently.  There, it's just a `char *`.
Fixes #1096

lua: fix crash when setting a string

---

Makefile.autosetup
auto.def
doc/Makefile.autosetup

This allows distros to set flags that must be used both for building
target and host executables.
Issue #980

Expose EXTRA_CFLAGS_FOR_BUILD and EXTRA_LDFLAGS_FOR_BUILD

---

doc/Makefile.autosetup
po/Makefile.autosetup

Sanitise some whitespaces.
I’m not sure the following files:
- autosetup/jimsh0.c
- mutt/queue.h
- INSTALL
should be tidying and how to handle it, because I cannot realise which code
or format style (whitespace related) they follow.
Also these files:
- autosetup/autosetup-config.guess
- autosetup/autosetup-config.sub
are more recent upstream [1], but with similar curious whitespaces.
References:
- [1] <https://git.savannah.gnu.org/gitweb/?p=config.git;a=tree>
none
none

Tidy space-before-tabs and multiple spaces

---

main.c

`neomutt -Z` should return `1` if there's no new mail.
This allows users to use the check in a script.
Fixes #1112

fix return code for 'neomutt -Z'

---

auto.def
mutt_notmuch.c

We need to distinguish between two versions of `notmuch.h`.
Both declare that they are v5.0.0.  They are:
- libnotmuch 5.0 (Notmuch 0.25)
- `notmuch_database_add_message()` is a normal function
- `notmuch_database_index_file()` doesn't exist
- libnotmuch 5.1 (Notmuch 0.26)
- `notmuch_database_add_message()` is **deprecated**
- `notmuch_database_index_file()` exists
To work around this, we check for `notmuch_database_index_file()` specifically.
<sub>Edited to match new commit</sub>

fix Notmuch deprecation warning

---

Makefile.autosetup
conn/tunnel.c
filter.c
init.c
main.c
mutt/envlist.c
mutt/envlist.h
mutt/mutt.h
protos.h
sendlib.c
system.c

The envlist code keeps a private copy of the environment.
This is manipulated by `setenv`/`unsetenv`.
Encapsulate the envlist code, document it and move it to the library.
This makes the code tidier, but I'm still not sure why we need a copy of the environment.
Some code needs to set variables before calling `exec()`, but that tends to happen **after** `fork()`.

refactor: move the envlist code to the library

---

init.c

Refactor the hostname-finding code into a separate function.
Delay the call until after the config and command line have been processed.
This means that some users, with mis-configured network lookups, can work around a long timeout during startup.
---
NeoMutt uses two forms of the hostname:
The **Hostname**, e.g. 'laptop.example.com', is only referenced by `mutt_fqdn()`, which is used to:
- expanding aliases
- determine if an address is _you_
- match encryption keys
- expand outgoing email addresses
The **ShortHostname**, e.g. 'laptop', is used to:
- generate the Message-ID header
- generate some unique temporary filenames
- fallback if the FQDN is missing
To find the hostname the code checks multiple sources in order.
Note: There's no default in `init.h`
1. Config file
- /etc/neomuttrc …

refactor: startup hostname

---

init.c
init.h
main.c
mutt/charset.c
mutt/charset.h

Five more simple changes.
They group and document the setting of config variables, making the precedence clearer.
| Prec | Source       | Example                | 
| :--- | :----------- | :--------------------- |
| 1    | command line | `neomutt -d 2`         | 
| 2    | environment  | `export TMPDIR="/tmp"` | 
| 3    | config file  | `~/.neomuttrc`         | 
| 4    | system file  | `/etc/neomuttrc`       | 
| 5    | code         | `init.h`               | 
- 0efe36606 nntp config
- f0c1cddfa mailcap config
- a7416afc2 tmpdir config
- 17e4dd34c editor, visual config
- 3b59d5484 separate get from set Charset

refactor config setting

---

.clang_complete.in
.gitignore
Makefile.autosetup
auto.def

For users of https://github.com/Rip-Rip/clang_complete, this allows to
always keep the .clang_complete file in sync with CFLAGS.

Generate .clang_complete

---

.gitignore

txt2c is replaced by a routine in the configure/autosetup script.
Update .gitignore accordingly.
This is just a little housekeeping.

Remove reminiscent of txt2c

---

curs_main.c
doc/manual.xml.head
functions.h
opcodes.h

The term 'message' is used for log-messages as well as for ordinary
mails. In the help 'message' usually means an email. Adjust the
description of <show-message>/OP_SHOW_MESSAGE to clarify that log and
debug messages are meant.

Describe <show-messages> more precisely

---

handler.c
imap/utf7.c
mutt/charset.c
mutt/charset.h
mutt/idna.c
mutt/rfc2047.c

Previously, mutt_ch_convert_string returned error only if any arguments failed the sanity check or iconv_open() failed.
With this change, an error value is returned even if the iconv() conversion fails, such as when the input string contains an invalid character in the source character set (EILSEQ).
I have looked at each caller and it seems to me that this change won't introduce any misbehaviour, but I'm far from being 100% confident.
Issue #1136

 Let mutt_ch_choose report conversion failure

---

init.c

This avoids blank lines and use double quotes for the `neomutt -D -S`
variable dump as in `neomutt -D`.
It also gives a little bit more detail on sensitive variable values and
should be unique enough to allow filtered results easily.

init.c: Ensure more consistent variable dumps

---

mutt/logging.c

Flush stream to the logging file after adding a line.
Without flushing logging messages are saved to file with delay due to stream buffering.

mutt/logging.c: set line buffering for logging stream

---

AUTOSETUP.md
INSTALL
auto.def
mutt/file.c

this splits mutt_file_lock and mutt_file_unlock into separate
fcntl() and flock() based versions.  It teaches ./configure
about the new --with-lock option (--with-lock=fcntl or
--with-lock=flock).
Includes updates to INSTALL and AUTOSETUP.md that reference the
removed --enable-fcntl and --enable-flock options.
Closes #1147

mutt/file.c: split mutt_file_{lock,unlock} into flock/fcntl versions

---

Makefile.autosetup
auto.def
doc/Makefile.autosetup
doc/manual.xml.head
doc/neomutt.man
doc/neomuttrc.man.head
doc/neomuttrc.man.tail
sendlib.c

The main goal is to build sorted lists of commands, functions and variables
for the documentation (`manual.xml`, `neomuttrc`, `neomuttrc.man`).
The latter needs further decisions, because the commands section in
`neomuttrc(5)` differs, due to usage of file `doc/neomuttrc.man.head`, from
the generated content of `manual.xml`. Also it is probably about the time
for timestamp updates within the manual pages:
- `doc/neomutt.man:20`               ... neomutt 1 "January 2009" Unix "User Manuals"
- `doc/neomuttrc.man.head:29` ... neomuttrc 5 "September 2002" Unix "User Manuals"
with the release version date, maybe?
If the code re-sort is OK, nothing special yet, I think. The most changes are
code …

Re-sort resources for better documents

---

init.c

Commit 0ef255e repositioned where Neomutt set its standard defaults in
init.c to after the logic for loading the VISUAL and EDITOR variables.
As a result, Neomutt overrides the values it retrieved from the
environment with the ones from the configuration file. This matches the
desired precedence of config->environment->code.
However, if `editor` is not set in the configuration file then Neomutt
does not retrieve EDITOR and VISUAL again. This results in Neomutt
falling back to the editor specified in the code. Thus the precedence is
config->code.
This commit returns the standard default set loop to its initial
location allowing for the environment variables to be usable.
This fixes #1162 
`MailcapPath` and `Tmpdir` were affected by commit 0ef255e as well; however, I did not know it when I …

Respect environment VISUAL and EDITOR variables

---

imap/message.c

On IMAP failure the message body can sometimes be truncated, which
leaves an empty message in the cache that must be manually deleted
to be properly re-fetched.
If the cached message body is zero-length, retry the message parse
once to be sure that the message body actually *is* empty.

message.c: retry message parse if first attempt is zero-length

---

body.h
compose.c
doc/manual.xml.head
functions.h
globals.h
handler.c
init.h
mutt/mime.c
mutt/mime.h
opcodes.h
parse.c
sendlib.c

- Allows reordering email attachments.
- Allow joining several attachments as a single `multipart/alternative` attachment.
This is still WIP, mutt segfaults right after sending the email.
This is the work of @oblitium, based on this unattributed patch:
https://github.com/altercation/arch-packages/blob/master/mutt-dgc-hg/dgc.groupalts
Everything?
for that)
- Added [doxygen code …

Support for multipart/alternative and multipart/mixed

---

mutt/file.c
mutt/file.h
mutt/string.c
muttlib.c

Eliminate static variable in mutt_file_dirname
Yes
for that)
- Added [doxygen code documentation](https://www.neomutt.org/dev/doxygen)
- Code follows the [style guide](https://www.neomutt.org/dev/coding-style)
Malloc a char *buf and free it in …

Eliminating static variable in mutt_file_dirname

---

mutt/rfc2047.c
test/rfc2047.c

Let's be more liberal and accept RFC2047 encoded-test productions that include white space. This is explicitly forbidden by RFC2047, but Mutt has been accepting them since (almost) forever, so let's not break existing clients.
#1189

Accept whitespace in RFC2047 encoded-text productions

---

doc/Makefile.autosetup

77155bb renamed some doc files but doc/Makefile.autosetup wasn't changed to match, this fixes it.

sync with doc tidying in 77155bb

---

init.c
mutt.h

This allows for example to simplify the solution given [here](http://mailman.neomutt.org/pipermail/neomutt-users-neomutt.org/2018-April/000325.html) as:
```
:set pager_index_lines=`dc -e "50 $pager_index_lines -p"`
```
Please review, my `mutt_extract_token`-foo is not as advanced.

Expand variables inside backticks

---

Makefile.autosetup
contrib/Makefile.autosetup
doc/Makefile.autosetup
po/Makefile.autosetup

The install was succeeding, even if some files weren't found.
This was due to a `for` loop eating the command's return code.
For the 'uninstall' targets, we don't really care -- they should try to continue.
Please can someone with a non-Linux make check this works ok.

build: stop on install failure

---

init.c

Do not truncate shell commands in backticks on the first ; or #

---

imap/imap.c
init.h

This changes the place where an LSUB is issued to an IMAP server in
order to populate the buffy list, when imap_check_subscribed is set.
Previously, LSUB was issued when a connection to an IMAP server was
*first* established.  This caused the commands sequence
":unmailboxes *<enter><change-folder>imaps://foo.com<enter>"
to populate the buffy list when *first* opening a connection to foo.com,
but not on subsequent back-and-forth between IMAP servers.
The new code moves the LSUB call - and thus the population of the buffy
list - to just before a mailbox is selected.
This fixes the above-mentioned issue, at the cost of additional LSUB
calls when switching between mailboxes on the same server. Given that
the list of subscribed mailboxes is expected to be in the tens, I think
this is a …

Move LSUB call from connection establishment to mailbox SELECTion

---

mutt/charset.c
mutt/charset.h

This adds the mutt_ch_check API that can be used to check whether a string can be converted between character sets. It is stricter than mutt_ch_convert_string in that it doesn't apply any replacement chars to
unconvertible characters and doesn't return the converted string.
This is an alternative approach at fixing #1136, but needs discussion. Possibly we can enhance the `mutt/charset.h` API in the process.

Add the mutt_ch_check API

---

imap/auth_plain.c

The incorrect assumption was that the first line of an AUTH PLAIN w/o
I-R was always successful, so the client could write the second line and
end up with a readable socket that would be activated by the server
sending the final OK or BAD response.
If however the first line results in a BAD response already, the server
wouldn't write anything else and the client would be left polling for an
additional response that never arrives, effectively hanging the process.
Issue #1236
[doc/manual.xml.head](https://www.github.com/neomutt/neomutt/blob/master/doc/man …

Handle a BAD response in AUTH PLAIN w/o initial response

---

pager.c

When we call mx_check_mailbox() and something change
header in Context->hdrs may have been updated.
In case of MUTT_NEW_MAIL, the page rebuild the index, and fixup
rd.index->current/max and extra->hdr. If the extra->hdr change
like when an above the opened one, or the selected one, is deleted, the
pager is closed.
In case of MUTT_REOPENED we do nothing. Making rd.index->current/max
wrong and extra->hdr perhaps pointing to something that doesn't exist
anymore.
This change makes the MUTT_REOPENED behavior similar to MUTT_NEW_MAIL.
Note that we this the pager have good change to be closed with the
mailbox is modified externally, just like the current MUTT_NEW_MAIL
behavior.
Closes #796

pager: index must be rebuild when check mailbox returns MUTT_REOPENED

---

po/ja.po

According to https://www.gnu.org/software/gettext/manual/html_node/Plural-forms.html, Japanese should also use `Plural-Forms: nplurals=1; plural=0;`.

Update ja translation

---

mx.c

The second `for` loop was using the value of `i` as a starting place.
By changing the first loop, the second loop wasn't doing any work.
Fixes #1253

fix trash mailbox

---

send.c

Option fcc_attach used to ask in any case, if there were attachment nad if there weren't.
In case there is no attachment, there is no need to ask.
I'm not very sure whether the actual behaviour with signatures is right: If you don't fcc the attachments, two signatures will be calculated: one for the bare mail and one for the whole multipart bundle.

fcc_attach: Don't ask every time

---

init.c
mutt.h

Issue #1262 
I've added a flag `MUTT_TOKEN_NOSHELL` for `mutt_extract_token()`
When we're recursively expanding backticks, set this flag.
This only affects SHELL variables, so:
```
my_var="`echo $SHELL $folder`"
set ?my_var
```
should show something like: `Europe/London /home/user/mail`

Fix env var quoting in backticks

---

ncrypt/crypt_gpgme.c
ncrypt/pgp.c
ncrypt/pgpmicalg.c
ncrypt/smime.c

Replace `mutt_mktemp()` to `mutt_file_mkstemp()` where it is easily done
#960

Simple replacements from mutt_mktemp() to mutt_file_mkstemp() in ncrypt

---

curs_main.c

Commit e85c735 introduced the `check-stats` function, designated by
`OP_CHECK_STATS`.
`OP_CHECK_STATS` had been inserted below `OP_MAIN_CHANGE_VFOLDER`, which is
`change-vfolder`'s designation; however, `OP_MAIN_CHANGE_VFOLDER` relies
on C's switch fallthrough logic to execute. As a result,
`change-vfolder` executed `check-stats`'s logic instead of the correct
logic.
This PR moves `OP_CHECK_STATS` to above the `#ifdef` that contains
`OP_MAIN_CHANGE_VFOLDER`, allowing the original `change-vfolder` logic to 
execute instead of `check-stats`'s logic.
Issue #1284

Do not interrupt switch fallthrough

---

main.c

This PR aims to partly address #589--only partly--because I believe there are two separate problems reported there, and this fixes only one of them. Both @rlue and I encountered the problem where if `locale` is set to the following:
```
LANG=
LC_COLLATE="C"
LC_CTYPE="UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```
then `charset` would be incorrectly set to `us-ascii`, causing problems when displaying UTF-8 characters. After some debugging I found out that https://github.com/neomutt/neomutt/blob/eb8b461a79c0c32c8c8eae70a0b762b57585f354/main.c#L323 is actually not using the `setlocale` function provided in `locale.h`, but rather overridden by a macro defined in `libintl.h`, which behaves incorrectly in macOS.
This PR includes a crude fix that addresses the …

[WIP] Do not let libintl.h override setlocale

---

contrib/Makefile.autosetup
doc/Makefile.autosetup

The /usr/libexec path is hardcoded in some of the samples. Run
sed on the installed versions to reflect the directory provided
in ./configure.
Fixes issue #1350.

build: make samples reflect the provided libexecdir in ./configure

---

notmuch/mutt_notmuch.c

Change the default query window to be open ended, allowing for mail
from the future to appear in a query. This may occur if the sender's
time settings are improperly configured.
This change was proposed by @ferriff and I've been testing it for 
several days without issue. Since @ferriff appears to be inactive, I'm
opening this PR.
#748

Notmuch: Change default window to be open ended

---

mutt/string.c
mutt/string2.h
notmuch/mutt_notmuch.c
notmuch/mutt_notmuch.h
test/main.c
test/string.c

This addresses an issue with how Neomutt encodes notmuch queries. If one uses `vfolder-from-query` and includes a `type=` statement, Neomutt will encode the statement as part of the query, which prevents the query type from being changed. Including `type=` statements is documented as supported behavior[0].
This PR achieves the desired result by introducing a case-insensitive implementation of `strstr(...)`, a function for removing all instances of a case-insensitive substring, and combining the two functions to find if a `type=` statement exists and to set the appropriate `query_type` in `NmCtxData`if one exists.
[0] https://neomutt.org/feature/notmuch#3-2-%C2%A0items
#1214

Allow `type=` statements in `vfolder-from-query`

---

curs_main.c
notmuch/mutt_notmuch.c

When the <vfolder-from-query> command is run while already in a vfolder,
it takes the current vfolder as context.  That means the global settings
(nm_query_type, nm_db_limit, nm_default_uri) are ignored in favor of the
current vfolder's settings.  This is confusing behavior because the new
vfolder is otherwise independent from the old one.
Set the nm_uri_from_query() context to NULL so that it uses the global
settings instead.
for that)
- All builds and tests …

notmuch: use global settings for vfolder-from-query

---

notmuch/mutt_notmuch.c

This makes `sidebar_format`'s `%S` display the same value as
`pager_format`'s `%m`.
`count_query` did not handle counting all messages in `type=threads`
queries. It returned the number of messages matching the `query=`
qualifier. Refactored `count_query` into two methods handling
`type=threads` and `type=messages`, respectively.
**Screenshots (if relevant)**
Compare the right-most number of the sidebar for `inbox threads` to the pager. 
Before:
After:
#721

notmuch: count messages in queried threads

---

browser.c
doc/manual.xml.head
init.h
mailbox.c
sidebar.c
status.c

Allows a user to set a description for a mailbox via `named-mailboxes`. This is similar to `virtual-mailboxes`.
To do this, first I fixed the issue affecting #1354 to recover descriptions when the `Context` is recreated. This allowed me to introduce the `%D` expando for `status_format` and `sidebar_format` so we can display an arbitrary mailbox's description. Then I added the the `named-mailboxes` command and modified `browser.c` to use a description instead of a path if one exists.
Only two known issue:
1. Cannot use description for `spoolfile` (this affects `virtual-mailboxes` as well and should be resolved alongside it)
2. Unable to tab complete on `Open mailbox ('?' for list):` prompt
Here is a partial `.neomuttrc` demonstrating its usage:
```vim …
```

Implement named mailboxes

---

doc/neomuttrc.man.head

Documents `named-mailboxes` in the `neomuttrc` manual page. This should have been included in the `named-mailboxes` implementation branch, but I had forgotten about manual pages.

manual: document `named-mailboxes` for neomuttrc

---

doc/manual.xml.head
hdrline.c
init.h

It adds a new "R" flag for the 3rd position of the index %Z field, for when user's own address is in the Reply-To header unless none of the other flags for that field is applicable.
* **Motivation**
Some mailing lists now do the following transformation of the headers: rewrite the From header to the list address, and add a Reply-To header with the poster address.  This feature helps highlight my own posts in folders dedicated to such lists.  Of course if you are _subscribed_ to the list (in the Mutt sense) you'll get the "L" flag instead, but in that case you don't care about hightlighting your posts anyway.
- Documentation …

Try adding status indicator R for my address in Reply-To

---

imap/imap.c

If an IMAP connection was never set up, do not try to write a LOGOUT
command through that connection or to close that socket.
Both results in segmentation faults.
How to reproduce:
- Connect to a server with an invalid or self-signed TLS certificate
- Press "q" to cancel the connection
- Press "q" again to leave neomutt
- neomutt crashes with a segmentation fault
This should at least partly fix https://github.com/neomutt/neomutt/issues/1364

Do not use disconnected socket.

---

notmuch/mutt_notmuch.c

The subsystem reused `ctx->mailbox->path` to store the absolute path for
an email so that it modify the maildir flags. In order to facilitate
this behavior, the subsystem copies the `uri` and uses it to replace the
absolute path after filename modification.
However, the `uri` variable is just a pointer to `ctx->mailbox->path` so
it is overwritten with the physical path.
This commit uses `mutt_str_strdup(...)` to duplicate the `uri` so it can
replace the physical path. Without this duplication, a
`virtual-mailboxes` will lose its notmuch query when modifying tags
corresponding to maildir flags. This results in a `virtual-mailboxes`
disappearing during runtime.
Fixes #1374

notmuch: duplicate `uri` during sync

---

notmuch/nm_db.c

When this portion of the code was migrated to use `NmAccountData`
instead of `NmMboxData` the check for an existing database handle was
removed. NeoMutt would lock-up trying to open another instance of the
database.
This commit re-adds the existing database check.
Fixes #1373

notmuch: use existing open database if possible

---

notmuch/mutt_notmuch.c

After architectural changes, NeoMutt was not updating the progress when
opening `virtual-mailboxes`. The math was out of date.
This commit corrects the math involved and removes the unnecessary
counting logic. If counting is necessary, use `nm_nonctx_get_count(...)`
in a future commit.
`type=` counts are still inaccurate, but implementing proper counting destroys performance.
**Does this PR meet the acceptance criteria?** (This is just a reminder for you,
I used `clang-format` but one line is slightly longer than 90 characters. When I correct it and run `clang-format` makes reverts my change.
Fixes #1368

notmuch: rework progress update math

---

notmuch/mutt_notmuch.c

vfolder-from-query would seg fault after architectural changes. Issue
was a bad pointer that I introduced in an earlier commit.

notmuch: fixed vfolder-from-query

---

browser.c
doc/manual.xml.head
init.h
mailbox.c
nntp/nntp.c
notmuch/mutt_notmuch.c
notmuch/mutt_notmuch.h
pop/pop.c
sidebar.c

`nm_nonctx_get_count(...)` did not count flagged messages. This means
they could not display flagged message counts in the sidebar _unless_ it
was the active mailbox (handled by a different function.)
This commit introduces NmFlaggedTag, mirrored from NmUnreadTag, and will
query the database for flagged messages.

notmuch: count flagged messages

---

browser.c
browser.h
curs_lib.c
curs_lib.h
curs_main.c
init.c
sidebar.c
sidebar.h

Removes the separation between mailboxes and virtual-mailboxes in the sidebar and browser. virtual-mailboxes are the ugly stepchild in NeoMutt, and there is arbitrary separation between them. This branch is working towards making virtual-mailboxes no different than any other.
Altered:
- Behavior of `%f`. Use path instead of description. 
`%i` display descriptions.
Removed:
- `sidebar-toggle-virtual` is created an unnecessary separation between mailboxes and virtual-mailboxes. It's still included as a command (so people don't get config warnings), but does nothing. It might be a good idea to remove it so people don't execute a useless keybinding.

notmuch: remove sidebar and browser special cases

---

init.h

Changes the default of status_format and folder_format to display
descriptions instead of file path.
With the inclusion of named-mailboxes, we should try to use descriptions
since they fall back to file path. Otherwise, there would not be a
distinction between mailboxes and named-mailboxes with the defaults.

format: use description by default

---

imap/imap.c

Currently imap_mbox_open call imap_conn_find2 and return without cleanup
if an error occurs.
This change restores the previous resources freeing code.

imap: fixup error handling of imap_conn_find2

---

imap/message.c

imap sometimes crashes when changing folder or quiting neomutt.
```
#1  0x000055555563833f in mutt_email_free (e=0x555555b0cb50) at email/email.c:55
#2  0x00005555555bb4e9 in mx_fastclose_mailbox (ctx=ctx@entry=0x555555980050) at mx.c:407
#3  0x00005555555bd593 in mx_mbox_close (pctx=0x5555558a69b0 <Context>, index_hint=index_hint@entry=0x7fffffffa074) at mx.c:727
...
```
This change adds the missing free_edata pointer to imap_free_edata.

imap: add missing free_edata pointer

---

browser.c

The browser searches on mailbox paths; however, with the introduction of
`named-mailboxes` and merging of `virtual-mailboxes`, it is necessary to
search of descriptions. If not, it may be impossible to find a mailbox
that is named.
For example, if we have `named-mailboxes "Test" "+work"` and searched
for "Test", it will not match because the path does not contain "Test".
Searching "work" would match the "Test" mailbox.
This commit modifies `select_file_search(...)` to use the description if
one exists. This way we can properly match searches for
`named-mailboxes` and `virtual-mailboxes` without know their underlying
mailbox paths.

browser: search on description if it exists

---

mx.c

At least for imap if "folder=imap://example.com" and mailboxes contains "=Foo"
mx_path_canon will construct imap://example.com//Foo
This change ensures we do not add the extra /.

mxapi: mx_path_canon should not double / uri

---

flags.c

`mailbox->msg_flagged` was stored as `mailbox` variable.
This change rename it to `flagged`.

flags: change confusing var name

---

imap/imap.c

imap: when opening mailbox, reset Mailbox attrs
We currently only reset vcount and msg_count.
But imap_read_headers() call from imap_mbox_open() reload all
messages and then call mx_update_context(). So attributes that have not
been reseted will grow from previous values.
This does the reset of size, msg_unread, msg_flagged, msg_new.

imap: when opening mailbox, reset Mailbox attrs

---

imap/command.c
imap/imap.c
imap/imap.h
imap/imap_private.h
mailbox.h
mx.c

remove mailbox.closing
mx_mbox_close() does not always put back mailbox.closing to false.
This make next imap_sync_mailbox() during mx_mbox_sync() closing the
imap connection when it should not.
Since this attribute is only used by imap backend, this change removes
it and handle the imap specific shutdown within the imap backend.

remove mailbox.closing

---

account.c
account.h
mailbox.c
mx.c
mx.h

Also delete account if needed during unmailboxes
When we do:
mailboxes imaps://foo
unmailboxes *
mailboxes imaps://foo
* account->mailboxes is not cleaned and have pointer to freed mailboxes
* account is still there even if not used
This changes cleanup account->mailboxes and account if needed.

Also delete account if needed during unmailboxes

---

imap/browse.c
imap/imap.c
imap/imap_private.h
imap/util.c

imap: simplify getter around ImapAccountData
Since we have accounts and only one connection for imap, we can simply the
code. This does:
* Remove now useless attributes of imap_prepare_mailbox()
* Rename imap_ac_data_find() to imap_adata_find() and move it in util.c aside
other adata related function.
* Parse path within ImapMbox in imap_adata_find() to remove some common code.
* Create ImapAccountData resource during imap_ac_add()

Pull request for better-adata-handling

---

imap/imap.c

When the additional ctx is closed, the mailbox is free'd too, which causes a crash back in the index.

Do not create an additional ctx for syncing a mailbox

---

compress.c
curs_main.c
flags.c
imap/imap.c
imap/imap.h
imap/imap_private.h
imap/message.c
imap/util.c
mailbox.c
maildir/mh.c
mbox/mbox.c
mutt_thread.c
muttlib.c
mx.c
mx.h
nntp/newsrc.c
nntp/nntp.c
notmuch/mutt_notmuch.c
pop/pop.c
pop/pop_auth.c

This is a **Work-in-Progress** (barely tested and incomplete)
It aims to reduce the number of `Context` references in the backends.
[This table](https://github.com/neomutt/neomutt/issues/1326#issuecomment-438085645) shows where there's work still to be done.
Refactor `ctx->mailbox` to `m`:
- a3f551f0f pop
- 80a917a88 mbox
- 7d4619196 maildir
- d3fd51edc nntp
- b15ce7371 notmuch
- 20dcb531e compress
- 720d05a00 imap
- 36b3dcebb flags
- b0b316883 mx
- d8617b65c threads
Replace `Context` pointer with `Mailbox` pointer:
- 8ffa6cd2f open_append: remove Context
- 8a2a3d84e msg_close: remove Context
- fb64e838d msg_commit: remove Context
- 2c38d871e msg_padding_size: remove Context
- e574bf2bb tags_edit: remove Context
- ff49ddc75 path_canon: drop folder

Factor out `struct Context`

---

imap/browse.c
imap/command.c
imap/imap.c
imap/imap.h
imap/imap_private.h
imap/message.c
imap/util.c
mailbox.c

This change reduce the usage of ImapMbox and imap_path_parse()
This change introduces `struct ImapMailboxData` to mainly store
the mbox name in all its form.
Next change will use this names instead of parsing again and again the
path.
At this end we should be able to drop ImapMbox and imap_parse_path().

Pull request for devel/imapmbox-removal

---

imap/command.c

When this error triggers I see `Mailbox @localhost closed`. It appears that account.login contains an empty string, while the IMAP username is in account.user.

account.login is empty, use account.user instead

---

imap/auth_login.c
imap/auth_oauth.c
imap/command.c
imap/imap.c
imap/imap_private.h
imap/message.c

imap_exec flag IMAP_CMD_FAIL_OK is the only one that configure the
function return instead of the function behavior.
Also returned value of the function depends on the flag make hard to
understand what happen after imap_exec() is run.
This change removes this flags, instead we always returns the detailed
returns code, the caller have to deal with it.
Return code are always IMAP_EXEC_SUCCESS/IMAP_EXEC_ERROR/IMAP_EXEC_FATAL and
depends on if the command succeed, failure or if the imap connection
fail.

imap: reduce complexity of imap_exec

---

imap/imap.c
imap/imap_private.h

The former call to `imap_adata_free((void **) adata);` caused an account to be around with no adata associated with it. This caused a crash when trying to access the account later on.

Keep adata on imap-logout-all

---

imap/command.c
mailbox.h
mx.c

When record is the current folder, we have two issue when we send a mail.
mutt fcc system will open and close the current mailbox.
And then for imap, server have good chance to send us EXPUNGE and EXISTS in the same pipeline.

Fixup issue when record is the current folder

---

doc/manual.xml.head
doc/neomuttrc.man.head

Changes all instances of GMail to Gmail for consistency (Google exclusively uses the Gmail variant).

Change instances of GMail to Gmail for consistency

---

notmuch/nm_db.c

In commit 1040935, I accidentally removed a check for using `Folder` as
the `db_filename` if `db_filename` is null. My change made it so that it
always overwrote the value.
#1455

notmuch: don't overwrite nm_default_uri

---

.gitignore
Makefile.autosetup
globals.h

Replaces `git_ver.h` with `git_ver.{c,o}` and removes dependency from all files on `git_ver.h`, having a dependency on only the final `$(NEOMUTT)` target
Every time I changed my git's state, the entire repository was rebuilt because `git_ver.h` changed: https://pastebin.com/v629aTPr
On top of that, it seems on some machines this dependency does not even get processed and the `git_ver.h` file is not updates: https://pastebin.com/xKXhD78R

Change dependency chain regarding git_ver

---

imap/command.c

When selected mailbox in unsubscribed, adata->mailbox may be NULL.
make imap_cmd_finish() handles it.
Closes #1460

imap: handle case where adata->mailbox is NULL

---

compress.c
imap/imap.c
imap/message.c
maildir/maildir.c
maildir/maildir_private.h
maildir/mh.c
maildir/shared.c
mbox/mbox.c
mx.c
mx.h
nntp/nntp.c
notmuch/mutt_notmuch.c
pop/pop.c

Following on from [this diagram of Context use](https://github.com/neomutt/neomutt/issues/1326#issuecomment-438085645), I've refactored the backends to move `mx_update_context()` out of `*_mbox_open()`.
Here are a couple of diagrams that may illustrate what I've done.
The represent the function call tree leading to `mx_update_context()`.
**Key:**
- **Solid Red** - The problem function, `mx_update_context()`, which has been eliminated
- **Dot** - New locations of `mx_update_context()` calls
- **Purple** - MXAPI functions
- **Green** - Other functions called by NeoMutt (from outside the email backend)
- **Red** - Private functions
---
This is an improvement for `mbox_open()`, but it just shifts the problem down to `mbox_sync()` and `mbox_check()`.

Factor out mx_update_context() from mbox_open()

---

imap/imap.c

This ensure we always have a valid adata.
Closes #1438

imap: login on startup

---

maildir/maildir.c
maildir/mh.c
mbox/mbox.c
mx.c
mx.h
nntp/nntp.c
notmuch/mutt_notmuch.c
pop/pop.c

This tries to avoid going out of sync with mailbox <-> context, by calling `mx_update_context` in a few more places and by making sure that if we call it twice we don't crash.
This is at the cost of recomputing the whole of `Context` each time we call `mx_update_context`.

Try to keep the current mailbox and the Context more in sync

---

init.h
recvattach.c
recvattach.h

This specifies the location where attachments are saved. The default is the current working directory.
Issue #1465

Add the "attach_save_dir" config variable

---

imap/imap.c
mailbox.c

Fixes the mailboxes new count after the latest `mbox_check_stats()` related merge.

Try to fix the mbox_check_stats() merge

---

notmuch/mutt_notmuch.c

previous behaviour: size was not reset. This resulted in mailbox size to
accumulate on each mailbox reopening, hence displaying incorrect mailbox
size information in the status bar.
new behaviour: size is reset to zero.
steps to replicate previous behaviour: open neomutt with vfolder. Press
space to refresh vfolder (open from sidebar) several times. Mailbox size
in the status bar accumulates.
fixes a small bug in status bar when using notmuch

reset notmuch Mailbox->size on opening

---

mailbox.c

The new mbox_check_stats work well, but MailboxCount was not correctly
updated.

mbox_check_stats: fix MailboxCount

---

imap/imap.c

This change calls imap_mailbox_status() instead of imap_status()
in imap_mbox_check_stats() as we known the Mailbox.
This also add more sanity check in imap_mailbox_status().

imap: use imap_mailbox_status() in imap_mbox_check_stats()

---

imap/imap.c
imap/imap_private.h
imap/message.c
imap/util.c

This change keeps the hcache open as long as the Mailbox is alive.

imap: open hcache only once per Mailbox

---

imap/imap.c
imap/imap_private.h
imap/message.c
imap/util.c

The ImapCache is useless since it's used only when we fail bcache.
And this is not really expected.

imap: remove ImapCache

---

init.h

Search & replace was a bit too enthusiastic in commit f4fbbda045ee, causing some
existing config files to become invalid, and giving an invalid example.

Fix mistaken hdrs -> email

---

doc/manual.xml.head
email/parse.c
email/parse.h
globals.h
hcache/serialize.c
init.c
init.h

When set, it automatically subscribes to mailing lists found in
List-Post headers.
This commit is based on Michael Elkins's patch from the thread
<https://marc.info/?l=mutt-users&m=127076105423565&w=2>.
I've added an opt-in variable $auto_subscribe and a hash table cache
to speed up reading headers when the variable is set.
Co-authored-by: Austin Ray <austin@austinray.io>

Add $auto_subscribe variable.

---

imap/command.c
imap/imap_private.h
imap/util.c

This patch adds support for unique sequence IDs to be logged. Each
new imap account is assigned an ID letter (seqid) which increments
to the next letter (and wraps at 'z') each time a new imap account
is created.
Signed-off-by: Mark Stenglein <mark@stengle.in>
for that)
* **What …

imap: command: Adds unique sequence IDs

---

contrib/colorschemes/solarized-dark-256.neomuttrc

slang is no longer a requirement for proper colors, one likely related fix is
commit a7102c721893d6a6fc33a8e9590f99c450e9fe9e
Author: Fabrice Bellet <fabrice@bellet.info>
Date:   Fri Aug 4 21:16:53 2017 +0200
color: call use_default_colors() in a single location
we call use_default_colors() when parsing colors in rc files only, and
unconditionally when defining the color of the tree element, because the
foreground color of the tree element may be combined dynamically with
the default background color of another element, not explicitely defined
in an rc file. This patch fixes a bug visible with some versions of the
ncurses library: use_default_colors() was used too late, and generated
color leakage effects. (#689)
-> colors look fine on Fedora 28 with ncurses backend. The comment about …

solarized dark color scheme: Remove outdated comment about ncurses

---

notmuch/nm_db.c

Since commit 1cdfc0da08e09b1756a7b4d422996e907c4390d0 the function
nm_db_release() does not release DB if long-run state is enabled.
This change make code more readable and shorter.
Unfortunately, nm_db_release() is called from nm_db_longrun_done(), so
after the change the function nm_db_longrun_done() is no-op and long
transaction never finish. It means:
- changes are not committed the database
- after mutt restart old state (tags) is read from DB
- mismatch between notmuch tags and maildir filenames
This commit disables long-run state in nm_db_longrun_done() before
nm_db_release() is called.

notmuch: make sure nm_db_longrun_done() release DB

---

mutt/charset.c

Running make with `./configure --disable-nls` fails when it encounters `mutt/charset.c` since it tries to include `libintl.h` which is part of gettext (which for reasons unknown is installed but broken on my mac so I need to disable NLS).
```
$ ./configure --disable-nls
[...]
$ make
[...]
cc -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -DNCURSES_WIDECHAR -I/usr/local/include -I. -I. -Wall  -I./test -MT mutt/charset.o -MD -MP -MF mutt/charset.Tpo -c -o mutt/charset.o mutt/charset.c
mutt/charset.c:34:10: fatal error: 'libintl.h' file not found
#include <libintl.h>
^~~~~~~~~~~
1 error generated.
make: *** [mutt/charset.o] Error 1
make: *** Waiting for unfinished jobs....
```
N/A

fix: mutt/charset.c: only include libintl.h if ENABLE_NLS is defined

---

hook.c
hook.h
index.c
main.c
sendlib.c

Use the description, in addition to the path, when determining to
execute a `folder-hook`. Since `named-mailboxes` and `virtual-mailboxes`
use descriptions to hide ugliness of raw paths, the description may
differ from the path and/or contain information not included in the
path.
The inclusion of description checking makes `folder-hook`s improves its
ergonomics. `notmuch` users were particularly affect by poor
`folder-hook` ergonomics since `virtual-mailboxes` paths often had large
overlap, making it hard to craft a good regex. A workaround was to add a
unique dummy key.
#1125 was tracking `folder-hook` and `notmuch` usage. This PR would provide a proper solution.
**Notes**
This may cause some issues with existing `folder-hook`s if a user is …

folder-hook: try matching on description

---

enter.c

Command prompt should close when deleting the ':' as it does in vim

---

mx.c

postponed/sendlib code can reopen an already opened mailbox.
This overrides m->ndata with a temporary context but never revert it back to
the previous one.
At first glance, when postponed/sendlib code open the mailbox they don't care
to have their context updated with the notification system. It should be
the Context used for the UI that should be updated instead.
So until we don't open a mailbox twice anymore, just set ndata when it
looks accurate to workaround the issue.

Don't override ndata with temporary context

---

init.h

Relax non-empty requirement on compose_format, pager_format, and status_format

---

doc/manual.xml.head
functions.h
index.c
opcodes.h

Implemented a read-only variant of vfolder-from-query for users who want
to have an immutable window. This ensures no accidental tag changes
occur.

notmuch: implement read-only vfolder-from-query

---

mx.c

Allow the creation of a new mbox when saving to a local file

---

email/tags.c
imap/imap.c

When we set multiple tags on multiple emails at once, only the first
email get all tags.
This is because we use strsep that will modify the initial buffer that
contains all tags.
This change fixes it by duplicating the buffer of tags before using
strsep on it.

tags: fix multiple tags set on multiple emails

---

browser.c

`sort_browser` config attribute was modified after calling `browser_sort`.
This means each time the browser was sorted it used the old sort parameter instead of the new one.
Fixes #1551

browser: sort_browser attribute being modified after sorting browser

---

index.c

I'd like to split up the ~2600 line function `mutt_index_menu()`.
This is a bit of preliminary tidying.
- b5ee70728 Refactor index's check macros
Replace over 200 macros with a function to test the pre-requisites
- 11b31bdf2 reduce scope of loop variables
All the `for` loops now have their own variable
- c7d530590 reduce scope of rc
Each `case` now has their own `rc` variable
The only shared variable left is `buf` -- a temporary buffer.
The next step is to move all the large `case` statements into functions.
**Note**: This tidying also needs to happen to `mutt_pager()` too.

Start to refactor mutt_index_menu()

---

pager.c

Like the Index changes, this PR is a step towards splitting up a gigantic `switch` statement.
- 5186f3cba reduce scope of loop variables
- 470de50c8 reduce scope of variables
- 4036eaddc tidy mutt_pager()
I'd like to factor out the `CHECK` macros, as I've done in #1560, but the logic is a little more complicated and I haven't decided on the best way yet.

Refactor/tidy mutt_pager()

---

browser.c

Like the Index and Pager changes, this PR is a step towards splitting up a gigantic `switch` statement.
- 7996ef013 use NUL rather than zero
- eb4e85712 boolify variables
- f7f88ac01 separate op
- fa5aec47f reduce scope of variables
- 4cf8c3a10 tidy mutt_select_file()

Refactor/tidy mutt_select_file()

---

compose.c

Like the Index and Pager changes, this PR is a step towards splitting up a gigantic `switch` statement.
- 460e9e168 reduce scope of variables
- 8d3a080ff boolify variables
- 02bc2f13b fix scoping
- 7aac12a41 merge non-overlapping buffer use
- 62f4412af use NUL rather than zero
- be0b361f2 var scope
- 9fc86fcde tidy mutt_compose_menu()

Refactor/tidy mutt_compose_menu()

---

enter.c

Like the Index and Pager changes, this PR is a step towards splitting up a gigantic `switch` statement.
- 9409b1cc7 boolify variables
- 83dc6207e use NUL rather than zero
- d42784d5b reduce scope of variables
- 5aa4b29d4 tidy mutt_enter_string_full()

Refactor/tidy mutt_enter_string_full()

---

commands.c
editmsg.c
flags.c
imap/message.c
index.c
mutt_thread.c
mx.c
nntp/newsrc.c
nntp/nntp.c
notmuch/mutt_notmuch.c
pager.c
pattern.c
postpone.c
protos.h
recvcmd.c

Boolify the parameters of functions `mutt_emails_set_flag()`, `mutt_thread_set_flag()` and macro `mutt_set_flag()`.

boolify mutt_set_flag() and friends

---

compose.c
init.h

Changes the wording of $postpone quadoption message. Global replace of "Postpone this message?" to "Save (postpone) draft message?". Resolves issue #1312. Additional update to documentation via init.h.
#1312

Rewording of "postpone" message to avoid a common confusion

---

context.c
imap/imap.c

This fixes an invalid access caused by NeoMutt not correctly rebuilding the context tables when an email disappears from a mailbox.
#1577

Fix crash when an email disappears from IMAP

---

doc/manual.xml.head
init.c

Adds ability for ifdef to work with environment variables.
chaotic asciinema…
[![asciicast](https://asciinema.org/a/pQAXhEzRl4cPxzSbaI5TeIo46.svg)](https://asciinema.org/a/pQAXhEzRl4cPxzSbaI5TeIo46)
* **Does this PR meet the acceptance criteria?** 
- Documentation created/updated
updated.
I'm not sure. I build it if it passes tests we will see.
Didn't seem to be necessary.
- Code follows the [style guide]
I hope so. I tried to keep style I've seen around. Maybe braces are not necessary:
https://neomutt.org/dev/coding-style#braces-placement but I would let it until some code style review.
* **What are the relevant issue …

Ifdef envvars

---

context.c
mx.c

Fixes: #1597 
The mx layer shouldn't be freeing the Mailbox (nor `ctx_close()`).
Since we now 'resolve' paths using Mailboxes, their lifespans are greater than just `mbox_open()` to `mbox_close()`.

mx: fix mbox double free

---

doc/neomuttrc.man.head

Previously:
/usr/bin/tbl:<standard input>:824: unrecognised format `\'
/usr/bin/tbl:<standard input>:824: giving up on this table
It seems the period after table headers must be on its own line.

Fix table in man page

---

notmuch/mutt_notmuch.c

While looking for ways to improve `notmuch` performance, I noticed `read_threads_query()` does not close hcache on SigInt. It's companion function, `read_mesgs_query()` closes hcache on SigInt.
This is my mistake as I failed to notice it in #1602's review.
Sadly, this removes Neomutt's ability to run at >100% efficiency when re-opening a thread query after SigInt

notmuch: close thread queries' hcache on SigInt

---

auto.def
color.c
color.h
mutt_curses.h

slang supports using direct color values in order to create color pairs, this means that neomutt is not limited to the console color palette.
The same is not possible with ncurses, since it doesn't support direct-color values ATM. The only way to have custom colors in ncurses is to set them in the terminal palette, which is very antisocial because there's no way to revert back to the original palette afterwards, leaving the console after quitting neomutt in a weird state (color-wise).
This series adds supports for RGB color values in the neomutt config file, like the following example:
https://gist.github.com/royger/80c8aeff38567aa47274165f2da19117
This is the solarized dark color scheme from:
https://github.com/altercation/mutt-colors-solarized/blob/master/mutt-colors-solarized-dark-256.m …

Add support for direct color values when using slang

---

context.h
hook.c
imap/imap.c
imap/imap.h
index.c
menu.c
mutt_curses.h
pattern.c
pattern.h
score.c

Refactors pattern.[ch] and a few other files to use the SLIST_* macros for linked lists in struct Pattern.
#1224

pattern: change Pattern linked-list(s) to use queue.h SLIST_* macros

---

mutt_lua.c

The 'lua' command uses the entire line of text.
Clear the Buffer so that NeoMutt doesn't try to interpret it.
Fixes #1610

lua: fix command-line processing

---

doc/manual.xml.head
init.h
sidebar.c
sidebar.h

Sometimes, there are multiple mailboxes available for an account, but a lot of them are empty. I want to display only the mailboxes that contain emails in them. This PR adds that option via a new configuration: `$sidebar_non_empty_mailbox_only`.
for that)
- Code follows the [style …

Add new option to display only non-empty mailboxes in sidebar

---

mutt/memory.c

mutt_mem_free() should return NULL, instead of 0, to match code style[0]
[0] https://neomutt.org/dev/coding-style#distinguish-between-0-and-null

memory: return NULL, not 0

---

send.c

Along the lines of commit 3c3156f's `ctx->` dereference fixes, fix one more.

fix further crash in ci_send_message()

---

email/tags.c
mutt/string.c
mutt/string2.h
test/main.c
test/string.c

This change introduces a new string function mutt_str_split(src, sep) to
return a STAILQ of the split string.
This new funtion is used first in tags code.

tags: Use STAILQ instead of strsep

---

context.c
imap/message.c
mailbox.c
mailbox.h
maildir/shared.c
notmuch/mutt_notmuch.c

Mailbox size update upon addition of messages was carried out in various places, using various methods. Update upon deletion was handled in a central place. When the methods used to account addition and subtracted don't match, you end up having bogus accounting:
```
---NeoMutt: +Trash [Msgs:0 17592186044412M]
```
This PR adds a centralized way to account mailbox sizes. While at it, I noticed NotMuch mailboxes weren't accounted for when deleting emails. I can't confirm that this fixes the particular issue, as I'm not a NotMuch user.

 Fix bogus mailbox size accounting

---

mx.c

This fixes a crash when two mailboxes have been opened within a session, and an `unmailboxes *` command is issued. In this case, both the current mailbox and the previously opened mailbox have a non-NULL `notify` member. The notify method assumes the mailbox is currently active within the context. The context gets thus doubly freed.

Disable mailbox notify on close

---

main.c

On IRC, compi123 reported problems, on FreeBSD 11.2, with text being left behind on the 'alternate' screen after NeoMutt closes.
This PR forcibly clears the screen on exit.

curses: clear screen on exit

---

commands.c

Fix save_message() - set the append flag to the correct mailbox

---

config/cfgaccount.c
config/set.c
hook.c
init.c
mutt_lua.c

Simplify functions by allocating Buffers on the heap, rather than using ones on the stack.

Tidy Buffer usage

---

maildir/maildir.c
maildir/mh.c
send.c
sendlib.c

When replying to an email, mark the original as 'replied'.
Fixes: #1647
**Notes**: `cur` used to refer to the `Email` to change.  It it was `NULL`, then the function would look for tagged `Email`s.  Now, the function is passed an `EmailList` to work on.

fix setting the 'replied' flag

---

browser.c
browser.h
mutt/buffer.c
mutt/buffer.h
mutt/path.c
mutt/path.h
muttlib.c
muttlib.h
test/Makefile.autosetup
test/buffer.c
test/main.c
test/path.c

Upstream introduced two new functions.  Move them to libmutt.
- `mutt_buffer_concat_path()`
- `mutt_path_getcwd()`

promote two functions to libmutt

---

init.c
mutt/buffer.c
mutt/buffer.h

This fixes an issue in the startup sequence where a buffer is requested from the buffer pool before mutt_buffer_pool_init is called. The latter doubles up the number of buffers even though there are free ones.

Make buffer pool initialization lazy

---

menu.c

This should finish the job done in 8e8344. Also, this addresses https://github.com/neomutt/neomutt/issues/1311#issuecomment-484762553 - I think we can close that issue after this one is merged.
Fixes #1311

Demote more 'first' and 'last' errors to messages

---

imap/auth_oauth.c

Currently when oauth success, we got this and neomutt UI got stuck:
[2019-04-21 15:35:38]<5> mutt_socket_readln_d() 5< a0001 OK xxxxxxxxxxxxx@xxxxxxxxx authenticated (Success)
[2019-04-21 15:35:38]<2> mutt_socket_write_d() 5> [2019-04-21 15:35:38]<2> imap_login() Communication encrypted at 256 bits
[2019-04-21 15:35:38]<3> imap_mdata_new() hcache uidvalidity 1, uidnext 228, modseq 0
[2019-04-21 15:35:38]<M> mx_mbox_open() Reading imaps://imap.gmail.com/INBOX...
[2019-04-21 15:35:38]<M> imap_mbox_open() Selecting INBOX...
[2019-04-21 15:35:38]<2> mutt_socket_write_d() 5> a0002 SELECT "INBOX"
[2019-04-21 15:35:38]<5> mutt_socket_readln_d() 5< * BAD [CLIENTBUG] Invalid tag
In fact neomutt send ^A to the server, but this should occurs only if
the authentication fails.
This changes fixes that.

imap: fix oauth

---

imap/auth_login.c

The auth_login returns an error when it succesfully logins.
This was introduced by 04892a48ea76b37f6aa9b369b5bc4f5cc362878c

imap: fix auth login

---

curs_lib.c
curs_lib.h
doc/manual.xml.head
doc/neomuttrc.man.head
hdrline.c
hook.c
hook.h
init.c
init.h
pattern.c
pattern.h

These upstream commits add an alternative way to conditionally format dates (and more...)
They add an `index-format-hook` and a new expando `%@name@`, e.g.
```
color index_date cyan default
set index_format="%4C %-6@date@ %-15.15F %Z (%4c) %@label@%s"
index-format-hook  date  "~d<1d"    "%[%H:%M]"
index-format-hook  date  "~d<1m"    "%[%a %d]"
index-format-hook  date  "~d<1y"    "%[%b %d]"
index-format-hook  date  "~A"       "%[%m/%y]"
index-format-hook  label  "~f github.com"   "GH "
index-format-hook  label  "~f flatcap.org"  "HAT "
```
The first set will choose a date format dependent on the age of the email.
The second set will add an optional label before the subject.

add index-format-hook

---

imap/imap.c

imap_check_mailbox return an detailed state, not only 0/-1.
imap_sync_mailbox assumes that the function was returning only 0/-1.

imap: fixing race when syncing mailbox

---

mutt/string.c
test/string/mutt_str_atoi.c
test/string/mutt_str_atol.c
test/string/mutt_str_atos.c
test/string/mutt_str_atoui.c
test/string/mutt_str_atoul.c
test/string/mutt_str_atoull.c
test/string/mutt_str_sysexit.c

There are 7 pairs of commits:
1. Add comprehensive tests
2. Tidy code
... for each of the functions:
- `mutt_str_sysexit()`
- `mutt_str_atos()`
- `mutt_str_atoi()`
- `mutt_str_atol()`
- `mutt_str_atoui()`
- `mutt_str_atoul()`
- `mutt_str_atoull()`
This raises the [coverage of libmutt/string](https://flatcap.org/mutt/lcov/mutt/index.html) to 70.9%.

Add Test Cases for some String Library Functions

---

imap/browse.c
imap/command.c
imap/imap_private.h

@nnathan 
This is your patch (via upstream).  Please can you check it still works.
---
Currently the IMAP browser relies on LIST and LSUB (for listing subscribed
folders) which may not provide the required hierarchy information.
RFC3348 section 3 goes as far as stating that a client mustn't rely on LSUB
for hierarchy information.
This patch implements the LIST command extensions specified in RFC5258
requiring that a server must respond with hierarchy information for
listed folders (whether or not filtering on subscribed folders).

Improve hierarchy information accuracy in IMAP browser

---

functions.h

This restores a subset of the keybindings found in the original vvv.nntp
patch that don't clash with any of neomutt defaults.
Specifically:
i to change-newsgroup
ESC-i to change-newsgroup-readonly

keybindings: restore nntp change-newsgroup keybindings

---

imap/utf7.c

Just some cleanup to avoid unnecessary string copies and allocations.

Avoid useless reallocations in IMAP utf8/utf7 conversion

---

imap/command.c

Because of a wrong argument passed into `imap_unmunge_mbox_name`, mailbox names encoded in utf7 are not properly converted into utf8. This causes two problems:
1. mailbox names are mangled in the UI (M&AOY-lstr&APY-m instead of Mælström)
2. mailbox names are re-encoded to utf7 before being sent to the server, resulting in "Mailbox does not exists" errors in commands such as DELETE

Fix utf7/utf8 conversion of mailbox names in LIST response

---

imap/imap.c
imap/imap.h
init.h

Allow to disable IMAP's ENABLE extension to work-around broken servers

---

address/address.c
color.c
email/parse.c
email/rfc2231.c
maildir/shared.c
mutt/regex.c

- Replace `atoi()` uses with `mutt_str_atoi()`
which has range checking and returns errors
- Fix memory leaks during header parsing
These were triggered by some fairly degenerate headers
- Check the value of the 'Content-Length' header more carefully
Large numbers could cause the `long` to overflow
Thanks to LGTM and oss-fuzz.

Fix bugs raised by automated testing

---

index.c

e4133e5cd2 have introduced a small regression.
next-unread-mailbox does not automatically open the mailbox.
This change fixes it.

Fix next-unread-mailbox

---

index.c

Previously oldcur was determined after nm_read_entire_thread(),
leading to entire-thread unintentionally jumping to the first message
in the thread.
Before 918885f32db41 that used to work, because mutt_sort_headers()
wasn't called from within nm_read_entire_thread().
Fix by moving oldcount computation a few lines up. Rename oc variable,
to avoid confusion.
Fixes: #1714

entire-thread: determine current position before resorting.

---

index.c

918885f added, indirectly, a mutt_sort_headers() call to
nm_read_entire_thread() (via mutt_mailbox_changed() ->
ctx_mailbox_changed() -> ctx_update()), but didn't remove the sort
after nm_read_entire_thread() in mutt_index_menu().
Remove the now superfluous sort.

Avoid redundant sort in entire-thread.

---

index.c

entire-thread will underflow CUR_EMAIL macro if no mailbox is
configured. To prevent this, call 'prereq()' before any other logic.
'prereq()' will ensure we have a mailbox thus preventing the underflow.
@flatcap deserves credit for identifying the solution.
Fixes: #1719

fix: stop CUR_EMAIL underflow in entire-thread

---

pager.c

- the calculation of number of lines to scroll up/down should not
depend on whether the number of rows in the pager/index/terminal is
odd or even.
- this patch will make the behaviour symmetric such that in both cases
(even/odd number of rows) scrolling up and down by half a page (or the
other way round) will get you back to the exact same line as before.

make OP_HALF_{UP,DOWN} behave symmetric.

---

doc/manual.xml.head

When you have many Maildir mailboxes (or if you change it regularly), it can be cumbersome to maintain the `mailboxes` list manually. This PR adds an example to automate that.
**NOTE**: I don't think the section ["Monitoring new Mail"](https://neomutt.org/guide/configuration.html#mailboxes) is correct for this example - but i haven't found a better place, since this section is the target-link for the `mailboxes` command in the [reference](https://neomutt.org/guide/reference#2-%C2%A0configuration-commands)

doc: add example to find all maildir mailboxes

---

handler.c
mutt_attach.c

This PR is primarily to get feedback about whether this is a reasonable approach. And not yet whether it can be committed as is.
The goal of the first patch is to increase the chances of finding a mailcap match. In my experience often "description" will have actual content, even though "filename" doesn't. Therefore it makes sense to match for description if filename doesn't find a match.
The second one is to allow to format attachments correctly. I use a syntax highlighter for patch attachments, but without this path that breaks when composing emails, as the attachment will be formatted with that syntax highlighter as well. Mailcap has 'compose' entries for that, but mutt didn't use them.

Improve mailcap handling

---

Makefile.autosetup
auto.def
backtrace.c
mutt.h
mutt/signal.c
mutt/signal2.h
mutt_signal.c
test/signal/mutt_sig_init.c

Add a configure option `--backtrace` that uses libunwind to print a basic backtrace if NeoMutt segfaults.
The backtrace is saved to the log, too.

devel: show backtrace on segfault

---

Makefile.autosetup
auto.def
autosetup/cc.tcl
autosetup/system.tcl
doc/Makefile.autosetup
po/Makefile.autosetup

By using autosetup's new @include feature, we are left with a single Makefile at build time. This should make it easier to spot dependency errors and faster to process.

Update to latest autosetup, use @include feature

---

init.h
recvattach.c
recvattach.h

If the 'save_without_prompt' variable is set (to true), then when saving
attachments the user will not be prompted each time for the name of the file.
Handling conflicting filenames is also handled.
closes #1603 
-=david=-

Save attachments without prompting.

---

init.h

Clarify header_cache behaviour on missing paths

---

auto.def

This commit adds a new --pkgconf switch to configure. When specified, the compiler and linker flags for most 3rd party dependencies will be figured out using pkg-config.

Optionally use pkg-config for 3rd party dependencies

---

auto.def

I'm not sure how this managed to get past all the tests I ran, but...
Running `./configure --pkgconf --disable-idn --idn2` means that `HAVE_IDN2_H` isn't defined,
so `address/idna.c` doesn't compile.

build: check which idn2 headers to include

---

curs_lib.c

Flushing `stdin` is undefined behaviour.
References
http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1570.pdf, chapter 7.21.5.2 (The fflush function)
http://en.cppreference.com/w/c/io/fflush
Replace a call to `fflush` on stdin
- Documentation created/updated
No documentation to update
If the function is appropriate, I'll gladly document it
It should …

Avoid UB when clearing stdin

---

commands.c

Fixes #1762
This works for me and was the most obvious way to fix it, but I'm not sure I appreciated the full set of consequences.

Fix saving a msg to a non-existent mailbox

---

pattern.c

As there is another definition of PatternFlags
Rename `typedef uint16_t PatternFlags`, as there is another definition of `PatternFlags`.
Multiple definitions with the same name can be problematic, in this case both types are defined in the same header file.
I must say, I'm not 100% sure this is also UB in the used C standard, but for forward compatibility with newer standard it is beneficial:
https://stackoverflow.com/questions/34986335/does-c-have-one-definition-rule-like-c
I choose to name to mimic `MUTT_PDR_NO_FLAGS`, suggestion are welcome.

Rename typedef to PDR_FLAGS

---

mutt/queue.h
test/address/common.h
test/config/common.h
test/file/common.h
test/md5/common.h
test/rfc2047/common.h

Found with `clang -Wreserved-id-macro`

Avoid using reserved identifiers

---

index.c

Prior to this commit, `index_hint` is initialized if `Context && !attach_msg`.
If `query_quadoption(C_Quit, _("Quit NeoMutt?")) == MUTT_YES`,
`!Context || ((check = mx_mbox_close(&Context)) == 0)` is `false` and
`(check == MUTT_NEW_MAIL) || (check == MUTT_REOPENED)` the function `update_index`
is called with parameter `index_hint`.
As one of the condition is `query_quadoption(C_Quit, _("Quit NeoMutt?")) == MUTT_YES`,
the real current position is probably not so important.
Initialize `index_hint`, as discussed in https://github.com/neomutt/neomutt/issues/1767

Initialize the variable `index_hint`

---

pop/pop.c
pop/pop_lib.c
pop/pop_private.h

Otherwise a realloc is potentnially unsafe
Make pop_fetch_t take const char* as param
https://github.com/neomutt/neomutt/issues/1777

Make callback take const param

---

curs_lib.c
init.c

Make the conversion between `bool and `QuadOption` explicit, and avoid
depending on the underlying `enum` value.
Also state that `mutt_yesorno` works correctly for `MUTT_YES` and `MUTT_NO`
https://github.com/neomutt/neomutt/issues/1765
* **Further consideration**
I've added an `assert` to ensure code-correctness/self-documentation, but I've noticed that they are not used so much in the code base.
Are there some guidelines? Are they accepted/avoided?
On https://neomutt.org/dev/coding-style they are not mentioned.

Avoid implicit conversion between bool and quadopt

---

init.c

`cmd` is a `Buffer` struct, it does not correspond to `%s` in the format string.
for that)

Fix struct Buffer used as %s

---

email/parse.c
mutt/charset.c
sendlib.c

`mutt_str_strcasecmp(path + szf - sze, p) == 0` is checked twice, merge them into one.
for that)

Remove duplicate conditional expressions

---

imap/imap.c

String `buf` is uninitialized when used here.
for that)

Remove uninitialized char array buf

---

browser.c
commands.c
email/parse.c
email/rfc2047.c
hook.c
imap/browse.c
index.c
mutt/charset.c
mutt/path.c
mutt/regex.c
mutt/regex3.h
muttlib.c
ncrypt/pgp.c
nntp/browse.c
notmuch/mutt_notmuch.c
pager.c
send.c
test/Makefile.autosetup
test/main.c
test/regex/mutt_regex_match.c

Minor refactor of the use of `regexec` with our own very `regex_is_match`/`regex_is_match_full`.
I'm still in the process of verifying a lot of this, but I'm creating a in spirit WIP PR so I kick myself into finishing this (sorry for the long wait). 
With prior discussions of testing, I've decided to take an unorthodox venue in testing as you may see, which will test old uses of `regexec` against its corresponding `regexec_is_match`, etc. 
Also creating this PR in the meantime so I can know if I'm doing something super wrong, or not in the project's spirit (so I hope that's OK).
N/A …

Refactor regex with custom wrapper

---

notmuch/mutt_notmuch.c

The notmuch-backend initializes a provided email struct with content
from notmuch. In rare instances, a provided email struct has a
message_id that does not match the one from notmuch. No validation to
ensure message_ids match is performed.
An issue occurs when running nm_mbox_check(), which stores all messages
in a hash table. The incorrect message_id is the key so our email is
considered missing, reloaded into the mailbox, and a duplicate appears
in the index. This triggers a warning from neomutt regarding external
modification.
Instead, validate the message_ids to ensure a match so our hash table
keys are correct. As a result, a reload is no longer performed and
neomutt's warning need not occur.
Fixes #1793

fix(notmuch): ensure message_id is correct

---

mx.c

Commit 45639e4 breaks partial notmuch mailbox loads. If a notmuch mailbox is
interrupted while loading, the index will be empty. To resolve this, add back
the 'mutt_sort_headers()' for the interrupted read case.
Fixes #1800

 fix(notmuch): sort headers on interrupted read

---

recvattach.c

This matches the length of the pipe command for messages, and is much less likely to be hit accidentally.

Increase length of attachment pipe command

---

ncrypt/pgp.c

In GnuPG output there is a space after "[GNUPG:]". If the space is
not taken into account, the rest of the parsing fails, e.g., because
the variable "line" starts with " BEGIN_DECRYPTION" instead of the
expected "BEGIN_DECRYPTION".
This commit restores the previous parsing functionality. It appears
that the number of spaces does not differ among GnuPG versions.
However, if we wanted to make the code robust to varying amount of
space following "[GNUPG:]", we could either trim the whitespace from
the beginning or take it into account with mutt_str_lws_len().
This commit fixes a regression introduced at c2aa0c06.
No screenshots but below is a (censored) log with debugging information without this patch from current master. Note the …

Fix parsing of GnuPG output

---

help/help.c
help/help.h
help/scan.c
help/vector.c
mx.c

Drop the global DocList cache and attach DocList to Mailbox
Before this change, help.c contains a global DocList containing parsed Email. As help documents are parsed only once. Caching is not necessary. Thus removing all caching logic and attach the DocList to Mailbox's mdata.
for that)
- …

Drop global DocList, attach the parsed result to Mailbox

---

hcache/hcachever.sh
hcache/serialize.c

This ensures using %W in index_format while having
header cache enabled works as expected.
Note that as we don't modify the header files that
hcachever.sh is looking for, but the serial_dump_envelope
and serial_restore_envelope functions instead, we have
to increment BASEVERSION to ensure that cache built with
previous versions gets invalidated in all cases.
Fixes #1808

Add envelope's Organization field to hcache

---

browser.c

Fixes #1781
@P-EB , can you please double check? This is related to https://github.com/neomutt/neomutt/commit/e7d6be50d1017541d81b32a8a43e110af6bbfc64 but I don't understand the rationale for that change. Does this branch introduce any regression wrt your fix?

Remember last visited folder when browsing

---

commands.c
imap/imap.h
imap/message.c
muttlib.c
muttlib.h
recvattach.c

This is less of a request for a review, more a case of here's some upstream merging for comparison.
- f9785ffa3 Convert mutt_display_message() to buffer pool
- 9d54533ba Convert mutt_save_message() to use buffer pool
- 46f9fce0c Convert recvattach save_attachment functions to use buffer pool.
- 819778dc2 Convert query_pipe_attachment to use buffer pool
- 51ac592d6 Convert print_attachment_list to use buffer pool
[This gist](https://gist.github.com/flatcap/1d12ea8380837184e84eb474dcce23ab) contains the original upstream patches and the tidied versions.
The tidied ones don't apply, but they make it simpler to cut'n'paste.

Upstream Buffer changes

---

imap/imap.c
index.c
maildir/maildir.c
maildir/mh.c
mbox/mbox.c
mutt_mailbox.c
mx.c
mx.h
notmuch/mutt_notmuch.c
sidebar.c

Recent refactoring introduced several bugs related to whether a mailbox was considered _new_.
- 252e4b757 fix: mbox_check_stats() retvals
We weren't distinguising between 'success: no new mail' and 'success: some new mail', which led to unnecessary checks (which are expensive for mbox).
- cf599f50b fix mbox's handling of new mail
Make sure that `Mailbox.has_new` behaves correctly, which means checking
- The timestamp on the mbox file
- Are there new emails in the Mailbox?
- Has the user visited the Mailbox?
- a4d9169b8 fix <change-folder> when $change_folder_next is set
Setting the config variable should pick the **next** Mailbox with new email, not the first
- 1c5ded977 fix sidebar colour for 'new' mailboxes
Only set the **new** colour, if `Mailbox.has_new` is set
Fixes: #1629 
Fixes: …

Fix mbox's understanding of 'new'

---

auto.def

Fix a `configure` note from autosetup: `Note: defaultprefix is deprecated. Use options-defaults to set default options`. https://travis-ci.org/neomutt/neomutt/builds/593779676#L512
N/A

build: fix autosetup warning

---

doc/manual.xml.head
globals.h
init.h
pager.c

By setting the configuration variable `toggle_quoted_show_levels`, when you
execute the `toggle-quoted` command, the specified number of levels
will continue to be visible.
Closes: #1802

Add ability to limit levels hidden with toggle-quoted command

---

email/email.h
pop/pop.c
pop/pop_lib.c
pop/pop_private.h

Move `Email->refno` to `PopEmailData->refno`
`Email->refno` was only being used in the POP backend.
The value **was** saved in the Header Cache, but the restored value was never used (see `pop_fetch_headers()`).

pop: refactor refno

---

index.c

If the notmuch database is missing a message, abort \<entire-thread\>
before causing a segfault. When \<entire-thread\> executes on a message
missing from the database, it segfaults. This happens because the
vfolder returned is empty and not in an properly initialized state for
the notmuch-backend. As such, the notmuch-backend segfaults.
To prevent a segfault, display a warning and pre-maturely exit
\<entire-thread\>. While the user is left in an empty vfolder, this is
consistent behavior for \<entire-thread\>. Ordinarily, you're left with
just the notmuch thread, which doesn't exist in this case.
The location of the abort is perfect for adding behavior to handle the
missing message. In the future, we can automatically run 'notmuch new'
after encountering a missing message. That is …

fix: abort entire-thread if database lacks message

---

address/group.c

This fixes the crash when creating alias groups.
However, it seems to leak the addresses and the group.
(I think it may always have leaked).
I can't see where the address groups are meant to go, or who's meant to own them.

fix: crash when using 'alias -group'

---

init.c

Set the "initial" value for "charset" from the user's locale.
"reset charset" left C_Charset empty leading to problems reading strings from the user.
Now, `reset` restores the original value.
Fixes: #1884 
---
The actual cause came after the field had been read.
NeoMutt attempts to check if it's an international email address, but as `C_Charset` is `NULL`, `mutt_idna_local_to_intl()` fails.
The failure causes an error message, which is immediately obscured by the address prompt.
- `ci_send_message()`
- `edit_envelope()`
- `mutt_edit_address()`
- `mutt_addrlist_to_intl()`
- `mutt_idna_local_to_intl()`

fix: reset charset

---

contrib/sample.neomuttrc-tlr
doc/neomutt.pwl
init.h

'$wrapmargin' is a long-deprecated alternative to '$wrap', except in reverse.
Setting `wrapmargin=4` was equivalent to `wrap=-4`.
The new config system eliminated all the custom handling of options.
Closes: #1883 
---
It was never part of NeoMutt, so this is the simple solution.
Alternatively, I can fix the behaviour until some future 'Deprecation Day'.

config: drop wrapmargin

---

browser.c
commands.c
filter.c
mutt_attach.c
mutt_attach.h
recvattach.c

Low urgency.
`mutt_create_filter_fd()` uses the screen width to set the environment variable `$COLUMNS`.
This allows certain filters / mailcap programs to adjust their output.
`$COLUMNS` is set/reset in the smallest scope possible.
This variable isn't set globally to avoid affecting other programs which don't need to know.

eliminate MuttIndexWindow from create_filter()

---

bcache.c
browser.c
complete.c
compose.c
compress.c
email/parse.c
email/rfc2231.c
hook.c
imap/imap.c
init.c
mailcap.c
maildir/maildir.c
maildir/shared.c
mutt/buffer.c
mutt/buffer.h
mutt_body.c
mutt_logging.c
muttlib.c
ncrypt/crypt_gpgme.c
ncrypt/pgp.c
ncrypt/pgpkey.c
pattern.c
pop/pop.c
recvattach.c

Low urgency.
The first commit adds return values (of the Buffer size) to several Buffer functions.
We have the information available, so it might be useful.
- `mutt_buffer_concatn_path()`
- `mutt_buffer_concat_path()`           
- `mutt_buffer_strcpy()`                
- `mutt_buffer_strcpy_n()`              
- `mutt_buffer_substrcpy()`  
The next two replace some common patterns (see a lot in the upstream refactoring),
with new functions: `mutt_buffer_strdup()` and `mutt_buffer_copy()`.
```diff
- mutt_str_strdup(mutt_b2s(buf));
+ mutt_buffer_strdup(buf);
```
```diff
- mutt_buffer_strcpy(dst, mutt_b2s(src));
+ mutt_buffer_copy(dst, src);
```

Buffer refactoring

---

muttlib.c

Issue #1898
I'm not totally positive this is the right place to do this - perhaps symlinks should be resolved just before opening a mailbox, so the mailbox path isn't magically changed to follow the symlink.

Resolve symbolic links when saving a message

---

core/account.c
init.c
main.c
mx.c

This fixes a bug whereas the failure to open a fresh mailbox caused the mailbox to remain attached to the Account's mailbox list. Further access to the Account's mailbox list caused the dangling pointer to be dereferenced, thus a crash.

Avoid dangling pointer in Account's mailbox list

---

mbox/mbox.c

Opening an mbox Mailbox, causes the entire file to be read.
A side-effect of this, is that the EOF flag is set on the FILE stream.
Later, when the Mailbox is used for trash, the EOF flag causes the operation to fail.

fix mbox save-to-trash

---

hcache/lmdb.c

Opening a maildir mailbox read-only creates a couple of LMDB transactions (for 'new' and 'cur').
As they are readonly, they don't get committed or aborted (the two actions that free a transaction) when the LMDB connection is closed.
I _think_ this is correct.
It works for read-only and write transactions and ASAN seems happy.

lmdb: fix txn leak

---

doc/manual.xml.head

Fix documentation whereby second level folders are not shown when a user hits `c` in their maildir.

Escape space to show second level folders with spaces

---

notmuch/nm_db.c

Modify 'nm_db_get_filename' to not terminate early if there's no mailbox
data. The notmuch backend may be activated in a mailbox without mailbox
data (e.g. vfolder-from-query), which results in a NULL DB filename.
Instead, use 'nm_default_uri' as the fallback even when there's no
mailbox data.
Fixes #1923

notmuch: use nm_default_uri if no mailbox data

---

muttlib.c

When a path at /foo/bar/s is a symlink to rel/path, the canoncial
expanded version should be /foo/bar/rel/path, not ./rel/path.
Fixes #1937.
Possibly also #1933 and #1920.
Supersedes #1939.

Fix relative symlink resolution

---

maildir/maildir.c
mx.c

A missing flag mean that saving trash to a non-existent file/directory would fail.
Tests:
- `mbox_type=mbox`, save to non-existent file, or non-existent dir/file
- `mbox_type=maildir`, save to non-existent dir, or non-existent dir/dir

fix: trash to non-existent file/dir

---

mbox/mbox.c
mx.c
sort.c

Change the calls to `fopen()` to always allow reading.
Saving to an email to the current mbox opened the file write-only.
This causes a crash when NeoMutt tries to reuse the FILE handle for reading.
Fixes: #1913

fix crash saving to mbox

---

color.c
color.h
doc/manual.xml.head
sidebar.c

With the change to 'sidebar_new' to exclude unread counts, there is no
mechanism to highlight mailboxes with unread mail in the sidebar. This
will appear as a regression to those using 'sidebar_new' for such
purpose.
To span the gap, introduce 'sidebar_unread' which restores the
highlighting for unread mailboxes. It's priority is higher than
'sidebar_flagged'.
Closes #1944
Closes #1875

feat: add 'sidebar_unread' color

---

mbox/mbox.c
mutt_mailbox.c
mx.c

- mbox: don't write unless it's really changed
- imap: clear the new flag on entry
A couple of misplaced flag-settings caused a heap of problems with new mail.
mbox, maildir and imap should now work correctly.

fix new-mail flags and behaviour

---

doc/neomutt.xsl

Makes HTML generated by docbook reproducible. It sets `<xsl:param name="generate.consistent.ids" select="1"></xsl:param>` in neomutt.xsl.
http://docbook.sourceforge.net/release/xsl/current/doc/fo/generate.consistent.ids.html
Affected files generated by docbook:
```
gettingstarted.html |    4 ++--
index.html          |    4 ++--
manual.html         |    8 ++++----
```
Example in HTML output:
```diff
-     </p></li></ul></div><div class="table"><a id="idm140737315569792"></a><p class="title"><str...
+     </p></li></ul></div><div class="table"><a id="id-1.3.6.5.14.5.6"></a><p class="title"><stro...
```

docbook: set generate.consistent.ids to 1 to make generated html reproducible

---

imap/imap.c

mutt_save_message_ctx requires the mailbox to be in append mode

---

index.c

The assumption that new emails would appear at the end of the
mailbox->emails array is wrong. Let's iterate the whole set of emails
until we find a new mail.
Fixes #1979

Fix new_mail_command notifications

---

test/address/mutt_addrlist_to_intl.c
test/date/mutt_date_localtime.c
test/rfc2047/rfc2047_decode.c
test/rfc2047/rfc2047_encode.c

This PR fixes two kind of test failures:
- `test_mutt_idna_intl_to_local` and `test_mutt_idna_local_to_intl` fail when tests are run in a sandbox or with `--exec=never` because some variables like `C_Charset` are set to some values by other jobs and are not cleaned. `C_Charset`, `C_IdnEncode` and `C_IdnDecode` are now cleaned in the tests changing it.
- a test is checking that the day of the year is always >= 119 which would cause it to fail when executed between Jan, 1st and Apr, 28th.
N/A
N/A

tests: fix context for failing idna and date-related tests

---

maildir/maildir.c
mbox/mbox.c
sendlib.c

Saving the sent-mail failed when the destination was a deep
non-existent directory.
Fixes: #1990

fix fcc for deep dirs

---

imap/imap.c

The original code took a copy of the email array, sized exactly for the
number of emails.  If a new mail arrived during the sync process, the
array would overflow causing a crash.
The size of the email array is actually email_max.  This gives us a
little room for new mail.
Ideally read_headers_fetch_new() would resize the email array.
Either way leads to problems sync-ing the original array and notifying
the caller about the new mail.

imap: fix crash when new mail arrives

---

main.c

Some users were seeing messages such as "Sorting mailbox..." on shutdown.
These messages should only be displayed in the GUI.
Any warnings or errors that occur during the shutdown will still be displayed.
This was caused by a recent change: 2a9267080 close logging as late as possible

quieten messages on exit

---

context.c
index.c
mbox/mbox.c
mx.c
pager.c

This is a mixed bag of small changes.
Importantly, it:
- Fixes: #1957 - crash when mbox is reopened
- Fixes: #1978 - 'new' flag not cleared
It also:
- 'peeks' when reopening mbox (to avoid losing stats)
- changes a couple of 'closed' notifications to 'update'
they were causing bits of Mailbox to freed unnecessarily
- adds a number of pointer checks

fix: crash after failed mbox_check

---

auto.def
version.c

A trivial change, here.
Display the notmuch library version in the NeoMutt command-line version output.
On RHEL7 (LTS Redhat Version), I'm forced to build NeoMutt against an old version of the Notmuch libraries, due to dependency problems (Gmime 3.0, GPGMe 1.8.0).
We already display 'ncurses', 'libidn' and 'GPGme' library versions.
---
**Question**:
How do people feel about dropping the 'Compiler Version' info?
I've never found any occasion to need it?
(and it takes up a lot of space)

show notmuch library version

---

compose.c

In compose menu, status bar was drawn without highlights applied. Now, it can be colorized with `color status ...`, just like every other status bars.
Not sure why it worked like this before.

compose: draw status bar with highlights

---

compose.c
mx.c

This fixes some problems when attaching an Email in compose.
- Shortcut re-opening a Mailbox
Re-opening an already open Mailbox wastes time (and confuses IMAP)
- Restore read-only flag afterwards
(after attaching, the Mailbox was being left read-only)

compose: fix attach message

---

pager.c

Fixes #2038
I am not sure why this should happend. This was also introduced by the CUR_MAIL reorg.

Fix crash in pager

---

curs_lib.c
curs_lib.h
sendlib.c

This commit reorganizes a bit the logging around write_one_header, so
that "too long" messages are only printed when the header is actually
too long, and new lines at the end of header lines do not get emitted by
them selves in the log.

Avoid logging single new lines at the end of header fields

---

ncrypt/crypt.c
ncrypt/crypt_gpgme.c
ncrypt/crypt_gpgme.h
ncrypt/crypt_mod.h
ncrypt/cryptglue.c
ncrypt/cryptglue.h
ncrypt/pgp.c
ncrypt/pgp.h
ncrypt/smime.c
ncrypt/smime.h

Currently, when running without autocrypt support, the signing key is
specified statically via settings such as pgp_sign_as / smime_sign_as
and pgp_default_key / smime_default_key. This makes it impractical to
select a signing key based on the address that is being used to send the
email. This is especially true when the From header is set manually via
edit_headers or in the compose screen.
This commit changes the ncrypt API to accept an AddressList as part of
the signing process. This AddressList consists of the addresses in the
From header and is used to help locate a signing key, if none can be
found using the static settings.
Note that only the GPGMe backend supports this new functionality. I am
not touching the GPG backend.

Try to infer the signing key from the From address

---

compose.c

Exclude the notmuch backend from the 'attach-message' command's
filesystem check. This check applies to all backends except remote
backends (IMAP, POP, NNTP.) The notmuch backend functions similar to a
remote backend, communicating through a protocol. As such, Neomutt
checks for a notmuch mailbox on disk and fails when it cannot find one.
Fixes #2062 
This portion of `compose.c` needs to be refactored to support the MX api, 
but that's outside the scope of this PR.

compose(attach-message): support notmuch backend

---

imap/command.c
imap/imap.c
imap/imap_private.h
imap/util.c

Tidy the code handling IMAP's response to a 'STATUS' command.
- 76e4fea50 tidy: cmd_parse_status()
- 555ba4dba add Account to ImapAccountData
- 9823f67fe lookup a Mailbox internally
When we get an untagged response from the server, we need to lookup the Mailbox.
We know the Account and have the Mailbox name from the server.
The MXAPI lookup functions perform a lot of unnecessary work searching through
all the Accounts, turning the Mailbox path into a URL and canonicalising it.

refactor: imap's cmd_parse_status()

---

Makefile.autosetup
auto.def
doc/makedoc_defs.h
doc/manual.xml.head
imap/command.c
imap/imap.c
imap/imap.h
imap/imap_private.h
mutt_config.c
mutt_zstrm.c
mutt_zstrm.h
po/POTFILES.in
version.c

Add a (de-)compression layer to the IMAP connection.
This feature uses zlib to compress data to/from an IMAP server.
When logging is enabled at level 5, it logs statistics on close.
> **zstrm_close() read 4055362 -\> 35314609 (8.7x) wrote 215993 \<- 18071 (12.0x)**
Enable with:
- `./configure --zlib`
- `set imap_deflate = yes` (default)

IMAP: add support for COMPRESS=DEFLATE, RFC4978

---

maildir/maildir.c

Currently maildir_mbox_check_stats always updates the statistics. This
should only happen when "mail_check_stats" is set to "yes".
Call chain:
mutt_mailbox_check()
->mailbox_check()
->mx_mbox_check_stats()
->maildir_mbox_check_stats()

maildir_mbox_check_stats should only update mailbox stats if requested

---

imap/imap.c
maildir/shared.c
mx.c

Here's the call graph:
`imap_check_mailbox()` can return `MUTT_NEW_MAIL` or `MUTT_REOPENED`.
Despite what the function comments say, these functions can also return the values above:
- `mx_mbox_close()`
- `mx_mbox_sync()`
- `imap_sync_mailbox()`
Unfortunately, a couple of problems prevent the values being propagated back to the index.
A recent refactoring meant that return values weren't being propagated.
Commit: 941e39acc fixes that (in this PR).
This function **used** to return the result of `imap_check_mailbox()`.
That was changed by commit: 60270c9fa8
> imap: fixing race when syncing mailbox
> imap_check_mailbox returns a detailed state not only 0/-1.
> imap_sync_mailbox assumes that the function was returning only 0/-1.
> This change fixes that.
```diff
diff --git a/imap/imap.c …
```

update_index() never gets called

---

mx.c

This was reported by 'swivel' on IRC.
Call tree:
- `sync_mailbox()`
- `MxOps::mbox_sync()`
- `mh_mbox_sync()`
- `maildir_mbox_check()`
Besides 0 and -1, `maildir_mbox_check()` can also return flags such as
`MUTT_NEW_MAIL`.  These get returned to `sync_mailbox()` which thinks
that non-zero must mean error.
Log any non-zero returns, but only error on negative values.

maildir: Don't error on new mail

---

globals.h
mutt_account.c
mutt_config.c

Add the missing $smtp_user config variable.
This brings SMTP into line with IMAP and POP.

config: add $smtp_user

---

config/dump.c
config/dump.h
config/subset.c
config/subset.h

`elem_list_sort()` and `get_elem_list()` are used by the subset code.
Move them out of dump.c, which has GUI dependencies.

config: move functions to avoid dependency problems

---

bcache.c
email/url.c
email/url.h
imap/command.c
imap/imap.c
imap/util.c
mutt_socket.c
nntp/newsrc.c
nntp/nntp.c
pop/pop.c

`struct Url` contains lots of pointers and a `STAILQ` (for the query strings).
Many of the `Url` uses didn't fully initialise the struct, which could lead to problems.
- Initialise all Urls on the stack
- Add `url_new()`
- Encode '=' too, in `url_pct_encode()`
- Generate query strings in `url_tobuffer()`
- Rename vars to 'url'

refactor: tidy Url usage

---

doc/manual.xml.head
mutt_config.c
sidebar.c

Adds number of old messages as `%o` to `sidebar_format` variable.
Counting behaves the same like for `%o` in `status_format`
[![asciicast](https://asciinema.org/a/WiOjaa5g9QumpUrGfCjrtyTqu.svg)](https://asciinema.org/a/WiOjaa5g9QumpUrGfCjrtyTqu)
* **Example**
Initial state: there are 8 unread messages in a mailbox: 5 new (unread, not seen), 3 old (unread, already seen)
| first time visit | %N | %o |revisiting mailbox | %N | %o |
| ---                    | ---  | --- |---                    | ---  | --- |
| mark_old=yes |     8 |    3 | mark_old=yes |     8 |    8 | 
| mark_old=no  |     8 | N/A |mark_old=no  |     8 | N/A |

add Number of old messages to sidebar_format

---

command_parse.c
mutt_commands.c
mutt_commands.h

`unmailboxes *` didn't consider virtual mailboxes (at least those defined by named-mailboxes)
I tested both unvirtual-mailboxes and unmailboxes commands. I have mailboxes defined as `named-mailboxes name mailbox`, where mailbox is maildir, mbox and notmuch query.
```
unmailboxes *
unmailboxes name
unmailboxes /path/to/mailbox
unvirtual-mailboxes *
unvirtual-mailboxes name
unvirtual-mailboxes /path/to/mailbox
```
All tested cases behaves as expected.

Unify unmailboxes and unvirtual-mailboxes commands

---

maildir/shared.c

Turns out we cannot stop after detecting ",".
In case <base_filename> did not contain any extra comman separated files
we end up cutting off the flags only.
1581495693.R3771990984008251196.p50:2,S
would end up as
1581495693.R3771990984008251196.p50:2
but it needs to be
1581495693.R3771990984008251196.p50

maildir: sanitize filename before hashing v2

---

Makefile.autosetup
browser.c
compose.c
compress/compress.c
compress/lib.h
hook.c
imap/imap.c
imap/util.c
index.c
maildir/maildir.c
maildir/mh.c
mbox/mbox.c
mutt/path.c
mutt/path.h
mutt/string.c
mutt/string2.h
mutt_mailbox.c
muttlib.c
mx.c
mx.h
nntp/nntp.c
notmuch/mutt_notmuch.c
po/POTFILES.in
pop/pop.c
test/path/mutt_path_tidy_slash.c

This is a mixed bag of minor refactoring.
All low impact and low urgency.
- 00f5f06aa7 create libcompress
- 21bfa9fceb add mutt_str_strnlower()
- 1793aacb00 refactor: mutt_path_tidy_slash()
- 3eb9b0b2ed imap: tidy code
- 06428cb4c9 mxapi: tidy stat(2) usage
- 37dfd38e69 mxapi: add missing prototypes
- 6f411b96a1 libmutt: split tilde from canon

Light refactoring in preparation for the path changes

---

ncrypt/crypt_gpgme.c

In `decrypt_part` the gpgme context was correctly deinitialized before a
retry, but was not reinitialized due to an incorrect label location. This PR 
corrects the label position.
I'm not aware of relevant issues, but this PR fixes displaying of `smime-type=signed-data` inside of an encrypted envelope (not sure about the technically correct terms here) for me. These types of mails appear to be generated by Evolution and some apple mail client.

Fix context reinitialization in gpgme decryption

---

commands.c
mx.c

Make calls to mx_mbox_close() and mx_mbox_close() retain the same
value for m->append. This is import for special handling in
mx_mbox_close() of the append case.

Restore mailbox append flag after mbox_close

---

mutt_config.c

GPGme will satisfy all but the most technical of crypto users.

enable gpgme by default

---

muttlib.c
mx.c

`mutt_alias_lookup` is allowed to return NULL and thus we should try to
handle that case.
I have a macro in my neomutt configuration that is being rendered and
the template file contains placeholders like `@notmuchmutt@`. That
placeholder is then replaced with the path to the notmuch-mutt script. I
had a typo in the file so some occurrences were not being replaced
properly. Thus neomutt tried to use the `mutt_alias_lookup` function on
the string (since it contained the at-sign). That function did return
NULL and in the neomutt code we are then dereferencing `al` by using
`TAILQ_EMPTY`.
By properly checking if the `mutt_alias_lookup` invocation actually
returned something non-NULL we can work around this.

libmutt: fix segfault when alias lookup returns NULL

---

conn/connaccount.c

Oauth uses `$imap_login` to create its token.  If that doesn't exist, it tries `$imap_user`.
The delegation wasn't happening correctly, causing the connection to fail.
Fixes: #2130

oauth: if 'login' name isn't available use 'user'

---

mx.c

Revert some of a previous change; only use the url-splitting for IMAP.
Fixes: #2131

fix path comparisons

---

Makefile.autosetup
command_parse.c
compress/compress.c
config/dump.c
config/lib.h
config/mbtable.c
config/path.c
config/path.h
config/types.h
init.c
maildir/shared.c
main.c
mbox/mbox.c
mutt/path.c
mutt/path.h
mutt_config.c
mutt_lua.c
mx.c
po/POTFILES.in
test/Makefile.autosetup
test/config/dump.c
test/config/path.c
test/config/path.h
test/main.c
test/path/mutt_path_canon.c
test/path/mutt_path_pretty.c
test/path/mutt_path_tidy.c

Further sub-class some config items:
> alias_file, attach_save_dir, autocrypt_dir, certificate_file, debug_file, entropy_file, header_cache, history_file, message_cachedir, news_cache_dir, newsrc, signature, smime_ca_location, smime_certificates, smime_keys, ssl_ca_certificates_file, ssl_client_cert, tmpdir
Before, they had type `DT_STRING|DT_PATH`.
Even though they were labelled as Paths, they weren't treated any differently from strings.
Now, `DT_PATH` has been promoted to a full type, with sub-types: `DT_PATH_FILE` and `DT_PATH_DIR`.
When config values are stored, they will be tidied: `~` will be expanded, and junk like `//` or `/./` will be removed.
- 9212976282 config: add path type
- 44cc5f73b5 test: add config/path
- 81aef62c5c config: convert path variables
- 34c633d740 propagate …

config: add path type

---

main.c

Fixes: #2138
If NeoMutt is run **with** a `mailto` link, but **without** a terminal, e.g. from `xdg-open`,
then NeoMutt sends an empty email.  It doesn't give the user a chance to edit anything.
- Check we have a tty
- Make sure we log an error if we don't

abort if run without a terminal

---

index.c

Some commands act on the whole mailbox (tag-pattern, delete-pattern,
search), and even though they don’t do anything when the mailbox is
empty, there is no reason to fail when it happens. This commit removes
the check that the mailbox is non-empty before doing said actions.
This PR partially solved the issue of failing macros. It solves all cases where an existant message is not required, but it doesn’t handle cases where a macro would take both a user input AND a current message.
The functions I identified from that last case are:
- compose-to-sender (may not have a solution since a pre-input contains element from the selected message)
- edit-type (same)
- set-flag/clear-flag

Fix commands that don’t need to have a non-empty mailbox to be valid

---

globals.h
gui/curs_lib.c
keymap.c
keymap.h
main.c
mutt_config.c

This PR adds the "abort_key" config option which can be used to change the key
used to abort prompts (previously unchangeable, now per default Ctrl-G). The
key can specified in the same format as bind/macro commands.
In contrast to previous work (see #1510) this PR replaces the code that previously explicitly checks for the keycode of Ctrl-G with checks against the keycode of the key specified by the newly introduced config option `abort_key`.  I propose this solution because I am under the impression that this abort behaviour is so low-level that it cannot be handled via an <abort> command that could be assigned using `bind`.
It should probably also be noted that this PR does not include any changes to the ncurses ESCDELAY (changable via environment variable …

Add abort_key config option

---

globals.h
menu.c
mutt_config.c
muttlib.c

Adds new config option `arrow_string` which changes default `->` arrow_cursor
for that)
Actually I haven't found anything even about arrow_curor in manual.xml.head.
no need for that

add 'arrow_string' config variable

---

ncrypt/smime.c
postpone.c

Replaces calls of `mutt_str_replace` on `C_SmimeEncryptWith`  with `cs_subset_str_string_set`
effectively resolving  #2154

Fixes #2154 by replacing mutt_str_replace calls on C_SmimeEncryptWith

---

enter.c
globals.h
mutt_config.c

Fixes #2002
I have to admit I don't like the new behaviour either, I'm too used to hit backspace many time as a kill-line (yes I know shortcuts exist). Also, we have ctrl-g to abort a prompt. Let's at least allow users to opt-in / out.

Allow controlling the "abort on backspace" feature

---

mx.c

Fixes: #2171
LGTM warned against the use of `ctime()` which is becoming obsolete, so I created a03dbb4bcb.
Converting to `strftime()` caused the day/month names to be written in the user's locale, not English.
Use `strftime_l()` instead with a C locale.

bug: force C local for email date

---

main.c
mbox/mbox.c
mutt/file.c
send.c
sendlib.c

Commit 331702b6 was created to fix issue #2138.
Unfortunately, that broke sending email from the command line.
Rather than check for a tty on stdin, count how many bytes are available.
If there is none, abort.
Fixes: #2176

fix command line sending

---

mx.c

Use `mx_mbox_find()` to lookup `$trash` because it can compare Mailbox paths more carefully.
Recent changes have made it more likely that an IMAP Mailbox will include the `user@` prefix in its path.
This mean that some comparisons againts `$trash` were failing, so it was impossible to empty the trash.

fix emptying trash

---

ncrypt/cryptglue.c

Don't warn the user about gpgme if it isn't built-in.
Fixes: #2174
---
This eliminates the warning and the "Press any key" prompt, however...
The real problem is that many `crypt_*`, `pgp_*` and `smime_*` config variables aren't built conditionally.

quieten gpgme warning

---

Makefile.autosetup
conn/lib.h
conn/zstrm.c
conn/zstrm.h
imap/imap.c

The zstrm code creates a compressed wrapper around a Connection.

lib: move zstrm to libconn

---

auto.def

This turns
```
Checking for GPGMe...Checking for gpgme_op_export_keys...not found
1.13.1
```
into
```
Checking for GPGMe... 1.31.1
Checking for gpgme_op_export_keys...not found
```

Fix order of messages when checking for GPGMe

---

sidebar.c

Take care when comparing "$folder" against an IMAP Mailbox path
(the `user@` may not be present on both sides).
Fixes: #2173
Fixes: #2175

fix sidebar indent

---

commands.c
mutt/file.c
mutt/file.h
muttlib.c

This partially undoes ad00c1bf, which added symlink resolution to all
path expansions. It turnes out that broke attaching files via symlinks
because symlink resolution happens too early causing the attachment name
to reflect the actual target instead of the symlink (see #2168).
This commit adds a new API mutt_file_resolve_symlink and calls it where
needed. Right now, the only place I am aware of is when selecting a
target for saving a message.
Fixes #2168

Resolve symlinks only when necessary

---

gui/curs_lib.c

This fixes mutt_get_field_full to use the full size of the buffer
provided by the caller instead of the default buffer size, thus allowing
reading more than the default 1024 bytes allocated by the buffer pool.
Fixes #2155

Allow to read more than 1024 characters

---

notmuch/mutt_notmuch.c

Fixes a segfault when neomutt tries to insert a notmuch mail that doesn't exist
into the hcache.
I was previously observing the below crash. I believe it is just an oversight
due to the USE_CACHE ifdef. The error checking had to be moved before the
hcache insert call.
```
$ bt
#0  memcpy (__len=0xa8, __src=0x0, __dest=0x7ffdcc8a8890) at /nix/store/hycbi8v31600cimx211ilj8p922nharl-glibc-2.30-dev/include/bits/string_fortified.h:34
#1  dump (uidvalidity=0x0, off=0x7ffdcc8a8884, e=0x0, hc=0xc18330) at hcache/hcache.c:164
#2  mutt_hcache_store (hc=hc@entry=0xc18330, key=0xc7d820 "/some/path/that/doesn't exist",
keylen=0x65, e=e@entry=0x0, uidvalidity=uidvalidity@entry=0x0) at hcache/hcache.c:592
#3  0x000000000049d677 in append_message (h=h@entry=0xc18330, …
```

neomutt: don't segfault on missing mailfile when inserting into hcache

---

commands.c

When first opening NeoMutt, the pager Window might not have been sized.
This lead to `$COLUMNS` being set to `0`, causing mailcap problems.
---
To test:
- NeoMutt config: `auto_view text/html`
- Mailcap: `text/html; elinks -dump -dump-width ${COLUMNS:-80} %s; nametemplate=%s.html; copiousoutput`
- Start NeoMutt and immediately open an email with HTML part
Result:
- `elinks` fails because `$COLUMNS` is set, but is `0`

fix: COLUMNS env var

---

history/history.c

Config strings can be NULL, so use mutt_file_fopen() for safety.

use mutt_file_fopen() on config variables

---

.cirrus.yml
.travis.yml
compress/lib.h
test/Makefile.autosetup

This is mostly a test of my `.cirrus.yml` change.
I've added:
```yml
only_if: $CIRRUS_BRANCH == "master" || $CIRRUS_PR != ""
skip: $CIRRUS_PR_DRAFT == "true"
```
This should limit Cirrus builds to `master` and Pull Requests (but not draft PRs).
---
- doxygen: add missing link
- build: fix creation of wrong dir
- travis: add compress libraries
- cirrus: limit builds to master/PRs

build: minor fixes

---

compress/lib.h
compress/lz4.c
compress/zlib.c
compress/zstd.c
doc/manual.xml.head
hcache/hcache.c
hcache/lib.h
mutt_config.c

This PR will externalise the two config variables `C_HeaderCacheCompressLevel` and `C_HeaderCacheCompressDictionary` from libcompress. The library itself gets 2 new functions for this:
1. set_level()
2. set_dictionary()
The two are only called once before compress()
If the default compression level is okay, the calling of these functions is not needed.

Libcompress update

---

sidebar.c

Sidebar folder indenting and shortening only work on a mailbox's path.
However, the sidebar will always use a mailbox's name so indenting and
shortening does not work for 'virtual-mailboxes' or 'named-mailboxes'.
To support these operations, extend the indentation and shorten code to
use the name if it exists. This behavior is an extension of the current
behavior of names taking presidence.
Now the sidebar behaves more consistently across all mailbox types.
Closes #1594
Using the configuration in #1594, here's a comparison:
master
this branch:

sidebar: support indenting and shortening of names

---

main.c

Config variables that contain filesystem paths, should have `~` expanded
before saving.  For `DT_PATH`, this is done automatically.
Restore `reset_tilde()` so that `DT_MAILBOX` get their initial values correct.
Fixes: #2206

fix mailboxes with tildes

---

.cirrus.yml
.travis.yml
test/Makefile.autosetup
test/file/common.c
test/file/common.h
test/file/mutt_buffer_quote_filename.c
test/file/mutt_file_check_empty.c
test/file/mutt_file_chmod.c
test/file/mutt_file_chmod_add.c
test/file/mutt_file_chmod_add_stat.c
test/file/mutt_file_chmod_rm.c
test/file/mutt_file_chmod_rm_stat.c
test/file/mutt_file_get_size.c
test/file/mutt_file_lock.c
test/file/mutt_file_quote_filename.c
test/file/mutt_file_resolve_symlink.c
test/file/mutt_file_stat_compare.c
test/file/mutt_file_touch_atime.c
test/main.c

The tests aren't very exciting, they simply cover functions from `mutt/file.c`
The tricky part is the test files required for these functions.
They live in the [neomutt-test-files](https://github.com/neomutt/neomutt-test-files) repo.
First, Travis/Cirrus clones the repo.
The location is passed to `neomutt-test` using an environment variable `$NEOMUTT_TEST_DIR`
(we can't pass parameters to the Acutest program)
Most of the functions being tested are expecting a fully-qualified path.
The test function expands a template, "%s/file/empty", using the environment variable, and tests a function with the result.

test: add test files

---

index.c

The 'entire-thread' command when executed outside a notmuch mailbox has
two operations:
1. Create a notmuch mailbox with only the current email.
2. Use Notmuch to get the thread based on message ID.
Commit e7682da912a64d1fe54b8a126dc072ef1699b5a5, removed the 'CUR_EMAIL'
macro, and replaced all usages with initializing 'e_cur' or 'e_cur' if
initialized within the scope.
However, 'entire-thread' relied on calling the macro twice when in a
non-notmuch mailbox. The first invocation returns the current email in
the non-notmuch mailbox for creating a notmuch mailbox, and the second
invocation returns the current email inside the notmuch mailbox. In
refactoring the macro, 'e_cur' never updates and holds the value of the
non-notmuch mailbox email.
To resolve the issue, update the 'e_cur' …

index(entire-thread): update current email pointer

---

README.md

shields.io images aren't loading properly.
From IRC several days ago:
```
2020-03-26 15:48:19     flatcap hmm... Travis has prompted me to 'migrate' things from travis-ci.org to .com ...
```

change travis-ci.org to travis-ci.com

---

mutt/date.c
mutt/date.h

Change the `timeout` parameter to be a `time_t`.
On the [x32 arch](https://wiki.debian.org/X32Port), `time_t` is 64-bit and `long` is 32-bit.
This meant that one of the 64-bit test `timeout`s was being truncated to 32-bits making the test fail.
Fixes: #2237

fix: mutt_date_add_timeout()

---

mutt/prex.c
test/url/url_parse.c

Allow spaces and square brackets in paths (e.g., [Gmail]/Sent messages)

---

send.c

Issue #2243 wants to send empty emails, but that conflicts with issue 2138
where empty emails were being sent by mistake.
For now, disallow: `neomutt user@example.com < /dev/null`
in favour of:      `echo | neomutt user@example.com`
Add an error message to suggest this behaviour.
> Refusing to send an empty email
> Try: `echo | neomutt -s 'subject' user@example.com`
Closes: #2243

add error for CLI empty emails

---

Makefile.autosetup
auto.def
docs/manual.xml.head
hcache/hcache.c
store/lib.h
store/rocksdb.c
store/store.c

This PR will add support for the RocksDB key/value Store backend. The database homepage is located here: https://rocksdb.org/ - and it's stable and fast. I also added a new environment configuration variable called  `$ROCKSDB_COMPRESSION` - I hope this is okay, if not, tell me how I should change the configuration stuff, to fit nicely into neomutt source.
The Documentation is updated, I hope my english is not to bad for that ;)

store: add RocksDB backend

---

address/address.c
address/address.h
compose.c
index.c
menu.c
mutt_menu.h

- Compose dialog uses multiple Windows
- `To:`, `Cc:` and `Bcc:` fields now span up to 5 lines
- `To:`, `Cc:` and `Bcc:` fields are now wrapped at address boundaries
- `To:`, `Cc:` and `Bcc:` fields indicate overflow with `(+3 more)`
- Truly fluid layout -- expand Envelope section to fit contents
---
Sample data: https://gist.github.com/flatcap/dfe02d1c71f080ca1de48409f8be0bad
```
neomutt -n -d1 -F names.rc -F auto.rc -f /dev/null
```
Press <kbd>F1</kbd> to open the compose menu.

Refactor the Compose screen

---

browser.c

Rearrange `mutt_buffer_select_file()` so that we can pass a Menu to `examine_directory()`.
Fixes: #2199

browser: fix hidden mailboxes

---

conn/raw.c
hcache/hcache.c
hcache/hcachever.sh
hcache/lib.h
hcache/serialize.c
hcache/serialize.h
imap/command.c
imap/imap_private.h
imap/message.c
imap/util.c
maildir/shared.c
mutt_logging.c
progress.c
progress.h

- `mutt_date_epoch_ms()`
Ensure variables are 64-bit (even on 32-bit arches)
- IMAP `UIDVALIDITY` is 32-bit
shrink variables to match
- Bump hcache version
The `UIDVALIDITY` change affects all records in the header cache

correct variable sizes

---

auto.def
mutt/prex.c

This introduces support for running pre-defined / pre-compiled regular expressions (prex) using PCRE2. In contrast with #2258, PCRE2 is **not** used for the regular code including user-defined regular expressions. This is to avoid incompatibilities when it comes to POSIX vs. PCRE syntax and semantics.

Add support for using PCRE2 in prex

---

browser.c
command_parse.c
commands.c
config/regex.c
config/regex2.h
conn/gnutls.c
email/parse.c
gui/color.c
gui/color.h
gui/curs_lib.c
hook.c
index.c
menu.c
mutt/charset.c
mutt/prex.h
mutt/regex.c
mutt/regex3.h
mutt_menu.h
mutt_parse.c
mutt_parse.h
muttlib.c
pager.c
pattern.c
pattern.h
protos.h
query.c

Make sure everyone uses "mutt/regex3.h" - that'll make it easier to switch to another regex engine, if we ever decide to do that.

Centralize regex includes

---

opcodes.h

A recent refactoring altered the ordering of the OPs when autocrypt was enabled.
This mean that OP_NULL wasn't 0 any more, causing some functions to break.
Fixes: #2268

ensure OP_NULL is always first

---

test/url/url_parse.c

* Test that we do not parse mailto URIs with fragment (#) chars in their query values. This is illegal according to https://tools.ietf.org/html/rfc6068#section-2.
* Test that we can parse such an URI when the fragment (#) char is properly %-encoded.

Add tests for the use cases in #2276

---

imap/imap.c
mutt/prex.c
test/url/url_parse.c
version.c

`[:alnum:]` doesn't match characters outside of ASCII. Let's use `\p{L}\p{N}` (letters and numbers) instead. This only matches a subset of printable characters, but should be enough for most cases (UTF-8 IMAP mailbox names).
Fixes #2283

Avoid crashing / handle UTF-8 URL paths

---

address/address.c
test/address/mutt_addrlist_parse.c

Correctly parse escaped characters in header phrases

---

docs/manual.xml.head
mutt_config.c

Keeping header_cache_backend unset disables use of header caching, which
is surprising; document that.
It might be nicer to fall back to one of the compiled-in backends, if
there's one.
Fixes documentation.
for that)
* …

docs: make header cache config more explicit

---

sidebar.c

After the refactor in commit d77c704ceb85f34061e1333ab9c8eb5a264a0685,
the sidebar only displays a mailbox's full path/URI except in the case
of 'sidebar_short_path'. The full path/URI is not preferable for end
users.
What broke during the refactor is how the variable 'display' is updated.
It's initialized to a mailbox's full path/URI and only updated if using
'sidebar_short_path'. However, after initialization, an abbreviation is
calculated to remove the 'folder' or protocol.
To resolve this issue, if there's an abbreviation, store it in the
'display' variable.
Fixes #2293
Using minimal config (`test/test` is just an empty file):
```
set folder="~/mail/austin@austinray.io"
set sidebar_visible=yes
unmailboxes *
mailboxes =INBOX =test/test
```

fix(sidebar): use abbreviated path if possible

---

index.c
sidebar.c

Because of lack of proper error propagation functions could return
without touching `buf`.
Initializes such buffers.
Fixes #2145. (And absolutely not sure, but maybe #2110 (at least the garbage).)

Make sure buffers are initialized on error

---

contrib/sample.neomuttrc-starter

So entered password won't be saved in bash history.

sample.neomuttrc-starter: Do not echo promted password

---

gui/mutt_window.h

The function declaration had a different meaning compared to the
function definition, as `row` and `col` where swapped.
As the row and column have the same type, it did not cause a linking
error.
Apparently all the places where `mutt_window_get_coords` has been used,
it has been used consistently, so just changing the definition is
enough.

Fix function declaration of mutt_window_get_coords

---

test/acutest.h
test/common.c
test/main.c
test/rfc2047/rfc2047_decode.c
test/rfc2047/rfc2047_encode.c
test/test_common.h
test/url/url_parse.c

- Update to [latest acutest.h](https://github.com/mity/acutest/commit/cde0c8e699c843b70c978a1b66a11b346c933957)
- Use the `test_init()` function for all tests:
- Check `$NEOMUTT_TEST_DIR` is set
- Set the locale to `en_US.UTF-8` or `C.UTF-8`
Fixes: #2309

acutest updates

---

enter.c
index.c
main.c
mutt_mailbox.c
mutt_mailbox.h

`main_change_folder()` is too complicated.  It's called from five places in a variety of different ways.
Some callers pass a Mailbox, other pass a string.
Replace it with three simpler functions:
- `change_folder_mailbox()` - Change to a different Mailbox by pointer
- `change_folder_notmuch()` - Change to a different Notmuch Mailbox by string
- `change_folder_string()` - Change to a different Mailbox by string
Next refactor the **`case`** blocks in mutt_index_menu().
- `OP_MAIN_CHANGE_FOLDER`, `OP_MAIN_CHANGE_FOLDER_READONLY`
- `OP_MAIN_CHANGE_GROUP`, `OP_MAIN_CHANGE_GROUP_READONLY`
- `OP_MAIN_ENTIRE_THREAD`
- `OP_MAIN_NEXT_UNREAD_MAILBOX`
- `OP_MAIN_VFOLDER_FROM_QUERY`, `OP_MAIN_VFOLDER_FROM_QUERY_READONLY`
- `OP_MAIN_WINDOWED_VFOLDER_BACKWARD`
- `OP_MAIN_WINDOWED_VFOLDER_FORWARD`
- …

refactor: main_change_folder()

---

imap/util.c
mutt_config.c

This changes how imap_fix_path understands a delimiter in an IMAP path.
Previously, the first occurrence of any of the characters in
C_ImapDelimChars was taken to be the delimiter for the path. Now, the
server-provided delimiter - if any - always takes precedence.
This makes C_ImapDelimChars a mere fallback.
Fixes #2110

imap: use the connection delimiter if provided

---

imap/command.c

Issue #2303
This is a first approach a fixing the issue. Instead of returning an error that ultimately ends up being handled as a fatal error + mailbox close, let's just show a message to inform the user that one of the IMAP commands has failed.
```
IMAP command failed: a0306 NO Mailbox doesn't exist: FooBar (0.001 + 0.000 secs).
```
I cannot foresee all implications of not returning an error, but at least we'd get some feedback and data to work on.

Inform but don't fail on IMAP NO/BAD responses

---

addrbook.c
autocrypt/acct_menu.c
browser.c
compose.c
conn/gui.c
debug/notify.c
gui/curs_lib.c
gui/mutt_window.c
gui/mutt_window.h
gui/reflow.c
index.c
index.h
main.c
mutt/notify_type.h
mutt_history.c
ncrypt/crypt_gpgme.c
ncrypt/pgpkey.c
ncrypt/smime.c
pager.c
postpone.c
query.c
recvattach.c
remailer.c
resize.c
sidebar.c

In ["Event-Driven Sidebar"](https://neomutt.org/dev/roadmap/event-sidebar), I map out the route to splitting up the Windows and encapsulating them.
Many of the required notifications, e.g. Config, Colour, are already in place.
This PR adds Window notifications.
- e0ecb92ada window: rename dlg_index
unify naming
- c17e983be4 window: name and notify
ensure all user-visible windows are named (debug only) and have notifications support
- 3ebcd28900 window: set_visible
helper function to make a window (and its children) visible or hidden
- a459d75001 notify: windows
send out notifications on window changes
- 0fa17ab368 debug: notify windows
update debugging to dump all window events
---
The debug logging looks like this:
```
[pager] visible 
[pager bar] visible 
[index] taller [10->39] 
[index …
```

Window notifications

---

mx.c

Otherwise hangs indefinitely, requiring SIGKILL
Fixes #2318

Error out when an mbox/mmdf mailbox is a pipe

---

Makefile.autosetup

This PR:
- Merges the separate Makefile blocks for each library
- Sorts the merged blocks
- Moves `MUTTLIBS` to the end to solve the dependencies
---
`Makefile.autosetup` currently has 22 libraries and each library adds two sections to it.
```make
###############################################################################
LIBADDRESS=     libaddress.a
LIBADDRESSOBJS= address/address.o
CLEANFILES+=    $(LIBADDRESS) $(LIBADDRESSOBJS)
MUTTLIBS+=      $(LIBADDRESS)
ALLOBJS+=       $(LIBADDRESSOBJS)
```
... lots of other libraries ...
```make
$(LIBADDRESS): $(PWD)/address $(LIBADDRESSOBJS)
$(AR) cr $@ $(LIBADDRESSOBJS)
$(RANLIB) $@
$(PWD)/address:
$(MKDIR_P) $(PWD)/address
```
After merging, we get:
```make
############################################################################### …
```

tidy makefile

---

maildir/mh.c

Fixes: #2324 
- Check for either new folder flags
- Use `mutt_file_mkdir()` in case dir already exists

mh: fix creating new mailbox

---

mbox/mbox.c

Fixes: #2325
A lot of shared functions weren't allowing **`MUTT_MMDF`**, only `MUTT_MBOX`.

mmdf: fix creating new mailbox

---

context.c

Fixes: #2333 
After editing a message, NeoMutt performs a 'new mail' update, which wipes and recalculates the Mailbox stats.
One of these numbers, `Mailbox->msg_tagged` wasn't getting updated, so `<tag-prefix>` failed thinking there weren't any tagged messages.

fix tagged message count

---

query.c

`mutt_mem_calloc()` does not alloc and returns NULL on zero items. In this
case `query_table` must not be dereferenced.
Fixes a crash.

Fix crash inside empty query menu

---

imap/command.c

Fixes #2331
This is still far from being optimal. The problem is that we end up receiving an error in two cases:
1. interactive case, such as login: here, we really want to know that the login failed so we can e.g., try with the next auth metod.
2. batch, such as STATUS for `mailbox-list`: here, we don't want to fail because some mailbox cannot be STATUS'd and we just want to go on.
With this change, we'd probably go back to square one wrt non-existent subscribed mailboxes. At least we'd have a nice error message, though.

Partially undo #2317: inform AND fail

---

docs/manual.xml.head
docs/neomuttrc.man.head

Adds missing `unbind` and `unmacro` commands to neomuttrc(5) man pages.
Also fixes namings for **map** vs **menu** for `unmacro` to match marco
desciption in NeoMutt manual.
for that)
should have been already added in #1599 
No code added, no need to
- Code follows the [style …

Add missing commands for unbind and unmacro to neomuttrc manges

---

test/string/mutt_str_atol.c
test/string/mutt_str_atoui.c
test/string/mutt_str_atoul.c
test/test_common.h

Check size of long using LONG_MAX instead of __WORDSIZE

---

compmbox/compress.c
core/mailbox.h
imap/imap.c
imap/message.c
index.c
maildir/shared.c
mbox/mbox.c
mx.c
nntp/nntp.c
notmuch/mutt_notmuch.c
pager.c
pop/pop.c
query.c
sort.c

Invert the `Mailbox->quiet` logic to reduce the number of negative `if`s.
There are ~60 uses of the `quiet` flag, but the vast majority are of the form:
```c
if (!m->quiet)
mutt_message();
```
This is replaced by:
```c
if (m->verbose)
mutt_message();
```
---
Ultimately, this flag shouldn't be part of `Mailbox` but removing it will take some time.

Rename Quiet to Verbose

---

sidebar.c

Picked up by coverity, the `sizeof()` should have been a `strlen()`.
I've also added `!= 0` to the `mutt_str_strncmp()` as it returns an `int`.

sidebar: fix path comparison

---

handler.c

Restore CRLF->LF conversion in base64 decoding for text/inline parts 

---

browser.c
command_parse.c
core/mailbox.c
core/neomutt.c
core/neomutt.h
email/rfc2231.c
email/rfc2231.h
email/tags.c
imap/browse.c
imap/imap.c
init.c
mutt/list.c
mutt/list.h
mutt_mailbox.c
sendlib.c
sidebar.c
test/list/mutt_list_str_split.c
test/neo/neomutt_mailboxlist_get_all.c
test/rfc2231/rfc2231_encode_string.c

These commits don't change the behaviour of the functions, just the manner in which they return a list.
Refactor: `neomutt_mailboxlist_get_all()`, `rfc2231_encode_string()` and `mutt_list_str_split()`.
They used to allocate a TAILQ on the stack, then return the object.
This leads to a bug when the List is returned empty.
The functions now add their results to a List passed in as a parameter.
---
When the STAILQ is initialised, `stqh_last` is set to the address of    
`stqh_first` which equates to the address of the STAILQ itself.    
The STAILQ is on the stack.    
If the function returned without adding anything to the STAILQ, the    
`stqh_last` pointer would now be invalid, pointing to the now-dead stack.

Refactor unsafe TAILQ returns

---

auto.def

This flag makes package managers such as Guix and Nix able to make their
neomutt package not reference "split outputs" library packages.
Fixes #2366.

Enable in ./configure to not record cflags

---

send.c

generate_body works on a potential list of mails but mutt_inline_forward
was taking an optional pointer on a mail and could list itself the
mailbox. Now it takes a non optional pointer and the generate_body is
reponsible for calling the function as many time as it has mails tagged.
It also fixed the fact that one could not tag several messages and
forward them at once via ';f'.

send.c: make mutt_inline_forward usage consistent in generate_body

---

command_parse.c
config/address.c
config/bool.c
config/enum.c
config/long.c
config/mbtable.c
config/number.c
config/path.c
config/quad.c
config/regex.c
config/set.c
config/set.h
config/slist.c
config/sort.c
config/string.c
config/subset.c
config/subset.h
docs/manual.xml.head
docs/neomuttrc.man.head
init.c
mutt.h
test/config/long.c
test/config/number.c
test/config/set.c
test/config/subset.c

Implements **+=** and **-=** operators to the config system.
- WIP in command_parse.c
- need to separate the addition substraction logic to a separate functions.
Remaining tasks:
```
flatcap | jindraj: [devel/config-increments]  It works!  Yeah!  So the next step is to
add plus_equals() minus_equals() to the ConfigSetType
flatcap | you'll need some glue functions in config/set.c and config/subset.c
flatcap | then you can change parse_set() to allow/disallow +=,-= based on the support
(and get them to do the work)
```
**To do**:
#243 + #2236 (dup)

Add += and -= to a config system

---

auto.def

The qdbm library exports a subset of the gdbm API, e.g., gdbm_open.
Moreover, auto.def prepends libraries to LIBS as they are found.   Let's
* check for qdbm before gdbm, so it's library appears before gdbm's
* check for a gdbm symbol that's not exported by qdbm

Avoid locating gdbm symbols in qdbm library

---

imap/imap.c
imap/message.c
imap/private.h
imap/util.c

The IMAP backend could end up opening the same header-cache file twice. This is not supported at least by LMDB. Make sure we cache the hcache handle and reuse it if needed.

Avoid opening the same hcache file twice

---

mbox/mbox.c

Use the message count for calculating the percentage for syncing mbox mailboxes instead of `ftello()` which was always zero.
Closes #2383

Fix progress percentage when syncing large mboxes

---

mx.c

This fixes the comparison when folder and spoolfile are local mailboxes
(simple filesystem paths), for which url_parse fails.
Fixes #2402

Check folder against spoolfile by simple string comparison first

---

alias/dlgalias.c
alias/dlgquery.c
autocrypt/acct_menu.c
browser.c
compose.c
conn/gui.c
core/account.c
core/mailbox.h
core/neomutt.c
gui/curs_lib.c
gui/mutt_window.c
gui/mutt_window.h
index.c
main.c
mutt/notify.c
mutt_history.c
ncrypt/crypt_gpgme.c
ncrypt/pgpkey.c
ncrypt/smime.c
postpone.c
recvattach.c
remailer.c

These small changes pave the way for a bigger reorganisation.
Currently, there's **lots** of code which **tells** various components to update themselves.
e.g.  The Index to Sidebar:
- `mutt_index_menu()`
- `index_custom_redraw()`
- `menu_redraw_sidebar()`
- `sb_draw()`
Ideally, the Index should be unaware of the Sidebar.
The Sidebar should observe Events, such as "Mailbox opened", "Window resized", and update itself.
These changes help the first step, the setting up of a Window.
- 4a39262b95 move notify setup
All Windows will have a Notify (before, some containers were skipped)
- 98246bb743 start redraw framework
Windows can support `recalc()` and `repaint()` methods
- da87d7ca45 add remove_child()
For symmetry with `mutt_window_add_child()`
- 3e81566bc3 organise notifications
Add …

Refactor: Window architecture

---

Makefile.autosetup
auto.def
main.c
mutt/lib.h
mutt/random.c
mutt/random.h
muttlib.c
muttlib.h
sendlib.c

These four functions have no dependencies and wide usage, so they belong in the library:
- `mutt_rand32()`
- `mutt_rand64()`
- `mutt_rand_base32()`
- `mutt_randbuf()`
Also change the preferred random method from a Linux syscall, to `getrandom(2)` (available on Linux and BSD).

move random functions to libmutt

---

docs/manual.xml.head
mutt_config.c

The current default `sidebar_format` uses `%B`, which displays the
mailbox path. Replace `%B` with `%D` to display mailbox names if user
uses named-mailboxes or virtual-mailboxes declarations.
With changes in #2389 stopping the sidebar from always displaying names,
despite `%B`, for named and virtual mailboxes, users will no
longer see the names. The current default forces named and virtual
mailbox users to update the default to see the names. This is
undesirable as those feature appears broken with default settings.
---
With minimal config:
```
set folder="~/mail"
set sidebar_visible=yes
named-mailboxes "Mailbox" "notmuch://?query=tag:inbox"
```
Before:
After:
Additionally, we should aware of #2389 will require all existing notmuch users with custom sidebar formats to update as they …

fix(sidebar): use %D in default format

---

compmbox/compress.c
imap/imap.c
index.c
index.h
maildir/maildir.c
maildir/mh.c
maildir/private.h
maildir/shared.c
mbox/mbox.c
mutt/string.c
mutt/string2.h
mutt_header.c
mx.c
mx.h
nntp/nntp.c
notmuch/notmuch.c
pager.c
pop/pop.c
postpone.c

This PR gets rid of the ugly `index_hint` variable that was passed around into the mx API. Now the index uses the selected email's message id to keep track of the cursor position and to refresh itself when the selected mailbox changes. 
Accidentally, this fixes an issue whereas the cursor position in the index was wrongly reset after an email disappeared (e.g., because it was deleted from another client).

Track currently selected email by msgid

---

icommands.c

Refactor `icmd_set()` to NOT create a tmp file unless needed.
Fixes: #2414

refactor icmd_set()

---

main.c
mx.c
mx.h

Allow opening neomutt with a mailbox name with `neomutt -f <name>` if
name exists in the user's configuration.
To support this behavior, introduce 4 new functions to provide a new
high-level abstraction for finding mailboxes and lower-level
name-specific functionality.
- mx_resolve() - Find a mailbox by checking name then path.
- mx_name_resolve() - Resolve a mailbox by name.
- mx_mbox_find_by_name() - Search all accounts for Mailbox with name.
- mx_mbox_find_by_name_acc() - Search a specific account for Mailbox.
Since 'mx_resolve()' is a new high-level abstraction for finding a
mailbox, replace call 'mx_path_resolve()' with 'mx_resolve()' in
'main.c'. The initial mailbox open only needs a Mailbox struct.
Closes #2101

feat: open neomutt with mailbox name

---

index.c
index.h
pager.c

This introduces a SelectedEmail struct to keep track of both the receive
time and the message id of the currently selected email. This way, when
the index is resorted, we first check for timestamps and only use string
comparison if the timestamps match. That should make the checking
faster.

Optimize checking for the current email in the index

---

sidebar.c

This commit changes sidebar indentation to respect user settings. Commit
6f01b47af53a15089ceb05e5651914ecaebb379a changed sidebar to always
indent, which disregarded 'sidebar_folder_indent' value. As such, the
behavior is forced on the user even if a user does not want indentation.
We should respect the user's decision.

fix(sidebar): respect sidebar_folder_indent

---

Makefile.autosetup
command_parse.c
command_parse.h
index.c
init.c
main.c
menu.c
mutt_commands.c
mutt_config.c
mutt_globals.h
pager.c
sidebar/commands.c
sidebar/functions.c
sidebar/lib.h
sidebar/observer.c
sidebar/private.h
sidebar/sidebar.c
sidebar/wdata.c

This PR reorganises the Sidebar to make it more like a plugin.
Currently, the Index and other components, **drive** the Sidebar by calling functions.
Ideally, the Sidebar, once initialised, should **react** to Events.
This is a step in that direction.
To the user, there should be no visible change.
- b14846f55f create library
Move the source into `sidebar/`
- 73550c61f7 `init()`, `shutdown()`
Create the 'plugin' setup for the Sidebar
- 6d5092181e decouple from index
Move the Sidebar creation out of the Index
The Sidebar observes the creation of the Index Dialog, then inserts itself
- 2be08eda3c add window data
Create a place for the Sidebar-specific data
The SidebarWindowData will be attached to the Sidebar Window
- c0218a8b32 encapsulate data
Wrap the Sidebar globals and move them to …

Make the Sidebar more independent

---

auto.def
mutt_lua.c

Trying to fix build failures against lua version 5.4
one test is actually failing:
`test_mutt_file_stat_compare...` always returned `0`

trying to fix building against lua 5.4

---

debug/window.c
docs/config.c
gui/mutt_window.c
index.c
test/Makefile.autosetup
test/gui/visible.c
test/main.c

Fixes: #2426
**To reproduce**:
- `set pager_index_lines = 0`
- Open email in pager
- `set pager_index_lines = 5`
**Expected**:
- 5 lines of index displayed at top of screen
**Actual**:
- A line of index would be displayed at the bottom of the screen.
---
To hide some windows (e.g. Index, Index bar), simply hide one of their parents.
Before, I was **hiding** each, but only **showing** the parent.

Fix: redrawing of pager_index_lines

---

debug/graphviz.c
debug/lib.h
email/email.c
email/email.h
hcache/hcache.c
hcache/hcachever.sh
maildir/maildir.c
maildir/private.h
maildir/shared.c
notmuch/notmuch.c
notmuch/private.h
test/email/common.c

This PR is a little sleight-of-hand.
It has no visible change to the user (and barely any for the developer).
**Note**: This change alters the header caching.
`maildir_flags` used to be cached (unnecessarily, as they're rebuilt from the filename)
---
[`struct Email`](https://github.com/neomutt/neomutt/blob/master/email/email.h#L37) has an [`edata`](https://github.com/neomutt/neomutt/blob/master/email/email.h#L107) member where backends can store private Email data.
This `edata` is used by Notmuch which means that Maildir can't use it (as the two backends share Emails).
This PR swaps the priorities around.
Maildir, as the base, gets to use `edata`, whilst Notmuch uses a private member in Email.
---
- 4e1b4a68d notmuch: hide details of edata
Use a helper, `nm_edata_get()` rather than …

Adjust the edata use in Maildir and Notmuch

---

autocrypt/config.c
config/dump.c
config/dump.h
config/set.h
conn/config.c
docs/manual.xml.head
hcache/config.c
helpbar/config.c
history/config.c
imap/config.c
init.c
init.h
maildir/config.c
main.c
mbox/config.c
mutt_config.c
ncrypt/config.c
nntp/config.c
notmuch/config.c
pattern/config.c
pop/config.c
send/config.c
sidebar/config.c

This trivial PR adds one-liner help to all the config items.
The docs can be viewed from the command line:
- `neomutt -D -O` (or `-DO`) - view all config
- `neomutt -O -Q name` - for a single config item
```sh
set visual = "/usr/bin/nvim"
set wait_key = no
set weed = yes
```

add docs to config items

---

imap/imap.c
mx.c
mx.h

Incidentally, this also allows to have "postponed" on a different
account.
Fixes #2430

Fix retrieval of drafts when "postponed" is not in the mailboxes list

---

recvattach.c
send/send.c
send/sendlib.c

Also, fix a failing stat(2) on the parent part, which doesn't have a
filename.
This unveils another problem: going back to the main loop in
mutt_send_message causes the alternative group to break. Trying to
recreate the group generates a new "unknown alternative group" part.
I think that's common to any code-path that does a goto main_loop in
mutt_send_message.
Fixes #2435

Check for missing attachments in alternative parts

---

index.c

`mx_mbox_check` can free the current email (e.g., because it was copied to some other mailbox). Make sure we refresh the mailbox state before tracking the current email.

Refresh current email after refreshing mailbox state

---

context.c
imap/imap.c
imap/lib.h

The Mailbox and Imap keep separate lists of Emails:
- `Mailbox.emails[]`
- `ImapMboxData.msn_index[]`
When `ctx_update_tables()` deletes an Email, it's vital to tell Imap so its pointers aren't invalidated.
Fixes: #2549

imap: fix crash in cmd_parse_expunge()

---

imap/imap.c

Prevent a failed SUBSCRIBE command from generating a new (unaccessible) mailbox in the sidebar / mailboxes view.

Avoid creating mailboxes for failed subscribes

---

hcache/hcache.c

Creates a path of directories for a nonexistant file hcache case. Path was only created for the directory cases.

Create directories for nonexistent file hcache case

---

notmuch/notmuch.c

This pull request contains three distinct changes (please don't squash):
1. Don't lock up Neomutt if it can't sync a Notmuch mailbox. Syncing may fail if Neomutt and Notmuch go out-of-sync. Instead of leaving users in an situation that requires a significant effort to fix the syncing issue, sync what's possible then notify user. This is not an optimal solution, but the user experience is enhanced until root cause is tracked down. Otherwise, users have to exit the mailbox without saving or undo their changes to the mailbox.
2. Update the email's path immediately after modifying tags. This ensures Neomutt and Notmuch stay more in-sync.
3. Query Notmuch for email's filepath if Neomutt thinks it doesn't exist. External modification with `notmuch` may cause Neomutt …

notmuch: improve synchronization with neomutt

---

maildir/maildir.c

When sending an email, the 'fcc' copy doesn't have a `MaildirEmailData`.
This meant that `maildir_gen_flags()` was failing, so the filename was missing its flags.
Without the flags, NeoMutt thinks it must be a new email.
Fixes: #2587

fix: maildir flag generation

---

alias/dlgalias.c
alias/gui.c
alias/gui.h
functions.c

This PR adds the capability of the address book screen to update  on `$sort_alias` configuration changes.
for that)
I don't think it does meet the acceptance criteria. What does need to be documented here? …

Live Sorting in Address Book

---

main.c

Fix neomutt not getting past startup:
```
nabijaczleweli@tarta:~/uwu/neomutt$ gdb ./neomutt
GNU gdb (Debian 8.2.1-2+b3) 8.2.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" …
```

Don't crash with no Context and no explicit folder

---

alias/dlgalias.c
alias/dlgquery.c
alias/gui.c
alias/gui.h
functions.c

Just like the Address Book Live Sorting PR, this one adds Sort and Reverse Sort functions to the Query window, where the user is able to sort the information by alias and address. It is also possible to "unsort".
A lot of the code from the PR mentioned above was reused.
I also took the liberty of putting the `alias_sort_observer` and the `alias_color_observer` functions into `alias/gui.c`, since they are both used by `dlgalias.c` and `dlgquery.c`.
There is no relevant issue number. (Is it needed?)

Query Live Sorting

---

sidebar/window.c

#2596 shifted around some code which resulted in failing to indent named mailboxes.

Restore indentation for named mailboxes, lost in #2596

---

command_parse.c
compose.c
core/account.c
index.c
sidebar/functions.c
sidebar/observer.c
sidebar/private.h
sidebar/sidebar.c
sidebar/window.c

After the refactor 093f19824, the Sidebar was ignoring notifications about new or removed mailboxes.
- Handle new Mailboxes
- Handle removed Mailboxes
- Ensure painting is done when there are only hidden Mailboxes
- Refactor for clarity

Fix sidebar on new/removed mailboxes

---

Makefile.autosetup
alias/config.c
alias/dlgalias.c
alias/dlgquery.c
alias/lib.h
mutt_config.c
mutt_globals.h

This PR moves Address configuration into its own configuration inside `alias`.
Then it is initialized through `CONFIG_INIT_VARS`.
The relevant issue number is #2621 , being this PR related to the first bullet point.
Hope everything okay. I did test it, everything seems to be working, sorting, alias file, etc.

Issue #2621: Move address config into libaddress

---

compose.c
compose.h
docs/config.c
mutt_config.c

Add `C_ComposeShowUserHeaders/compose_show_user_headers` which defaults to
true and determines whether user headers should be displayed in the
compose screen.
(See PR #2614 for more details on these custom headers)
This is the first part of #2622

Add show user headers config

---

email/email.c
email/email.h
hcache/hcache.c
index.c

* b3f077a : use an incrementing sequence number to track emails
* c3c5688 : fix index tracking so the current email is not set too early
Fixes #2588

Fix tracking the current email in the index

---

auto.def

I'm not sure why we didn't think to add this sooner.
However, I couldn't figure out how to check if ASAN was actually installed.
I tried:
```
if [cc-with { -libs -fsanitize=address }] {
```
and
```
if [cctest -link 1 -libs -fsanitize=address] { 
```
Nothing quite worked.
Those that didn't fail, also meant that all the later checks had the Sanitizer compiles flags, too.

build: Add the Address Sanitizer

---

debug/notify.c
gui/color.c
gui/color.h
helpbar/helpbar.c
menu.c
sidebar/observer.c

Refactor the Color Event so that it works like the other Event notifications.
The Color Event now has two subtypes `#NT_COLOR_SET` and `#NT_COLOR_RESET` and passes the actual color in the Event data struct (instead as the subtype).
#2640

Refactor the Color Event

---

alias/dlgalias.c
alias/dlgquery.c
alias/gui.h
docs/manual.xml.head
pattern/exec.c
pattern/lib.h
pattern/pattern.c

This PR adds the possibility of using patterns (e.g.: `~b EXPR` to search comments`) in the Alias and Query menus.
In this PR there are three different patterns that can be used:
- `~f EXPR` - Alias
- `~t EXPR` - Address
- `~b EXPR` - Comment
The relevant issue number where this was discussed is #2621.

Issue #2621: Add patterns to alias/query

---

pattern/exec.c
pattern/pattern.c

I've changed the "simple search" case for Aliases..
If the user doesn't put a pattern in the search, the code used `C_SimpleSearch` to expand the pattern.
Unfortunately, that isn't meaningful for Aliases (wrong `~` patterns).
It now expands to `~f %s | ~t %s | ~c %s`
This is hard-coded to match on **any** Alias field.
I'm not sure if it's worth making this into a config variable.
Any thoughts?

alias: fix simple searches

---

imap/imap.c
imap/message.c

Index is used for [reverse-|last-]mailbox-order. Most backends assign an
increasing number to each Email as it's created parsing the mailbox. For
IMAP, we have the luxury of UIDs assigned for us by the server, see
https://tools.ietf.org/html/rfc3501#section-2.3.1.1
This saves us from reassigning ascending numbers on expunge, which was
the cause for the bug.
Fixes #2651

Use the email's IMAP UID instead of an increasing number as index

---

pattern/compile.c

Fixes #2653
I think the mismatch between the return type and how it's checked was introduced by 4a6cf9e30ddf949b4df2999f73268db11c4b67e0.

Fix checking the return of the eat_* APIs

---

pattern/compile.c

I was instructed to change appearances of `mutt_str_copy()` which write into a buffer to `mutt_buffer_addstr` or `mutt_buffer_copy`.
Now, the only occurrence I could still find that wasn't writing into a char[] was the one here.  
Considering that addstr doesn't make too much sense and copy isn't applicable, I've used the strcpy variant, which seems to do what we want?

Use mutt_buffer_strcpy instead of mutt_str_copy

---

browser.c

~Do not try to parse the IMAP path as an URL, which it is not, as the
regex engine might or might not eat Unicode characets.  Instead, use a
simple string-based algorithm to decide whether we need to add a
separator to LastDir.~
The path will eventually be `url_parse`'d anyway, so just check for a failure and avoid crashing.
Fixes #2666
P.S. this is not the highest level of confidency I've ever had, i.e., things I am not foreseeing might break.

Fix crash on failure to parse a URL

---

bcache/bcache.c

- If message_cachedir is not a valid directory, create a temporary directory
- Prevents remote backends (imap, pop, nntp) to repeatedly fetch messages during the same session
A _suggestion_ to ease symptoms described in #1949.

Show error when message_cachedir is invalid

---

sidebar/functions.c

Commit 7e743a9fe63bea20d20070e34c86837083790005 "Convert Sidebar entries to ARRAY" incorrectly inverted a `do {} while(!has_new && msg_unread == 0)` into `if(has_new && msg_unread != 0)`, whereas the correct De Morgan is `if(has_new || msg_unread != 0)`
Fix a regression against 20200821
Closes #2670

Fix <sidebar-{next,prev}-new>

---

command_parse.c
compose/compose.c
email/email.c
email/email.h
mutt/notify_type.h
test/Makefile.autosetup
test/email/email_header_add.c
test/email/email_header_find.c
test/email/email_header_free.c
test/email/email_header_set.c
test/email/email_header_update.c
test/main.c

Adds notifications for `my_hdr` changes (note, nothing added for `unmy_hdr`):
* Add utilities for navigating and updating headers to share logic with `my_hdr` parsing
* Refactor parse_my_hdr using new header utils
* Add notification type for headers
* Add header notifications for `parse_my_hdr`
*  Add header observer in compose screen
Add an observer for NT_HEADER events that updates the current email's
header and redraw the screen if my_hdr adds or updates a header.
#2622

my_hdr compose screen notifications

---

index.c

Please see commit e15cbe5 for context on how 'entire-thread' functions
internally for non-notmuch mailboxes.
This commit fixes a regression in 467c06c where the current email in
the second mailbox isn't passed to 'nm_read_entire_thread()'. We have to
use the 'mutt_get_virt_email()' call to get the current email.
Without this patch, users have to execute 'entire-thread' twice. Once to
get into a notmuch mailbox with a single email then again for the entire
thread.
Partially addresses #2597

fix(entire-thread): query for current email

---

conn/sasl.c
conn/sasl.h
imap/auth.c
imap/auth.h
imap/config.c
pop/auth.c
pop/config.c
pop/private.h
send/config.c
send/smtp.c
send/smtp.h

Adds validators to {imap,pop,smtp,nntp}_authenticators config variables. This also includes some refactoring of code in some files.
#2583 .
* **Things to Review**
Obviously the whole commit should be looked at for errors etc. but here are the key areas I would like input/confirmation on:
1. **Placement of function declarations**: `bool {imap,pop,smtp,nntp}_auth_is_valid()` functions are placed in .h files to make them visible to the validator functions. I just want to make sure they're not wandering in the wrong places :).
2. **Changes in `smtp/`**: Namely, I added a SmtpAuth multiplexor (similar to imap and pop's) and slightly modified `smtp_auth()` and `smtp_auth_sasl()`. I tested them and they work fine, but I want …

Add validators for {imap,smtp,pop,nntp}_authenticators

---

auto.def

Change the build flags:
- Replace `-O2` with `-O0` (turn off optimisations)
- Add `-fno-omit-frame-pointer -fno-common`
as suggested here, https://github.com/google/sanitizers/wiki/AddressSanitizerFlags

build: improve ASAN flags

---

compmbox/compress.c
imap/imap.c
maildir/maildir.c
maildir/mh.c
main.c
mbox/mbox.c
mx.c
mx.h
notmuch/notmuch.c
pop/pop.c

Move `mx_check_empty()` into the mx_ops and rename to `mx_path_is_empty`.
The actual business logic is moved to the backends.

Move mx_check_empty into mx_ops

---

send/send.c

prints error using mutt_perror when signature file is missing, or doesn't have enough permissions

add warning when signature file is missing or not readable

---

sidebar/window.c

Fixes #2311
Because of us checking that mbox length be strictly greater than folder length, we were missing the opportunity to shorten `C_Folder`.

Handle the case where a mailbox is "folder"

---

send/header.c

This will ensure that postponed mails are written with a Date header.
rfc5322 says the Date field must be there for an email to be valid.

Change postpone mode to write Date header too

---

hdrline.c
notmuch/lib.h
notmuch/notmuch.c

Changes the behavior of '%b' in 'index_format' to display the email's
folder instead of the notmuch query if it exists. In a notmuch mailbox,
the current behavior of index_format's %b' expando displays the query
portion of a notmuch mailbox declaration.
The reference documentation for 'index_format' says '%b' shows "Filename
of the original message folder (think mailbox)". By my interpretation,
displaying the notmuch query is incorrect as it _is not_ the original
message folder. The underlying maildir folder _is_ the original message
folder. Therefore it should be shown instead.
[0] https://neomutt.org/guide/reference.html#3-169-%C2%A0index_format
* **Some decision considerations**
1. This brings the `%b` behavior in line with other local mailboxes; however, it only displays the last part …

feat(notmuch): show originating folder in index

---

imap/browse.c

Cleans up (in my view) a redundant str len call after copying a string.
Was there a particular reason why the size variable was a short instead of a size_t? Seems roundabout to me, even if the destination buffer size fits in a short as is.

imap/browse: avoid redundant function call

---

alias/alias.c

Fix a crash when trying to access the config variable `alias_file` as a string instead of as a path.
This was introduced in 6f79d959b2d2ca88898ab0c24e4caa70af56967c.

crash: alias_file is a path, not a string

---

mbox/mbox.c

Fixes the detection of mbox files with new mail.
mbox_mbox_check_stats() is supposed to return the number of new messages, but if flags = 0 we only look at mtime and atime values without actually parsing the mbox file, so we don't know how many new messages there are.  We just know there are _some_, so let's return 1 and hope for the best.
**Screenshots (if relevant)**
for that): pretty sure bugfixes are not mentioned in the manual
- All builds and tests are passing: hopefully?  I ran `make …

Fix detection of mbox files with new mail

---

index.c

Replace 'e.cur' with 'e_oldcur' similar to commit 19eb4cbd6. Since
19eb4cbd6 established 'e.cur' as "stale" in the second mailbox, it's
probable that it'll cause an issue when calling
'mutt_uncollapse_thread()'.
Fixes #2736

fix(entire-thread): stop crash on collapsed thread

---

send/send.c

The bug was introduced in this chunk of 999e51eb43ec028fcd31a3fe8b3f9587037c898d
```diff
-      mutt_addr_append(&out->to, in->to, true);
-      mutt_addr_append(&out->cc, in->cc, true);
+      mutt_addresslist_copy(&out->to, &in->cc, true);
+      mutt_addresslist_copy(&out->cc, &in->cc, true);
```
Fixes #2745

Fix group-chat-reply

---

docs/config.c

The documentation was bogus'd in 8ffa473227cd121a88aeb7512569dc651a361992.
Fixes #2721

Restore correct `sort_re` documentation

---

index.c

A folder-hook might have various effects on the mailboxes.
1. opening of an existing mailbox: `unmailboxes ...` might make it
invalid (the previous code was guarding against this case)
2. opening of a new mailbox: `mailboxes ...` might create and link to an
account the same mailbox we're trying to open (the new code guards
against this case too)
3. both of the above, which resulted in a crash in the sidebar
Fixes #2743

Always recreate a mailbox after folder-hook

---

compmbox/compress.c
imap/imap.c
maildir/maildir.c
maildir/mh.c
mbox/mbox.c
mx.c
mx.h
nntp/nntp.c
notmuch/notmuch.c
pop/pop.c

The `ac_find` API does not find anything, it either returns NULL on
failure or the first argument on success. It's actually a boolean
function, so let's name it accordingly.

Rename API ac_find into ac_owns_path

---

command_parse.c
core/mailbox.c
core/mailbox.h
sidebar/private.h
sidebar/sidebar.c
sidebar/sort.c

This fixes the generation order of mailboxes by regenerating the value when a hidden mailbox becomes visible again. This happens when the currently open mailbox is `unmailboxes...`'d and `mailboxes...`'d again.
Fixes #2750

Reset a Mailbox's gen value when it becomes visible

---

index.c
pager.c

When the terminal is resized (or the font-size is changed),
the screen must be redrawn.  This *used* to involve clearing the entire
screen.  Soon, it will be delegated to individual windows to refresh
themselves.
In the mean time, forcibly clear the MessageWindow.
Fixes: #2749
---
To repeat the bug:
In the Index, or Pager: reduce the height of the window by a line or two.
This will cause the Status Bar to be duplicated in the Message Window.
Rapidly reducing the height could sometimes cause the Index lines (or Pager contents) to be left in the Message Window.

clear the message window on SIGWINCH

---

browser.c
commands.c
commands.h
context.c
context.h
index.c
main.c
menu.c
pager.c

The simple fix would be to check for Context (and Context->mailbox)
inside mutt_shell_escape, but I really think mutt_mailbox_check belongs
at the caller's.
Fixes #2757

Do not crash on return from shell-exec if there's no open mailbox

---

auto.def
compmbox/compress.c
conn/openssl.c
docs/config.c
mutt_config.c
test/file/mutt_file_mkstemp_full.c

Termux (Android) and Debian packagers would like to be able to configure the
/tmp location to somewhere else. Add a corresponding --with-tmpdir option.
The docs of neomutt (https://neomutt.org/dev/build/autosetup) say that if you set a default option eg `with-mailpath:=/var/mail   => "Location of the spool mailboxes"` you should be able to get the default by using `[opt-val with-mailpath]`. However at least on my machine that isn't actually working and I need to repeat the default argument there.

Make the location of /tmp configurable

---

docs/manual.xml.head

Adaptation of the upstream patch 
https://gist.github.com/flatcap/9d701d2ec21057dd77c6f685c56647c6#file-0002-clarify-pattern-completion-uses-complete-patch
Manual chapter 4 "Advanced Usage " section 5 "Using Tags" now mentions that tags are completable

docs: clarify pattern completion
