neomutt/neomutt

init.c
**Upstream patch**
https://gist.github.com/flatcap/9d701d2ec21057dd77c6f685c56647c6#file-0005-ensure-mutt_extract_token-never-returns-a-null-dest-patch
**Upstream commit message**:
Commit e5a32a61 removed a 'mutt_buffer_addch (dest, 0)' at the end of
the function.  Most callers had been converted to use the buffer pool,
and the call was strange since buffers self-terminate.
However, this line covered up logic errors in some of the callers,
which assumed the buffer->data could not be NULL afterwards.
I will try to fix up callers with the logic errors in master.  This is
to fix the problem in stable, and also ensure future callers don't
make the same mistake.
=> Ensure mutt_extract_token() never returns a NULL dest->data

hcache/serialize.c, icommands.c, init.c, mutt/base64.c, mutt/buffer.c, mutt/buffer.h, muttlib.c, test/pattern/extract.c
upstream patch: https://gist.github.com/flatcap/9d701d2ec21057dd77c6f685c56647c6#file-0006-add-mutt_buffer_rewind-function-patch
This makes it a bit clearer what the assignment is doing, and reduces
direct dptr manipulation a bit.
=> Add mutt_buffer_seek() function

docs/neomutt.man
upstream patch: https://gist.github.com/flatcap/9d701d2ec21057dd77c6f685c56647c6#file-0003-mutt-man-h-clarify-that-a-from_-line-in-the-draft-fi-patch
man: -H: clarification
`From` line in the draft file is silently discarded because this is likely an mbox file
=> man: -H: clarification

imap/message.c
Upstream patch https://gist.github.com/flatcap/9d701d2ec21057dd77c6f685c56647c6#file-0010-abort-imap-open-if-condstore-qresync-updates-fetch-f-patch
Abort IMAP open if condstore/qresync updates fetch fails
An error in imap_cmd_step() was not being properly returned to the
caller.
=>  Abort IMAP open if condstore/qresync updates fetch fails

send/smtp.c
Upstream patch: https://gist.github.com/flatcap/9d701d2ec21057dd77c6f685c56647c6#file-0013-fix-smtp-debug-segfault-on-invalid-smtpauthenticator-patch
sasl_client_start() sets the mech parameter only on success.
mutt_debug(LL_DEBUG) the whole mechlist on failure.
=> Fix smtp debug segfault on invalid C_SmtpAuthenticators list

pager.c
Upstream patch: https://gist.github.com/flatcap/9d701d2ec21057dd77c6f685c56647c6#file-0007-fix-pager-dropped-input-on-sigwinch-flag-handling-patch
Fix pager dropped input on SigWinch flag handling
The code to process the SigWinch flag ocurred after, and would drop an
input character when the flag was set outside of, km_dokey().  This
could happen, for instance, when a pipe operation was invoked.
Thanks to Vincent Lefèvre for uncovering the problem.
=> Fix pager dropped input on SigWinch flag handling

send/sendlib.c
When libsend's was converted to use the config system, rather than global variables, a typo was introduced.
Fixes: #2788
---
History:
.   8e3bda144 merge: Convert libsend to use Config functions
|\  
| . 4e434fe55 send: get Config from a ConfigSubset -- **BAD COMMIT**
| . 8732a7280 config: add Config helpers
| . 3e0667e93 send: add ConfigSubset param to functions
| . d8a6a6c19 smtp: move mutt_fqdn() to mutt_smtp_send()
| . 6e686c31c smtp: pass SmtpAccountData
|/  
. 9d6fb50e5 refactor icmd_set
---
Code before conversion (using `C_MimeForwardDecode`):
https://github.com/neomutt/neomutt/blob/9d6fb50e5dafc614bfddde55e0c00c83dd9247f6/send/sendlib.c#L958-L959
Code after conversion (uses `$forward_decode`, `c_forward_decode`):
https://github.com/neomutt/neomutt/blob/4e434fe5564430ad23d00eb7886f8 …
=> fix mime forwarding

docs/manual.xml.head, functions.c, mutt_attach.c, mutt_attach.h, opcodes.h, recvattach.c
This uses a copiousoutput mailcap entry, or falls back to raw text.
The existing functions do not provide a way to use copiousoutput
mailcap entries exclusively.  The default <view-attach> will use one
for internally supported types if auto_view is configured, but there
is no way to do so for other mime types (such as application/pdf).
Upstream-commit: https://gitlab.com/muttmua/mutt/commit/474d368e859aa86b4adf9e41f1048488ece99c42
https://gist.github.com/flatcap/9d701d2ec21057dd77c6f685c56647c6#file-0004-add-view-pager-function-to-attachment-menu-patch
=> Add <view-pager> function to attachment menu

send/send.c
Recently, I converted `libsend` to use the config system, rather than the `C_*` global varaibles.
Unfortunately, calling hook functions can invalidate config variables that we've already fetched.
I've traced all the callers of `mutt_parse_rc_line()` and `*_hook()` and found that there's only a bug in one place.
1. `mutt_send_message()` stored the value for '$editor'
2. A hook fired which set the value for '$editor'
3. The config system freed the original string, leaving a dangling pointer
=> config: get values after hooks

docs/manual.xml.head, functions.c, opcodes.h, pager.c
This is based on `<skip-quoted>`, and is bound to 'H' by default.
I've added an error message in case there is no text past the headers,
just to cover the logical case.  I don't think Mutt allows that to
happen for text passed to the pager, but just in case.
Upstream-commit: https://gitlab.com/muttmua/mutt/commit/42331065e432c03903eac2fc8cc2aa94f7da501e
=> Add <skip-headers> to skip past message headers in pager

commands.c, commands.h, imap/imap.c, imap/lib.h, imap/message.c, index.c, mx.c, pager.c
This PR has many refactorings of `mutt_save_message()` function.
Each commit is atomic and results in a green build.
Brief overview of changes:
- `decrypt` and `decode`  boolean flags are merged into `enum MessageTransformOpt` 
- `delete_original` boolean flag is changed into `enum MessageSaveOpt`
- upstream patch https://gist.github.com/flatcap/9d701d2ec21057dd77c6f685c56647c6#file-0008-add-a-mutt_error-when-copy-save-messages-fails-patch
- `single` local variable is removed as unneded in favor of `msg_count` that was already present
- various whitespace, formatting, naming changes,  minor code restructuring to improve readability
Please see individual commit messages for details and explanations.
=> mutt_save_message refactoring

command_parse.c, compmbox/compress.c, imap/imap.c, imap/message.c, imap/private.h, index.c, maildir/lib.h, maildir/maildir.c, maildir/mh.c, maildir/private.h, maildir/sequence.c, mbox/lib.h, mbox/mbox.c, mutt_mailbox.c, mx.c, mx.h, nntp/nntp.c, notmuch/notmuch.c, pager.c, pop/pop.c, postpone.c
Small API tidying.
The structure `MxOps` in mx.h defines the interface that mailbox backends such as mbox, maildir, or IMAP implement. The scope of this PR is to review and clean up this API, e.g.,
* functions returning `int` with values `0` (success) and `-1` (failure) can be changed to return `bool`
* functions returning `int` with values `0` (something), `1` (something else), `2` (something different) can be changed to return an `enum`
=> MX API review

mx.c
Compiling on macos will give
```mx.c:1113:7: error: use of undeclared identifier 'locale_t'```
Error
To counteract that Added header for OSX.
Added OSX Platform-specific headers
=> Added Locale headers for OSX platforms

alias/alias.c, alias/dlgquery.c, autocrypt/autocrypt.c, browser.c, commands.c, compose/compose.c, conn/connaccount.c, conn/sasl.c, gui/curs_lib.c, gui/curs_lib.h, imap/browse.c, imap/imap.c, index.c, menu.c, mutt_header.c, muttlib.c, ncrypt/crypt_gpgme.c, ncrypt/pgp.c, ncrypt/pgpkey.c, ncrypt/smime.c, notmuch/notmuch.c, pager.c, pattern/pattern.c, recvattach.c, recvcmd.c, send/send.c
Simplify the callers for all the `enter_field()` functions.
Expand:
- `mutt_get_field()` to `mutt_get_field_full()`
- `mutt_buffer_get_field()` to `mutt_buffer_get_field_full()`
- `mutt_buffer_enter_fname()` to `mutt_buffer_enter_fname_full()`
- `mutt_get_password()` to `mutt_get_field_unbuffered(MUTT_PASS)`
Then rename:
- `mutt_get_field_full()` to `mutt_get_field()`
- `mutt_buffer_get_field_full()` to `mutt_buffer_get_field()`
- `mutt_buffer_enter_fname_full()` to `mutt_buffer_enter_fname()`
Call Tree before and after:
| |
| --: |
| <img width='800' src='https://gist.github.com/flatcap/d120ee4a39aad9365a94f4a5d23b8f51/raw/b836b41e3d327fc46b9a37e043a06556637641e4/enter_before.svg'> |
| <img width='500' src='https://gist.github.com/flatcap/d120ee4a39aad9365a94f4a5d23b8f51/raw/b836b41e3d327 …
=> Eliminate the macros from all the enter_field() functions

docs/manual.xml.head
Move sort after sed to prevent the sub-directory test/baba[/cur] from sorting before its parent test[/cur]
=> Fix mailboxes command for Maildir

imap/imap.c
(Re)fixes #2823
I think I previously misunderstood the reason why I wasn't able to push
labels to GMail. Now everything seems to work fine.
=> Fix caching new labels in the header cache

.gitignore
This is a small quality of life improvement for those wanting to use the clangd[0] language server protocol (LSP) implementation. It obviates the need to exclude clangd's configuration and cache when making a commit. I've found clangd to be a productivity multiplier when working with C.
[0] https://clangd.llvm.org/
=> misc: ignore clangd lsp files

auto.def
If CC happens to be "ccache cc", exec will fork with literally "ccache
cc" as the first argument. We need to expand it.
=> List-expand CC in [exec]

docs/config.c, init.c, mutt_config.c, mutt_globals.h, send/send.c
- 619f926b18 config: deprecate $visual
Config variable hasn't been used in a long time
- 16923700c4 config: fix editor defaults
`$EDITOR` env var wasn't being honoured, when `$editor` neomutt config wasn't set
- 3d42e5706d config: fix signature warning
Only warn about a missing signature file **IF** the user set the config
=> config: fix a couple of small bugs

core/account.c, imap/imap.c, mx.c
Imagine the sequence `unmailboxes *`; `change-folder`. The currently open
mailbox cannot be removed by `unmailboxes *`, which only marks it as
hidden. Then, on `change-folder`, the current mailbox is closed, but
nobody notifies the Account that the mailbox is gone, so in case of IMAP
the connection to the old server stays around.
=> Cleanup account data when closing the last mailbox

docs/manual.xml.head, docs/neomuttrc.man.head, hook.c
This is helpful if we want to match mailbox that comes from a variable exactly (or we simply can't be bothered to escape the whole thingie).
As an example, in `folder-hook -noregex $trash set my_foo=bar` we don't want an expansion of `$trash` such as `imaps://user@gmail.com/[Gmail]/Trash` to be treated as a regex containing a character class `[Gmail]`.
An alternative approach would be to create different commands with an additional flag
```
{ "folder-hook-noregex",  mutt_parse_hook,  MUTT_FOLDER_HOOK | MUTT_HOOK_NOREGEX}`
```
and handle the flag in `mutt_parse_hook`. I'm fine with implementing either approach.
=> Allow a -noregex param to folder and mbox hooks

commands.c, gui/curs_lib.c, gui/curs_lib.h, help.c, icommands.c, index/index.c, mutt_attach.c, ncrypt/dlggpgme.c, ncrypt/dlgpgp.c, pager/lib.h, pager/pager.c, send/sendmail.c
Begins monumental pager refactoring:
- introduces `PagerMode` enum
- removes `IsEmail`, `IsAttach` and `IsMsgAttach` macros
- splits `struct Pager` into `struct PagerData` and `struct PagerView`
- does some code readability improvements that help @ngortheone to stay a bit more sane
- adds tons of comments
=> pager: monumental refactoring part 1.

alias/dlgalias.c, alias/dlgquery.c, commands.c, commands.h, copy.c, copy.h, gui/color.c, hook.c, imap/imap.c, index/index.c, init.c, pattern/compile.c, pattern/lib.h, pattern/pattern.c, postpone.c, score.c, test/pattern/comp.c
These commits reduce function dependencies.
They mostly eliminate the use of the global `Context`.
- 3d3d009b07 strip gui dep from `mutt_check_traditional_pgp()`
Crypto functions should know about GUI flags
- b86af1a2ae context: eliminate from pattern functions
Don't pass a Context parameter when only a Mailbox is needed
- 2ac84e2974 context: eliminate from alias/query
The alias/query patterns don't need a Context/Mailbox
- 0f44eb4d17 context: eliminate from `mutt_save_message_ctx()`
Pass a Context paramater, rather than using the global
- 237cb9f811 context: reduce complexity of `complete_all_nm_tags()`
Simple tidying
=> refactor: Don't use the global Context when not necessary

commands.c
This fixes #2875
The only other place this function is used other than to calculate when
to redraw changes in compose is in `recvattach_edit_content_type`, but I
think this change improves that.
Not exactly sure of the context around why a user would want to change
the content type of a recieved email, but I can't trigger the longer
path in that function without the changes in this commit
It's either this or undoing the redraw check made in 49e4decd88
=> Return type_changes too for mutt_edit_content_type

mutt/notify.c
When adding observers, check the global_data when looking for duplicates.
Some observers will add the same callback function multiple times, differing only by their associated data.
=> observer: check global_data

command_parse.c
We we are in attach-message mode, we have a stack of two mutt_index_menu
running, and the global Context refers to the mailbox we're browsing to
select the files to attach. The mailbox in the background, where we were
when we started to compose a new message, must be kept alive even if it
is not currently in the Context.
As a side effect, this decontextualizes command_parse.c.
Fixes this use case:
1. open +Inbox
2. compose
3. attach-message, chose another mailbox, e.g., +Sent
5. unmailboxes *
6. <kbd>q</kbd> to get back to compose
7. crash
Fixed #2874
=> Do not remove "active" mailboxes

mx.c
Fixes a change-folder-readonly +Foo, followed by change-folder +Foo,
which was keeping the folder read-only with no way to get back to a
read-write state.
=> Don't propagate read-only state across reopens

commands.c, gui/curs_lib.c, gui/curs_lib.h, help.c, icommands.c, index/index.c, mutt_attach.c, ncrypt/dlggpgme.c, ncrypt/dlgpgp.c, pager/lib.h, pager/pager.c, send/sendmail.c
Here is @ngortheone's Pager refactoring.
There's quite a lot of churn, because the Pager code is a extremely complicated,
but the main changes are fairly straightforward.
- **Remove references to the global variable `Context`**
The Index should pass in a parameter `struct Context *ctx` instead.
- **Move local variables into `struct PagerData` and `struct PagerView`**
The goal is to turn the Index/Pager into sets of functions that work upon some shared data.
- **Define specific modes of display: Viewing: email, plain text, help, etc**
Eliminate the cryptic macros which used to determine behaviour.
This may lead to separate top-level functions for displaying: emails, plain text, help, etc
- **Eliminate some static variables which controlled behaviour**
Like the mode macros, these variables …
=> pager refactoring

commands.c, docs/manual.xml.head, email/body.h, handler.c, mailcap.c, mailcap.h, mutt_attach.c
~Disable wrapping in the pager if the data is being generated by a mailcap command.~
This implements a new mailcap extension flag, `x-neomutt-nowrap`, to disable wrapping in the pager for particular mailcap entries.
=> Provide a mean to turn off wrapping output of mailcap commands

ncrypt/crypt_gpgme.c
Previously, flags that show keys to be revoked/expired/disabled were
not transfered from the gpgme_key_t to KeyFlags for smime, even though
they were for pgp keys.
Not sure if there are any. I've just noticed that neomutt kept showing me a list of smime keys for contacts where all but one of them were expired and I went to see why. Turns out that there is code that checks for/filters valid keys (in particular paths that use `pgp_show_unusable`), but the flags that indicate invalidity were never set.
=> Set invalidity flags for gpgme/smime keys

alias/dlgalias.c, alias/dlgquery.c, autocrypt/dlgautocrypt.c, browser.c, conn/dlgverifycert.c, gui/dialog.c, gui/dialog.h, history/dlghistory.c, main.c, menu.c, ncrypt/dlggpgme.c, ncrypt/dlgpgp.c, ncrypt/dlgsmime.c, pattern/dlgpattern.c, postpone.c, recvattach.c, remailer.c
There are 13 'Simple' Dialogs - those screens that have a single window and limited interaction with the user.
- 357b78addd menu: make observers menu-specific
Eliminate some global dependencies
(Most of the diff is moving two functions, without change)
- 7d856b03e4 window: refactor simple dialogs
Move a couple of pairs of functions into the shared code:
- `mutt_menu_new()` / `mutt_menu_free()`
- `mutt_menu_push_current()` / `mutt_menu_pop_current()`
<details>
<summary>Simple Dialogs</summary>
| Function                         | Description                                 |
| :------------------------------- | :------------------------------------------ |
| `dlg_select_alias()`             | Display a menu of Aliases                   |
| `dlg_select_attachment()`        | Show the …
=> Simpify the code for the 'Simple' Dialogs

mutt/notify.c
Filter out just the notifications types the user wants.
Observing `NT_ALL` will give an unfiltered view.
This should reduce the torrent of callbacks.
(I _thought_ I'd already done this)
=> limit observer callbacks to a single type

notmuch/db.c
Show error when directory provided in `nm_default_uri` doesn't exist, or isn't directory. The same applies for subdir `./.notmuch`
for that)
#2891
=> Show error if nm_default_uri{,/.notmuch} doesn't point to a valid dir

compose/compose.c
The Pager is expecting an Email when viewing an attachment.
Fixes: #2895
=> compose: pass Email to pager

notmuch/notmuch.c
Fix for #1818.
append_message() has is_old hardcoded to false, which might make
messages that are old be moved back to the `new` subdirectory in
a maildir when calling maildir_sync_mailbox_message() later.
Update `Email.old` in update_message_path() so it matches
the detected maildir subdirectory.  As update_message_path() is
always called by init_email(), `Email.old` will always be
consistent with maildir message paths.
for that)
- not applicable
- build …
=> notmuch: Update Email.old when a maildir file path is detected

docs/manual.xml.head
The required format for `nm_default_url` exists in section 8 of the
notmuch feature page[0] and the neomuttrc manual. However, users using
section 4[1] to discover configuration options may miss the required
format and receive a config. error. While the error message contains the
correct format, it's sub-optimal user exprience. A better user
experience is noting the required format in section 4 so a user never
receives an error.
[0] https://neomutt.org/feature/notmuch#8-%C2%A0neomuttrc
[1] https://neomutt.org/feature/notmuch#4-%C2%A0variables
=> docs(notmuch): specify `nm_default_url` format

attachments.c, hdrline.c, pager/pager.c, recvattach.c, recvcmd.c, recvcmd.h, send/send.c, send/send.h
Some Config items have format strings that allow Mailbox properties:
```sh
set attribution = "On %d, %n wrote:"
set forward_attribution_intro = "----- Forwarded message from %f -----"
set forward_attribution_trailer = "----- End forwarded message -----"
set forward_format = "[%a: %s]"
set indent_string = "> "
set post_indent_string = ""
```
Ultimately, these end in calls to `index_format_str()`.
By dropping the Mailbox parameter, we remove the possibility of using a few expandos
| Expando | Description                                                        |
| :------ | :----------------------------------------------------------------- |
| `%b`    | Filename of the original message folder (think mailbox)            |
| `%B`    | The list to which the email was sent, or else the folder …
=> formats: drop Mailbox param

attachments.c, attachments.h, commands.c, copy.c, copy.h, editmsg.c, hdrline.c, index/index.c, maildir/maildir.c, maildir/mh.c, mbox/mbox.c, mx.c, ncrypt/crypt.c, ncrypt/crypt_gpgme.c, ncrypt/crypt_gpgme.h, ncrypt/crypt_mod.h, ncrypt/cryptglue.c, ncrypt/lib.h, ncrypt/smime.c, ncrypt/smime.h, nntp/nntp.c, pager/pager.c, pattern/exec.c, recvattach.c, recvattach.h, send/send.c, send/sendlib.c, test/pattern/dummy.c
This reduces the number of calls to mx_msg_open when viewing a message,
its attachments, or limiting the index, by trying to call mx_msg_open as
soon as possible and pass the resulting Message or FILE pointer down.
This has impact mostly on IMAP w/o `message_cachedir`.
Some net results:
- `<display-message>` then `<view-attachments>` fetches the message once
instead of twice
- limiting with `|` or `&` with patterns that require a full message
(e.g., `~M`) fetches the message once instead of once per branch of
the conditional
=> Try to avoid redundant mx_msg_open calls

index/index.c, pager/lib.h, pager/pager.c
This makes the log viewer  of `<show-log-messages>` always scroll to the bottom, so the most rececent log lines are visible.
=> Focus the logs pager view to the bottom

pattern/exec.c
This _may_ fix #2915
`pattern_needs_msg()` checks for `MUTT_PAT_MIMETYPE`, `MUTT_PAT_WHOLE_MSG` and `MUTT_PAT_MIMEATTACH`
but `pattern_exec()` has three cases: `MUTT_PAT_BODY`, `MUTT_PAT_HEADER` and `MUTT_PAT_WHOLE_MSG`
=> fix crash in msg_search()

hcache/hcache.c
Don't save `Email->notify` to the header cache.
When restoring from the cache, preserve the existing `notify` value.
Fixes: #2919
=> hcache: preserve Email->notify

compose/compose.c, debug/common.c, gui/curs_lib.c, gui/mutt_window.h, gui/simple.c, index/index.c, index/observer.c, pager/pager.c, test/pattern/dummy.c
Preparation for some Menu refactoring.
- efe7372ff8 compose: ensure focus is on Menu
- 93830484be index: move private data to panel
- d1e54c269e window: focussed Window is a Menu
All the Windows whose `wdata` is a `struct Menu`, now have type `WT_MEMU`.
This will allow us to find the 'current' Menu, e.g. for refreshes, without needing a global stack.
With the new naming, the Index/Pager now looks like:
- WT_DLG_INDEX
- WT_SIDEBAR
- WT_CONTAINER
- WT_INDEX
- WT_MENU
- WT_STATUS_BAR
- WT_PAGER
- WT_MENU
- WT_STATUS_BAR
=> Eliminate Menu Stack - Part 1

gui/color.c
Fixes: #2928
If the user hasn't configured any quoted-email colours, then NeoMutt tries to calculate a value modulo zero!
=> fix crash with uncoloured quotes

mutt/string.c, mutt/string2.h, notmuch/query.c, test/Makefile.autosetup, test/main.c, test/notmuch/query_type.c, test/string/mutt_istrn_rfind.c
Fixes an implementation error in query type parsing where having a `type=messages` parameter before a `type=threads` parameter can override the a correct threads query type.
=> Fix notmuch query type parsing

.github/ISSUE_TEMPLATE/config.yml
Change the IRC address in the GitHub issue template from FreeNode to
Libera. Commit 069cd6a01 updated the IRC information elsewhere.
=> docs: update irc address in github issue template

mutt_attach.c
Fixes attachment view when using a custom script in mailcap that is disowned.
An example for PNG images:
```
image/png; mkdir -p /tmp/neomutt/ && notify-send 'Test' %s && cp %s /tmp/neomutt && sxiv /tmp/neomutt/$(basename %s) & disown
```
I would ask for more testing from other people and @TornaxO7 .
I did some testing:
Test with `& disown` (example above)
Test without `& disown`
Test with the one I use: `image/*; /usr/bin/feh %s; copiousoutput`
#2926
=> Always add attachement to temporary list for it to be cleaned later

Makefile.autosetup, notmuch/lib.h, notmuch/notmuch.c, notmuch/tag.c, notmuch/tag.h, po/POTFILES.in, test/Makefile.autosetup, test/main.c, test/notmuch/tag.c
Refactors the three spots of tag parsing into a single low-level, unit tested function. This removes redundancy and makes the higher-level functions easier to understand.
This is the first time I've used the array API so hopefully it's correct.
=> notmuch: refactor tag parsing

alias/dlgalias.c, alias/dlgquery.c, autocrypt/dlgautocrypt.c, browser.c, commands.c, compose/cbar.c, compose/compose.c, conn/dlgverifycert.c, flags.c, gui/curs_lib.c, gui/mutt_window.c, gui/mutt_window.h, gui/sbar.c, gui/simple.c, history/dlghistory.c, index/ibar.c, index/index.c, index/observer.c, menu/menu.c, ncrypt/dlggpgme.c, ncrypt/dlgpgp.c, ncrypt/dlgsmime.c, pager/do_pager.c, pager/pager.c, pager/pbar.c, pattern/dlgpattern.c, postpone.c, recvattach.c, remailer.c
Some more preparation for the Window event/focus changes that are coming soon.
- 6b12157c4 **use one status bar type**
Each Window used to have a unique type.
Now it seems simpler to have some generic types like, `WT_MENU` or `WT_STATUS_BAR`
- 211c44275 **add `window_status_on_top()`**
Given a Window containing children `WT_MENU` and `WT_STATUS_BAR`, swap them around.
- 3ae97b5d4 **unify handling of `$status_on_top`**
Use the new helper function.
- 9313f9401 **set focus explicitly**
When focus is needed, take it.  When done put it back where it was.
- c16c79068 **move EditorHelp**
This data belongs in the Editor code, not the MessageWindow code.
(currently `curs_lib.c` rather than `mutt_window.c`)
=> window refactoring

Makefile.autosetup, commands.c, enter.c, flags.c, gui/curs_lib.c, gui/curs_lib.h, gui/lib.h, gui/msgwin.c, gui/msgwin.h, gui/mutt_window.c, gui/mutt_window.h, index/index.c, keymap.c, menu/draw.c, menu/menu.c, mutt_logging.c, mutt_mailbox.c, muttlib.c, pager/pager.c, po/POTFILES.in, progress/progress.c, recvattach.c, recvcmd.c
Make the MessageWindow self-contained.
**This PR** is quite simple, but it explains the changes coming in the next PR.
- 6ea96d9ca factor out MessageWindow
Move the Message Window into separate source file.
- 4cba5ca3b let the MessageWindow paint itself
Give the MessageWindow `recalc()` and `repaint()` functions.
- 17dac7ca2 add helper functions
Future changes to the MessageWindow will be done using these functions.
- 03119e38b Convert the code to use `msgwin_set_height()`
- 7c61d8c01 Convert the code to use `msgwin_get_width()`
- 4a488b733 Convert the code to use `msgwin_clear_text()`
- 65965f8f5 Convert the code to use `msgwin_set_text()`
- 17bbd4e5f ask for a MessageWindow pointer
The active users must ask for a pointer to the MessageWindow.
- 4161a1377 convert the Progress Bar to use …
=> msgwin: factor out MessageWindow

postpone.c
The issue here is that mx_mbox_open does not number emails (e->msgno).
To do that, we need to build a context.
Fixes #2955
=> Make sure we have a context so emails are numbered

contrib/samples/sample.neomuttrc, docs/config.c, docs/manual.xml.head, pager/config.c, pager/dlg_pager.c
implements https://github.com/neomutt/neomutt/issues/2954
- config: add pager_read_delay config var
- docs: document it
- dlg_pager: pager_check_read_delay: new helper function
- dlg_pager: mutt_pager: use it to delay marking new message as read
Supersedes https://github.com/neomutt/neomutt/pull/2958
for that) …
=> pager: add pager_read_delay

pager/dlg_pager.c
We don't necessarily need to be sitting on an open mailbox (hence, have
a Context) when composing and email and viewing attachments: we might be
sending from the command line.
Reported by @guckes
=> Fix too strict assertion when viewing an attachment

docs/manual.xml.head
Given that the new config variable gives us feature parity with other
MUAs (for example, Thunderbird has had read delay for some time[1]),
it's worth documenting it as a feature to call attention to this
enhancement.
[1] https://support.mozilla.org/en-US/questions/1246812
- docs: add a <sect1> feature page
* Call more attention to pager_read_delay by marking it as a feature
* followup to https://github.com/neomutt/neomutt/pull/2960
=> docs: Document pager_read_delay as a feature

command_parse.c, docs/manual.xml.head, myvar.c, myvar.h
Fixes: https://github.com/neomutt/neomutt/issues/2937
- myvar: add append parameter to myvar_set
- command_parse: use it in parse_set
- docs: tweak docs to match
* Make it possible to use 'set my_var += "string value"'
* Error out on 'set my_var -= anything' instead of silently treating it like '='
2937
=> myvar: Allow += modification of my_ variables.

mutt/hash.c
Fixes: #2969
When NeoMutt frees a ConfigSubset, it iterates through the set passing the name (key) of each item to mutt_hash_delete().
Unfortunately, passing the key name from `struct Inheritance` doesn't work.
The HashTable uses the name after deleting the item to check for duplicate items.
=> hash: fix crash on element deletion

notmuch/notmuch.c
Resolves https://github.com/neomutt/neomutt/issues/2973
In commit 731a3d9c, we noted that aborting a mailbox sync on a
notmuch failure is not helpful (the user is now stuck in that mailbox,
and must quit neomutt to recover); it was deemed better to notify the
user of the failure, but to allow sync to claim success after all.
But the logic in that patch was flawed: the final value of rc depends
on the value of rc for the last message visited in the mailbox: if an
earlier message fails and a later one resets rc back to 0, we get the
desired behavior, but if the last message fails, rc is an error.
Later, commit c3afc987 cleaned up the error return code to make rc
sticky: now it gets set to a non-zero value on ANY failed message, not
just the last one in the notmuch mailbox being synced.
In …
=> notmuch: really tolerate file renames behind neomutt's back

pager/dlg_pager.c
Fixes: #2978
On startup, the Pager does a looped refresh to move the focus to the required place.
Without the MENU_REDRAW_FULL flag the line offsets weren't being updated so it kept looping forever.
=> pager: fix infinite loop

muttlib.c
Fixes: #2984 
Off-by-one caused a buffer overflow when formatting `$status_format`.
=> status: fix buffer overflow

docs/config.c, docs/manual.xml.head, opcodes.h, pager/config.c, pager/dlg_pager.c
Synchronize https://neomutt.org/feature/skip-quoted with the comparable pager_skip_quoted_context that just landed in upstream mutt
for that)
2965, plus a partial fix for 2977
=> skip quoted fixes

mutt_thread.c
Partially Fixes: https://github.com/neomutt/neomutt/issues/2996
Commit b698a6ab added an assert that tctx->tree was set and dropped an
'if', because I could not at the time find any scenario where we would
try sorting threads but not find any.  But in the meantime, I found
(at least) one: when using <attach-message> and selecting the same
folder as already being visited, and when no new mail has arrived in
the meantime, then ALL messages already have e->thread set, and there
is no need to sort subthreads.  But the comment behind the assert was
correct: in that code path, we forgot to restore the value of $sort
after temporarily munging it to the value of $sort_aux.
Later, commit aaa2ece04 changed things so that we no longer munge
$sort in the first place.  So now all we need to do is …
=> sort: avoid assertion under <attach-message>

docs/manual.xml.head, functions.c, index/dlg_index.c, notmuch/lib.h, notmuch/notmuch.c, opcodes.h
This PR adds a user function to reset the current query window position to the present. It's a quality of life improvement for notmuch users as there's no documented way to reset the position. While it's possible to use the undocumented config. variable `nm_query_window_current_position`, it's used for internal state keeping so not something a user should access. It's much better to give the user a function.
In addition to the feature, there's a refactor merging all the query window `index` code into a single code block because the only difference between them is the notmuch backend call. There's no need for duplication at this time.
---
@ebblake can you test this functionality to see if it matches your request in #2972
=> notmuch: implement query window reset functionality

commands.c, compose/compose.c, contrib/samples/sample.neomuttrc, contrib/samples/sample.neomuttrc-tlr, docs/config.c, docs/manual.xml.head, email/thread.c, email/thread.h, flags.c, hdrline.c, index/dlg_index.c, index/index.c, mutt_config.c, mutt_thread.c, mutt_thread.h, score.c, sort.c, status.c
Add $sort_thread so that I can finally sort emails in the same manner as Thunderbird.
With the March 2021 neomutt-devel archives mbox, `ot:set sort_thread=last-date` produces the following (no combination of $sort and $sort_aux without this patch is able to achieve the same):
```
q:Quit  d:Del  u:Undel  s:Save  m:Mail  r:Reply  g:Group  ?:Help
1 O   Mar 02 toogley         (  66) [neomutt-devel] Lua in neomutt | systemat
2 O   Mar 02 Ihor Antonov    (  70) ├─>
3 O   Mar 03 Pietro Cerutti  (  35) │ ├─>
4 O   Mar 03 toogley         (  51) │ └─>
5 O   Mar 03 Richard Russon  (  88) ├─>
6 O   Mar 04 toogley         (  39) │ └─>
7 O   Mar 03 Anton Rieger    (  23) └─>
8 O   Mar 06 Richard Russon  (  33)   └─>
9 O   Mar 06 Anton Rieger …
```
=> Add $use_threads config variable

docs/config.c, docs/manual.xml.head, notmuch/config.c, notmuch/notmuch.c, notmuch/query.c, notmuch/query.h, test/notmuch/window_query.c
Sometimes a user may wish to include certain messages in a query window
even if it exists outside the date range. For example, always showing
flagged messages.
To support this, extend the query window code to emit a window
containing an `OR` statement with additional search terms if a user
configures the `nm_query_window_additional_terms` variable.
For example, using the mailbox `notmuch://?query=tag:inbox` as the
mailbox and `tag:flagged and tag:unread` as the additional search terms
will produce a query window such as:
`notmuch://?query=tag:inbox and (date:... or (tag:flagged and tag:unread))`
The `date` value was omitted for brevity. The resulting mailbox contains
mail with tag inbox within the date range and mail with tags inbox,
flagged, and unread.
Closes #2972
---
Some notes to …
=> notmuch: show additional mail in query windows

core/account.c, sidebar/sidebar.c
This fixes a couple of closely-related bugs.
The problem comes where we free the Account before the Mailbox.
The Mailbox still had references to the Account: `Mailbox->account` and `Mailbox->notify`.
@ebblake's test case triggered one problem and a missing mailbox triggered the other.
---
**Update**
This fixes three problems:
A dangling `Mailbox->account` pointer was causing crashes
When a Mailbox is deleted it sends a notification: `NT_MAILBOX_DELETE`.
That's forwarded to the Account, then to NeoMutt.
The Sidebar is observing NeoMutt to see all Mailbox changes.
If the Mailbox has been separated from the Account, then that notification would never reach NeoMutt,
so the Sidebar would end up with dangling pointers.
Some temporary Mailboxes might have paths matching existing Mailboxes.
When …
=> unlink mailbox when freeing account

auto.def, notmuch/db.c
Notmuch 0.32 introduced a new database open function that allows using
the user's configuration. With libnotmuch using the user's
configuration, the notmuch backend behaves more like the notmuch CLI. It
will exclude tags defined in `.notmuch-config`, correct file paths for
split database and email directory setups, and allow notmuch saved
queries.
The new function call is wrapped behind a libnotmuch version check or if
libnotmuch provides the new method. Notmuch 0.32-0.32.2 didn't bump the
version number so it incorrectly reports 5.3. The version number will be
fixed in notmuch 0.32.3.
Fixes #3017
=> notmuch: open database with user's configuration

mutt_mailbox.c
`mailbox_check()` has a single caller `mutt_mailbox_check()`, which
passes `check_stats=true` when there's a forced update or the mail check
stats interval passes (assuming user enable those settings.) However,
`mail_check()` doesn't use `check_stats` and passes it to
`mx_mbox_check_stats()` which doesn't use it either and passes it onto
the backends. Some backends, like notmuch, do not check this value
before calculating stats.
As a result, for some backends, every call to `mailbox_check()` checks
stats even when it shouldn't. Since checking stats can be expensive,
performance will degrade with a low `mail_check` value, and scale with
the number of mailboxes. If a user sets `mail_check=0`, NeoMutt will
check stats as fast as possible and the UI lags. Having `mail_check=0`
isn't unusual …
=> stats: don't check mailbox stats unless told

auto.def, color/color.c, gui/mutt_curses.c, gui/terminal.c, main.c, menu/draw.c, mutt_commands.c, pager/display.c, version.c
All the curses functions that we check for have been in ncurses for over a decade.
Remove the individual checks for the functions:
- `bkgdset()`                                                                       
- `curs_set()`
- `meta()`
- `start_color()`
- `typeahead()`
- `use_default_colors()`
- `use_extended_names()`
This change shaves nearly **0.4s** off the `./configure` time, which over my lifetime may save me several minutes :-)
=> build: strip back curses checks

notmuch/notmuch.c
`nm_mbox_check_stats()` duplicates logic for calculating the notmuch
database filename. Instead it should use the existing implementation in
`notmuch/db.c` to prevent discrepencies in calculation.
=> notmuch: remove duplicate filename logic

notmuch/db.c, notmuch/notmuch.c, notmuch/private.h
Sometimes libnotmuch's version isn't bumped when new APIs are available.
Some new features require updating our integration to support users
using them, such as separate database and email directories, but we're
unable to use the standard `LIBNOTMUCH_CHECK_VERSION` macro. The current
approach is #ifdef on a function's existence; however, this is
inconsistent with our usage of the version check macro.
Instead, move the function existence checks into
`LIBNOTMUCH_CHECK_VERSION`. Since we know which libnotmuch version
introduced a function, we're able to check the major and minor version
against the function's existence.
There are two libnotmuch version bumps NeoMutt corrects for:
- libnotmuch 5.1 released in notmuch 0.26 but not bumped until 0.26.1
- libnotmuch 5.4 released in notmuch 0.32 …
=> notmuch: handle missing libnotmuch version bumps

conn/connaccount.c, conn/connaccount.h, contrib/Makefile.autosetup, contrib/oauth2/mutt_oauth2.py, contrib/oauth2/mutt_oauth2.py.README, docs/config.c, docs/manual.xml.head, imap/auth.c, imap/auth.h, imap/auth_oauth.c, imap/command.c, imap/private.h, pop/auth.c, send/smtp.c
It adds XOAUTH2 authentication support for IMAP and SMTP. XOAUTH2 is an authentication scheme used by OWA/Office365, and is required by some organizations.
for that)
Yes.
Unrelated tests failed. (symlink, chmod, etc.)
Yes.
As best as I could.
* **What …
=> Add xoauth2 support for imap and smtp

attach/dlg_attach.c, debug/email.c, debug/graphviz.c, docs/manual.xml.head, email/envelope.c, email/envelope.h, email/parse.c, email/parse.h, functions.c, hcache/serialize.c, imap/message.c, index/functions.c, opcodes.h, pager/functions.c, send/send.c, send/send.h
This function uses the List-Subscribe and List-Unsubscribe headers from [RFC2369](https://datatracker.ietf.org/doc/html/rfc2369) to send a subscribe/unsubscribe email request. Works best with `unignore list-subscribe list-unsubscribe`.
**TODO**
=> Implement list-(un)subscribe

compose/functions.c
It adds an `ifdef USE_AUTOCRYPT` around the inclusion of `autocrypt/lib.h`. This `ifdef` "vanished" during the refactoring at commit c4ff91c0cd55b7995171340d9d7a680a792d1599.
Without this patch I cannot compile neomutt without autocrypt-support.
=> compose: include autocrypt depending on USE_AUTOCRYPT

email/parse.c
Fix logical test in `mutt_rfc822_parse_line` from commit d2bd01662a9
In the commit d2bd01662a9 the parsing of the user headers changed.
Before: https://github.com/neomutt/neomutt/blob/a86eda64bfdd4477bbbd6c60081ffd98218039a8/email/parse.c#L1025-L1030
With this commit: https://github.com/neomutt/neomutt/blob/d2bd01662a94de29ca052de395f168ee8192b4f9/email/parse.c#L1022-L1038
Before: The header line was added iff `weed` and/or `c_weed` and/or `mutt_matches_ignore` was `false`. To put it in other words: It was enough that one of the three was `false`.
In my case I had the (pseudo-)header line (added in the editor, and obviously `user_hdrs` is `true`):
```
Pgp: ES
```
and the command `ignore *` and `Pgp` is/was *not* mentioned in the `unignore` command. Then …
=> fix parsing of user headers

notmuch/notmuch.c
Only mark messages as old when the user has set mark_old.
Fixes https://github.com/neomutt/neomutt/issues/3047
Note, that introduces a new user of the global config object, that's what maildir does.
Would you rather have the function accept the config as a parameter?
=> notmuch: respect mark_old

.github/workflows/coverity.yml
Use a GitHub Action to perform automatic Coverity Scans.
The action is triggered by a [cron job](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#onschedule).
The job is scheduled for: Mondays at 3am.
This PR removes another dependency on TravisCI.
=> coverity scan

mutt/hash.c
This commit mirrors the change to 'gen_string_hash()' from commit
2c4c7a9c3. It ensures a non-NULL key as generate the hash may cause a
segfault.
---
Pre-emptive improvement. No known issue.
=> improve: ensure non-null key in 'gen_case_string_hash()'

progress/progress.c
This gives me a 15% speedup at mailbox open time.
((please double check my boolean logic))
=> Avoid unnecessary gettimeofday calls during progress update

browser.c, nntp/newsrc.c, remailer.c, test/compress/common.c, test/hash/mutt_hash_new.c
See each commit for warnings from GCC 11.2.0-10.
Found these when building for x32, remaining warnings for a `--mandir=/usr/share/man --libexecdir=/usr/libexec --with-mailpath=/var/mail --gpgme --lua --notmuch --with-ui --gnutls --gss --idn --mixmaster --sasl --tokyocabinet --zlib --zstd --testing` build:
```
notmuch/notmuch.c: In function ‘rename_filename’:
notmuch/notmuch.c:1238:29: warning: ‘%s’ directive output may be truncated writing 3 bytes into a region of size between 0 and 4095 [-Wformat-truncation=]
1238 |   snprintf(buf, buflen, "%s/%s/%s%s", folder,
|                             ^~
notmuch/notmuch.c:1238:3: note: ‘snprintf’ output between 6 and 12291 bytes into a destination of size 4096
1238 |   snprintf(buf, buflen, "%s/%s/%s%s", folder,
| …
```
=> Fix scanf/printf bugs (one critical, three less so) and constant string warning

monitor.c
Commit message
```
PollFdsLen tracks the maximum elements of the pollfd struct before
needing reallocation, whereas PollFdsCount tracks the number of actual
elements in it. Polling has to be done only on the actual number of
elements.
```
The original code in `mutt_monitor_poll` calls `poll(PollFds, PollFdsLen, MuttGetchTimeout)`.
We can see in `mutt_poll_fd_add` that when a new fd is to be added in the `pollfd` struct, if no space is available in the struct, the struct is extended to fit two more elementrs (`PollFdsLen += 2`) and the number of elements gets incremented by 1 (`++PollFdsCount`). The expansion of 2 happens probably in order to reallocate just once for the basic scenario of only polling for `STDIN` and `INotifyFd`. 
If for some reason, a 3rd fd is added, then `PollFdsLen` …
=> [Fix] poll to use PollFdsCount and not PollFdsLen

mutt/regex.c, test/regex/mutt_replacelist_match.c
A back-reference not at the end of the string was not properly parsed.
This is because our mutt_str_ato[li] functions explicitely check that
the full string was parsed. Perhaps we should do something about it.
Also, without the fix, the test would crash because `mutt_replacelist_match` keeps some static variables that are not properly reset.
=> Fix back-reference parsing in mutt_replacelist_add

color/regex.c
The colour code shouldn't be updating the Index.
Send a `NT_COLOR_SET` notification for colour `MT_COLOR_INDEX`.
The Index's `index_color_observer()` will do the work.
=> color: notify index of change

docs/config.c, send/send.c
```
The recipients of a message are not confirmed/edited if the program flow
has defined them in any kind of way. This extends the fast_reply
functionality for the compose_to_sender function and the case of command
line defined arguments related to the above parameters.
```
Docs will be updated in a future commit, if the patch is accepted provisionally.
Let's discuss all the relevant parts in this merge request.
=> fast_reply applied when to, cc, or bcc predefined

ncrypt/crypt_gpgme.c
If the key isn't held locally, `uid` may be `NULL`.
Situation:
- Using GPGME
- Decrypting an email
- Decryption key doesn't have a UID
If the encrypted email contains a PGP key, then NeoMutt will display a block, like this:
```
[-- BEGIN PGP PUBLIC KEY BLOCK --]  
pub EdDSA 255/ABC123DE 2020-11-29 John Doe <jd@example.com>
sub  ECDH 255/456DEF78 2020-11-29
sub EdDSA 255/12345678 2020-11-29
[-- END PGP PUBLIC KEY BLOCK --]
```
If the UID ("John Doe...") isn't defined, then `uid` in `pgp_gpgme_extract_keys()` will be `NULL` leading to a crash.
---
Thanks :heart: to Nick Johnson for his help debugging.
=> gpgme: fix crash with partially defined keys

docs/config.c
The "query" section doesn't appear in the neomuttrc man page, so the text 'See
"query" for more information wasn't useful there.
NB: I haven't tried re-building the docs with this change (man page or website). Also, it presumably makes the web version of the docs a bit worse since the URL is redundant there, so not sure if it should be merged.
Makes the `neomuttrc`  man page more useful.
=> Add url corresponding to $query.

conn/connaccount.c
A user reported a token size of 2304.
Ensure we have plenty of space.
oauth2 tokens can be pretty big.
Increase the buffer size to 4096 bytes.
Thanks :heart: to `neo43589367` on IRC for their help debugging.
=> imap: increase max size of oauth2 token

color/command.c, config/long.c, config/number.c, email/parse.c, email/rfc2231.c, email/url.c, imap/command.c, imap/imap.c, imap/message.c, imap/search.c, imap/util.c, index/functions.c, maildir/mh.c, maildir/sequence.c, main.c, menu/menu.c, mutt/regex.c, mutt/string.c, mutt/string2.h, ncrypt/gnupgparse.c, notmuch/notmuch.c, resize.c, score.c, send/smtp.c, test/string/mutt_str_atoi.c, test/string/mutt_str_atol.c, test/string/mutt_str_atos.c, test/string/mutt_str_atoui.c, test/string/mutt_str_atoul.c, test/string/mutt_str_atoull.c
The signature of the `mutt_str_ato*` functions have been changed to return the endptr argument to the relative libc functions. In addition, I have added wrappers named `mutt_str_ato*_full` that return a bool indicating whether a successful conversion consumed the whole string. So, the changes at API level are
```diff
- if (mutt_str_ato*(...) < 0)
+ if (!mutt_str_ato*(...))
```
and
```diff
- if (mutt_str_ato*(...) != 0)
+ if (!mutt_str_ato*_full(...))
```
Additionally, whoever needs more control can use the returned endptr, see e.g., the changes in mutt/regex.c .
=> Improve API of strto* wrappers

init.c
This was introduced in 6b893166b9d724e22db0b45803fc4a45ccb2fb17, I can't see why :/
=> Remove config_init_autocrypt dummy definition

imap/browse.c
Fix leak of `mdata` when successfully renaming an imap mailbox.
`mdata` should always be freed, not just on failure.
=> imap: fix leak in imap_mailbox_rename()

auto.def
Enable debugging on mutt/queue.h macros:
- `LIST`, `SLIST`, `TAILQ`, `STAILQ`
This enables two symbols:
- `QUEUE_MACRO_DEBUG_TRACE`
Store the last 2 places the queue element or head was altered
- `QUEUE_MACRO_DEBUG_TRASH`
Invalidated pointers will be set to `0xffffffffffffffff`
---
These macros are reliable and very well tested, but they can be hard to use.
Defining these symbols will make it easier to spot mistakes in our code.
In `gdb` examine the contents of a `TAILQ_HEAD`:
```
p *head
1: *head = {tqh_first = 0x850480, tqh_last = 0x850490,
trace = {lastline = 215, prevline = 74, lastfile = 0x58a3d6 "email/parse.c", prevfile = 0x58a3b3 "email/parameter.c"}}
```
Here we can see the contents of the `TAILQ` **plus** the exact locations of the previous two changes to it.
In `gdb` see the …
=> build: configure --debug-queue

notmuch/notmuch.c, notmuch/query.c, notmuch/query.h, test/notmuch/query_type.c
The implementation of `nm_parse_type_from_query()` assumes a default
value of `NM_QUERY_TYPE_MESGS` if it's unable to parse a `type=`
statement. However, defaulting to `NM_QUERY_TYPE_MESGS` is not a safe
assumption as `nm_query_type` controls the default query type. This
assumptions results in using query type `messages` for
`vfolder-from-query` with `nm_query_type=threads`. The single caller of
`nm_parse_type_from_query()` overrides `mdata->query_type` with the
returned value, resulting in the assumption replacing the default query
type.
To fix this, this commit modifies `nm_parse_type_from_query()` to take a
fallback parameter for the default value. This avoids introducing state
into `nm_parse_type_from_query()`. Its single caller passes the global
`nm_query_type` value as the fallback. …
=> fix(notmuch): use 'nm_query_type' as default for vfolder-from-query

alias/alias.c, alias/dlgquery.c, browser/browser.c, commands.c, compose/functions.c, conn/sasl.c, imap/browse.c, index/functions.c, menu/menu.c, mutt_header.c, ncrypt/crypt_gpgme.c, ncrypt/pgpkey.c, ncrypt/smime.c, pager/functions.c, pattern/pattern.c, recvcmd.c, send/send.c
This very repetitive PR refactors 36 functions to use `mutt_buffer_get_field()` rather than `mutt_get_field()`.
See "The Near Future", below.
The code to read some text from the user is too complicated.
It's a mix of functions that take `char []` or `struct Buffer`,
flags that are relevant to some functions but not others,
parameters (arrays of files) that _might_ be needed,
and originally a bunch of macro wrappers.
The names have been abbreviated by `mutt_` for clarity.
The blue nodes are macros.
We eliminated the macros a while back, leading to:
**Key**:
The numbers in `()`s show the number of callers of each function.
Worryingly, many of the functions pass `CompletionFlags` and an Array for the results of completion.
This means that `mutt_enter_string_full()` has to know a lot about …
=> refactor mutt_get_field()

send/send.c
This is a backport of commit 04a7f1d9585ca21894ec09283becd9425d1c1334
from [0]
[0]: https://github.com/neomutt/upstream-mutt/commit/04a7f1d9
=> send: Allow an empty To: address prompt

compose/functions.c, imap/command.c, imap/imap.c, index/functions.c, mbox/mbox.c, mx.c, mx.h, postpone.c
Fixes #3152
We still won't be able to reopen the mailbox, since the mailbox is gone after `mx_fastclose_mailbox`. We'll need to look more into that part.
=> Optionally keep an account alive on removal of its last mailbox

index/functions.c
This was producing an index with no email selected when unapplying a
limit that produced an empty email set.
=> Fix selecting the right email after limiting

index/functions.c
Fixes #3143
`priv->menu->max` still contained the number of messages in the *old* limit at this point.
=> Fix restoring the selected message after limiting

mutt/logging.c, mutt_logging.c
mutt_perror calls can overflow the internal 1024 byte buffer when
errno string representation is added.
Since snprintf returns the amount of bytes it would write regardless
of the limitation of the second argument, the return value has to be
checked for such a truncation before incrementing the start position.
Proof of Concept (compile with -fsanitize=address):
```
echo "set mbox_type=MH" > muttrc
python -c 'print("set postponed=\"/tmp/"+1024*"a"+"\"")' >> muttrc
neomutt -F muttrc -d 1
```
Postpone a newly created mail to see the OOB write.
No issue created.
=> Fix out of boundary write with long log lines

handler.c
This PR ensures the `first_part` Body pointer of a `multipart/multilingual` email is set even if `$preferred_languages` is not set.
=> Fix default display when preferred_languages unset (fixes #3174)

attach/recvattach.c
Display `multipart/multilingual` attachment lists in the same way as `multipart/alternative`.
=> Consistent attachment list for multilingual emails (closes #3175)

mutt/hash.c
Fixes: #3180
When Emails don't have a Message-ID, we store them in the HashTable with a key of "".
Remove the check that prevented this.
=> fix leak of threads

alias/dlgquery.c, autocrypt/autocrypt.c, color/regex.c, compose/compose.c, copy.c, hook.c, index/index.c, index/lib.h, init.c, main.c, menu/draw.c, menu/menu.c, monitor.c, score.c, send/sendlib.c
Fixes: #3176 
Historically, (Neo)Mutt maintained a global `Context` representing the "current" `Mailbox`.
Most code doesn't actually need a `Context`, it just needs the current `Mailbox` or `Menu`,
and most of these needs have been met by passing parameters to functions.
A few poorly written bits of code still use the `Context`.
Instead, use a couple of helper functions: `get_current_mailbox()`, `get_current_menu()`.
The helper functions work out-of-band -- they look up the most recent Index Window and get the `Mailbox` or `Menu` from its private data.
This isn't ideal, but it avoids dangling pointers when the `Context` changes,
- 1f3ca6844 index: move mailbox helper
Move the helper into the Index library
- a3d0d4652 index: use mailbox helper
Replace lots of `Context->mailbox` or …
=> Refactor uses of global Context

attach/recvattach.c, compose/compose.c, compose/functions.c, docs/manual.xml.head, email/attach.c, email/attach.h, functions.c, opcodes.h, postpone.c, send/send.c
The present support for creating multipart emails is basic and suffers from functionality and usability problems. For example,
- Grouped attachments display as a single attachment which cannot be modified or ungrouped.
- Grouped attachments are appended to the list of attachments and can not be made the body of the email if other attachments have been added prior to grouping. See issue #2387.
- Grouping is lost if sending is aborted for any reason (e.g., crypt function fails or failed attachment check) or an email is postponed.
The goal for this branch is to provide better support for both composing multipart/alternative and multipart/multilingual emails.
=> Improve composition of multipart messages

nntp/newsrc.c
time_t is an undefined type, according to the spec, and %jd is the right
format string to use, according to the docs. Squelch a compiler warning
related to this is newsrc.c.
Signed-off-by: Ramkumar Ramachandra <r@artagnon.com>
=> newsrc: squelch warning; format string corresponding to time_t

contrib/hcache-bench/README.md
Some Markdown implementations (e.g. the GitHub one, as can be seen at [0]) can treat a line starting with `-` as a list item.  Move a line break to avoid that happening unnecessarily.
[0]: https://github.com/neomutt/neomutt/blob/1ce876f0c2935832ed6a2c11ff85dd5708f11daa/contrib/hcache-bench/README.md
=> hcache-bench: adjust README.md linebreaks

muttlib.c
When saving multiple attachments, it's good to know which files already exist
=> Say which file exists when saving attachments

send/send.c
Commit 93501456cfd2e9ff2dfab95773882639a044e023 omitted handling sending from a draft file.
This PR does two things:
1. Add the missing code to ensure that the first attachment of a draft email beginning with a group is the one opened for editing.
2. Simplifies the analogous checks for other cases in `mutt_send_message()`.
Fixes issue #3210
=> Fix issue 3210

main.c, send/send.c
When the `-E` flag is passed along with `-i filename` to Neomutt, `filename` should not be deleted.
Neomutt does this by setting `email->body->unlink = false` just before it frees `email`. However this is too late as by that time, the body may have moved from the fundamental part (either by grouping it or explicitly moving it). If this happens `filename` will be deleted and the new `email->body` will remain on disk.
This PR sets `body->unlink = false` for `filename` as soon as it's created and does not change `email->body->unlink` just before freeing the `email`.
This fixes issue #1590.
=> Fix issue 1590

mutt_body.c
To forward an attachment, NeoMutt makes a copy of the `Body`.
Unfortunately, `mutt_body_copy()` uses `memcpy()` which duplicates pointers too.
When the email is sent, the `Body` is freed, leaving dangling pointers in the original `Body`.
Ensure that all heap-allocated objects are duplicated, or their pointers are set to `NULL`.
Fixes: #3215
---
**Steps to reproduce**:
- Index: select an email with attachments
- <kbd>v</kbd> (`<view-attachments>`)
- Select an attachment
- <kbd>f</kbd> (`<forward-message>`)
- Hit <kbd>\<Enter\></kbd> at the prompt (cancel the sending)
- <kbd>q</kbd> (`<exit>`) quit the attachment view
- <kbd>q</kbd> (`<exit>`) quit NeoMutt
- Crash - heap-use-after-free
=> fix crash when forwarding attachments

gui/curs_lib.c
A call to getch() in OptNoCurses mode will return -1. We need to differentiate it from a regular timeout, or the caller will re-enter infinitely. This prevents NeoMutt from hanging e.g., on a certificate verification dialog when running with -Q varname.
=> Avoid infinite loop in OptNoCurses mode

compose/functions.c, docs/manual.xml.head, email/parse.c, functions.c, opcodes.h, send/header.c
Adds support for composing `multipart/related` emails.
run `./neomutt -n -F multipart-related.rc`
```
unset record
unset signature
set attach_format = "%u%D%I %t%4n %T%.40d%> [%.15m/%.15M, %.6e%?C?, %C?, %s]"
set editor = "echo '![Neomutt Logo](cid:neomutt-256.png)' >> %s"
set from = "john.doe@example.com"
set help = no
set postpone = no
set postponed = "postponed.mbox"
set realname = "John Doe"
set recall=no
set spoolfile = "inbox.mbox"
macro index   <F1> "<mail>John Doe <john.doe@example.com><enter>test<enter>"
macro compose <F2> "<attach-file>contrib/logo/neomutt-256.png<enter>"
macro compose <F3> "<rename-attachment><enter><toggle-disposition>"
macro compose <F4> "<attach-file>html-part.html<enter>"
macro compose <F5> "<toggle-disposition><tag-entry>1<enter><tag-entry><group-alternativ …
```
=> Add support for composing 'multipart/related' emails

gui/curs_lib.c
When decrypting an email, gpg can change the screen mode.
This can confuse ncurses, causing it to write to the "normal", rather than the "alternate" screen.
Forcibly switch to the alternate screen after gpg operations.
Fixes: #3217
=> fix screen mode after attempting decryption

send/send.c
It can be useful to send empty emails where the subject is the message.
A recent refactoring caused an unwanted warning message in this case.
Fixes: #3234
=> prevent warning on empty emails

index/dlg_index.c, index/functions.c, index/functions.h, index/lib.h, pager/dlg_pager.c, pager/functions.c, sidebar/functions.c, sidebar/functions.h, sidebar/lib.h, sidebar/observer.c, sidebar/private.h, sidebar/sidebar.c, sidebar/wdata.c, sidebar/window.c
In the beginning, the Index and Pager had to handle all the sidebar function in a big `switch`.
Next came the separate op functions -- better but still lots of duplication.
This PR creates a Sidebar-specific function dispatcher.
Now, the Index and Pager are _almost_ unaware of the Sidebar.
- 694a76159 sidebar: reorder functions
- 669f5a5d4 sidebar: rename functions
- b808899be sidebar: refactor op_sidebar_next/prev()
- 8490dd35f sidebar: add the window to wdata
- 33842b594 sidebar: convert work functions
- 7f3d28177 sidebar: create functions for open and toggle
- beef03872 sidebar: add a function dispatcher
- 1736fbbb0 index/pager: convert to use the sidebar dispatcher
The changes are broken into small pieces.
The first couple don't make any functional changes.
Then refactor the functions …
=> Refactor Sidebar Functions

.github/PULL_REQUEST_TEMPLATE.md, docs/config.c, docs/manual.xml.head
This PR updates (corrects) the documentation concerning the need to set `$header_cache_backend` for header caching to work. Reality is that `$header_cache_backend` doesn't need to be set unless the user wants to explicitly specify which backend should be used for header caching.
Also part of this PR is a small change (26fbd795c0f55782d016507cf33b047afd087b51) to fix a broken link in the GitHub pull request template.
#3259
=> Update documentation wrt. need to set $header_cache_backend

notmuch/notmuch.c
Using a notmuch virtual mailbox folder can give strange behaviour for the old/new flags.  When the nm_mailbox_check function is called, the maildir flags are parsed from the filename.  However the maildir_parse_flags function does not set "old" in the Email structure.  This change ensures that the previous version of the "old" flag is preserved.
It would seem to me that this might actually be a problem in the maildir_parse_flags function and not due to the notmuch code.  I would expect that when parsing the flags, the 'old' flag is set in accordance to where the message is found in the maildir (i.e. in cur/ or new/).  I'm unsure how doing this would break other code.
=> notmuch: Ensure old flags are preserved in the index

color/regex.c
Fix a crash where a `mono` follows a `color` with the same regex, e.g.
```
color body      red green "signature from"
mono  body bold           "signature from"
```
Thanks to:
- Vladimir Zakharov (@z2v)
- Sam Axe (@SamAxe)
- Страхиња Радић (@Strahinja)
=> color: fix dupe regex crash

Makefile.autosetup, alias/dlgalias.c, alias/dlgquery.c, alias/functions.c, alias/functions.h, alias/gui.c, alias/gui.h, alias/lib.h, functions.c, index/functions.c, opcodes.h, pattern/pattern.c
This PR changes the behaviour of the Alias and Query Dialogs.
It brings them in line with NeoMutt and each other.
The workflow is changed so that leaving the Alias/Query Dialog always returns you to where your _were_.
(See the diagrams at the bottom)
The diffs are quite large, but most of that bulk is non-functional (moving functions around).
- 876a93d4d drop `query_search()`
`query_search()` hasn't been needed since `menu->custom_search` was enabled.
- b435f3345 convert `dlg_select_alias()` to use Buffer
This brings it in line with `dlg_select_query()`.
- 70d7a391c add `<alias-dialog>` function
Add an `<alias-dialog>` function to mirror the `<query>` function.
This gives the user direct access to the address book.
- 52cf73fbd enable `<mail>` function
Enable the `<mail>` function in the …
=> Unify Alias and Query with function dispatcher

mutt/file.c
Removes overwriting file contents with zeroes in the function for unlinking
files.
neomutt/neomutt#3219
=> Don't overwrite with zeroes after unlinking the file

menu/draw.c
Ensure that when `$arrow_cursor` is set, only the arrow gets coloured.
This fixes some display issues for the menu.
The first commit does some minor, non-functional, refactoring for clarity.
---
**test.rc**
```
set menu_scroll = no
set arrow_cursor = yes
color indicator white red
```
**Tests**:
Use `<next-entry>`, `<previous-entry>` to move the highlight onto a new page.
Watch carefully as the page changes.
Repeat the tests with, `set arrow_cursor = no`
=> menu: fix repainting of arrow_cursor/indicator

send/smtp.c
Chicken and egg: MUTT_ACCT_USER gets set the first time the username is
requested, but SMTP requests the username (i.e., does authentication)
only if MUTT_ACCT_USER is set.
This was causing an smtp_url without the username part to never trigger
an authentication even when smtp_user was set.
=> Force SMTP authentication if smtp_user is set

browser/browser.c, command_parse.c, commands.c, core/account.c, core/mailbox.c, core/mailbox.h, editmsg.c, index/dlg_index.c, index/functions.c, main.c, mutt_mailbox.c, mx.c, postpone.c, send/send.c, send/sendlib.c, sidebar/observer.c, sidebar/sidebar.c, sidebar/window.c
Let's just try and free a mailbox whenever we're done with it, and
leave it to mailbox_free to decide when it's actually safe to do.
In this PoC, safe means the mailbox isn't open and isn't visible. This
can probably cause a few leaks, e.g., when quitting NeoMutt.
Fixes #3098
=> Make free'ing a mailbox easier for the caller

index/functions.c
If the selection was on a non-matching line
and that line's number is beyond the number of limited entries,
then selection would end up off-screen and the screen would be blank.
**Test case**:
- Mailbox with 3 entries
- Flag the second entry
- Put the cursor on the third entry
- Command: `<limit>~F`
A recent fix moved the `menu_set_index()` into the `for` loop.
Unfortunately, if the selection ended up off-screen, it wouldn't get corrected.
`menu_set_index()` clamps its inputs to valid values,
so if the match isn't found the selection will be set to a safe value.
=> fix selecton after <limit>

alias/dlg_alias.c, alias/dlg_query.c, alias/functions.c, alias/lib.h, index/functions.c
Fix crashes introduced by recent refactoring.
Tests:
- `<query>`, no matches
- `<query>`, matches
- `<mail>` `<complete>`, no matches
- `<mail>` `<complete>`, matches
- `<query>`, matches, `<query>`, no matches
- `<query>`, matches, `<query>`, matches
- `<mail>` `<complete>`, matches, `<query>`, no matches
- `<mail>` `<complete>`, matches, `<query>`, matches
- `<query>`, matches, `<query-append>`, no matches
- `<query>`, matches, `<query-append>`, matches
- `<mail>` `<complete>`, matches, `<query-append>`, no matches
- `<mail>` `<complete>`, matches, `<query-append>`, matches
Fixes: #3300
=> query: fix crashes

timegm.c
Fix a small compilation issue on systems not having timegm.
=> Add missing stdbool.h to timegm fallback

color/quoted.c, envelope/functions.c
Close #3311
Given the following working diff:
```diff
diff --git a/color/quoted.c b/color/quoted.c
index 820563d3e..3689f7074 100644
--- a/color/quoted.c
+++ b/color/quoted.c
@@ -50,6 +50,7 @@ int find_highest_used(void)
}
return 0;
}
+static void walk(struct QuoteStyle *l);
/**
* quoted_colors_clear - Reset the quoted-email colours
@@ -182,11 +183,21 @@ static void qstyle_free(struct QuoteStyle **ptr)
return;
struct QuoteStyle *qc = *ptr;
+dprintf(3, "qfree: %p\n", qc);
FREE(&qc->prefix);
FREE(ptr);
}
+static void walk(struct QuoteStyle *l) {
+	struct QuoteStyle *next = l;
+	while(next) {
+		dprintf(3, "w: %p: d=%p, n=%p; pref='%s'\n", next, next->down, next->next, next->prefix);
+		walk(next->down);
+		next = next->next;
+	}
+}
+
/**
* qstyle_free_tree - Free …
```
=> Don't leak neighbours of new top-level QuoteStyles

commands.c, core/neomutt.h, index/dlg_index.c, index/functions.c, index/index.c, pager/dlg_pager.c, pager/functions.c, pager/pager.c
- notify on neomutt commands
Index/Pager perform some updates after every NeoMutt command
- index: use the global function dispatcher
Call the global dispatcher, strip out our own functions
- pager: use the global function dispatcher
Call the global dispatcher, strip out our own functions
=> Index/Pager: use the global function dispatcher

keymap.c
`unmacro * dd` adds a binding from `dd` to `OP_NULL` (i.e., `noop`) to
all menus, including the editor. This `dd` mapping will keep matching
text typed into the editor, so if we type `abcde` the `d` will be
matched and eaten, resulting in `abce`.
This is a quick fix that solves the `unmacro *` case of #3288, but the
problem is more profound. If we want the editor to jump to the
begin-of-line on `bl`, we might try to `macro editor bl <bol>`. This
works, but this also eats any `b` we type in the editor. The editor is
special in this regard, because unlike other dialogs we want typed keys
to actually appear. ~I don't have a solution for this yet.~ 
Edit: I think [26d8c59](https://github.com/neomutt/neomutt/pull/3316/commits/26d8c5901b0241c979633ab66bc7ae85f8aa7dcb) might be a reasonable fix …
=> Do not insert an actual key mapping for noop

functions.c, gui/global.c, index/functions.c
Move `<show-log-message>` from the Index to the Generic Menu.
Now it can be called from anywhere in NeoMutt.
Also, add a synonym `<error-history>` for Mutt compatibility.
=> global: move show-log-messages

command_parse.c, email/tags.c, email/tags.h, init.c, mutt_globals.h
Also, I refactored the code to parse tag-transforms and tag-formats,
which was basically identical except for the hash table used, and I
moved TagFormats from globals into email/tags.h
**TODO**
Fixes #3324
=> Fix memory leak in tag-transforms and tag-formats

gui/curs_lib.c, index/dlg_index.c, index/functions.c, index/shared_data.c, pager/dlg_pager.c, pager/functions.c, pager/lib.h, pager/message.c, pager/pager.c, pager/private_data.h
Refactor the Pager to use `index_function_dispatcher()` rather than its own copy of functions.
Add `PagerLoopMode` to control when the Pager should close or reload.
To reload an email, `mutt_pager()` returns to `mutt_display_message()`, which regenerates the file.
I have tested all 130 functions, accessible from the Pager, to make sure they work correctly.
<details>
<summary> ☑️ Handled by Pager (19)</summary>
- `OP_EXIT`
- `OP_HALF_DOWN`
- `OP_HALF_UP`
- `OP_HELP`
- `OP_NEXT_LINE`
- `OP_NEXT_PAGE`
- `OP_PAGER_BOTTOM`
- `OP_PAGER_HIDE_QUOTED`
- `OP_PAGER_SKIP_HEADERS`
- `OP_PAGER_SKIP_QUOTED`
- `OP_PAGER_TOP`
- `OP_PREV_LINE`
- `OP_PREV_PAGE`
- `OP_SEARCH`
- `OP_SEARCH_NEXT`
- `OP_SEARCH_OPPOSITE`
- `OP_SEARCH_REVERSE`
- `OP_SEARCH_TOGGLE`
- `OP_VIEW_ATTACHMENTS`
</details>
<details> …
=> Split the Index/Pager (Part 2)

index/dlg_index.c
This PR restores the behaviour before the Index/Pager refactoring.
If the Index doesn't have focus, then the Pager must be active.
Adjust the layout rules to keep the indicator near the top of the window.
=> index: fix indicator for mini-Index

command_parse.c
Turn logs into warnings so the user sees that a command wasn't successful.
=> Issue warnings on duplicate keys

browser/browser.c, commands.c, commands.h, core/mxapi.h, gui/global.c, imap/imap.c, index/dlg_index.c, maildir/maildir.c, main.c, mbox/mbox.c, mutt_mailbox.c, mutt_mailbox.h, status.c
When handling the -Z command line option, we want to force checking stats. Also, when we do that, we want to turn off queuing IMAP commands since the caller wants the answer immediately.
=> Force checking stats when launching with -Z

handler.c, handler.h, send/send.c
`mutt_can_decode` is used in `inline_forward_attachments` to decide
which parts of a message need to be attached when forwarding an email.
If we don't consider skipped types such as signatures, this set must be
equal to the set of parts that wasn't included in the email text.
However, using `mutt_can_decode` is not enough, because parts with
disposition = attachments that could be decoded might have been skipped
during the formation of the email text because of `honor_disposition`.
Hence, we need a common piece of code to decide if a part is handled
inline or in an attachment.
An alternative to this would be to mark the parts that were handled in
the main body and include all others. I am not sure what is the best
approach.
While at it, use `b` for bodies.
Also, please double check my …
=> Fix forwarding text attachments when honor_disposition is set

index/functions.c, index/functions.h, pager/functions.c
Fix the `$pager_stop` behaviour.
If `pager_stop=no`, then using `<next-page>` or `<half-down>` at the end of an email will jump to the next undeleted email.
This was broken by the Index/Pager refactoring.
=> pager: fix $pager_stop

docs/manual.xml.head
Fix example multipart compose macro in documentation.
=> docs: fix example multipart/alternative compose macro

color/command.c
Historically the `mono` and `unmono` commands were only enabled if:
- Mutt was compiled **without** support for colour,
- Your terminal didn't support colour.
Both these conditions are very unlikely, these days.
The `color` command can take attributes in addition to the colours, e.g.
```
color body bold underline red default "neomutt"
```
During the refactoring, I made the decision to turn `mono` commands into a stripped down `color` command.
This would have allowed the user to tweak the attributes of an object, without having to specify the colour info.
```
color body bold default default "neomutt"
mono body bold "neomutt"
```
Unfortunately, this means that all those `mono` commands that were laying dormant in users' config files have started interfering with their themes.
(including our …
=> color: disable mono command

color/quoted.c, compose/cbar.c, envelope/window.c, gui/curs_lib.c, gui/msgwin.c, gui/sbar.c, helpbar/helpbar.c, index/dlg_index.c, index/ibar.c, keymap.c, menu/draw.c, pager/display.c, pager/pager.c, pager/pbar.c, progress/progress.c, question/question.c, sidebar/window.c
Some index colours can be configured multiple times with different patterns.
`index_author`, `index_flags`, `index_subject`
If multiple patterns match an entry, their colours will be merged in config order.
@riesebie Please can you give this a try.
=> index: merge more colours

index/dlg_index.c
`menu->max` needs to be updated to reflect the number of messages after a resort.
=> Make sure to update the menu size after a resort

index/functions.c
Steps:
- Enable mini-index (pager_index_lines=10)
- Disable resolve (resolve=no)
- Select last email
- Delete email
- Sync mailbox
This would cause the mini-index to not fill the space and display duplicate copies of emails.
---
Fixes: #3363 
There are bound to be other quirks, but this fixes the immediate problem
=> fix: misalignment of mini-index

color/regex.c, pager/display.c
Fix a crash caused by an unset colour.
Make sure that setting a colour to "default default" actually clears the colour.
Fixes: #3364
=> fix: clearing color with default

index/dlg_index.c, index/index.c, index/private.h
This is not very elegant. @ebblake I'm open to better approaches to avoid
a crash on startup.
Fixes #3126
=> Do not crash on an invalid use_threads/sort combination

functions.c
In the Index, if you `unbind index q`, then `q` will still quit, because the Generic menu has a `q` of its own.
Copy the `<exit>` function into each separate menu and remove the Generic binding.
This will allow users to disable the `q` binding.
**Note**: The `<exit>` function still exists in the Generic menu.
Fixes: #3371
This PR fixes the exact issue, nothing else.
---
**Steps**:
- Run NeoMutt
- Enter: `unbind index q`
- Hit <kbd>q</kbd>
**Results**:
- Nothing happens, NeoMutt doesn't quit
=> generic: split out OP_EXIT binding

send/sendmail.c
Steps to reproduce:
- set sendmail to "x -- a"
- try to send a mail
- NeoMutt hangs
=> Fix parsing of sendmail cmd

browser/browser.c
Restore the mailbox selection when toggling from the Directory to the Mailbox view.
Do this in `OP_TOGGLE_MAILBOXES` rather than every loop.
Fixes: #3376 
Some recent refactoring meant that `last_selected_mailbox` wasn't being updated,
so the main loop kept setting the cursor position to the same place.
---
**Steps**:
- Open mailbox
- Open browser `c?`
- Repeat:
- Move cursor
- `<tab>` to switch views
**Results**:
- The cursor position for the Mailboxes view is remembered
- The cursor can be moved after switching back-and-forth several times
=> fix: stuck browser cursor

store/lmdb.c
Co-authored-by: Richard Russon <rich@flatcap.org>
Fixes https://github.com/neomutt/neomutt/issues/3387
=> Don't overlimit LMDB mmap size

imap/edata.c, imap/edata.h, imap/message.c
We have three nested loops here:
1. separate chunks (see imap_fetch_chunk_size)
2. messages within one chunk + handle the datastructures for loop 3
3. responses from the server until we get a message
Loop 2 was entered a last time after all messages were fetched. I have
moved the call to progress_update to where we are sure we are handling a
new message, moved the exit condition at the end of loop 3 and turned
loop 2 into a while (true) to make it clear that the exit condition is
elsewhere.
Fixes #3389
=> Fix off-by-one error in progress during IMAP fetch

index/functions.c, menu/move.c
Remove lots of historic calls to `menu_queue_redraw()`.
In many cases, we already call `resolve_email()`, which is sufficient.
Also, change the Menu to only send a notification if something actually changed.
Fixes: #3390 
Functions affected (and tested):
- `<delete-message>`
- `<flag-message>`
- `<jump>`
- `<modify-labels>`
- `<next-entry>`
- `<next-new>`
- `<next-thread>`
- `<next-undeleted>`
- `<previous-entry>`
- `<previous-undeleted>`
- `<root-message>`
- `<save-message>`
- `<set-flag>`
- `<tag-message>`
- `<toggle-new>`
- `<undelete-message>`
---
**Steps**:
- Create an mbox format Mailbox containing ~100 emails
- Mark all of them _read_ apart from number 75
(it's important that are enough emails before and after so that the screen is filled)
- Run on this mailbox: `neomutt -f …
=> remove lots of unnecessary refreshes

gui/curs_lib.c
We use mutt_endwin whenever we need to switch to another program, e.g.,
set pager=vim, pinentry, etc... In #3318 I wrongly assumed that the
function would only be called on exit, so I hooked the cleanup and
freeing of queued macro and key events in it.
This caused the issue in #3398, where part of a macro was forgotten upon
calling an external program.
In this PR, I'm only removing the wrong cleanup. I'll keep the task of
moving the cleanup to a better spot for next time.
Fixes #3398
=> Don't free and forget queued macro/key events in mutt_endwin

Makefile.autosetup, attach/cid.c, attach/cid.h, attach/lib.c, attach/lib.h, attach/mutt_attach.c
When viewing a `text/html` part within a `multipart/related` group, this PR adds support for writing out all attachments with a Content-ID header and mapping `cid` references to filenames in the `text/html` part.
- The logic of `save_cid_attachment()` is similar to the code that saves the attachment in `mutt_view_attachment()`.
- The logic of `map_cid_to_filename()` is similar to the code that edits an attachment in `mutt_rfc3676_space_unstuff_attachment()`.
- #3209
- #3168
Call the following `rc` file using `./neomutt -n -F view-related.rc` from within the build directory.
A `multipart/related` email with an embedded image is created, postponed, and then its `text/html` part viewed.
If it worked (and you have an appropriate `mailcap` entry for `text/html`), you should see:
```
unset …
```
=> Support viewing text/html attachments with embedded images

conn/dlg_verifycert.c, history/dlg_history.c, keymap.c, pattern/dlg_pattern.c
Recent key-handling changes have left the user unable to quit from the three generic dialogs:
- Verify Certificate Dialog
- History Dialog
- Pattern Dialog
This PR changes those dialogs to accept <kbd>q</kbd> as `<exit>`
The bit I'm not certain about is the change to `retry_generic()`.
Before the change, the `q` keypress is pushed into the queue:
```c
if (lastkey)
mutt_unget_ch(lastkey);
```
but then dumped:
```c
if (mtype != MENU_EDITOR)
{
/* probably a good idea to flush input here so we can abort macros */
mutt_flushinp();
}
```
meaning that:
```c
return (struct KeyEvent){ .ch = mutt_getch().ch, .op = OP_NULL };
```
hangs, waiting for the user to hit <kbd>q</kbd> a second time.
=> menu: allow the user to quit generic menus

Makefile.autosetup, README.md, conn/accountcmd.c, conn/accountcmd.h, conn/config.c, conn/connaccount.c, conn/lib.h, docs/config.c, docs/manual.xml.head, mutt/prex.c, mutt/prex.h, mutt_account.h
This implements the proposal spec'd in #3405: it introduces a new
`account_command` config variable that can be set to the path of an
executable used to retrieve account credentials.
The following arguments to the script are produced:
* `--hostname`
* `--username`
* `--type` (`imap`, `pop`, `smtp`, `nntp`, with an optional trailing `s` for ssl)
The following keys are parsed from the command's output
* `login`
* `username`
* `password`
As an example, here's an account command that wraps [bwget](https://github.com/gahr/bwget):
```tcl
set entries {
imap.fastmail.com     { me@fastmail.com   "^FastMail-Me$"
you@fastmail.com  "^FastMail-You$" }
smtp.fastmail.com     { me@fastmail.com   "^FastMail-Me$"
you@fastmail.com  "^FastMail-You$" }
outlook.office365.com { me@hotmail.com    "^Hotmail$" …
```
=> Implement account_command

browser/browser.c, browser/config.c, docs/config.c
Implementation of #181.
Adds a new format string for viewing non-local mailboxes in the browser.
- browser/browser.c: folder_make_entry: receive BrowserState as data
and check if it's a mailbox to print it accordingly.
- browser/browser.c: mutt_buffer_select_file: pass BrowserState as data.
- browser/config.c: declare mailbox_folder_format.
- docs/config.c: document the new var.
For the default value, mailboxes should look like this:
=> browser: add mailbox_folder_format config variable

attach/mutt_attach.c
=> attach: fix segfault when viewing HTML attachment in compose mode

keymap.c
Probably shouldn't have done it but I was curious why pager did not use the generic menu.
On the way I found this superfluous piece of code.
It's superfluous because in the previous if we already checked the op for mtype, no need to do it again for editor if mtype == MENU_EDITOR.
=> keymap.c: Remove superfluous code

Makefile.autosetup, enter/enter.c, enter/enter.h, enter/functions.c, enter/lib.h, enter/state.c, enter/state.h, functions.c, opcodes.h, test/Makefile.autosetup, test/enter/editor_backspace.c, test/enter/editor_backward_char.c, test/enter/editor_backward_word.c, test/enter/editor_bol.c, test/enter/editor_case_word.c, test/enter/editor_delete_char.c, test/enter/editor_eol.c, test/enter/editor_forward_char.c, test/enter/editor_forward_word.c, test/enter/editor_kill_eol.c, test/enter/editor_kill_eow.c, test/enter/editor_kill_line.c, test/enter/editor_kill_whole_line.c, test/enter/editor_kill_word.c, test/enter/editor_transpose_chars.c, test/enter/state.c, test/main.c, test/pattern/dummy.c
Unify the behaviour of text-entry with that of readline.
- Kill line <kbd>Ctrl-u</kbd>
**Old**: Kill the entire line
**New**: Kill from the cursor to the beginning-of-line
- Capitalise <kbd>Alt-c</kbd>, Downcase <kbd>Alt-l</kbd>, Upcase <kbd>Alt-u</kbd>
**Old**: Fix case of **entire** word
**New**: Fix case from cursor to end-of-word
---
- 33571c45c add function `kill-whole-line`
Add a new NeoMutt function that kills the **entire** line
- 0e91123fa add state resize function
Let the state do its own memory management.
(this is another step towards making the text-entry buffer opaque)
- 028ccc9d8 match functions to readline behaviour
Fix behaviour of: `kill-line`, `capitalize-word`, `downcase-word`, `upcase-word`
- a8c405939 add test coverage
Create units tests for all the editor functions
=> enter: unify behaviour

Makefile.autosetup, enter/functions.c, enter/functions.h, enter/window.c, gui/lib.h, gui/msgcont.c, gui/msgcont.h, gui/msgwin.c, gui/rootwin.c, imap/imap.c, imap/private.h, progress/lib.h, progress/progress.c, progress/wdata.c, progress/wdata.h, progress/window.c, progress/window.h
The MessageWindow is used to display messages but also hijacked for user input and the progress bar.
As each user may want to store their own data, while active, this presents a problem.
The solution is to make each separate user have their own window.
A Message Container Window will be LIFO stack of windows, with only the top-most being visible.
The Message Window would always be present and accept `mutt_message()`, `_warning()`, etc.
When other users need to use the space, they will create a new window that has its own private data.
To check the window layout, compile with `--debug-window` and follow the logs, e.g.
```sh
tail -F ~/.neomuttdebug0 | sed 's/.*\]<.> [a-z0-9_]\+() //'
```
=> Put the MessageWindow users in Containers

contrib/Makefile.autosetup, contrib/account-command/README.md, contrib/account-command/keychain.py
A small Python 3 wrapper program to access the operating system's Keychain via the `security` command. Details for setting up NeoMutt to use this program are contained in `contrib/account-command/README.md`.
Using the recently implemented [account command](https://neomutt.org/feature/account-cmd)  (#3408), this is a Mac OSX specific implementation to use the internal password manager, Keychain Access. A small Python 3 program called by NeoMutt obtained from the `account_command` variable calls in turn the `security` program to obtain a password from the Keychain that is passed on back to NeoMutt.
For example, if you want to retrieve an IMAP email account `me@example.com` using SSL/TLS from `imap.example.com`, first generate an entry in the Keychain via
```
security add-internet-password …
```
=> Mac OSX Keychain support via account-command

muttlib.c
It allows expansion strings not to be limited to 256 characters.
In my index, I like to use a lot of icons and colors to categorize my messages based on the notmuch tags they get, this results in a very long `index_format` string because I'm not using `%g`, but am individually enumerating all the tags as `%Gx`.
My currrent index_format:
``
set index_format='%4C %Z %<[y?%<[m?%<[d?%10[     %H:%M  ]&%10[%a %b %d  ]>&%12[%b %d  ]>&%10[%b %d, %Y]> %-20.20L %?E?%2.e/%2.E&     ? %?Gi?%Gi&?%?GS?%GS&?%?Gr?%Gr&?%?Gt?%Gt&?%?GI?%GI&?%?GL?%GL&?%?Gl?%Gl&?%?GW?%GW&?%?GD?%GD&?%?Gc?%Gc&?%?Gs?%Gs&?%?Ge?%Ge&?%?Gp?%Gp&?%?Gw?%Gw&?%?Gf?%Gf&?%?Gn?%Gn&?%?Gu?%Gu&?%?Gg?%Gg&?%?Gy?%Gy&?%?GP?%GP&?%?Gh?%Gh&?%?GF?%GF&?%?G2?%G2&?%?GT?%GT&?%?GM?%GM&? %s'
``
This didn't render correctly as the …
=> muttlib/mutt_expando_format: allow for longer expansions in e.g. index_format

mutt/buffer.c
Fix a bug introduced in 34dc388b4 that caused `mutt_buffer_addstr_n()` to get a bit carried away when allocating memory.
As the function is used by the config parsing code, it caused a slowdown on startup and excessive memory usage.
Fixes: #3445
=> buffer: fix runaway memory allocation

contrib/oauth2/mutt_oauth2.py, contrib/oauth2/mutt_oauth2.py.README
allow use of oauth2 script without manual modification, set executable bit on script
* **Validation**
I didn't see any existing tests (please correct me if I'm wrong). To minimally validate the behavior works as expected, I applied the following patch and tested some inputs:
```diff
diff --git a/contrib/oauth2/mutt_oauth2.py b/contrib/oauth2/mutt_oauth2.py
index 66b741ae3..1bc9f6687 100755
--- a/contrib/oauth2/mutt_oauth2.py
+++ b/contrib/oauth2/mutt_oauth2.py
@@ -103,6 +103,9 @@ args = ap.parse_args()
ENCRYPTION_PIPE = args.encryption_pipe
DECRYPTION_PIPE = args.decryption_pipe
+print(ENCRYPTION_PIPE)
+print(DECRYPTION_PIPE)
+import os; os._exit(0)
token = {}
path = Path(args.tokenfile)
```
note that `shlex` handles spaces in quoted arguments as one would …
=> Add encryption and decryption pipes to arg parser

docs/manual.xml.head
Currently, there is no mentioning in the manual on how keys and certificates are handled with the GPGME backend for S/MIME.
Add a paragraph which gives some basics, so users are on the right track to get a simple S/MIME setup working.
=> Mention S/MIME key/certificate management with GPGME

Makefile.autosetup, complete/complete.c, complete/data.c, complete/data.h, complete/helpers.c, complete/lib.h, enter/functions.c, enter/wdata.h, enter/window.c, init.c, main.c, notmuch/lib.h, notmuch/notmuch.c
This is a small step forward towards an auto-completion API.
- 0ccb31556 complete: kill global data
Rather than using six global variables, create `struct CompletionData` and pass it to the functions
- 7d023452a complete: unify naming
Clean up the member naming
- 6d49fd2d9 complete: strip notmuch
Refactor the Notmuch completion to use the same array as other completions.
The other completion code fills the array with strings that are owned by other structs.
In the Notmuch case, we need to free them after use.
=> Refactor auto-completion code

index/dlg_index.c, index/functions.c, index/lib.h
Some functions when used from the Pager, cause threads to be uncollapsed:
- `<delete-message>`
- `<delete-thread>`
- `<edit-label>`
- `<flag-message>`
- `<modify-labels>`
- `<next-undeleted>`
- `<previous-undeleted>`
- `<save-message>`
- `<set-flag>`
- `<toggle-new>`
This behaviour was broken by the Index/Pager refactoring.
Fixes: #3460 
---
Change functions to optionally uncollapse a thread:
- `ci_next_undeleted()`
- `ci_previous_undeleted()`
- `resolve_email()`
Whether or not to uncollapse is determined by whether the Index is focussed, or not.
=> pager: fix next/prev behaviour wrt collapsed threads

pager/dlg_pager.c
WIP: This solves the problem, but it may need work...
- 700b91d9f help: disable index functions
When in the Help Screen (pager) disable the Index and Sidebar functions.
- cb68f49de pager: clear input buffer on error
If the function isn't recognised, this could be a broken macro.
Clear the input buffer to prevent accidents.
- c6aafb201 pager: only clear input buffer for help
Tighten up the check.
The macro behaviour when viewing emails is unchanged.
Fixes: #3464
=> help: disable index functions

compress/lz4.c, compress/zlib.c, hcache/hcache.c, imap/mdata.c, imap/message.c, nntp/newsrc.c, store/gdbm.c
Check local cache files while parsing them to prevent undefined behavior
like out of boundary reads.
No issue created. It can be tested by compiling with asan, gdbm, and zlib
(or lz4) and modifying the relevant store functions to write only 1 byte.
Required configuration: `set header_cache = "~/.mutt/cache"`
=> Handle corrupted header caches

enter/window.c
When using auto-completion on addresses, completing a second address would overwrite the first.
Partially reverts commit d5b865cbcd83e9499ad8f2b1f7006dce1a466419.
The commit keeps the memory-leak fixes, but restores the buffer check that was causing multiple addresses to be lost.
Fixes: #3473
=> enter: fix auto-complete loss of text

docs/config.c, nntp/config.c, nntp/lib.h, nntp/newsrc.c, nntp/nntp.c
Short values for this option are too limiting. And I came across
servers/implementations where not only article numbers are not
serial, but long gaps can exist between successive ones, so you
would have to set nntp_context to a high enough value (> SHRT_MAX)
to get enough articles back.
=> nntp: change nntp_context type to DT_LONG

enter/window.c
If the entry field has some default text, e.g. when changing folder, fix `<enter>` to select that text.
This was broken by some recent refactoring of the enter code.
=> enter: fix default text

command_parse.c, command_parse.h, hook.c
=> Allow `source` in hooks to point to relative paths

index/dlg_index.c
I don't know whether the assumption should hold, but currently it clearly does not.
Fixes #3498
=> Don't assume e->tree != NULL implies e->thread != NULL

enter/state.c, enter/window.c, test/enter/state.c
Fix a regression that lost data, e.g. when entering "To:", after using auto-completion on a second address.
---
Working:
- Selecting a default, e.g. a mailbox with new mail
- Adding to existing text, e.g. "To:" prompt + address auto-completion
=> enter: re-fix lost data

send/send.c, send/send.h
Fixes #3461
[`mutt_send_message`](https://github.com/neomutt/neomutt/blob/d8fd4643b1a4221163a96974543fcbd4c4a78892/send/send.c#L2303-L2320) needs the current email (first entry in EmailList) to resolve the reverse name.
=> Resolve alternates when subscribing/unsubscribing

complete/helpers.c
Fix a crash during auto-completion.
When resizing a block of memory there was an off-by-one when zeroing the new bit.
Thanks to @RaitoBezarius for the ASAN report (IRC)
```
=================================================================
==3638517==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6210000a4d00 at pc 0x7fbfa076528e bp 0x7fffbf64fca0 sp 0x7fffbf64f450
WRITE of size 1 at 0x6210000a4d00 thread T0
#0 0x7fbfa076528d in __interceptor_memset (/nix/store/k2a429wpxgfwp4jaacl9iaqw4kxqjaxa-gcc-11.3.0-lib/lib/libasan.so.6+0x3c28d)
#1 0x443e27 in memset /nix/store/ck17nf5q2m51d9jpkpsirx91s64vh202-glibc-2.35-163-dev/include/bits/string_fortified.h:59
#2 0x443e27 in matches_ensure_morespace /build/source/init.c:107
#3 0x443e84 in candidate /build/source/init.c:128
#4 0x4442d7 …
```
=> complete: fix resizing of matches

docs/manual.xml.head
Document that the `source` command accepts multiple filenames.
Document how `source` handles relative file names.
=> Document `source` command more thoroughly

core/mailbox.h, mbox/lib.h, mbox/mbox.c
Failing to do so results in checking the stats anew at each change change-folder. This might be slow for mboxes.
Fixes #3517
=> Keep track of when we last checked a mbox

docs/manual.xml.head, notmuch/config.c, notmuch/db.c
Since `notmuch` 0.32, `libnotmuch` has an API to open the database with
a configuration file. The options are a fully qualified path, empty
string for no configuration file, and NULL for auto-detection of notmuch
configuration. The `notmuch` backend relies on the auto-detection for
opening the database with a fallback to no configuration. We have no
mechanism for user-specified configurations.
To allow user specification, this commit introduces a new configuration
variable, `nm_config_file`. Users have the option of three values:
1. A path
2. An empty string for no configuration file
3. `auto` for auto-detecting a config. file
Allowing users to express the three possible options we can pass to
`libnotmuch`. The `auto` keyword allows us to workaround the constraints
of the configuration …
=> feat(notmuch): allow specifying notmuch configuration file

color/command.c
This makes sure that an invalid regular expression in a `color` command is caught and reported at parse time. See https://github.com/neomutt/neomutt/issues/3527.
=> Do not ignore errors parsing color lines

postpone/postpone.c
Fixes #3268
This is actually what the comment says we're doing, except we werent.
=> Do not look for a reference if we don't have a mailbox

email/parse.c, maildir/maildir.c
Distinguish between old/new with mark_old unset for maildir
Fix #1536
=> Distinguish between old/new with mark_old unset

.github/workflows/build-and-test.yml, .github/workflows/centos.yml, .github/workflows/fedora.yml, Makefile.autosetup, auto.def, conn/gsasl.c, conn/gsasl2.h, conn/lib.h, imap/auth.c, imap/auth.h, imap/auth_gsasl.c, imap/auth_sasl.c, imap/config.c, main.c, pop/auth.c, pop/config.c, send/config.c, send/smtp.c, version.c
Add support for the GNU SASL library, using **configure** option **`--gsasl`**
Add multiline response support for SMTP authentication (which is probably not actually needed).  Also add arbitrary line length for the SASL server responses (the RFCs note that for SASL, the protocol line lengths don't apply).
Upstream-commit: https://gitlab.com/muttmua/mutt/commit/68caf9140c8217ecf6c848460c4b4d27996b2922
=> Add GNU SASL support for authentication

auto.def
Arch Linux' gpg-error package comes without a `gpg-error-config` binary. Let's keep that as a fallback use pkg-config preferably.
=> Use pkg-config to locate gpg-error

auto.def, version.c
This adds `--ubsan` as a configure option. Adds compilation flag `--fsanitize=undefined`.
=> Add support for compiling with undefined behaviour sanitizer

imap/util.c
Apparently, the UB sanitizer isn't happy with us doing `foo + hlen + 1` when hlen is -1.
=> Make the UB sanitizer happier

docs/manual.xml.head, notmuch/config.c, notmuch/db.c
Introduce the `nm_config_profile` option for users to use notmuch profiles. It has a default of an empty string so notmuch will try `NOTMUCH_PROFILE` or the default value (`default` for directories, empty string for config files.)
=> feat(notmuch): allow usage of notmuch profiles

notmuch/db.c
Small refactor around the `msg` variable in `notmuch/db.c`.
- Removes a version check to improve function readability. There's negligible performance impact of an unused null pointer on the stack.
- Always frees `msg` if it's not null.
=> Refactor `msg` in `notmuch/db.c`'s `nm_db_do_open()`

notmuch/notmuch.c
Document that `get_nm_message()` returns `NULL` if an errors occurs, which sets `id` or `db` to `NULL`.
---
I was pretty confused why I was getting `NULL` during debugging when the function didn't mention that as a valid return value.
=> notmuch: document `get_nm_message()` error value

test/date/mutt_date_parse_imap.c
Obvious bug, this is supposed to be a string, but a struct is passed instead, fails on some uncommon calling conventions.
=> fixed possible fail in mutt_date_parse_imap

Makefile.autosetup, auto.def, ncrypt/crypt_gpgme.c, ncrypt/gpgme_functions.c
The first GPGMe version to ship a pkg-config file is 1.13.0, released in March 2019. See this [upstream commit](https://dev.gnupg.org/rMf3e60521899e6126229b6efedc9f011b84122e11). I think it's ok to assume at least 1.13.0 is present, given that we already use pkg-config for gpg-error.
Fixes #3553
=> Use pkgconf to find GPGMe

auto.def
Debian [1], FreeBSD [2], and probably other OSs provide pkg-config files for lmdb. However, brew [3] and upstream [4] don't and don't want to.
Let's fallback to manual detection of LMDB, in case the pkg-config file is not there.
[1] https://salsa.debian.org/debian/lmdb/-/blob/master/debian/rules#L27-36
[2] https://cgit.freebsd.org/ports/plain/databases/lmdb/files/lmdb.pc.in
[3] https://github.com/Homebrew/homebrew-core/pull/115376#issuecomment-1310483540
[4] https://github.com/Homebrew/homebrew-core/pull/115376#issuecomment-1310462073
=> Fallback to manual detection of LMDB

conn/getdomain.c
When we compute the hostname, we get the canonical name from addrinfo, take the part after the first ".", and use that as a domain name. It might happen (see #3568) that addrinfo.ai_canonname ends in a ".". In this case, we don't want to end up constructing "<hostname>.", so let's skip an empty domain name altogether.
Fixes #3568
=> Do not return a single "." for a domain name

conn/getdomain.c
This is an attempt to speedup recovery from getaddrinfo_a timeouts. I am not familiar with this family of APIs and I don't have a linux box to test this on, so I have no idea if this is correct.
=> Don't wait after timeout from getaddrinfo_a

address/group.c
The cleanup is already taken place by the group_hash_free destructor.
Fixes #3588
=> Fix deletion of address group

pop/pop.c
The member `a->adata` used to be a dangling pointer when
`mutt_conn_new()` returned a null pointer. This would cause either a
double free or a segmentation violation further in the execution.
It prevents `pop_ac_add()` from leaving a dangling pointer in `a->data`.
This dangling pointer causes at least two crashes:
* A double free at this stacktrace (truncated at `free()`):
```
#8  0x000055555565a4ec in mutt_mem_free (ptr=ptr@entry=0x5555558bb1f0) at mutt/memory.c:75
#9  0x00005555555b8928 in pop_adata_free (ptr=0x5555558bb1f0) at pop/adata.c:47
#10 0x000055555563f2ad in account_free (ptr=ptr@entry=0x7fffffffe060) at core/account.c:155
#11 0x000055555559bd43 in mx_mbox_ac_link (m=m@entry=0x5555558a8e10) at mx.c:286
#12 0x000055555559c03f in mx_mbox_open …
```
=> Fix dangling pointer in `pop_ac_add()`

send/smtp.c
Prevent Neomutt from sending an incomplete line (without \r\n) to an SMTP server if the username or password is to long.
=> Do not truncate "\r\n" in SMTP communication

docs/neomutt.man
Adds missing markup in docs/neomutt.man to separate `-H` from other command line options.
**Important**: Do not forget to run your strange, *secret*, rituals to update the documentation. ;-)
Solves #3598.
=> Fix markup-typo in neomutt(1) man page

envelope/window.c
Not sure about this but it seems that changes of `$smime_sign_as ` are not responded to.  If this is intentional, feel free to close this PR.
=> Recalc envelope window if smime_sign_as changes

envelope/window.c
Do not use pgp_sign_as but smime_sign_as when signing messages.
I believe there is a copy and past error as the signing for S/MIME queries the **pgp**_sign_as instead of the **smime**_sign_as config varialble.
=> Use smime_sign_as when signing S/MIME messages

docs/config.c, docs/manual.xml.head, send/config.c, send/send.c
Rename the config variable `ask_follow_up` to `ask_followup_to` so that its name matches the header name it is guarding (namely `Followup-To:`) and to be consistent with the config variable `followup_to_poster`.
Create synonym `ask_follow_up` to not break existing configs.
=> Rename ask_follow_up to ask_followup_to

docs/neomuttrc.man.head
Fix markup typo in description of `uncolor` in neomuttrc(1)
=> Fix markup typo in description of uncolor in neomuttrc(1)

docs/config.c
Document interaction between $reflow_wrap and $wrap
It might be surprising to some that even if lines of format=flowed messages are wrapped using $reflow_wrap they are then again wrapped at $wrap characters.
=> Document interaction between $reflow_wrap and $wrap

docs/neomuttrc.man.head
The `attachments` command was only partially documented in the neomuttrc(5) manpage.  Copy the bits from the Neomutt Online Reference about the "+" and "-" argument as well as the "attachments ?" and "unattachments *" commands.
Fix also markup and highlight the "inline" and "attachment" arguments as keywords.
=> Fully document `attachments` command in neomuttrc(5)

docs/neomuttrc.man.head
1) Fixes a markup typo
2) Documents the syntax `color status foreground background [ regex [ num ]]` in neomuttrc
=> Document regex and sub-match argument to `color status`

docs/config.c
Change references of `$sidebar_whitelist` to `sidebar_whitelist`. Since `sidebar_whitelist` is a command it should not be prefixed by a dollar `$`.
=> Omit `$` as `sidebar_whitelist` is a command not a variable

docs/config.c
The documentation of $header_cache reference a section "caching" which only exist in the NeoMutt Guide but not in the man page.  Clarify that this is reference to the guide.
Note: We did not change the name ("caching") of the reference, even if the referenced section is called "Local Caching" in the chapter "Optional Features".  The reason to keep this wrong name is to get a proper linking as "caching" is the HTML anchor name of the target section.
=> Clarify reference to NeoMutt guide in $header_cache

docs/config.c
Enhance the documentation of `$thread_received`.
From the old explanation I didn't understand what `$thread_received` does.
Digging into the code I *believe* it does what the doc in this PR describes.
The relevant lines of code (and only usage side of `$thread_received`) are in `mutt_thread.c` lines 502-605:
`https://github.com/neomutt/neomutt/blob/7ddad5ee30830496d336cd9c2cb756cfd547bc8b/mutt_thread.c#L502-L605`
P.S.: Again don't forget to run your strange, secret, rituals to update the manpage and homepage ;-)
https://github.com/neomutt/neomutt/blob/7ddad5ee30830496d336cd9c2cb756cfd547bc8b/mutt_thread.c#L502-L605
=> Document $thread_received more detailed

docs/config.c, handler.c, mutt_config.c
Rename `implicit_autoview` to `implicit_auto_view` to bring its name in line with the command `auto_view`.
A synonym `implicit_autoview` is provided for backwards compatibility.
Fixes #3626
=> Rename `implicit_autoview` to `implicit_auto_view`

docs/config.c, docs/manual.xml.head, docs/neomuttrc.head, docs/smime-notes.txt, ncrypt/crypt.c, ncrypt/smime.c
Do not generate the legacy MIME types application/x-pkcs7-* (note the "x-") but the standardised types application/pkcs7-*.
The application/pkcs7-* MIME types are standardised in [RFC8551] section 3.2.  The (historic) [RFC2311] states in section C.1
Some early implementations of S/MIME agents used the following MIME
types:
application/x-pkcs7-mime
application/x-pkcs7-signature
application/x-pkcs10
In each case, the "x-" subtypes correspond to the subtypes described
in this document without the "x-".
[RFC8551] https://datatracker.ietf.org/doc/rfc8551/
[RFC2311] https://datatracker.ietf.org/doc/rfc2311/
=> Use the (new) application/pkcs7-* MIME types

docs/neomuttrc.head
**WARNING This patch is intended to be on top of PR #3634**
To save me and you from some merge conflicts I made this adjustments after the correction to the MIME type application/pkcs7-*.  However, I was not able to figure out how to tell GitHub that this comes after that PR. So this also includes the commit of PR #3634.
---
Reword the comments around the handling of attachments with respect to application/pkcs7-
Also update the style to reflect the other comments and get rid of artefacts from a time long gone, where attachment handling was a separate patch to Mutt.
=> Update style and comments in the default neomuttrc

docs/manual.xml.head, docs/neomuttrc.man.head
1) `attachments` and `unattachments` can take more than one MIME type
2) When counting attachments the first MIME part is treated slightly differently, we document this.
**Note** maybe the algorithm for the exceptions of the first MIME part is documented to precisely.  Maybe it suffices to just say:
> "The first MIME part is treated slightly differently because it is almost always the message text."
=> Document additional quirks of the `attachments` command

docs/manual.xml.head, docs/neomuttrc.man.head
Since eb48fd1368b5d821a74708963aff45f61b709a4b hook store the file context they are defined in and restore that context when they execute their commands.  As a result a source command inside a hook is executed with the context of the file the hook was defined in.  Thus, relative filenames are interpreted relative to the source file the hook was defined in.
=> Document handling of `source` command inside hooks

color/command.c, init.c
- warn about colours not objects
(we already have a translation)
- config: skip line rest of line after a warning
Don't try to parse the rest of a line, after a mistake is found
Fixes: #3615
=> config: skip line rest of line after a warning

sidebar/observer.c
If `$sidebar_divider_char` changes, force a repaint of the sidebar.
Fixes: #3610
=> sidebar: repaint on sidebar_divider_char change

docs/manual.xml.head, mutt_header.c
When composing messages NeoMutt supports some pseudo headers like "Attach:" or "Pgp:".
Implement the "Smime:" header which allows to select S/MIME encryption/signing just like the "Pgp:" header. The valid values for the header are the same as for "Pgp:", namely "E" (encrypt), "S" (sign), and "S <id>" (sign as).
Brings support of S/MIME closer on par with PGP.
* **Rambling Notes**
I noticed that postponed mails have an "X-Mutt-PGP:", "X-Mutt-SMIME:" header.  Maybe it might be worth supporting those too when composing a message? (maybe even saying that those should be used as they avoid ambiguity??)
=> Implement `Smime:` pseudo header for composing

docs/manual.xml.head, docs/neomuttrc.man.head
As of 7d01b8c2dac8f3497e714b95625010fcafae5296 the suffix version (`set allow_8bit?`) is preferred over the prefix version (`set ?allow_8bit`).
Document the querying syntax with a suffix ``?``, e.g.
:set allow_8bit?
prominently and note that the old prefix syntax is still supported.
=> Document the suffix querying syntax for config variables

docs/manual.xml.head
The internal viewer can only handle the text/plain MIME type correctly. While it is true that the pager can view any plain text, it does not necessary display it faithful, e.g. HTML tags would be shown as is and not hidden.
Do not exaggerate that capability by claiming all text/* MIME types are supported.
Also mention that S/MIME is internally supported just like PGP.
=> Neomutt does internally only support text/plain MIME type

pager/dlg_pager.c
I don't understand the event loop (nor the "multi"threading) between pager and index fully.  However, the timer check should be done *after* the statement which takes the idle time, here waiting for user input.  They should also done *before* handling the operations as those can alter the internal state (like the current mail) leading to bugs such as #3609.
Alternatively, we can do the timer check at the end of the loop. To this end, we have to introduce two local variables `cur_mail`, `cur_mailbox` set them at the beginning of the loop and use those cached values at the end of the loop in the timer check (the `mutt_set_flag` call).
Please check if this does not break any other invariant other parts of the code relay upon.
Fixes #3609.
=> Fix `$pager_read_delay`

docs/config.c
It might be just me but I found the wording "or as a result ..." confusing.
When describing $keep_flagged the "move" verb was ambiguous on whether it meant only in the $move context or generally when moving mail from one mailbox to another, e.g. with <save-message>.
=> Reword documentation of $keep_flagged and $move

docs/config.c, docs/manual.xml.head, docs/neomutt.man, init.c, mbox/mbox.c, mutt/file.c, mutt_config.c, muttlib.c, test/file/mutt_file_mkstemp_full.c
Rename `tmpdir` to `tmp_dir` to bring it in line with other `*_dir` config variables like `attach_save_dir`, `autocrypt_dir`, `news_cache_dir`.
A synonym `tmpdir` is provided for backwards compatibility.
This rename can be seen as controversal:
Pro: uniform naming scheme
Con: $TMPDIR (the environment variable) is a well known, well, environment variable and `tmpdir`/`tmp_dir` is closely related.
If you don't like it, then close it.
=> Rename `tmpdir` to `tmp_dir`

maildir/maildir.c
Reset `m->msg_new` to zero unconditionally, because `check_new` triggers a recomputation of it.
Fixes #3649
=> Fix negative new count on maildir

pager/display.c
Fixes #3580
Upstream-commit: https://gitlab.com/muttmua/mutt/-/commit/a60b22fe2a250f87769239b6120c2ff5de751b28
=> Skip zero width non-joiner in the pager

docs/config.c
$forward_decrypt also applies to S/MIME encrypted mails.  Remove the "PGP only" flag on that option.
=> Document that $forward_decrypt is not PGP only

ChangeLog.md, alternates.c, docs/config.c, docs/manual.xml.head, docs/neomuttrc.man.head, email/globals.h, sidebar/commands.c, sidebar/observer.c, sidebar/private.h, sidebar/sidebar.c, sidebar/window.c
* Rename sidebar_whitelist / sidebar_unwhitelist to sidebar_pin / sidebar_unpin (old commands are still provided for backwards compatibility)
* Rename internal functions to match the above command renaming
* Remove the words "blacklist" and "whitelist" from API comments.
Closes: #3619
=> Rename sidebar_whitelist to sidebar_pin

docs/manual.xml.head, docs/neomuttrc.head
Similar to https://github.com/neomutt/neomutt/pull/3634
---
We already exclude text/x-vcard from being an attachment, also do that for its successor text/vcard.
[RFC 6350] states in section 10.1 that text/x-vcard is a deprecated/legacy MIME-type and that text/vcard should be used.
[RFC 6350] https://datatracker.ietf.org/doc/rfc6350/
=> Recognise text/vcard as not an attachment

docs/config.c
Enhance documentation of $suspend to mention that NeoMutt tries to identify the correct default behaviour.
=> Clarify the default of $suspend

docs/config.c, docs/manual.xml.head, notmuch/config.c
1. Deprecated `$vfolder_format`.
2. Swap paragraphs in `$virtual_spool_file` to make clear that this variable is also considered deprecated.
Closes: #3667
=> Deprecated `$vfolder_format`

copy.c
The algorithm to sort headers by the order given in hdr_order sorted the last mentioned header in hdr_order at the same level as unmentioned headers, i.e. not at all.
The bug was introduced in d9ff90dced82e7328dff4abc0918ee0020af8d0a.
The algorithm puts headers in buckets labeled by their priority (0 = highest, n = lowest).
The problem is that the "priority counter" (which starts at 0) `x` is first incremented and then the header is assigned to priority `x`. Thus, the buckets 0 to n become 1 to n+1 and the header mentioned last in hdr_order (number n) was sorted in the bucket n+1 together with all other headers.
The fix is simple: First sort the header in the bucket, then increase the priority counter.
=> Fix bug: hdr_order did not sort last header correctly

pop/pop.c
In commit  [c97f9d9d23e90e65e204d2a3b33bb3f7f935a8ff](https://github.com/neomutt/neomutt/commit/c97f9d9d23e90e65e204d2a3b33bb3f7f935a8ff), I fixed a memory leak when closing a POP connection. This turned out to cause a double-free crash when fetching mail. `mutt_mem_free()` setting its passed pointer to `NULL` did not help because the pointer stored in `adata` was a copy.
This commit fixes this. Valgrind does not report the resource to leak when fetching mail.
None.
=> Fix a double-free crash when using :fetch-mail

gui/curs_lib.c
1) Clarify to the user that exiting via SIGINT does *not* save. Previously, the question was phrased the same as the for the `quit` function (which dose save the mailbox), now it is the one from the `exit` function (which does not save).
(No new translation entry is needed)
2) Exit with exit code 0.  The user was asked, they replied, we acted, so this should be considered a normal run, not one with a special exit condition (i.e. != 0)
---
When comparing the SIGINT exit routine with the `exit` function one, we see differences (see below).
This leads to the question, whether the SIGINT code path should do a little more than calling `exit(0)` directly (maybe closing the mailbox)?
https://github.com/neomutt/neomutt/blob/ff76d02c585b81daae56d03e86222621dbd86abc/gui/c …
=> Make exiting via SIGINT more graceful

color/curses.c
The format string used 4 arguments, but only 3 were given.
I made a blind guess what could have been meant.  If that's not it, then please help yourself.
=> Fix printf-format string in debug output

docs/config.c, docs/manual.xml.head
Remark: It might be worth unifying the values between the classic PGP (`+ -?`) and the GPGME backend (`?qnmfu`).
=> Document values of the %t expand for the GPGME backend

pager/pager.c
I got a crash here after a restart of dovecot left me without a mailbox:
```
pager/pager.c:323:59: runtime error: member access within null pointer of type 'struct PagerView'
```
Not sure how we came here, but I figure it's worth checking before dereferencing anyway :)
=> Check before dereference

conn/config.c, conn/raw.c, docs/config.c
Instead of adding dedicated timeout options for read/write, like upstream did, we're reusing the connect_timeout and renaming it to socket_timeout. At this point, we don't see a reason for wanting to specify different values for the connect/read/write operations.
Upstream-commit: https://gitlab.com/muttmua/mutt/-/commit/185346ad778f85f7889cff662516e2121bb1edbb
=> Rename connect_timeout to socket_timeout, use it for read/write ops too

opcodes.h
The patterns given to the functions `<delete-pattern>`, `<undelete-pattern>`, `<tag-pattern>`, and `<untag-pattern>` only match messages which are not hidden, i.e. shown by the limit and not collapsed inside a thread.  This is in contrast to the pattern matched by the `<limit>` function which applies to all messages in the mailbox hidden or not.
Note: This might invalidate a couple of translations.
Closes: #3690
=> Document that some pattern operations only apply to visible messages

send/send.c
When sending fails after a message has been signed (but not encrypted), then the `multipart/signed` container is not removed, leaving a corrupt `multipart/signed` message without the actual signature. Subsequent attempts to send the message add additional corrupt `multipart/signed` containers.
This PR removes the `multipart/signed` container in this case.
Fixes #3705
=> send: delete signature when sending fails

docs/config.c, ncrypt/crypt_gpgme.c, ncrypt/dlg_gpgme.c
1) The first commit fixes a legacy/mixup of $smime_default_key, I've stumpled while coding the rest.  Since you flatten your history anyway, I refrained from providing a separate PR.
2) Add a new expando, `%i` to `$pgp_entry_format` which expands to the full fingerprint of a key (or its long id, if there is no fingerprint).
3) Discussion worthy:  change the meaning of `%k` and `%i` expandos.  This naming aligns better with the actual names `i` for id and `k` for `key fingerprint`.  Obviously, this is a user visible change, its strictly providing more information as the keyid is a substring of the fingerprint.  I guess almost nobody will notice.  To mitigate the change even further we could change the default `$pgp_entry_format` to use  `%i` instead of `%k`, so …
=> Provide expando to show the fingerprint of a key

browser/browser.c, docs/config.c
This is a patch I've bin sitting on for a while, I've polished it a little, so maybe it might be useful to others.
The patch adds the `%[fmt]` expand to browser format to allow formatting the date with an `strftime(3)` sequence similar to what `$pgp_entry_format` has.
To my knowledge this is the last format which relies on `$date_format` but had no other way of formatting dates, so maybe you guys can think about deprecating `$date_format`.
=> Allow %[fmt] in $folder_format

docs/config.c
This is a followup to #3717 following a suggestion of @flatcap.
Describe alternatives to using $date_format, namely `%[fmt]` (or in the case of the index also `%{fmt}`)
=> Document alternatives to $date_format

debug/graphviz.c, docs/manual.xml.head, docs/neomuttrc.man.head, pattern/exec.c, pattern/flags.c, pattern/lib.h
Maybe answer @flatcap 's question:
> Are you sitting on any other useful patches?
Whether this is useful to you or not depends.  It slightly modifies existing patterns (or phrased pessimistically it breaks them) and steals another character from the alphabet for the Bcc field.  Note that lower k is used to find keys, since I do not expect a ~c <-> ~C duality for Bcc, one letter is all we need.  I believe I chose K because its counterpart was already taken, instead of e.g. j where both j, J are still free.
1) patterns ~C, %C, ~L and ~p now also search Bcc
2) add pattern ~K to search Bcc field
=> Let patterns cover Bcc header

debug/parse_test.c, docs/config.c, docs/manual.xml.head, recvcmd.c, send/config.c, send/send.c, send/send.h
Rename $attribution to $attribution_intro and $post_indent_string to $attribution_trailer.
Some minor rewording in the documentation.
Fixes #3715
=> Rename $attribution and $post_indent_string

.gitignore, Makefile.autosetup, auto.def, test/Makefile.autosetup
This adds a `--compile-commands` configure option to generated a clang
compilation database. This only works if the compiler is clang.
=> Generate compile_commands.json

init.c, main.c, myvar.c, myvar.h
`neomutt -D` now also lists user-defined variables.
=> Dump user-defined variables in `neomutt -D`

docs/manual.xml.head
Doc update for the now randomly generated message-id header.
=> Information leaks: Mention that Message-ID is random

postpone/postpone.c
I don't claim that I fully understand what the code does, but by symmetry between S/MIME end PGP this should be as presented here (and it fixes #3711 too!)
The issue is that when postponing a Mail marked for S/MIME encryption and then recalling that encrypted message, then the headers seem to get corrupted.  Actually, I believe now that the headers are not corrupted they are the headers belonging to the outer message + some random(?) modification to set the MIME type to text/plain:
https://github.com/neomutt/neomutt/blob/01733225d4eed2a12b8400d37df881b3d94143c5/postpone/postpone.c#L466-L467
(Quest for the ambitious: Figure out why this is there and if it can be removed)
I believe what actually happened was, that the S/MIME message was *not decrypted at all*! A decryption code path existed …
=> Fix decryption issue when postponing S/MIME encrypted mails

init.c
A few config variables' initial values weren't being set correctly.
Fix the initial values of:
- `$mailcap_path`
- `$tmp_dir`
- `$suspend`
Fixes: #3741
=> config: fix initial values

docs/config.c
The Message-ID: header is now random and does not contain the $hostname anymore.  Purge all statements stating the contrary.
=> Remove outdated statements about $hostname in Message-ID

color/color.h, color/command.c, docs/config.c, docs/manual.xml.head, docs/neomuttrc.man.head, sidebar/observer.c, sidebar/window.c
A minor addition to the sidebar:
- Add a `sidebar_background` colour
- Allow the `$sidebar_divider_char` to be empty
- Remove some very old sidebar docs
Give the Sidebar a background colour to allow contrast from the Index.
This now allows the divider character to be turned off (giving the user extra space).
=> sidebar: add background colour

docs/config.c, sidebar/config.c, sidebar/observer.c, sidebar/private.h, sidebar/window.c
- Allow an empty value for the divider
- Set the divider's default value to a Unicode vertical line
- Simplify the logic for `$ascii_chars`
If the user sets `$ascii_chars` or the charset isn't utf-8, then the divider character will fallback to an ASCII pipe character `|`.
Fixes: #3750
=> sidebar: allow an empty divider

address/address.c, address/address.h, alias/alias.c, alias/dlg_alias.c, alias/dlg_query.c, autocrypt/gpgme.c, commands.c, config/address.c, copy.c, envelope/functions.c, envelope/wdata.c, envelope/wdata.h, envelope/window.c, hdrline.c, main.c, mutt/buffer.c, mutt/buffer.h, ncrypt/pgpinvoke.c, recvcmd.c, send/header.c, send/send.c, send/sendlib.c, test/Makefile.autosetup, test/address/mutt_addr_write.c, test/address/mutt_addrlist_parse.c, test/address/mutt_addrlist_write.c, test/address/mutt_addrlist_write_list.c, test/buffer/mutt_buffer_insert.c, test/main.c, test/parse/mutt_parse_mailto.c
Fixes #3745 
Also, refactor the AddressList writing routines to avoid duplicated logic.
In particular, we don't want multiple places in the code to be aware of how we represent address groups:
it's ugly and I would like to change it, eventually.
=> Fix how group addresses are displayed

docs/config.c, docs/manual.xml.head, docs/neomuttrc.man.head, hook.c
1) Try to use the word "pattern" only for NeoMutt patterns like `~f Alice` otherwise use regex or string.  This applies to the synopsis of commands as well as their description
2) Add examples how to quote inside patterns and inside regexs
3) Fix some quoting mistakes in examples (last commit, please verify)
=> Rewording around Regex and Pattern

.editorconfig
According to the spec, utf-8 must be spelled "utf-8" https://spec.editorconfig.org/#supported-pairs
https://spec.editorconfig.org/#supported-pairs
=> editorconfig: fix charset entry

docs/config.c, imap/command.c, imap/config.c, imap/imap.c, imap/private.h
Adds a `imap_send_id` boolean config, defaults to false. When set, an `ID` command will be sent to the server when logging in. This provides the IMAP client name and version to the server.
Example log output:
> [2023-03-25 10:49:45]<2> mutt_socket_write_d() 4> a0004 ID ("name" "NeoMutt" "version" "20230322-18-a8bdba-dirty")
#3769
=> Add support for IMAP ID extension

notmuch/db.c
According to Debian clang version 17.0.0 (++20230318071855+864a2b25beac-1\~exp1~20230318072020.597):
```
notmuch/db.c:84:20: warning: unused function 'get_nm_config_file' [-Wunused-function]
static const char *get_nm_config_file(void)
^
```
There's one user, just below, guarded by the same `#if`
=> notmuch: #if out get_nm_config_file() where unused

auto.def
On macOS, neomutt can be built against the system-provided `libsasl2`.
However, since d52a637, detection of the system `libsasl2` broke since
there is no pkg-config file provided.
We can fix that by falling back to the old detection scheme for SASL,
which allowed use of system `libsasl2`. This allows users on macOS to
enable the feature without having to provide additional dependencies
themselves.
I patterened this change after the similar fallback for LMDB in 4974ff3.
=> Fall back to manual detection of SASL

Makefile.autosetup, contrib/Makefile.autosetup, data/Makefile.autosetup, docs/Makefile.autosetup, po/Makefile.autosetup
- d3403d150 build: use `$(INSTALL_DATA)`
- 04b61e5e2 build: create `$(INSTALL_DIR)`
- 2c67e8161 build: create data dir separately
Tested:
- A wide variety of builds
- Building out-of-tree
- Installing, uninstalling
=> build: tidy Makefiles, fix race condition

send/smtp.c
This follows the same logic as all the other protocols, imap, pop etc.
smtp seems to have been forgotten at the time.
This fixed the issue Dan had on the neomutt-users ML (I hope?)
It might also segfault, or eat my cat or whatever as I am not a C dev... just tried to replicate the imap code here.
I'm also not sure which header to include to get the Neomutt global object to get at the config option.
=> smtp: ignore oauth if it isn't configured and not requested

attach/mutt_attach.c, copy.c, help.c, index/functions.c, mutt_config.c, pager/config.c, pager/do_pager.c, pager/lib.h
The setting `$pager` has three possible values.
If it's empty, or contains the magic string `builtin`, then the internal pager will be used.
Otherwise it's the name of an external command.
Create a helper to hide the `builtin` magic. 
---
- Move the $pager config item to libpager
- Create a wrapper for $pager to hide the magic value: "builtin"
=> pager: add helper for getting $pager

hcache/serialize.c
Removes spurious +1 added to allocated buffer size in hcache serialization. This causes read overruns, e.g. 257 bytes from a 256 byte buffer which leads to ASan crashes when the stars align right.
None.
No user visible changes, no new test failures.
#3763
=> hcache: remove spurious +1 from Buffer serialization.

mutt/string.c, mutt/string2.h
This function is heavily used, so it can be inlined. Also convert it from a strchr() call to a simple if, which the compiler can optimize into a bit test.
Speeds up opening a large Maildir by about 2%.
for that)
* **What are …
=> mutt: optimize and inline mutt_str_is_email_wsp()

progress/progress.c
If we're not changing the progress bar, there's no need to ask ncurses for an update.
This means that we won't immediately resize on SIGWINCH, but wait until the next time the progress bar updates. That should be fine, though.
Speeds up opening a large Maildir by about 3.5%.
for that)
- …
=> progress: update ncurses only when there is actual progress

email/parse.c, email/rfc2047.c
Looking up assumed_charset in the configuration hash table is not free, so doing it over and over again is not useful.
Speeds up opening a large Maildir by about 1.5%.
for that)
=> email: Read assumed_charset outside loops

hcache/hcache.c, maildir/maildir.c
If hcache is compiled in, but it's not actually in use, we would still go through a lot of the motions; check for flags, stat() files (if maildir_header_cache_verify is not explicitly turned off), and so on. We can short-circuit a lot of these operations by simply checking early on whether the hcache is NULL or not.
Speeds up opening a large Maildir by about 2.5% (in the specific situation where hcache is compiled in but not enabled).
for that)
- All builds …
=> hcache: do less work when not in use

AUTHORS.md, browser/functions.c
Fix a segmentation fault that occurs in `op_browser_subscribe()` when the list of mailboxes is empty. The macro `ARRAY_GET` intentionally returns NULL when an out-of-bounds index is accessed; this value is assigned to `*ff`, causing a null pointer access in `mutt_str_copy()`.
Return `FR_ERROR` from `op_browser_subscribe()` if there are no mailboxes in the browser.
=> browser: fix crash in op_browser_subscribe()

pop/pop.c, send/send.c
The first patch is copied from the IMAP one. The rest should be functionally equivalent.
See #3810
=> Roundup but for warnings

convert/convert.c, email/rfc2047.c, handler.c, main.c, mutt/charset.c, mutt/charset.h, ncrypt/gnupgparse.c, ncrypt/pgpmicalg.c
Calling iconv_open() for every message can be expensive (it seems especially with some source charsets, like iso-2022-jp), and libc does not necessarily cache anything itself. Add a small LRU cache around it.
Speeds up opening a large Maildir by about 8%.
for that)
- Code follows the …
=> mutt: cache calls to iconv_open()

Makefile.autosetup, auto.def, test/Makefile.autosetup
Make it more obvious how to run the NeoMutt unit tests.
- e40deede4 build: drop configure --testing option
Always include the test Makefile, just don't build anything by default
- 2f5080c86 build: add instructions for testing
If `$NEOMUTT_TEST_DIR` isn't set, or the directory doesn't contain `setup.sh`
---
To run the unit tests, test files must be downloaded from:
- https://github.com/neomutt/neomutt-test-files
and an environment variable must be set to point to the test files:
- `export NEOMUTT_TEST_DIR=/path/to/neomutt-test-files`
=> build: refactor testing

auto.def
We don't need to add all the subdirs because their .o files are listed including the subdir path.
This unbreaks `make clean; make test/neomutt-test; make neomutt`, which previously failed in the last command because the `main.o` target required by `neomutt` was resolved by `test/main.o`, for the utmost sorrow of the linker.
=> Only add the root SRCDIR to VPATH

email/parse.c, email/parse.h, pattern/exec.c, test/parse/mutt_rfc822_read_line.c
This cleans up the mutt_rfc822_read_line API and implementation, and it makes it return the number of chars read from the file.
=> Use Buffer in mutt_rfc822_read_line

email/parse.c
Every call to ftello() translates into an lseek() system call, because glibc cannot know whether someone moved the underlying file descriptor or not. Keep track of the position ourselves instead of checking anew for every header line that we read.
Speeds up opening a large Maildir by about 19% (!).
for that) …
=> email: call ftello() less

mutt/date.c, mutt/eqi.h, mutt/lib.h, mutt/prex.c, mutt/prex.h, test/date/mutt_date_check_month.c
sscanf() is a generic and large function, which is overkill for parsing our simple 2- and 4-byte dates and years. Replace it with a trivial integer parsing routine.
Speeds up opening a large Maildir by about 3%.
for that)
* …
=> mutt: do strict date parsing without regex

email/parse.c, email/parse.h, mutt/eqi.h, mutt/lib.h, test/parse/mutt_rfc822_parse_line.c
Instead of calling the fully general mutt_istr_equal(), we can do with a few loads, ORs and compares.
Speeds up opening a large Maildir by about 1%.
for that)
=> parse: faster case-insensitive mutt_rfc822_parse_line()

docs/config.c, pager/message.c, pager/pager.c
`set pager_index_lines = 5` will use less than five rows when fewer than five messages. `set pager_index_lines = -5` always uses five rows, even if some are blank.
> &lt;flatcap&gt; start with no config, and we can think a bit longer about if we want to change the default behaviour
=> Make $pager_index_lines use a fixed number of rows

auto.def, color/command.c, color/curses.c, docs/config.c, docs/manual.xml.head, docs/neomuttrc.man.head, init.c, mutt_config.c, parse/extract.h
and, yes, this is a one line change.
Obviously, this is the bare heart of the machine without any chassis, safeguards, etc.
It's a proof of concept whether this would be acceptable to NeoMutt and maybe we can built on it.
Try this:
```
TERM=xterm-direct neomutt  -F /dev/null -e 'color status color65535 color16711935'
```
This should display a cyan on magenta status line.  The numbers are the RGB color `#00FFFF` and `#FF00FF` expressed in base 10.  Another example: If you want to, say, use the color `#12af84`, you would use the number 1224580.
*  Needs a new enough ncurses and terminal as well as properly setup terminfo.
*  For some reason on my system the colours `#000000` to `#000007` are not black but the standard 8 terminal colours (red, green, ...).  I assume ncurses dose some …
=> Implement 24bit colors aka truecolor

pager/pbar.c, progress/window.c, status.c
Some languages, including Turkish, French etc. use a different percentage display format like %100, 100 % respectively. Allowing percentage i18n makes it more coherent with the system locale settings.
=> Allow percentage i18n

maildir/maildir.c
We only want to change msg_new if we're gathering stats. If we are only checking whether the mailbox has any new messages, we'll stop at the first new message we encounter, so msg_new would always be 1.
We've been touching this code lately, so I'm unsure if I'm breaking something else..
Fixes #3843
=> Fix counting new mails in maildir

compmbox/compress.c, copy.c, core/mxapi.h, external.c, hdrline.c, imap/message.c, imap/private.h, index/functions.c, maildir/lib.h, maildir/maildir.c, maildir/mh.c, mbox/mbox.c, mx.c, mx.h, ncrypt/crypt.c, nntp/nntp.c, notmuch/notmuch.c, pager/message.c, pattern/exec.c, pop/pop.c, postpone/postpone.c, send/send.c, send/sendlib.c, test/pattern/dummy.c
This PR refactors numerous functions to replace `int msgno` with `struct Email *e`.
The result is that the backends no longer reference `Email->msgno`.
---
This was a happy discovery...
`Email->msgno` is a sequential number given to Emails as seen in the Index.
(see: [`%C` in `$index_format`](https://neomutt.org/guide/reference#index-format))
It's also used as an index number, into the `Mailbox->emails[]` array, for `MxOps->msg_open()`.
e.g. `pipe_message() -> mx_msg_open() -> maildir_msg_open()`
In every case, the caller passes `Email->msgno` through the MXAPI and the backend, then looks up that number in `Mailbox->emails[]`.
---
Of course, there's a diagram of the changes :-)
- Each left-hand leaf uses `Email->msgno`
- Each right-hand leaf uses `Mailbox->emails[msgno]`
=> Refactor MxOps->msg_open() to eliminate msgno

email/parse.c
The code to parse an RFC2822 header wasn't properly emptying its buffer on enter, but it was merely resetting the write pointer: https://github.com/neomutt/neomutt/blob/dde403334f7a5c0f2a746735076cddbccdbd605d/email/parse.c#L1091
For this reason, the code that was in place to detect and return in case of an empty line at the start of a header (i.e., the empty line dividing the headers from the body) wasn't triggered:
https://github.com/neomutt/neomutt/blob/dde403334f7a5c0f2a746735076cddbccdbd605d/email/parse.c#L1105-L1109
This was causing the code used to parse the headers to keep trying to parse the whole body:
https://github.com/neomutt/neomutt/blob/dde403334f7a5c0f2a746735076cddbccdbd605d/email/parse.c#L1193-L1197
Fixes #3860
=> Stop parsing headers at the end of the headers section

conn/tunnel.c
When $ssl_force_tls=yes imap bails out with "Encrypted connection unavailable" on reconnect when the tunnel process exits. We observed `conn->ssf==0` in this case.
This happens because the tunnel backend only sets `conn->ssf=1` once ever in mutt_tunnel_socket_setup, but mutt_socket_close sets `conn->ssf=0` on process exit.
Fix this by refreshing `conn->ssf` in mutt_socket_tunnel_open.
---
Note: as a workaround `$ssl_force_tls` can just be set to false.
=> Fix broken $tunnel reconnect with $ssl_force_tls=yes

index/index.c
Fixes: commit 968e302be1d2ac8d952b25bf4fced0d568e81e8e ("index: refresh the menu on window changes")
It appeared (though dprintf()ing the subtype) like `C+Trash<Enter>` yielded event 5 (focus), so just don't redraw for that one
Closes: #3781, see that one for bisexion
=> index: only refresh the menu on non-focus window changes

keymap.c
When we compare an incoming new binding against the existing ones, we do need to return to the caller how many characters mached, but we don't have to retain the count found during the previous comparison. Morally, we should just return two values here: the keymap, and the number of chars matched.
This code is scary - I might break stuff...
Fixes #3759
=> Fix keymap comparison

test/attach/mutt_actx_add_fp.c, test/charset/mutt_ch_fgetconv_open.c, test/file/mutt_file_copy_bytes.c, test/file/mutt_file_copy_stream.c, test/file/mutt_file_iter_line.c, test/file/mutt_file_map_lines.c, test/file/mutt_file_read_line.c, test/parse/mutt_parse_multipart.c, test/parse/mutt_parse_part.c, test/parse/mutt_rfc822_parse_message.c, test/parse/mutt_rfc822_read_line.c
Some C libraries don't expose the contents of `FILE`.
This means that the shortcut used in some tests doesn't work:
```c
FILE fp = { 0 };
```
Replace them all with real `FILE` pointers:
```c
FILE *fp = fopen("/dev/null", "r");
// ...
fclose(fp);
```
=> test: use a real FILE pointer

index/shared_data.c
Drop 150 lines of unused code.
`struct IndexSharedData` holds the data common to the Index, IBar, Pager, PBar and Sidebar.
It holds a pointer to the **current** Email, Mailbox and Account.
The code used to relay notifications from the current E/M/A so that observers would only have to observer the `IndexSharedData`.
It seemed like a good idea at the time, but it hasn't been used and it's getting in the way of my Index refactoring.
=> drop notification relays

external.c, imap/message.c, mx.c
The "(un-)tagging" of Emails is a GUI thing; it doesn't belong in the backends.
When `imap_copy_messages()` succeeds, it checks config `$delete_untag` and untags the Emails that it worked on.
This is called from `mutt_save_message()` and `mx_mbox_close()`.
Move this code out of Imap into the two callers.
=> imap: move $delete_untag out

core/mailbox.h, imap/imap.c, imap/message.c, maildir/shared.c, mbox/mbox.c, mx.c, mx.h, nntp/nntp.c, notmuch/notmuch.c, pop/pop.c
- Add a parameter for a required size
- Simplify all the callers
Tell the function how much space we need and avoid any looping.
**Note**: I haven't used `m->msg_count` in the function to allow the callers to increase the size of `m->emails[]` **before** they start populating it.
---
There are three types of caller for `mx_alloc_memory()`
```c
// Safe
while (m->msg_count > m->email_max)
mx_alloc_memory(m);
```
```c
// Risky if msg_count is bigger than the alloc step size
if (m->msg_count >= m->email_max)
mx_alloc_memory(m);
```
```c
// Very risky if the counting is off
if (m->msg_count == m->email_max)
mx_alloc_memory(m);
```
Replaced by:
```c
mx_alloc_memory(m, m->msg_count);
```
=> refactor mx_alloc_memory()

mutt/logging.c, mutt/logging2.h, mutt_logging.c
This means that NeoMutt can fully log the recently enlarged IMAP commands.
(see d35fc6a30 imap: increase max command length)
=> logging: increase max length of lines

send/send.c
The two branches of the `if (single)` worked the same way, so combine them.
=> simplify make_reference_headers()

attach/mutt_attach.c, docs/config.c, imap/config.c, imap/imap.c, imap/lib.h, imap/util.c, keymap.c, system.c
Rename `$imap_keepalive` to `$imap_keep_alive` for consistency with the other config.
=> imap: rename config imap_keepalive

address/address.c, hcache/serialize.c
The code base is still treating `a->personal` and `a->mailbox` as strings, i.e., a non-NULL value means a non-empty string.
Alternatively, we could change the callers to check for `buf_is_empty`, but we would probably still check if the pointers are valid, so at this point I guess I'd go the cheap way and *not* have a `personal` or `mailbox` member if it's empty.
=> Don't create empty buffers for Address mailbox/personal parts

browser/config.c, docs/config.c, docs/manual.xml.head, docs/neomuttrc.man.head, mutt_config.c
Upgrade `%?...?` conditional expandos to `%<...>`
They are easier to parse visually and can be nested.
(no code changes)
**default config changes**
```diff
-attach_format = "%u%D%I %t%4n %T%d %> [%.7m/%.10M, %.6e%?C?, %C?, %s] "
+attach_format = "%u%D%I %t%4n %T%d %> [%.7m/%.10M, %.6e%<C?, %C>, %s] "
-index_format = "%4C %Z %{%b %d} %-15.15L (%?l?%4l&%4c?) %s"
+index_format = "%4C %Z %{%b %d} %-15.15L (%<l?%4l&%4c>) %s"
-mailbox_folder_format = "%2C %?n?%6n&%6 ? %6m %i"
+mailbox_folder_format = "%2C %<n?%6n&      > %6m %i"
-status_format = "-%r-NeoMutt: %D [Msgs:%?M?%M/?%m%?n? New:%n?%?o? Old:%o?%?d? Del:%d?%?F? Flag:%F?%?t? Tag:%t?%?p? Post:%p?%?b? Inc:%b?%?l? %l?]---(%?T?%T/?%s/%S)-%>-(%P)---"
+status_format = "-%r-NeoMutt: %D [Msgs:%<M?%M/>%m%<n? New:%n>%<o? Old:%o>%<d? Del:%d>%<F? …
```
=> expandos: use `%<...>` conditionals

hcache/hcache.c, hcache/hcachever.sh, hcache/serialize.c, hcache/serialize.h
**tl;dr** -- Save **352 bytes** per record in the header cache.
Mutt's header cache stores an entire `struct Email` and `struct Body` into the backend Store for every Email.
While this is efficient, it wastes a lot of space.
Back in #1870 (the PR, not the year :-) I worked out how little we actually needed to save.
This PR implements the idea.
**Note**: `hcache/hcachever.sh` has been updated because I've changed the on-disk format of the cache, but the structs haven't changed.
---
Here are the `struct Email` members that we want to save:
https://github.com/neomutt/neomutt/blob/14d6d0607e4b9c6c901eeac9425bde872e7c4e37/email/email.h#L38-L60
To save space, I've packed the `security` and other flags into one `uint32_t` and the timezone info into another.
There are some helper functions to do …
=> shrink the header cache

mutt/logging.c, mutt/logging2.h, mutt_logging.c, mutt_logging.h
**Updated**:
- Refactor the log dispatcher to explicitly name the printf format parameter
- Add the _printf_ attribute to the log dispatcher
These functions can now be checked for mismatched parameters:
- `mutt_debug()`
- `mutt_error()`
- `mutt_message()`
- `mutt_perror()`
- `mutt_warning()`
e.g.
`error: format specifies type 'char *' but the argument has type 'struct Buffer *'`
=> test for, and fix, logging problems

core/mxapi.h, imap/imap.c, maildir/lib.h, maildir/maildir.c, maildir/mh.c, main.c, mbox/mbox.c, mx.c, mx.h
Convert MxOps path_is_empty() to take a Buffer. Based on the discussion here: https://github.com/neomutt/neomutt/discussions/3902.
=> convert MxOps path_is_empty() to take a Buffer

auto.def
Build with **`-g -O0`** if debug options are enabled, **`-O2`** otherwise.
Nearly a year ago, upstream Autosetup made [this change](https://github.com/msteveb/autosetup/commit/ef0915f8a56cc7bf0789abb2acf2a004c593e428), arguing that it wasn't their place to be setting `CFLAGS`.
```diff
-foreach i {LDFLAGS LIBS CPPFLAGS LINKFLAGS {CFLAGS "-g -O2"}} {
+foreach i {LDFLAGS LIBS CPPFLAGS LINKFLAGS CFLAGS} {
```
A few months later we adopted the change, 8b31f42532027d435cfcaf308046eabaecdfe7c0.
Since then, builds haven't included **`-O2`** by default.
This PR adds a local variable (`debug_build`) to `auto.def`.
If any of the debug configure options are given, then build with **`-g -O0`**, otherwise build with **`-O2`**
(`--debug-{backtrace,color,email,graphviz,notify,queue,window}`)
=> build: reinstate -O2 and -O0

compmbox/compress.c, core/mxapi.h, imap/imap.c, maildir/maildir.c, maildir/mh.c, mbox/mbox.c, mutt/path.c, mutt/path.h, mx.c, mx.h, nntp/nntp.c, notmuch/notmuch.c, pop/pop.c
Convert MxOps path_parent() to take a Buffer. Based on the discussion here: #3902.
=>  convert MxOps path_parent() to take a Buffer

config/cache.c, config/cache.h, docs/config.c, maildir/config.c, maildir/maildir.c, notmuch/notmuch.c, test/common.c, test/config/common.c
We allow overriding `:` as field delimiter for maildir using the option maildir_field_delimiter. This option should be changed only in tandem with changing existing maildir files to have that field delimiter.
=> Maildir: Configurable field delimiter

keymap.c
Some buffers used a constant incorrectly making them too short for long key bindings, e.g. `<space><space><space>`
```
unbind index <space>
macro  index <space><space><space> previous-entry
```
- `neomutt -n -F test.rc`
- `:macro index`
```
macro index <Space><Space><Space> "previous-entry"
```
```
macro index <Space> "previous-entry"
```
Note macro string is truncated to 8 chars: `<Space>`
=> fix truncated binding strings

enter/functions.c, functions.c
- 8dafdf7a5 editor: drop `<exit>` function
Added accidentally during a refactoring.
- 2b08fab83 editor: add `<redraw-screen>` function
Bound to <kbd>\<Ctrl-L\></kbd>
- 04d0ea54d editor: add `<help>` function
Bound to <kbd>\<Alt-?\></kbd>
To test the help:
- Start NeoMutt
- Type `:echo hello`
- Hit <kbd>\<Alt-?\></kbd>
- <kbd>q</kbd> to quit
=> editor: Small Improvements

test/path/mutt_path_tilde.c
Fix the test for `mutt_path_tilde()` where I assumed `root`s home would be in `/root`
=> test: fix path_tilde(root)

.github/workflows/macos.yml, test/enter/editor_backspace.c, test/enter/editor_backward_char.c, test/enter/editor_delete_char.c, test/enter/editor_forward_char.c, test/enter/editor_kill_eow.c, test/enter/editor_kill_word.c
These failing tests involve non-ascii characters and emojis.
@roccoblues
Yep, you're right.  The tests are wrong.
I found two problems in the code: combining characters and `iswalnum()`.
A simple case for combining characters is 0xFE0F (Variation Selector-16).
This turns, `0xE2 9C 89` ( `✉` ) into `0xE2 9C 89 EF B8 8F` (`✉️`)
In the wide buffer, the "emoji" envelope is stored as two characters.
If 0xFE0F isn't recognised as a combining character then some functions will not work correctly.
`iswalnum()` is used to determine where "words" start and end.
On Linux, `iswalnum()' on Chinese characters returns true, on macOS it returns false.
At some point we need to:
- Define the behaviour code wider character sets
- Devise lots of tests to verify the behaviour
- Create a clean system to …
=> test: disable faulty editor tests

color/color.h, color/command.c, color/simple.c, docs/neomuttrc.man.head, help.c, pager/display.c, pager/lib.h, pager/pager.c
This PR add alternating colors for the help menu.
New config variables: `$help_alternate`
New colors: `pager_even`, `pager_odd`.
To enable this feature add this to `.muttrc`:
```bash
set help_alternate = yes
color pager_odd  blue cyan
color pager_even black white
```
=> Alternating colors in help

functions.c
All of NeoMutt functions are divided into blocks, e.g. [`OpAlias`](https://github.com/neomutt/neomutt/blob/5bbc865600107986f20066c2e4169ad1866c117d/functions.c#L55-L64).
Each of these blocks is handled by a function dispatcher, e.g. [`alias_function_dispatcher()`](https://github.com/neomutt/neomutt/blob/5bbc865600107986f20066c2e4169ad1866c117d/alias/functions.c#L332-L357).
Function `<show-version>` is implemented by the [`global_function_dispatcher()`](https://github.com/neomutt/neomutt/blob/5bbc865600107986f20066c2e4169ad1866c117d/gui/global.c#L165-L185), so it belongs in [`OpGeneric`](https://github.com/neomutt/neomutt/blob/5bbc865600107986f20066c2e4169ad1866c117d/functions.c#L289-L345).
This PR moves the function out of [`OpIndex`](https://github.com/neomutt/neomutt/blob/5bbc86560010798 …
=> functions: move <show-version> to generic

conn/dlg_verifycert.c, functions.c, functions.h, history/dlg_history.c, history/functions.c, keymap.c, menu/type.c, menu/type.h, pattern/dlg_pattern.c, pattern/functions.c, test/pattern/dummy.c
Define OpDialog so that these dialogs can use km_dokey() rather than km_dokey_event().
- dlg_history()
- dlg_pattern()
- dlg_verifycert()
--- 
@lucilanga No action required on either PR; just thought you might like to read them.
=> separate dialogs from km_dokey_event()

alias/dlg_alias.c, alias/dlg_query.c, attach/dlg_attach.c, autocrypt/dlg_autocrypt.c, browser/dlg_browser.c, compose/attach.c, compose/cbar.c, compose/cbar_data.c, compose/dlg_compose.c, config/cache.c, envelope/window.c, gui/rootwin.c, gui/sbar.c, gui/simple.c, helpbar/helpbar.c, index/ibar.c, index/index.c, index/ipanel.c, main.c, menu/observer.c, mixmaster/dlg_mixmaster.c, ncrypt/dlg_gpgme.c, ncrypt/dlg_pgp.c, pager/do_pager.c, pager/pager.c, pager/pbar.c, pager/ppanel.c, pattern/dlg_pattern.c, postpone/dlg_postpone.c, sidebar/observer.c
Move the config and colour observers to reduce the load.
- Config: move observers from `NeoMutt` to `NeoMutt->sub` (`ConfigSubset`)
- Colour: move observers from `NeoMutt` to `ColorsNotify`
(wrapped by `mutt_color_observer_add()`, `_remove()`)
- Remove a couple of redundant observers from `cbar_data_free()`
---
Notifications are hierarchical and pass upwards to NeoMutt.
Observers attach themselves to `Notify` objects and observe, say `NT_CONFIG`.
All notifications pass through `NeoMutt`.
The notifications _are_ filtered, but any observers on `NeoMutt` will mean more filtering.
=> optimise config observers

mutt/mbyte.c, mutt/mbyte.h, test/mbyte/mutt_mb_width.c
`mutt_mb_width()` calculates the number of screen columns some text will occupy.
e.g. `a` takes up 1 cell, `한` takes 2.
Replace `mbtowc()` with the improved version `mbrtowc()`.
(one multibyte width function with another)
This was the last case in the code.
Add some tests for `mutt_mb_width()`.
---
The change is simpler that it looks.
`mbtowc()` takes a `struct mbstate` param that we reset if we detect an illegal sequence.
Other than that, I've just renamed all the cryptic one-letter variables.
=> mbyte: upgrade `mutt_mb_width()` to use `mbrtowc()`

mview.c
Fix a race condition that caused a `MailboxView` to not be freed.
**Steps**:
- Run NeoMutt with zero config
`./neomutt -n -F /dev/null`
- Exit NeoMutt
---
`op_quit()` calls `mview_free(shared->mailbox_view)`
`mview_free()` sends a notification that's observed by the `IndexSharedData` which then does `shared->mailbox_view = NULL;`
This clears the very pointer that `mview_free()` was about to `free()`.
Make a copy of the pointer and free _that_ after the notification.
=> fix mview leak

send/send.c, send/sendlib.c
When `$from` isn't set, NeoMutt tries to construct a `From:` address using, the user's _username_ and the machine's _hostname_.
Ensure that we have a `Buffer` to put them in.
When `$real_name` isn't set `Address.personal` should be `NULL`.
Ensure we don't allocate an empty `Buffer`.
**Steps**:
- Run NeoMutt with zero config:
`./neomutt -n -F /dev/null`
- Compose an email
**Expected Behaviour**:
- `From:` field contains `username@hostname.com`
**Actual Behaviour**:
- `From:` field contains `<;`
=> fix 'from' address when real name isn't set

init.c
`conn/lib.h` is required in `init.c` to define `getdnsdomainname()`.
Fix the build error reported by @jindraj: https://pastebin.com/EL7PXNCE. Broken in 1c3de6e65.
=> fix macOS build

index/functions.c, mutt_thread.c
Fix crash on `<next-thread>` when the `<limit>`ed view is empty.
Fixes: #3959 
- Fix Index Functions' `prereq()` check
- Make `mutt_aside_thread()` more robust
---
**Steps**:
- Start NeoMutt
- `<limit>qweasdfa<enter>` - no results
- `<next-thread>` or `<previous-thread>`
**Expected Result**:
- Error: "No visible messages"
**Actual Result**:
- Crash
=> bug: fix limited threads

alias/sort.c, browser/sort.c, commands.c, complete/helpers.c, config/subset.c, config/subset.h, core/command.c, imap/imap.c, imap/message.c, imap/msg_set.c, imap/msg_set.h, maildir/maildir.c, maildir/mh.c, mutt/array.h, mutt_thread.c, muttlib.c, ncrypt/dlg_gpgme.c, ncrypt/dlg_pgp.c, sidebar/sort.c, sort.c, sort.h, test/array/mutt_array_api.c, test/config/dump.c, test/imap/msg_set.c
* replace `qsort()` with `mutt_qsort_r()`, passing an additional data parameter where appropriate
* change `ARRAY_SORT` to accept a data parameter and switch it to `mutt_qsort_r()`
* change `sort_t` to a `qsort_r()` compatible definition
* add `@ingroup sort_api` doxygen label to compatible functions
Also see the discussion in https://github.com/neomutt/neomutt/discussions/3952.
=> replace qsort() with mutt_qsort_r()

imap/imap.c, maildir/maildir.c, maildir/mh.c
I ran this through Coverity and it didn't show any new defects. I also tried to follow the callers to see if we didn't initialize the envelope anywhere but that proved impossible.
Do we want to try this out?
=> remove unecessary e->env checks

alias/dlg_alias.c, gui/mutt_window.h, mutt/buffer.h, mutt/state.h, mutt/string2.h
This was probably missed during the auto-completion buffer transition (https://github.com/neomutt/neomutt/discussions/3899).
Fixes: https://github.com/neomutt/neomutt/security/code-scanning/589
=> fix wrong printf argument in alias_complete()

.cirrus.yml
This fixes our broken FreeBSD CI builds.
=> use FreeBSD 13.2 in Cirrus CI

enter/functions.c
Fix a typo that meant the auto-completion result wasn't being used.
Fixes: #3983
=> browser: fix completion

pager/display.c
Don't search empty/missing arrays.
Fixes: #3987
=> pager: fix search crash

browser/dlg_browser.c, browser/lib.h, commands.c, core/mailbox.c, core/mailbox.h, docs/manual.xml.head, docs/neomuttrc.man.head, imap/imap.c, mutt_mailbox.c, nntp/browse.c, sidebar/window.c
Add new options to the `mailboxes` command (to match upstream).
- `mailboxes -label LABEL FOLDER`
Add a mailbox with a descriptive label.
(Equivalent to `named-mailboxes LABEL FOLDER`)
- `mailboxes -nolabel FOLDER`
Remove a label from an existing mailbox.
- `mailboxes -notify FOLDER`
Notify the user that new mail has arrived (default behaviour).
- `mailboxes -nonotify FOLDER`
Do not notify the user of new mail.
- `mailboxes -poll FOLDER`
Check the mailbox for new mail (default behaviour).
- `mailboxes -nopoll FOLDER`
Do not check the mailbox for new mail.
These commands can be used at any time, e.g. to change the behaviour.
---
The first three commits are refactoring prep.
- d1f122f84 refactor loop
- 9243be67e browser: unify observers
- 7ec63bb82 browser: add mailbox observers
This allows …
=> `mailboxes`: add `-label`, `-notify` and `-poll` options

nntp/newsrc.c
`adata` is only initialized with NULL and never touched again until this check.
I suggest we remove it if we don't want need this code to make merging (upstream) nntp changes easier
=> remove dead code in nntp_select_server()

index/functions.c
It makes `index_function_dispatcher` check whether `win` has a parent, fixing a segfault.
A trivial change in structure made the code shorter despite doing more checks.
#3924
=> Add a check in `index_function_dispatcher`

gui/curs_lib.c
I was about to add mutt_resize_screen() when returning from mutt_shell_escape() and call it a day.
But looking at bug #1208, flatcap suggested comparing mutt and neomutt behavior. And to my own shock mutt was
working fine for issues described on #3980.
Debugging mutt I could reproduce the same behavior: SIGWINCH does not trigger when coming back from curses shutdown (eg. mutt_endwin()), but it was working there so I narrowed down to commit 619db54f5133cc788513737ca354f91ab54130fc in mutt tree.
Kevin writes the following:
"Since mutt_reflow_window() needs to be called on a resize, and it's
possible for programs to block SIGWINCH being sent to Mutt, this is a
fail-safe to ensure it's run."
I'm not entirely sure about programs blocking SIGWINCH signal, I've tried …
=> force SigWinch after endwin()

pager/display.c
The recent change (73d873e42) to add striped highlighting had an unfortunate side-effect.
It masked the search highlighting, which is kinda useful in the help :-)
Here's what the fixed help looks like, with a variety of config settings:
**Config**:
```
color stripe_even default default                      color stripe_even underline default default
color stripe_odd  magenta yellow                       color stripe_odd  underline default default
color stripe_even white color234                       color stripe_even underline default default
color stripe_odd  white black                          color stripe_odd            default default
color stripe_even default color234                     color stripe_even bold default default
color stripe_odd  default default …
```
=> help: fix search highlight

auto.def
Extend the pkgconf check for Lua in auto.def to not only look for lua and lua-5.x, but also for lua5.x as used by some distributions.
I've run into this issue on Gentoo when looking into adding Lua support to the Neomutt ebuild; while `./configure --enable-lua` works fine with older Neomutt releases (e.g. 20220415), it doesn't find the Lua installation when using newer Neomutt releases. Digging into this, it turned out that the root cause is that there are multiple naming conventions for the Lua pkgconf files, so that checking for multiple variants is required. While one could adapt the [Alpine Linux solution](https://git.alpinelinux.org/aports/commit/?id=93d811c319d6479dba4716800d8b809f0b458fe2) for Gentoo, it still seems sensible to also amend the check in …
=> build: more robust pkgconf check for lua

Makefile.autosetup, alias/dlg_alias.c, alias/dlg_query.c, alias/functions.c, alias/gui.h, globals.h, index/functions.c, index/shared_data.c, index/shared_data.h, pattern/lib.h, pattern/pattern.c, pattern/search_state.c, pattern/search_state.h, postpone/dlg_postpone.c, postpone/functions.c, postpone/functions.h
**Goals**
* get rid of `OptSearchReverse` from `globals.c`
* don't use op codes (`OP_SEARCH_BACKWARDS`, ...) in `mutt_search_command()` and `mutt_search_alias_command()`
* remove `SearchPattern`, `LastSearch` and `LastSearchExpn` globals from `pattern/pattern.c`
**Idea**
I split the required search data into two parts:
1. State that needs to be kept across operations. This is what the globals `OptSearchReverse` and `SearchPattern`, `LastSearch`, `LastSearchExpn` currrently hold.
2. "one-time" search flags:
a. `OP_SEARCH` and `OP_SEARCH_BACKWARDS` trigger the search functions to prompt the user for input.
b. `OP_SEARCH_OPPOSITE` tells the search function to search in the opposite direction of what is currently the global state. 
For the state data I've added a new struct `SearchState` that …
=> remove search globals

globals.c, globals.h, index/dlg_index.c, index/functions.c, pager/dlg_pager.c, pattern/pattern.c, test/pattern/dummy.c
Instead of setting `OptSearchInvalid = true` when an action (switch mailbox, new mail, sort, ...) "invalidates" the current search, we free the current search pattern. This triggers a recompile in the search methods.
This means the search methods behavior changes a bit: before we only "forgot" which mails we already searched and if they matched. Now we recompile the search pattern on invalidation.
I actually like this change because it makes the search methods `mutt_search_command()` and `mutt_search_alias_command()` a bit clearer. But if we decide that this is too expensive we could simply move the `invalid` bool to the `SearchState` and keep the current logic.
=> remove OptSearchInvalid global

send/header.c, send/sendlib.c
Port of two string-handling fixes from Mutt [issue 456](https://gitlab.com/muttmua/mutt/-/issues/456). In Mutt, these are reachable for external input due to an invalid `continue` statement in `rfc2047_decode_word`. Neomutt's corresponding `rfc2047.c:decode_word` calls out to `mutt_b64_decode` instead of using an ad-hoc base64 decoder, and does not appear vulnerable; I could not reproduce ASAN crashes with the PoC included in the issue. 
Hence AFAICT the fixed issues do not appear to be a security issue in Neomutt.
See Mutt commit messages (linked to in the commits) for detailed descriptions of the changes.
Mutt [issue 456](https://gitlab.com/muttmua/mutt/-/issues/456). No Neomutt issue.
=> Header parsing fixes from Mutt

email/rfc2047.c
When `decode_word` handles quoted-printable encoded text, it will look past the current point when it encounters a `=` to check whether it looks like a hex-encoded character. If passed a malformed QP string with a `=` at the end, this may read past the end of the buffer as given by `len`.
In practice this shouldn't make a difference, because AFAICT the buffer passed from `rfc2047_decode` will have `?=` at the end. But to avoid surprises, do a bounds check anyway.
No issue opened.
=> email/rfc2047: avoid reading past `len` in QP decode.

alias/complete.c, browser/complete.c, complete/helpers.c, notmuch/complete.c, pattern/complete.c
Only the Alias completion needs to distinguish between `<complete-query>` and `<complete>`.
In other places, treat `<complete-query>` as `<complete>`.
This restores the behaviour that we had before the completion refactor.
Fixes: #4032
=> complete: relax complete/query checks

alias/dlg_query.c, attach/mutt_attach.c, attach/recvattach.c, conn/accountcmd.c, conn/connaccount.c, external.c, handler.c, mixmaster/remailer.c, mutt/filter.c, mutt/filter.h, muttlib.c, ncrypt/pgpinvoke.c, ncrypt/smime.c, pager/message.c, parse/extract.c, pattern/compile.c, send/sendlib.c, test/filter/filter_create.c, test/filter/filter_create_fd.c
Change `filter_create_fd()` and `filter_create()` to accept the environment variables as parameter. This removes `globals.h` from `mutt/filter.c`. 
Discussion: https://github.com/neomutt/neomutt/discussions/3993
=> remove global EnvList from mutt/filter.c

attach/recvattach.c, conn/dlg_verifycert.c, enter/wdata.h, enter/window.c, external.c, flags.c, gui/curs_lib.c, gui/msgcont.c, gui/msgcont.h, gui/msgwin.c, gui/msgwin.h, gui/msgwin_wdata.c, gui/msgwin_wdata.h, gui/mutt_window.c, gui/mutt_window.h, gui/rootwin.c, index/dlg_index.c, index/functions.c, keymap.c, main.c, menu/observer.c, menu/tagging.c, mutt_logging.c, mutt_mailbox.c, muttlib.c, pager/dlg_pager.c, question/question.c, recvcmd.c
The Message Window is a one-line area at the bottom of the screen.
It's used by a large number of places in the code for messages and text entry.
Historically, each of these places was responsible for their own painting and resizing.
NeoMutt's first step to improvement was to create a dedicated Message Window.
The text and colour could be set, typically by `mutt_message()`, and friends.
The Window had a `repaint()` function which allowed it to redraw itself.
Other users, e.g. `mw_get_field()` or `mw_yesorno()` were still responsible for painting themselves.
Some magic was used to temporarily disable the Message Window's `repaint()` function.
The next step was to add a Message Container.
This Window was a wrapper around a **stack** of Windows.
As a new Window was added, the others would be …
=> Refactor the Message Window Usage

attach/functions.c, attach/recvattach.c, compose/functions.c, external.c, imap/imap.c, imap/message.c, index/functions.c, mutt/string.c, mutt/string2.h, muttlib.c, mx.c, ncrypt/crypt.c, ncrypt/crypt_gpgme.c, ncrypt/pgp.c, nntp/nntp.c, pager/message.c, pop/lib.c, pop/pop.c, question/lib.h, question/question.c, recvcmd.c, send/send.c, send/smtp.c, test/Makefile.autosetup, test/main.c, test/string/mutt_str_hyphenate.c
This PR adds an upstream feature and extends it.
Many of the questions in NeoMutt are associated with config variables.
(All quad-options and many bools)
When the user is presented with a 
**Before**:
```
Append messages to work? ([yes]/no): 
```
**After**:  (note the '/?' )
```
Append messages to work? ([yes]/no/?): 
```
**Press <kbd>?</kbd>** to get:
```
$confirm_append - Confirm before appending emails to a mailbox
Append messages to work? ([yes]/no): 
```
**Additionally**, if `$help` is set (as beginners might):
```
$confirm_append - Confirm before appending emails to a mailbox
https://neomutt.org/guide/reference#confirm-append
Append messages to work? ([yes]/no): 
```
---
- dd32bddae query help y/n/?
Add help to quad option and some y/n questions
- b4fd3a4a9 query help web link …
=> Add Help to Quad/Yes/No Questions

enter/wdata.h, enter/window.c, flags.c, gui/curs_lib.c, gui/msgwin.c, gui/msgwin_wdata.h, gui/mutt_window.c, gui/mutt_window.h, keymap.c, question/question.c
Painting the screen inevitably means moving the cursor.
After the painting is done, an interactive Window, e.g. `mw_multi_choice()` needs an opportunity to restore the cursor position.
This can be achieved by implementing `Window.recursor()`.
---
- 529c04bc2 window: add recursor()
After all the repainting is done, the focussed window will be given an
opportunity to set the position and visibility of the cursor.
- adb3c45f9 msgwin: implement recursor()
- Drop WT_MSG_FOCUS Window type
- Drop MsgWinWindowData.interactive
- Move cursor setting to msgwin_recursor()
- ef419f630 upgrade simple MessageWindow users
Let the MessageWindow do the cursor setting.
- 0bc3cce1b mw_get_field: implement recursor()
- Drop EnterWindowData.col
A local variable in enter_repaint() was sufficient
- Add …
=> refactor cursor positioning

alias/dlg_alias.c, alias/dlg_query.c, attach/dlg_attach.c, autocrypt/dlg_autocrypt.c, browser/dlg_browser.c, compose/dlg_compose.c, conn/dlg_verifycert.c, gui/dialog.c, gui/dialog.h, gui/mutt_window.c, gui/simple.c, history/dlg_history.c, index/dlg_index.c, index/ipanel.c, menu/menu.c, mixmaster/dlg_mixmaster.c, ncrypt/dlg_gpgme.c, ncrypt/dlg_pgp.c, ncrypt/dlg_smime.c, pager/dlg_pager.c, pattern/dlg_pattern.c, postpone/dlg_postpone.c
Explicitly set and restore the Window focus.
Before, this used to happen in helper functions.
=> explicitly set the focus

attach/dlg_attach.c, attach/functions.c, attach/private_data.h, attach/recvattach.h, compose/functions.c, globals.c, globals.h, index/dlg_index.c, index/functions.c, index/private_data.h, index/shared_data.h, mutt_config.c, pager/dlg_pager.c, pager/functions.c, status.c
* move `attach_msg` flag from `IndexPrivateData` to `IndexSharedData`
* add `attach_msg` flag to `AttachPrivateData`
* replace uses of `OptAttachMsg` with this flags
* remove `reply_validator()` and drop global `OptAttachMsg`
Triggered by this discussion: https://github.com/neomutt/neomutt/discussions/3996
=> eliminate global OptAttachMsg

mview.c
When freeing the MailboxView, reset the Emails' Thread pointer before freeing the ThreadsContext.
Fixes: #4041
=> disconnect emails from threads

init.c
On startup we try to detect the terminals capability for direct color and set value of $color_directcolor accordingly.  However, we forgot to set its initial/default value.
Set the initial/default value for $color_directcolor like we do for all other config variables which depend on the environment, e.g. $editor.
Config file `neomuttrc-reset`:
```
reset all
```
```
EDITOR=foo TERM=xterm-direct neomutt -F /dev/null
:set color_directcolor?  # ==> "yes"
:set editor? # ==> "foo"
EDITOR=foo TERM=xterm-direct neomutt -F neomuttrc-reset
:set color_directcolor?  # ==> "no"
:set editor? # ==> "foo"
```
```
EDITOR=foo TERM=xterm-direct neomutt -F /dev/null
:set color_directcolor?  # ==> "yes"
:set editor? # ==> "foo"
EDITOR=foo TERM=xterm-direct neomutt -F neomuttrc-reset
:set color_directcolor?  # …
```
=> color_directcolor: Also set the default/initial value on startup

gui/msgwin.c
Return early from `msgwin_set_text()` if the text hasn't changed.
Fixes: #4055 
`msgwin_set_text()` is called to set or clear a message.
Displaying a long message would require the `MsgWin` to resize itself.
Later, calling `msgwin_set_text(NULL)` to clear the message would cause the `MsgWin` to shrink back to 1 line.
However, if the `MsgWin` wasn't visible, e.g. a progress bar was in use, then it would get into an infinite loop trying to resize itself.
Fix: If the text isn't changing, then don't try to resize yourself.
=> msgwin: check for dupe text

gui/global.c, mx.c, mx.h
Workaround to fix #4048. By backdating the last mailbox check time we restore the previous behavior.
A cleaner way would be to rethink the whole mail (stats) check, notification and `new_mail_command` situation. I'll open a discussion with some thoughts later. But I don't think we want to include another big change like that in the next release.
=> force mail check on current mailbox after <shell-escape> (fixes #4048)

gui/rootwin.c
I couldn't repeat the crash, but I _think_ I can see how it _might_ be happening.
On exit, `main()` calls `rootwin_cleanup()` to free the `MuttWindow`s.
There are a couple of helper globals that don't get cleared by this:
- `AllDialogsWindow`
- `MessageContainer`
If some code were to try to clear the `MessageWindow` after `rootwin_cleanup()`, it would use a dangling pointer.
Probably fixes: #4059
=> fix crash on exit

pager/display.c
`color header` should extend to the end of the line.
(`color quoted` too)
Remove a spurious `mutt_curses_set_color_by_id()` that was resetting the colour to normal.
---
This bug was introduced as I refactored the stripes code.
The PR fixes the problem and everything seems ok, stripes included.
=> fix header colour

mutt/date.c
A misplaced `(` meant that `tv.tv_sec` would overflow before being converted to a sufficiently long type.
=> fix 32-bit date overflow

index/dlg_index.c
If new mail arrives that doesn't match the current limit, the Menu loses its selection leading to errors:  "no visible messages".
Fixes: #4072
---
When new mail arrives, `Mailbox->emails[]` is updated and the view (`Mailbox->v2r`) must be recalculated.
During this process, `Mailbox->vcount` gets set to `0`, which leads to `Menu->max` being set to `0`.
Unfortunately, `Menu->max` wasn't being reset afterwards, so the Menu thought it was empty.
The fix resets `Menu->max` as soon as possible after the updates, in time for the selection to be restored.
=> fix new mail in limited view

index/dlg_index.c, index/private_data.c, index/private_data.h
This seems to be unused. Setting `oldcount` is wrong because that is the count of mails in the mailbox and never the count of mailboxes with new mail.
=> remove unused count of new mails from index private data

commands.c, init.c, init.h, main.c
- 1c69ae782 fix logging on error
Some debugging messages were lost if there was an error in the config file
- 9c8613ba6 boolify: need_pause
- 49967ec49 log: vim-style
Change the form of the error message to: `file:line_num: message`
=> logging: minor fixes / improvements

alias/alias.c, attach/recvattach.c, browser/complete.c, compose/functions.c, muttlib.c
- Fix file auto-completion
The selected file was being lost
- Use `CompleteFileOps` where possible rather than `CompleteMailboxOps`
e.g. Save file
=> fix file auto-completion

send/smtp.c
There's only 1 call to this function, so we can simplify by passing the entire buffer, instead of extracting the string before the call.
$ grep -rn '\<smtp_code\>' *
send/smtp.c:440: * smtp_code - Extract an SMTP return code from a string send/smtp.c:445:static int smtp_code(const struct Buffer *buf, int *n)
send/smtp.c:484:    if (!smtp_code(input_buf, smtp_rc))
for that)
N/A
I can't build from source successfully without the patch, so didn't try with the …
=> Simplify the API of smtp_code()

color/ansi.c, color/ansi.h, color/attr.c, color/attr.h, color/color.c, color/command.c, color/command2.h, color/curses.c, color/merged.c, color/parse_ansi.c, color/parse_color.c, color/parse_color.h, color/quoted.c, color/quoted.h, color/regex.c, color/regex4.h, color/simple.c, color/simple2.h, pager/display.c
This is a **Work-In-Progress**.
It works, but I still need to make sure it's robust and degrades correctly if true-colour isn't enabled.
Refactor the colour parsing.
- d75aacfd3 color: introduce ColorElement
Keep track of the _type_ of colour being used, e.g. palette
- 8c627cd7c color: change parse_color() to use an AttrColor
Use a temporary object to track the fg, bg, attrs
- 30fd6d697 color: move business logic out of parsers
Simplify the parsers to just check the **syntax**.
`parse_color()` will check whether the colours are allowed.
Source: [graphviz](https://flatcap.org/mutt/colour/parse_color4.gv)
=> color: refactor parsing

mx.c
Improves performance when increasing memory space required for mailbox.
Note that this PR is made on top of #4089. By no means this PR should be merged before #4087 is fixed as increasing `grow` to `1000` would absolutely blow memory requirements.
Related to #4087.
=> Mx alloc overhead reduction

config/bool.c, config/enum.c, config/long.c, config/mbtable.c, config/mbtable.h, config/number.c, config/path.c, config/quad.c, config/regex.c, config/regex2.h, config/set.h, config/slist.c, config/sort.c, config/string.c, config/types.h, maildir/config.c, mutt_config.c, ncrypt/config.c, test/config/bool.c, test/config/enum.c, test/config/long.c, test/config/mbtable.c, test/config/number.c, test/config/path.c, test/config/quad.c, test/config/regex.c, test/config/slist.c, test/config/sort.c, test/config/string.c
Some config variables may only be set at startup.
This can be either in a system/user config file or using the `-e` command line. 
- 95ff7c418 config: add more sameness checks
- 466a3fac0 config: create a new flag, `DT_ON_STARTUP`
- 6f95fdb79 config: add tests for DT_ON_STARTUP
- 4b66a50ba config: apply DT_ON_STARTUP
- `$abort_key`
- `$color_directcolor`
- `$crypt_use_gpgme`
- `$maildir_field_delimiter`
=> config: add DT_ON_STARTUP

hcache/hcache.c, maildir/maildir.c
Fix a couple of bugs in the header cache key handling.
- maildir: factor out key location
- realkey(): honour key length
Given an Email with path, **`cur/1462463620.M306996P28816.flatcap.org,S=4057,W=4147:2,RS`**
Maildir was adding 3 to the start, which meant that the **`/`** was included.
This has been changed to 4, so that the **filename** is the base of the key.
In the Header Cache, `realkey()` performs a transform on the key depending on whether compression is enabled.
Unfortunately, both branches were producing the wrong output.
When compression was enabled, the entire filename was used -- this includes the flags: **`:2,RS`**
When compression wasn't enabled, the `memcpy()` assumed the string was `NUL`-terminated at keylen.
This lead to a stray **`:`**  being included.
The fixes mean …
=> hcache: fix key handling

version.c
Declutter the output of `neomutt -v`, by removing the block of 'default' options: 
> Default options:
>   +attach_headers_color +compose_to_sender +compress +cond_date +debug 
>   +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
>   +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
>   +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
>   +skip_quoted +smtp +status_color +timeout +tls_sni +trash 
This block hasn't changed in four years and isn't likely to in the future.
=> version: drop default features

main.c
The HelpBar has a colour observer, so it needs to be created after the colours are initialised.
**Test**, in NeoMutt:
- Enable the Help Bar, `set help = yes`
- Create a hook: `folder-hook . 'color status black yellow'`
- Change folder using `<sidebar-open>`
Both the Status Bar (Index) and the Help Bar should change colour.
=> create HelpBar after colours

hcache/hcache.c, imap/mdata.c, imap/message.c, imap/util.c, maildir/maildir.c
This PR is mostly refactoring, but also fixes a few bugs.
(It's also shown me that the Notmuch backend is a disaster area, w.r.t. the Header Cache)
MH/Pop/NNTP didn't put a leading `/` on their Header Cache Key.
This was inconsistent the the other backends.
Code called `hcache_delete_record()` for both Emails and raw data.
When compression was enabled, the wrong key would be generated.
---
The Header Cache Key is generated from several pieces of data:
- Mailbox path
- Unique Email ID
- Compression suffix
The refactoring centralises the key assembly, saving effort in the callers.
- 39469ac72 separate `store_email()` from `store_raw()`
Call the underlying `Store` function directly from `store_email()`.
- c18b3e72c `realkey()` separate out compression
Make the compression suffix, e.g. …
=> Fix Header Cache Key Handling

config/charset.h, config/sort2.h, config/types.h, mutt/regex3.h, mutt/slist.h
Adding the `DT_ON_STARTUP` config flag, in 9a904e578, exposed a bug.
Some of the config flags overlapped causing a bug in the browser.
Trying to set the file mask in the browser <kbd>m</kbd> (`<enter-mask>`)
fails with the message: "Option mask may only be set at startup".
---
Each config variable has a type, e.g. `DT_STRING`.
Additionally, they have flags `OR`d with the type, e.g. `DT_NOT_EMPTY`.
`$mask` has the flag `DT_REGEX_MATCH_CASE` which had the same value as `DT_ON_STARTUP`.
This caused the bug.
Of the 471 config variables, just 8 have flags from multiple sets of flags:
```c
{ "charset",            DT_NOT_EMPTY|DT_CHARSET_SINGLE },
{ "group_index_format", DT_NOT_EMPTY|R_INDEX },
{ "index_format",       DT_NOT_EMPTY|R_INDEX },
{ "mbox",               DT_MAILBOX|R_INDEX },
{ …
```
=> config: fix flag overlaps

alias/alias.c, alias/alias.h, alias/commands.c, alias/dlg_alias.c, alias/dlg_query.c, alias/lib.h, mutt/prex.c, mutt/prex.h, pattern/exec.c, test/pattern/dummy.c
A bit of time doing something easy :-)
Parse a magic "tags:" field in the comment of an 'alias' or 'query' command. e.g.
```
alias jd John Doe <jd@example.com> # comment tags:work,football
```
This adds a new expando `%Y` to `$alias_format` and `$query_format` and a pattern `~Y` for searching / limiting.
Using config from the [sample-data repo](https://github.com/neomutt/sample-data/blob/main/actor-alias-tags.rc):
[actor-alias-tags.rc](https://github.com/neomutt/sample-data/blob/main/actor-alias-tags.rc)
[actor-query-tags.txt](https://github.com/neomutt/sample-data/blob/main/actor-query-tags.txt)
and
```
set alias_format="%3n %f%t %-15a %-56r │ %c%>  %-25Y"
set query_format="%3c %t %-25.25n %-25.25a │ %e%>  %-25Y"
```
Resulting in something like:
```
12    amanda          Amanda Bynes …
```
=> alias: add tags

main.c, send/send.c, send/send.h
Allow `echo ... | neomutt -H -`, as it worked before, and as mutt(1) works.
N/A
for that)
[ Hopefully this is just a bugfix and don't need to]
Manual tests seem to work, better than before.
N/A
Hopefully.
* **What are the …
=> Fix Batch Sending of Emails

mutt_mailbox.c
Remove the arbitrary exclusion of notmuch mailboxes. This appears as holdover behavior from before the 4e5d94bc2a281d3f171d2b6c61f89cbbf9b7b394 unification of mailboxes.
Fixes #1982
Original commit by @Austin-Ray
=> fix(change-folder): don't exclude notmuch

mbox/mbox.c, mutt/date.c, mutt/date.h, mutt_mailbox.c
Abstracts away the `#ifdef` and also uses nanosecond precision for the mbox `stats_last_checked` field if available.
Nanosecond precision was introduced in commit 42b436392846f06ebbc01dba7642361f163a8aad to fix high resolution issues with the inotify interface.
=> add mutt_time_now()

browser/config.c, config/types.h, imap/config.c, index/index.c, mutt_config.c, send/config.c, test/parse/parse_rc.c
I should have done this long ago...
---
Kill the R_ flags that tell the Index what to do.
- R_INDEX
- R_RESORT
- R_RESORT_INIT
- R_RESORT_SUB
Instead, check for specific config options.
---
#4124 (config: fix flag overlaps) fixed one problem, but introduced another.
`$reply_regex` was left with conflicting config flags.
=> config: factor out R_ flags

email/envelope.c, email/envelope.h, email/parse.c, email/rfc2047.c, envelope/functions.c, hcache/serialize.c, index/index.c, main.c, ncrypt/crypt.c, pager/message.c, postpone/postpone.c, send/send.c
As it stands, subject is assigned at will throughout every interested piece of code, and real_subj is parsed with $reply_regex and set in three unaffiliated places.
This means that, for example, IMAP mailboxes simply do not have $reply_regex processing. Unless you change it, then they refresh to have it. Until you reopen and then it's lost.
Mark both fields as const and introduce a mutt_env_set_subject() setter that sets subject and parses real_subj. This interior mutability is bypassed only in hcache serialisation, by necessity. rfc2047 (un)parsing needs to abuse it slightly to match the calling convention.
This ensures that real_subj always matches subject, and so $reply_regex works as documented instead of not at all.
Fixes: https://mailman.neomutt.org/pipermail/neomutt-devel-neomutt.or …
=> envelope: manage subject/real_subj together

init.c
The environment variable REPLYTO should be parsed into a user header of "Reply-To:"
---
Some past refactoring broke this.
The fix is to reset the `Buffer` pointer so that `parse_extract_token()` reads from the beginning of the string.
---
To test:
```sh
REPLYTO=john.doe@example.com neomutt
```
then compose an email.
In Compose, you'll see: `Reply-To: john.doe@example.com`
=> fix parsing of $REPLYTO

index/functions.c
Fixes: #4157 - Manual sync "$" should be reflected immediately in status bar
At the end of `<sync-mailbox>` send out a notification of change.
This triggers the Index Bar (status) to refresh itself.
**To Test**:
- Open an Imap Mailbox
- Toggle the New status of an Email
(the Index Bar should show `-*-`)
- Press <kbd>$</kbd> to `<sync-mailbox>`
(the Index Bar should show `---` again)
---
The purists among you will realise that the notification should be coming from the IMAP backend.
If someone has the time to refactor `imap_sync_mailbox()` it'd be very welcome.
=> status: fix refresh after sync-mailbox

Makefile.autosetup, maildir/account.c, maildir/hcache.c, maildir/hcache.h, maildir/lib.h, maildir/mailbox.c, maildir/mailbox.h, maildir/message.c, maildir/path.c, maildir/shared.c, maildir/shared.h
Encapsulate all of Maildir's Header Cache code.
No _functional_ changes.
Wrapping the header cache calls simplifies the maildir code and reduces dependencies.
---
Currently, the header cache calls are deeply embedded in maildir.
The next step (part of #4112) is to move the header cache calls into the top-level MXAPI functions.
This would create a clearer separation between the two.
A possible future direction might be to turn the header cache into a layer **above** the backends.
=> maildir: encapsulate the header cache

index/dlg_index.c, notmuch/db.c
This addresses issue #4033 as well as another leak when opening a notmuch database.
It fixes two memory leaks that have to do with notmuch support.
The first has to do with `change_folder_mailbox` returning a nonnull pointer to a mailbox on which the call to `change_folder_mailbox` failed. Since `change_folder_mailbox` doesn’t return any error code, the checking is done by checking whether it stored a mailbox view into the index shared data.
The second has to do with the case of `config_file` being a null pointer instead of an empty string in `nm_db_do_open`. This lead to `msg` not being freed.
With this patch, Valgrind no longer reports any definitely lost block in @scottkosty’s example.
#4033
=> Fix two memory leaks in notmuch support

attach/cid.c, complete/lib.h, mutt/buffer.c, mutt/buffer.h, mutt/string.c, mutt/string2.h, notmuch/complete.c, test/Makefile.autosetup, test/buffer/buf_rfind.c, test/main.c
Bufferize `mutt_strn_rfind()`. The callers already have a `struct Buffer`.
I've also simplified and fixed the Notmuch code. `mutt_nm_query_complete()` is only called from one place and the "position" parameter was always set to the buffer length. I've removed it. Also it used to pass the Buffer pointer instead of `buf->data` for the string to search into `mutt_strn_rfind()`.
=> bufferize mutt_strn_rfind() as buf_rfind()

core/mailbox.h, editmsg.c, gui/global.c, imap/imap.c, mx.c, mx.h
Instead of using one variable `MailboxTime` to keep track of when we last checked any mailbox for mail, store that information on the `Mailbox` itself.
I didn't notice any immediate issue related to this but I still think something like this could happen:
1. regular mail check on all mailboxes -> set `MailboxTime`
2. `mx_mbox_check()` on current mailbox -> set `MailboxTime`
3. regular mail check not run because not enough time elapsed since last run (on a single mailbox only)
=> track new-mail check time per mailbox

docs/mbox.5, docs/mmdf.5, docs/neomutt.man, docs/pgpewrap.1, docs/smime_keys.1
Before these patches, the Linux man-pages build system reported many problems in the pages:
```sh
$ make -C ~/src/linux/man-pages/man-pages/master/ -k build lint check MANDIR=~/src/mutt/neomutt/main/ builddir=old
make: Entering directory '/home/alx/src/linux/man-pages/man-pages/master'
MKDIR	old/man/
Build	old/man/man-pages.pdf
for my (...) is experimental at ./scripts/LinuxManBook/prepare.pl line 62.
grep: /home/alx/src/mutt/neomutt/main//man*/*: No such file or directory
MKDIR	old/man/docs/
PRECONV	old/man/docs/pgpewrap.1.tbl
TBL	old/man/docs/pgpewrap.1.eqn
EQN	old/man/docs/pgpewrap.1.cat.troff
TROFF	old/man/docs/pgpewrap.1.cat.set
an.tmac:/home/alx/src/mutt/neomutt/main//docs/pgpewrap.1:23: style: blank line in input
an.tmac:/home/alx/src/mutt/neomutt/main//docs/pgpewrap.1:27: style: …
```
=> Several fixes for the manual pages

mx.c
* The PR fixes a memory leak involving `mx_path_resolve`. It addresses some leaks in `trash_append` where `m_trash` is allocated by `mx_path_resolve` but not freed on a given path when appending to trash fails when syncing or closing a mailbox.
In fact there is a similar error path above where `m_trash` is freed and returns -1. Additionally I was able to verify that all tests succeeded with the patch
=> Fix memory leak in mx.c

hdrline.c
When the mailbox path is fetched with `nm_email_get_folder_rel_db`, the first character should not be removed, but was. This bug would lead to the first character of %b being chopped off in notmuch folders. This PR fixes that.
=> Fix off-by-one error in %b with notmuch

core/mailbox.c
I've just been hit by a crash when triggering the machinery (sourcing config files) to connect to an IMAP account after the connection dropped. As part of the machinery, there's an `alternates` command being triggered. This ends up with the following stack trace:
```
(gdb) bt
#0  0x00000000002602b6 in mutt_alternates_reset (mv=0x6e1ca84c7d0) at alternates.c:80
#1  0x00000000002a8f13 in index_altern_observer (nc=0x8209c3238) at index/index.c:231
#2  0x00000000003c7883 in send (source=0x6e1ca8c69e0, current=0x6e1ca83b180, event_type=NT_ALTERN, event_subtype=1, event_data=0x0) at mutt/notify.c:132
#3  0x00000000003c7935 in send (source=0x6e1ca8c69e0, current=0x6e1ca8c69e0, event_type=NT_ALTERN, event_subtype=1, event_data=0x0) at mutt/notify.c:140
#4  0x00000000003c775d in notify_send …
```
=> Zero-out mailbox counters on delete

contrib/oauth2/README.md
Fixes oauth2 example. The script returns an error if the command is copy-pasted as is.
=> Fix oauth2 example on README.md

gui/msgwin.c, pager/display.c, question/question.c
When displaying the help page, remember to honour the `normal` colour.
Fixes: #4203
Steps to reproduce:
```sh
neomutt -F /dev/null -e 'color normal white blue' -e 'push ?'
```
=> help: honour normal colour

main.c
The folder hook run on startup only matched against the path. We can try to find a Mailbox with that path and also match against the name. Like we do when switching mailboxes.
=> match folder-hook also against mailbox name (fixes #4201)

test/expando/node_conddate.c
The same setting is already done in `test_init()`.
I also tried to remove the variable with `unsetenv("TZ")` but that didn't work. That might be because some code already called `tzset()` before the test code unsets the variable.
Or, quoting from tzset(3):
> If TZ does not appear in the environment, the best available
> approximation to local wall clock time, as specified by the
> tzfile(5)-format file #ifdef UNIFDEF_MOVE_LOCALTIME
> /var/db/timezone/localtime, #else /* !UNIFDEF_MOVE_LOCALTIME */
> /etc/localtime, #endif /* UNIFDEF_MOVE_LOCALTIME */ is used.
=> test: remove unnecessary setting of TZ var

mbox/mbox.c, sort.c, sort.h
Syncing an mbox requires the Mailbox to be in disk order.
This PR forcibly sorts them to fix `mbox_mbox_resync()`.
Fixes: #4210 
---
The Emails are shared by the GUI and the Backend (Mailbox proper).
Most of the time, the Emails are in the user's preferred order, e.g. "Thread"
When the Backends work on the Emails, they often want the array in a different order.
Typically, the behaviour is like this:
- User: sync mailbox
- Backend:
- Sort Emails into **disk** order
- Sync changes to disk
- Sort Emails back into **user** order
Recent changes have started so separate the GUI parts from `struct Mailbox` (into `struct MailboxView`).
This means that the Backends can no longer restore the user's sort order.
Instead, they send a notification:
```c
mailbox_changed(m, NT_MAILBOX_RESORT);
```
This …
=> mbox: fix sorting for mbox_resync()

expando/config_type.c, expando/expando.c, expando/helpers.c, expando/node_condition.c, test/config/string.c, test/expando/config.c, test/expando/helpers.c
Many expandos can be used as the test condition, e.g. `%<A?&%C>`
Here, `%A` should be tested but its value shouldn't be displayed.
Fixes: #4209
=> expando: don't render the condition node

docs/manual.xml.head, envelope/window.c
It includes two contributions.
The first commit addresses issue #4216 by not drawing the Mixmaster line when it’s empty.
The test for an empty chain inside `draw_mix_line()` now being dead code, I removed it and instead made it a precondition. That precondition is included in the Doxygen comment.
Along with a few punctuation fixes and adjustments, I split the POP3 section into two to emphasize the two different ways of using it. Each of the two methods now has a sample config file.
* #4216
=> Hide empty Mixmaster line and clarify POP3 usage

expando/expando.c, menu/menu.c
Searching Attachments falls back to the default Menu search.
Menu search runs `make_entry()` on each row, giving it plenty of space.
Unfortunately, INT_MAX amount of space combined with padding led to some enormous strings.
Limit the space to 8KiB.
Fixes: #4231
=> expando: fix attach search

address/address.c, test/Makefile.autosetup, test/address/mutt_addrlist_write_wrap.c, test/main.c
Simpler version of https://github.com/neomutt/neomutt/pull/4239 without the refactoring.
=> only wrap after first address in header lines (fixes #4206)

commands.c, commands.h, imap/command.c
Shortcut IMAP's workflow when adding a Mailbox.
When `$imap_check_subscribed` is set, NeoMutt sends an `LSUB` command to the server.
The server responds with a list of "subscribed" Mailboxes.
The IMAP code used to create a fake `mailboxes NAME` command.
Now it skips that step and calls `mailbox_add()` (via a wrapper).
This removes the need to quote the Mailbox name, only for `parse_rc_line()` to dequote it.
---
- 35dd92fca create `mailbox_add_simple()` wrapper
- de6354027 imap: add mailboxes more directly
=> imap: add mailboxes more directly

ncrypt/crypt.c
Quoting RFC1521:
> Each part starts with an encapsulation boundary, and then contains a
> body part consisting of header area, a blank line, and a body area.
If the user has enabled $crypt_protected_headers_read, they want to see
the entire body part, which consists of a header area, a blank, and a
body area (well, from the headers they only want the important fields, ignoring the MIME metadata).  If there are no header fields in the header area, that's
irrelevant to the rest of it, and a blank is still meaningful (it shows
precisely that there are 0 header fields).
So, by having the blank line even if there are no header fields, we're
being more informative to the user, and more faithful about what the
contents of the original message are (and the code will be simpler when we have …
=> ncrypt/crypt.c: Print a blank before the body area even if the header area is empty

mutt/base64.h, mutt/filter.h
Fix copyright boilerplate.
Pretty minor changes to comment sections so I think we are okay.
Didn't create one, but this is the result of [overhauling debian/copyright](https://salsa.debian.org/charles/neomutt/-/commit/1783df0406b252575a45f43200194e247f5e15dc) to include the updated copyright boilerplates.
=> mutt: fix copyright boilerplate in base64.h and filter.h

bcache/bcache.c, hcache/hcache.c, nntp/newsrc.c
The filename of a cache consists of two parts.
- A config variable + mailbox path
Config: `$header_cache`, `$message_cache_dir` or `$news_cache_dir`
For filesystem compatibility, the mailbox path is converted to ASCII and some characters, such as `:` are replaced with `_`
It's important that only the mailbox path is converted and the user's config is left as-is.
---
This also fixes a difference in behaviour between the header and body caches.
They'd write to different directories, e.g.
- `imaps:dev-mail@flatcap.org`
- `imaps_dev-mail_flatcap.org`
=> fix: cache naming

expando/format.c
Fix expandos to allow newlines `\n`.
Newlines were being treated as invalid and replaced with `?`s.
Some format strings, e.g. `$attribution_intro` need to allow `\n`.
e.g.
```sh
set attribution_intro = "On %d, %n wrote:\n"
```
Fixes: #4271
=> expando: allow newline

test/color/attr.c
`color_xterm256_to_24bit` is only available when `NEOMUTT_DIRECT_COLORS` is defined. This [fixes our macOS build](https://github.com/neomutt/neomutt/actions/runs/8827950283/).
=> guard truecolor function in tests

attach/mutt_attach.c, core/neomutt.c, core/neomutt.h, docs/manual.xml.head, maildir/message.c, main.c, mh/shared.c, mutt/file.c, mutt/file.h, send/sendlib.c, test/file/mutt_file_open.c
Adds a new option that allows for umask to be respected when attachments are saved, or when the attachments are viewed in an external program. Fixes #4148.
* **Does this PR meet the acceptance criteria?** Not yet, that's why I added a TODO list. I'm currently failing one of the tests, and probably righteously, since an assertion fails. Something is wrong with how I use the `NeoMutt` "global" variable.
#4148
=> Respect umask when saving attachments

mutt/list.c, mutt/list.h, mutt/slist.c, ncrypt/crypt.c, send/send.c, test/Makefile.autosetup, test/list/mutt_list_copy_tail.c, test/list/mutt_list_write.c, test/main.c
Protect more header fields.
```
--45wprh5a3u4z6yxp
Content-Type: text/plain; protected-headers=v1; charset=utf-8
Content-Disposition: inline
Content-Transfer-Encoding: quoted-printable
To: alx@kernel.es
Cc: foo@example.com
Subject: test protected to
MIME-Version: 1.0
asd
--=20
<https://www.alejandro-colomar.es/>
--45wprh5a3u4z6yxp
```
for that)
Not yet.
It works, partially.  It protects the headers when sending.  It doesn't …
=> Protect more header fields

docs/config.c, docs/manual.xml.head, ncrypt/config.c
-  This is a cherry-pick of commit 1 from <https://github.com/neomutt/neomutt/pull/4248> (at v1e):
```
$ git range-diff neomutt/devel/security gh/cphwrite gh/cphw_def 
1:  dc32b3b11 = 1:  dc32b3b11 $crypt_protected_headers_write: Change default to 'yes'
2:  6863989c6 < -:  --------- $crypt_protected_headers_write: Remove variable
```
=> $crypt_protected_headers_write: Change default to 'yes'

docs/config.c, ncrypt/config.c, ncrypt/crypt.c
- This is an alternative to <https://github.com/neomutt/neomutt/pull/4246>.
In this case, I opted by adding a variable instead of simply not weeding them.  This way, careless users (users that don't care, that is) will have their needs served.
Cc: @nabijaczleweli 
Cc: @flatcap 
-  This patch depends on <https://github.com/neomutt/neomutt/pull/4247>, so I'll keep it as a draft until that's merged.
=> Cryptoweed;  Add  `$crypt_protected_headers_weed`

ncrypt/crypt.c
This reverts commit 944e06904e8b3b088dbf58cc2f84bf7120af3539.
---
I thought I had tested that commit, but maybe I only tested the reading of the date field (generated with mutt(1)), and not the generation of it with neomutt(1)).  :|
Either that, or I broke it at some point.  But I tend to think that I forgot to test it properly.  Especially seeing that mutt(1) did a lot more work to get the date protected.  So, let's just not protect the date.  Anyway, the date of the PGP signature should be more useful than the date of the mail, and is simpler.
But it's weird, because I remember being surprised that it worked, since I was expecting it not to work.  Maybe I accidentally sent from mutt(1), and thought I had sent from neomutt(1), and that's why I thought it was working...
I only reverted …
=> Revert "ncrypt/crypt.c: Protect Date"

browser/complete.c, editor/enter.c, editor/functions.c, editor/state.c
This avoids an explicit size multiplication, which can overflow the calculation.
=> Use wmem*() functions with wide-character strings

ncrypt/crypt.c
Fixes: b423ebbfa9d2 ("Make the experimental branch the main trunk.")
Cc: @ossilator 
Cc: @gahr 
Cc: @flatcap 
Link: <https://github.com/neomutt/neomutt/pull/4294>
This was found thanks to the MUTT_MEM_REALLOC() macro, which caused a compiler error.
=> ncrypt/crypt.c: Fix allocation size calculation

auto.def
Specify which C standard we're using in CFLAGS.
=> Add -std to CFLAGS too

INSTALL.md, auto.def
Update NeoMutt's build requirements to C11.
- https://en.wikipedia.org/wiki/C11_(C_standard_revision)
This will allow us to use `_Generic(3)` in macros.
See also: #4294
=> build: require C11

alias/alias.c, browser/functions.c, commands.c, imap/imap.c, imap/lib.h, mutt_lua.c, muttlib.c, muttlib.h, nntp/newsrc.c, send/sendlib.c, test/pattern/dummy.c
This replaces the remaining uses of `mutt_expand_path()` with `buf_expand_path()` and removes the unused functions.
=> remove mutt_expand_path() and mutt_expand_path_regex()

conn/zstrm.c, send/sendlib.c
With this two fixes NeoMutt compiles for me with -Werror -Wdouble-promotion (`Apple clang version 15.0.0 (clang-1500.3.9.4)`).
=> fix -Wdouble-promotion warnings

history/history.c, imap/message.c, mutt/date.c, nntp/newsrc.c, nntp/nntp.c, pop/pop.c
`scanf()` returns values via pointers.
Ensure that all of them are initialised.
It seems to be the only difference between whether CodeQL warns us, or not.
=> scanf: initialise out-vars

hcache/hcache.c, hcache/lib.h, imap/imap.c, imap/mdata.c, imap/message.c, imap/private.h, imap/util.c, maildir/hcache.c, mh/mh.c, nntp/newsrc.c, notmuch/notmuch.c, pop/pop.c, store/bdb.c, store/gdbm.c, store/kc.c, store/lib.h, store/lmdb.c, store/qdbm.c, store/rocksdb.c, store/tc.c, store/tdb.c, test/store/bdb.c, test/store/common.c, test/store/gdbm.c, test/store/kc.c, test/store/lmdb.c, test/store/qdbm.c, test/store/rocksdb.c, test/store/tc.c, test/store/tdb.c
This enhances the header cache API so we can specify whether we want to create the cache file if it doesn't exist at `hcache_open` time. So far, I have only tried to come up with meaningful variations for IMAP. All other uses of the header cache always specify to create the file if it doesn't exist (current behaviour).
Fixes #4287
=> Allow opening the header cache in non-O_CREAT mode

hcache/hcache.c
This prevents us from trying to use the hcache later on, only to get a failure from the store.
Missed in #4312
=> Close the hcache handle on failure to open the store

conn/gnutls.c, conn/openssl.c
Currently it is not possible to authenticate to a SMTP server using a
client certificate only as neomutt prompts for an username if one is not
provided in the configuration file. This will fail if the server doesn't
support username authentication as seems to be common with servers
expecting a client certificate.
This patch changes the behaviour so that username is only used if it's
explicitly set before the operation is started (e. g. via the
configuration file).
I haven't been able to verify whether it is possible for a server to require
both an username and a client certificate - please let me know if you are - but
this (i. e. not being prompted for the username and having to set it
beforehand) seems to be at least better than not being able to use the …
=> conn: do not prompt for username with client certificate

attach/cid.c, compose/functions.c, email/body.c, email/body.h, email/parse.c, send/header.c
Fixes #4327
This moves `Content-ID` into its own dedicated place instead of reusing the container for `Content-Type` parameters, so we stop applying to it (`Content-ID`) what we should apply to them (`Content-Type` parameters), e.g., RF2231 splitting. See https://github.com/neomutt/neomutt/issues/4327#issuecomment-2165520188.
=> Dont' mix Content-ID with parameters

alias/complete.c, browser/complete.c, color/command2.h, complete/helpers.c, notmuch/complete.c, pattern/complete.c
This fixes the UB warning: `Call to function ... through pointer to incorrect function type`.
=> Fix function pointer types

timegm.c
This is just to mute clang being a bit overzealous:
`'&&' within '||' [-Werror,-Wlogical-op-parentheses]`
=> Fix '&&' within '||' warning

autocrypt/autocrypt.c, question/question.c
`mw_yesorno()` is used for asking the user a yes/no question and hopefully doesn't need to read macro events.
If we ignore them we can remove the flushing of the buffer from `mutt_autocrypt_init()` and with that fix #4316.
=> ignore macro events in mw_yesorno()

alias/lib.h
This declaration is useless: the function is only ever used within the same translation unit where it's defined.
See https://github.com/neomutt/neomutt/commit/f10c0f0dd82d97f88fe54efc1e9aad2c1066d407#commitcomment-143849983
=> Remove unused declaration

email/parse.c, mutt/date.c, mutt/prex.c, test/date/mutt_date_parse_date.c
While at it, extend PREX_RFC5322_DATE_LAX to accept full month names.
Fixes #4344
=> Check mutt_date_parse_date's return value

hdrline.c
Fixes #4335
See https://github.com/neomutt/neomutt/pull/4339#issuecomment-2202293925 for an explanation of what I think is going on here.
=> Fix '%z' and '%Z in '%{...}' expando

INSTALL.md
configure.autosetup was renamed to configure in 2017 (commit cf3e8ff3).
Fixes a mistake in the installation instructions.
for that)
Hopefully this won't affect any tests. I haven't checked.
* **What are the relevant issue …
=> Fix configure script name in INSTALL.md.

globals.c, globals.h
From git-bisect it looks like the last uses of it went away in commit a82d8d0f.
(Discovered while exploring the code.)
=> Remove unused global CurrentMenu.

maildir/message.c
Custom flags can make the suffix of a maildir filename longer than 16 characters.
This fixes the following bug:
1. Give a message in a maildir a lot of custom flags (making the suffix more than 16 characters long).
2. Change the flags with neomutt (e.g. flag the message).
3. Neomutt drops some of those custom flags.
A more specific example:
- Setup: using dovecot IMAP server with Maildir backend.
- Connect to dovecot and give a message a lot of IMAP keywords. As a result, its maildir filename will end with something like `:2,FSabcdefghijklmn`. NB: these keywords must be listed in the `dovecot-keywords` file; after the first 26 keywords dovecot gives up and stops trying to store them in the filename. [How dovecot stores IMAP keywords in a …
=> Allow longer maildir filename suffixes.

auto.def, mutt/file.h
It is guaranteed by ISO C11, which is the minimum C version we support.
=> Assume 'struct timespec' exists

browser/sort.c, mutt/string.c, mutt/string2.h, muttlib.c, muttlib.h, sidebar/sort.c, test/Makefile.autosetup, test/main.c, test/string/mutt_str_inbox_cmp.c
Fixes #4364
The bottom line is:
```c
return mutt_istr_equal(a + 1, "inbox") ? -1 :
mutt_istr_equal(b + 1, "inbox") ? 1 :
0;
```
vs.
```c
#define IS_INBOX(s) (mutt_istrn_equal(s, "inbox", 5) && !isalnum((s)[5]))
#define CMP_INBOX(a, b) (IS_INBOX(b) - IS_INBOX(a))
...
return CMP_INBOX(a + 1, b + 1);
```
so,
1. check both `a` and `b` in all cases: before, we weren't contemplating the possibility that both folders might be Inbox-ish
2. treat `Inbox.<Anything>` as `Inbox`
=> Fix sorting INBOX and its subfolders

core/mxapi.h, gui/global.c, index/dlg_index.c, maildir/mailbox.c, main.c, mbox/mbox.c, mutt_mailbox.c
This supersedes #4346.
Here's my current best understanding of the issue:
On startup, `main()` used the flags `MUTT_MAILBOX_CHECK_FORCE | MUTT_MAILBOX_CHECK_IMMEDIATE` in its call to `mutt_mailbox_check`. The flag `MUTT_MAILBOX_CHECK_FORCE` was checked only in two places, inconsistently:
1. in `mutt_mailbox_check`, to call `mutt_update_num_postponed()` https://github.com/neomutt/neomutt/blob/19653add8a9b372fd078aa98662b4d2c989445a7/mutt_mailbox.c#L174-L175
2. by the mbox backend, same as it used `MUTT_MAILBOX_CHECK_FORCE_STATS` https://github.com/neomutt/neomutt/blob/19653add8a9b372fd078aa98662b4d2c989445a7/mbox/mbox.c#L1691
The result is that main is forcing a stats check on mbox mailboxes, even though that was never the intention.
As correctly pointed out in #4346, in …
=> Don't force mbox stats calculations on startup

main.c
This used to be "mailx compatible send mode" and was removed in 93c6a5a.
=> remove leftover references to -x cli option

autocrypt/autocrypt.c, question/lib.h, question/question.c
This takes another stab at fixing #4316. The previous attempt (#4326) was to invasive.
We only disable the reading from the macro events buffer during the autocrypt initialization. This restores the original behavior (https://github.com/neomutt/neomutt/commit/3b2790cb5c808e71ed7978f54b4fbb15de77a289) from before it was slightly changed in https://github.com/neomutt/neomutt/pull/3998.
I added an additional wrapper `query_yesorno_ignore_macro()` to not change all callers of `query_yesorno()`.
=> ignore macro events during autocrypt initialization (fixes: #4316)

hcache/hcachever.sh, hcache/serialize.c
In #4327, I added a new member to Body and I forgot to add it to the hcache serialization.
The change in the Body structure should be enough to invalidate the current caches, but apparently it does not. I might try to figure out why later, but for now, let's bump the hcache version to force invalidation.
Fixes #4374
=> Fix serialization of Body.content_id, bump hcache base version

compose/functions.c, mutt_body.c
=> Make sure `mutt_body_copy` deep-copies `content_id`

expando/node_padding.c
Fixes #4377
There were actually two bugs here:
1. the first loop went on infinitely if `pad_len` is 0
2. the second loop incremented the `buf` pointer, probably a left-over of thinking that `buf` is a `char *` instead of a `struct Buffer`
=> Fix padding with an empty string

send/send.c, send/sendlib.c, send/sendlib.h
This will allow protecting the field cryptographically.  thunderbird(1) protects the Message-ID.  And neomutt(1) already protects the In-Reply-To and References headers, so this would be more consistent.
neomutt(1) was already capable of using a Message-ID generated earlier, if a user enabled `edit_headers` and manually generated the field, or if a template for the message contained the field.
Closes: <https://github.com/neomutt/neomutt/issues/4382>
Cc: @gahr 
Cc: @ossilator 
---
Revisions:
<details>
<summary>v2</summary>
-  Obvious typo fixes
```
$ git range-diff neomutt/main neomutt/alx/msgid alx/msgid 
1:  3000cd16d ! 1:  508f7a464 send/: Generate the Message-ID earlier
@@ send/send.c: static int edit_envelope(struct Envelope *en, SendFlags flags, stru
mutt_env_set_subject(en, …
```
=> send/: Generate the Message-ID earlier

pattern/exec.c
A reply-hook when replying to a message/rfc822 attachment gets evaluated without a Mailbox context.
This might limit the things we can match against (e.g., the message content), but should work fine for basis cases.
Fixes #4387
=> Handle a NULL mailbox while pattern matching

ncrypt/config.c
Fix a typo found during packaging this release for Debian.
=> ncrypt: fix typo in config.c

commands.c, mutt/path.c, test/path/mutt_path_to_absolute.c
According to POSIX, the output argument of `realpath(3)` is undefined on failure. The Linux man page agrees, but apparently if the failure is caused by EACCESS or ENOENT, the resolved path is still provided as output. This is also the behaviour on FreeBSD, which specifically says that on failure the path that caused the issue is left in the output.
Anyway, we should not rely on anything being in the output argument on failure, and we should leave the path argument alone.
Follow up of #4351.
=> Don't return the result of `realpath` on failure

hook.c
Fixes: #4258
(and fixes a memory leak)
**Test config**:
```
save-hook . +wrong
save-hook . +right
```
The second `save-hook` should overwrite the first, so `<save-message>` would show the prompt `+right`
---
When a duplicate pattern is found, the `hook->command` was being replaced, but **not** the `hook->expando`.
=> fix duplicate save-hook

editor/window.c
Fixes: #4385 
Ensure that a successful return code is propagated.
If the Message Window was refreshed (Ctrl-L), it could cause `mw_get_field()` to NOT return 0 on success.
=> browser: fix enter-quit-enter

mutt_config.c
Fixes: #4402 
The notmuch expandos `%Gx` have their own custom parser -- `parse_tags_transformed()`
This function lets `node_expando_parse()` do most of the work.
This is fine for plain expandos, e.g. `%GI`
However, conditional expandos work slightly differently.
They should be type `ENT_CONDBOOL` and use the render function `node_condbool_render()`.
This custom render function knows how to  bool-ify numbers and strings. 
---
I checked the following conditions to make sure there weren't any side-effects.
1. (numeric)             * (0)
1. (numeric)             * (n)
1. (conditional numeric) * (0)
1. (conditional numeric) * (n)
1. (string)              * (empty)
1. (string)              * (non-empty)
1. (conditional string)  * (empty)
1. (conditional string)  * (non-empty)
1. (conditional …
=> tags: fix conditionals

parse/set.c
Fixes: #4406
Be very explicit in the handling of deprecated config variables.
Print a warning and succeed immediately.
---
The crash in #4406 was caused by the Expando code trying to interpret the deprecation date as a `struct ExpandoDefinition`.
https://github.com/neomutt/neomutt/blob/3dec975cde8d46f0b0c4ad764f09674c24ee2a9a/mutt_config.c#L884
=> config: warn about deprecated variables

pager/ppanel.c
When the Pager receives a state change notification, force a repaint.
Fixes: #4361 
**Test steps**:
- `set pager_index_lines = 5`
- <kbd>\<enter\></kbd>, open an email
- <kbd>f</kbd>, forward the email
- Type an address
- <kbd>\<tab\></kbd><kbd>\<tab\></kbd>, Auto-completion to bring up the Alias Dialog
- <kbd>\<enter\></kbd>, select an address
**Expected result**:
- Screen is redrawn correctly:
1. Mini-index
2. Pager
3. Message window (with address)
=> pager: fix repaint

ncrypt/crypt.c
I've seen some messages sent with thunderbird(1) which protected the Message-ID field.  Let's read it if it's there.
Tested with an old mail I had in my mailbox:
```
...
[-- Begin signature information --]
Good signature from: Alejandro Colomar <alx@alejandro-colomar.es>
aka: Alejandro Colomar <alx@kernel.org>
aka: Alejandro Colomar Andres <alx.manpages@gmail.com>
created: Thu Dec 22 15:11:26 2022
[-- End signature information --]
[-- The following data is signed --]
From: Alejandro Colomar <alx.manpages@gmail.com>
To: Deri <deri@chuzzlewit.myzen.co.uk>
Subject: Re: The Linux Manpages Book - Happy Christmas
Message-ID: <e5567e8b-def9-288a-c0bb-32ab3d67e3ea@gmail.com>
References: <1842694.tdWV9SEqCh@pip>
In-Reply-To: <1842694.tdWV9SEqCh@pip>
[-- Attachment #1 --]
[-- Type: text/plain; …
```
=> ncrypt/crypt.c: Read the protected Message-ID

alias/dlg_alias.c, alias/functions.c, alias/gui.c, pattern/lib.h, pattern/pattern.c
Two minor upgrades:
**Query Dialog**:
Allow tagging aliases using <kbd>\<space\></kbd> as well as <kbd>t</kbd>
This brings it in line with the Alias dialog
**Alias/Query Dialogs**:
Add two functions: `<tag-pattern>` and `<untag-pattern>`.
This copies the behaviour of the Index dialog.
=> Alias/Query: Upgrade tagging

compose/cbar.c, compose/dlg_compose.c
Fix the repainting of the Compose Bar after adding/deleting an attachment.
Also fix a leak of an Observer.
**Tests**: Open the Compose Dialog, then
1. Attach a file, then cancel, `<attach-file>`, "main.c" <kbd>Ctrl-G</kbd>
Compose bar unchanged
1. Attach a file by name, `<attach-file>`, "main.c" <kbd>\<enter\></kbd>
Compose bar updated
1. Attach a file by dialog, then cancel, `<attach-file>`, <kbd>?</kbd>, <kbd>q</kbd>
Compose bar updated
1. Attach a file by dialog, `<attach-file>`, <kbd>?</kbd>, select file
Compose bar updated
1. Delete an attachment, `<detach-file>`
Compose bar updated
=> compose: fix redraw on attachment

autocrypt/db.c
`copy_normalize_addr()` creates a new `Address` for the result.
`mutt_addr_new()` doesn't create any `Buffer`s in the `Address` so create one manually.
Only `Address.mailbox` is needed.
=> autocrypt: fix copy_normalize_addr()

alias/dlg_query.c, envelope/functions.c, send/send.c
When editing a list of email addresses, the cursor starts at the end of the line.
Ensure that the line ends with ", " (comma, space) so that auto-completion is available immediately.
e.g. (`|` denotes the cursor)
```
Dave Smith <dave@orange.com>, |
```
When editing an Address List, the user is more likely to **add** Addresses than remove them.
With a trailing comma-space, they can immediately type a new Address, or hit `<complete>` to select from a dialog.
This already happens when using `<mail>` and auto-completion, but not elsewhere.
The PR adds this behaviour to query-completion and field editing in Compose.
---
**Tested**:
- `<mail>` + `<complete>` + cancel
- `<mail>` + `<complete>` + single
- `<mail>` + `<complete>` + multiple
- `<mail>` + "addr, " + `<complete>` + cancel
- `<mail>` …
=> Add trailing commas when editing addresses

attach/attachments.c, attach/attachments.h, hdrline.c, pattern/exec.c
I'd like to use the `mutt_count_body_parts()` in the compose window where I don't have a `Mailbox`.
=> remove unused mailbox param from mutt_count_body_parts

auto.def, mutt/memory.c
MacOS doesn't provide reallocarray(3).
Link: <https://github.com/neomutt/neomutt/pull/4294#issuecomment-2477224262>
Reported-by: @flatcap 
---
Revisions:
<details>
<summary>v1b</summary>
-  Add doxygen comments.
-  Fix position of brace.
```
$ git range-diff neomutt/main gh/alx/reallocarray alx/reallocarray 
1:  4dfc74175 ! 1:  cb5fd19b6 mutt/memory.c: Add my_reallocarray()
@@ mutt/memory.c
#include "exit.h"
#include "logging2.h"
++/**
++ * my_reallocarray - My reallocarray(3) implementation
++ * @param p     Address of memory block to resize
++ * @param n     Number of elements
++ * @param size  Size of element
++ *
++ * See reallocarray(3) for the documentation of this function.
++ * We need to implement it because MacOS is cruft from another century
++ * and doesn't have this …
```
=> mutt/memory.c: Add my_reallocarray()

compose/shared_data.h
Both `ComposeEnvelopeData` and `news` are unused.
=> remove unused fields from ComposeSharedData

gui/mutt_window.c, gui/mutt_window.h, test/Makefile.autosetup, test/gui/swap.c, test/main.c
This adds `mutt_window_swap()` to swap the location of two windows. 
I need this for https://github.com/neomutt/neomutt/pull/4437 but I figured we could add it separately.
Thanks to @flatcap for coming up with all the test cases. This version differs a bit from the initial one. 😏
=> add mutt_window_swap()

auto.def, docs/config.c, index/expando_index.c
Fix two small compilation issues on SmartOS, use of tm_gmtoff (not available) and index_t already defined in sys/types.h.
=> Smartos fixes

expando/format.c
"The glyph is a wide version of the glyph Space. Accordingly, its width in East Asian Text is fullwidth."
https://codepoints.net/U+3000?lang=en
Fixes #4460
=> Spaces can be wide

Makefile.autosetup, compose/attach.c, compose/config.c, compose/dlg_compose.c, compose/functions.c, compose/lib.h, compose/preview.c, compose/private.h, compose/shared_data.h, docs/config.c, docs/manual.xml.head, gui/mutt_window.h, gui/opcodes.h
This adds a message preview to the compose dialog. The preview is enabled by default but can be disabled with `compose_show_preview=false`. Two additional config variables control the behavior:
*   `compose_preview_min_rows`: The minimum number of rows that must be available for the message preview window to be shown.
*   `compose_preview_above_attachments`: Show the message preview above the attachments list. By default, it is shown below it.
If the message is larger than the number of available rows in the window, the content can be scrolled using:
* `preview-page-down` (default `<pagedown>`)
* `preview-page-up` (default `<pageup>`)
Example screenshot (with `compose_preview_above_attachments=true`):
Initially I wanted to add text wrapping to the window but I decided to skip that for the …
=> show message preview in compose view

compose/preview.c
As pointed out by Ismael on -devel: The attachments bar uses a different format than the preview bar. This adjusts the preview bar to match the attachments bar.
=> fix compose preview title

mutt/mbyte.c, mutt/mbyte.h
It is [possible](https://en.wikipedia.org/wiki/Byte_order_mark#cite_ref-5) for UTF-8 to have a BOM. We currently display it as a question mark.
=> Remove BOM from UTF-8 text

conn/gnutls.c
Fixes bug with wrong fingerprints been written to
certificate_file when using "Accept always" option.
The issue is that `fpbuf` has to be cleared before calling `tls_fingerprint` because `tls_fingerprint` uses `buf_add_printf` and only adds data to the buffer on every call.
Fixes the issue https://github.com/neomutt/neomutt/issues/4466
https://github.com/neomutt/neomutt/issues/4466
=> fix: Bug with wrong fingerprints in certificate_file

compose/functions.c, compose/preview.c
The preview renders the first "attachment" of the email which should be the actual message.
However when people mess with the order of attachments it could be that we end up with content that we can't render (binary files for example). To prevent that we limit the preview to attachments with `Content-Disposition: inline` and `Content-type: text/*`.
=> only show text inline attachments in the compose preview

mutt_thread.c
Reported by @ukleinek on IRC: `neomutt -p` crashes (assertion failure).
Tested on `main` (311dd98e9)
<details>
<summary>Backtrace</summary>
```
#0  0x000056353a15e8f2 in mutt_sort_subthreads (tctx=0x56353f4cb7a0, init=true) at ./mutt_thread.c:799
#1  mutt_sort_threads (tctx=<optimized out>, init=<optimized out>, init@entry=true) at ./mutt_thread.c:1270
#2  0x000056353a2550bc in mutt_sort_headers (mv=mv@entry=0x56353f4177e0, init=<optimized out>, init@entry=true) at email/sort.c:405
#3  0x000056353a15feeb in mview_update (mv=mv@entry=0x56353f4177e0) at ./mview.c:227
#4  0x000056353a16003a in mview_new (m=m@entry=0x56353f4b4620, parent=0x56353f3bd030) at ./mview.c:109
#5  0x000056353a198e90 in dlg_postponed (m=0x56353f4b4620) at postpone/dlg_postpone.c:215
#6  0x000056353a198858 in …
```
=> fix postponed sorting assertion failure

mutt_header.c
In 9c30730b04 an attempt was made to handle errors when i) reading the body, and ii) reading back the headers in edit_headers mode. I have no idea why, but the temporary file was left dangling in the filesystem. I think it's worth removing it.
=> edit_headers: cleanup temporary file on error

attach/mutt_attach.c
The `truncate()` here is a temporary measure.
Since all the `fopen()` calls were "upgraded" to `mutt_file_fopen()`, the write mode "w" hasn't truncated existing files correctly.
Fixes: #4469 
---
I need to analyse the 169 calls to the `mutt_file_fopen()` family of functions.
There are 72 **read-only** calls, which we can ignore, leaving 97 **read-write** calls to examine.
<details>
<summary>Mode: `a`</summary>
- Open for appending (writing at end of file).
- The file is created if it does not exist.
- The stream is positioned at the end of the file.
```
attach/mutt_attach.c:890:22:     `a`
attach/mutt_attach.c:1053:30:    `a`
attach/recvattach.c:507:62:      `a`
compmbox/compress.c:117:29:      `a`
conn/gnutls.c:576:26:            `a`
conn/openssl.c:962:28:           `a` …
```
=> fix: `save_attachment_open()` when overwriting

main.c
Bug reported on IRC by @RaitoBezarius
> I am seeing on 20241002 a heap-after-free reported by ASAN:
<details>
<summary>ASAN Report</summary>
```
READ of size 3 at 0x60200000fb10 thread T0
#0 0x7f61aa89223a in __interceptor_regexec.part.0
#1 0x8d8ab6 in mutt_regex_capture mutt/regex.c:603
#2 0x8da823 in mutt_regex_match mutt/regex.c:616
#3 0x45effd in mutt_folder_hook hook.c:644
#4 0x473b59 in main main.c:1406
#5 0x7f61a943127d in __libc_start_call_main
#6 0x7f61a9431338 in __libc_start_main_alias_1
#7 0x40e424 in _start
0x60200000fb10 is located 0 bytes inside of 10-byte region [0x60200000fb10,0x60200000fb1a)
freed by thread T0 here:
#0 0x7f61aa8dad18 in __interceptor_free.part.0
#1 0x8cecb5 in mutt_mem_free mutt/memory.c:76
#2 0x8dec9d in mutt_str_replace mutt/string.c:286
#3 0x4138a1 in …
```
=> fix crash in folder-hook

mutt_lua.c
Fix a faulty `Buffer `refactor.
When we pass a `Buffer` to the command parsing routines,
we need to `seek(0)` so that they start at the beginning of the string.
**Test NeoMutt config file**: `test.rc`
```
echo "hello"
```
**Test steps:**
- Build with Lua `--lua`
- Run command  `:lua mutt.call("source", "/tmp/foo.muttrc")`
**Expected Result**:
- Message window shows "hello"
=> lua: fix lua_mutt_call()

alias/alias.c, attach/mutt_attach.c, attach/mutt_attach.h, attach/recvattach.c, compmbox/compress.c, compose/functions.c, history/history.c, mutt/file.c, mutt/file.h, muttlib.c
Historically, mutt_file_fopen was trying to be smart when files were opening in write or read/write mode:
"When opening files for writing, make sure the file doesn't already exist to avoid race conditions."
We think this is over-zealous and just makes the code difficult. Here, I'm turning mutt_file_fopen into a simple wrapper around fopen + logging.
=> Simplify mutt_file_fopen

config/dump.c, config/dump.h, init.c, main.c
**post-release**
A couple of ideas to improve the config dump command line options.
- Don't "quote" enumerations -- they're keywords, not strings
- Use ANSI Escape sequences to link config to the web guide (terminal dependent)
You can see the config settings with `neomutt -D`, `neomutt -Q` or `:set` within NeoMutt.
Typically, we don't "quote" numbers or booleans.
This PR extends the non-quoting to enumerations, such as `$sort`.
These values are fixed **keywords** rather than freeform strings.
By leaving them unquoted, we can syntax highlight them as keywords.
This affects the following config:
- `$alias_sort` - alias, email, name, unsorted   
- `$browser_sort` - alpha, count, date, desc, size, new, unsorted 
- `$mbox_type` - mbox, MMDF, MH, Maildir 
- `$pgp_key_sort` - address, date, …
=> config dump refactoring

color/color.h, color/command.c, color/dump.c, color/quoted.c, color/quoted.h, color/regex.c, color/simple2.h, debug/notify.c, docs/manual.xml.head, docs/neomuttrc.man.head, pager/display.c, test/color/color_dump.c
**post-release**
- Unify the behaviour of quoted colours
- Unify the symbols for the compose colours
- Unify the behaviour of smart-case
Broadly, there are two types of colours: **Simple**, **Regex**.
**Simple Colours** are exactly _that_, simple.
They're a set of { attributes, foreground, background }.
Simple Colours are applied to a fixed object, e.g. Error Message.
If you set a Simple Colour a second time, it overwrites the old value.
**Regex Colours** are a set of Simple Colours, each paired with a Regex.
They're stored as a List and they're accumulative.
If you set a Regex Colour with a different Regex, it will be added to the list.
If you set a Regex Colour with an existing Regex, it will overwrite the original.
---
The Quoted Colours are an exception.
They have a Simple Colour and …
=> colour refactoring

init.c
Reported by sideshowbarker on IRC:
> `set real_name = ""` in the config file has no effect
> It's overridden by the user's real name from the system.
NeoMutt asks the system for the user's real name.
This is stored in `$real_name`.
Move this initialisation before the user's config is read, so that they can override the value.
---
**Test Steps**:
Config: **test.rc**
```
set real_name = ""
```
**run**:
`neomutt -n -F test.rc`
In NeoMutt, **test**:
`:set real_name`
**Expected Result**:
`set real_name = ""`
=> move real_name init

alias/dlg_alias.c, alias/dlg_query.c, alias/functions.c, alias/sort.c, autocrypt/dlg_autocrypt.c, browser/dlg_browser.c, expando/node_padding.c, maildir/mailbox.c, mh/mh.c, mutt/array.h, pattern/pattern.c, send/send.c, sidebar/functions.c, sidebar/sidebar.c, sidebar/window.c, test/array/mutt_array_api.c
`ARRAY_FOREACH_FROM_TO()` uses a loop variable, `ARRAY_FOREACH_IDX`.
If you compile with `-Wshadow` you get warnings if `ARRAY_FOREACH()` are nested.
(There aren't any examples in the code yet, but I'd like to be able to).
The problem can be worked around by manually creating a `for` loop.
The change works by replacing `ARRAY_FOREACH_IDX` with a new "templated" loop variable.
The variable is a macro concatenation of literal `idx_` and the `elem` param.
e.g.
```c
struct Object *obj = NULL;
ARRAY_FOREACH(obj, object_array)
{
printf("%ld\n", idx_obj);
}
```
**Note**: In a couple of the `FOREACH` macros, I've removed the `()` from the `elem` param, so that it can be concatenated.
One possible problem with the naming is that it's not immediately obvious where the variable comes from.
I've …
=> Allow nested ARRAY_FOREACH()

compose/preview.c, mutt/string.c, mutt/string2.h, test/Makefile.autosetup, test/main.c, test/string/mutt_str_expand_tabs.c
As reported in (#4534), the message preview in the compose window incorrectly rendered tabs (`\t`) as `?`.
The reason was that `mutt_paddstr()` replaces everything that is not `IsWPrint()` with `?`. To fix this we expand the tabs in each line before we measure the width and print it.
=> expand tabs to spaces in compose preview (fixes #4534)

mutt/signal.c, mutt/signal2.h, mutt_signal.c
The SEGV Handler may already have been set, e.g. by ASAN.
After NeoMutt has cleaned up, chain the old handler.
---
At startup ASAN sets an signal handler to catch SEGV.
NeoMutt sets its own handler to do cleanup, but this tramples over ASAN.
(NeoMutt's handler, resets the screen back to normal mode)
On startup, store the old value of the SEGV handler.
If NeoMutt crashes, cleanup then chain ASAN's handler.
---
To test:
- Build with ASAN enabled
- Edit the code and set a pointer to NULL
- Crash NeoMutt
Expected result: ASAN log file   
/cc @auouymous
=> debug: Chain old SEGV Handler

config/dump.c, config/set.c, init.c
The `:set` command without any arguments opens a pager showing all the config variables that have been set (changed from their defaults).
If the user runs **`neomutt -n -F /dev/null`**, this list **ought to be empty**.
Fix a few minor bugs in the code dealing with initial values:
- `dump_config()`
Make sure the quoting/escaping is the same for both value and initial value.
- `cs_register_variable()`
Temporarily disable the validator when setting the initial values.
The config options may be set in an order that the validator doesn't like.
- `mutt_init()`
Use an `Slist` to de-dupe the initial value of `$mailcap_path`.
- `mutt_init()`
Don't set `$alias_file` to `/dev/null` in response to `-F /dev/null`.
=> fix dumping of initial values

contrib/oauth2/README.md, contrib/oauth2/mutt_oauth2.py
In order to use oauth tokens for IMAP/POP/SMTP connections, one needs to wrap them in a way which depends on the method (bearer/xoauth2) and - possibly - the host and protocol. OAUTH2 aware clients typically know how to do that, but if you want to debug using a direct connection you need the wrapped token.
We compute the wrapped token anyways for --test, so offer to return it instead of the plain access token if --sasl <protocol> is given.
Submitted upstream as https://gitlab.com/muttmua/mutt/-/merge_requests/179 but we know the uptake in contrib there.
=> mutt_oauth2: offer to return SASL method and string

index/index.c
When the user changes $hide_thread_subject, refresh the thread tree.
=> fix refresh on toggle hide_thread_subject

mutt/buffer.c
If `Buffer.dptr` hasn't been set yet, then `buf_len(buf)` will return 0. This means that `buf_seek()` will also fail.
Instead, use `Buffer.dsize` as a guide to where we can seek to.
---
Fixes: #4548
This bug caused Autocrypt Peer Discovery to fail.
NeoMutt decoded the key, but then used a zero length when using the value.
=> buffer: fix seek

alias/dlg_query.c
Append a comma-space to the end of a <complete-query> match.
This behaviour matches the other locations where the user edits addresses.
**To test**:
- Start composing an email: `<mail>` (<kbd>m</kbd>)
- Enter a partial, but unique, address: `john smith`
- Auto-Complete, using `<complete-query>` (<kbd>Ctrl-T</kbd> by default)
**Expected**:
- Address is completed
- A comma and a space is appended
`John Smith <js@example.com>, `
=> add comma to single <complete-query> match

docs/manual.xml.head, docs/neomutt.man, main.c
Add a new command line sub-option `-D -D` or `-DD`
This simple addition to the command line only shows the **changed** config.
It can be used with the other dump options, e.g. `-O` (one-liner).
---
- Dump all config: `neomutt -D`
- Dump changed config: `neomutt -DD`
This is particularly effective when using zero config, or a simple test config, below:
- `neomutt -n -F /dev/null -DD`
Shows nothing
- `neomutt -n -F test.rc -DD`
Shows just the config frrom `test.rc`
(plus `$alias_file`, which is automatic)
**test.rc**
```sh
set assumed_charset = "ascii:utf-8"                        # slist
set attach_format = "attach"                               # expando
set attach_save_dir = "save-dir"                           # path
set editor = "nano"                                        # string …
```
=> CLI: `neomutt -DD` -- Dump Different

alias/dlg_alias.c, alias/dlg_query.c, attach/dlg_attach.c, autocrypt/dlg_autocrypt.c, browser/dlg_browser.c, compose/attach.c, compose/cbar.c, expando/filter.c, expando/filter.h, history/dlg_history.c, index/dlg_index.c, index/expando_index.c, index/status.c, ncrypt/dlg_gpgme.c, ncrypt/dlg_pgp.c, nntp/newsrc.c, pattern/dlg_pattern.c, send/send.c, send/sendmail.c, sidebar/window.c, test/expando/filter.c
`EnvList` is NeoMutt's copy of the global environment variables.
It lives in `globals.[ch]` (along with many other globals).
This PR changes `expando_filter()` and `filter_text()` to take `EnvList` as a parameter.
This reduces the dependencies of `libexpando` (by pushing the problem outwards).
Anyone have a better solution?
=> expando: move EnvList out of library

debug/pager.c, mutt/array.h, test/array/mutt_array_api.c
Add new ARRAY functions to iterate backwards.
- `ARRAY_FOREACH_REVERSE(elem, head)`
- `ARRAY_FOREACH_REVERSE_FROM(elem, head, from)`
- `ARRAY_FOREACH_REVERSE_TO(elem, head, to)`
- `ARRAY_FOREACH_REVERSE_FROM_TO(elem, head, from, to)`
I'd like to add these for my (so-far-mythical) Simple Pager.
---
The first commit adds functions and tests.
Unfortunately, they trigger a build warning:
```
warning: comparison of unsigned expression in ‘>= 0’ is always true [-Wtype-limits]
```
This comes from a test: `(ARRAY_FOREACH_IDX_##elem >= (to))` where `to` is 0.
`-Wtype-limits` is enabled by `-Wextra`.
---
The second commit changes a couple of types from `size_t` to `int`.
This works around the build warning.
=> array: foreach_reverse()

.cirrus.yml
The docs say FreeBSD is still at 14-1, but for some reasons the jobs fail. Let's see if 14-2 is there already.
See https://github.com/cirruslabs/cirrus-ci-docs/pull/1301
=> Use FreeBSD 14.2 in Cirrus CI

.cirrus.yml, .github/workflows/asan.yml, .github/workflows/build-and-test.yml, .github/workflows/coveralls.yml, .github/workflows/debug.yml, .github/workflows/fedora.yml, .github/workflows/macos.yml, Makefile.autosetup, cli/lib.h, cli/objects.c, cli/objects.h, cli/parse.c, globals.c, globals.h, main.c, test/Makefile.autosetup, test/cli/cli_parse.c, test/main.c, version.c
**WIP** -- Create a new library solely to parse the command line.
- bfd89eb52 libcli - parse the command line
- ec6f130bc test: libcli - test the command line
- a34d5f0e7 main: refactor command line parsing
The **current parser** has problems,
- It's buried deep within `main()`
- It uses lots of variables, which are lost amongst the others of `main()`
- It mixes parsing and acting
- It doesn't do the entire job -- some processing happens later
The **new parser** is:
- self-contained
- testable -- full coverage
- only a parser
NeoMutt has six distinct modes of operation (see [comment below](https://github.com/neomutt/neomutt/pull/4571#issuecomment-2652541997)).
Each of these has a separate `struct` for the results.
The parser works well, but its integration into `main()` is naive.
Now that …
=> libcli - parse the command line

.cirrus.yml, .github/workflows/asan.yml, .github/workflows/build-and-test.yml, .github/workflows/coveralls.yml, .github/workflows/debug.yml, .github/workflows/fedora.yml, .github/workflows/macos.yml, Makefile.autosetup, cli/objects.h, cli/parse.c, main.c, test/cli/cli_parse.c, usage.c
**WIP** -- Overview done; Still working on the sections
The "help" page is very dense and hard to understand.
**Changes**:
- Change `neomutt -h` to print a legible overview of options
- Create six sections of detailed help, with examples.
e.g. `neomutt -h config`
=> Split CLI Usage into sections

pager/dlg_pager.c, pager/pager.c
Eliminate some unnecessary file and screen activity.
---
The Pager functions were sending notifications to `priv->notify` (the correct place), but the Pager was observing `shared->notify`.
Fix the observer and remove a couple of lines from the Pager Event Loop that forced a display update every timeout.
=> pager: fix lost NT_PAGER notifications

contrib/oauth2/mutt_oauth2.py
There was an unused import in `contrib/oauth2/mutt_oauth2.py`, so I just removed it.
=> Remove unused import from mutt_oauth2.py

pager/dlg_pager.c, pager/functions.c, pager/pager.c
Fix `<top>` in the Pager.
The Pager wasn't refreshing itself after the `<top>` function.
This was exposed by b44c6760f.
**Steps**:
- Open a long email
- Page down a bit
- Hit `<top>` (<kbd>Home</kbd>)
**Expected**:
- Top of email is shown
=> pager: fix refresh on <top>

browser/functions.c
Change the behaviour of the browser to honour `<tag-prefix><select-entry>` when the cursor is on a directory.
The user's *intent* is to select, not descend into a directory.
**Steps**:
- Compose email
- Attach file (opening file browser)
- Select several files
- Position the cursor on a directory
- Press `<tag-prefix><select-entry>` (`;<enter>`)
**Old Behaviour**:
- NeoMutt descends into directory
**New Behaviour**:
- NeoMutt attaches selected files
This behaviour is also exhibited by Mutt.
=> browser: tag select rather than descend

alias/dlg_query.c
External address queries should be of the form:
name@example.com<tab>Real Name
Historically, (Neo)Mutt would accept email addresses that were wrapped in `<>`s.
This feature stopped working in 5d8a41679 alias: unify query parsing
---
**This PR restores the old (undocumented) behaviour.**
**Is this what we want?**
=> query: allow <>s around email addresses

main.c
If /var/spool/mail/USER is missing, continue to the GUI and display an error message.
Fixes: #4599 
---
If you supply an explicit Mailbox on the command line and it doesn't exist,
then display an error message on the command line and stop. 
This was the behaviour before 699657c main: refactor command line parsing
---
First make sure that `$MAIL` isn't set.
**Test cases**:
1. `/var/spool/mail/USER` exists
`neomutt -n -F /dev/null`
**Result**: NeoMutt TUI starts and opens the mailbox
1. `/var/spool/mail/USER` does **not** exist
`neomutt -n -F /dev/null`
**Result**: NeoMutt TUI starts and displays an error
1. Explicit Mailbox exists
`neomutt -n -F /dev/null -f ~/mail`
**Result**: NeoMutt TUI starts and opens the mailbox
1. Explicit Mailbox does **not** exist
`neomutt -n -F /dev/null -f …
=> main: don't stop if /var/spool/mail is missing

color/quoted.c
The quoted colour constants don't start at zero, so remember to subtract the base `MT_COLOR_QUOTED0`.
**Steps**:
- Create an email with multiple quoted levels, e.g. `> > > text`
- Config one colour: `color quoted0 brightgreen default`
**Broken Result**:
- Only the initial `> ` is coloured
**Expected Result**:
- Entire quoted line is coloured
---
Fixed bug introduced in 42d0c273a color: make quoted colours simple
Thanks :heart: to @charles2910 for the bug report and his help debugging.
=> color: fix quoted maths

copy.c
In #4546, I was a bit too aggressive and applied "weed" in more places than needed, namely to `Status` and `X-Status`. This was the cause of #4601.
However,  when `CH_UPDATE` is part of the `chflags`, we really want to persist the email, e.g., to sync an mbox, so we want to write all headers no matter what "weed" says. 
Fixes #4601
=> Don't consider "weed" when writing an email to file

imap/imap.c
When syncing an IMAP Mailbox, check that we have all we need.
Fixes: #4611
=> imap: check for incomplete Mailboxes on sync

data/account-command/gpg-json/credentials.sh
The gpg-json example doesn't spit out passwords in the format the account_command expects them, see
=> Fix gpg-json output

editor/window.c
Don't free the completion data until we're done with it.
Thanks to @jxlambda for finding, debugging and fixing this problem.
---
**Steps**:
- Open an IMAP folder
None of the emails in the folder should have labels
- `<edit-label>` (<kbd>Y</kbd>)
- Type a letter, then hit <kbd>\<Tab\></kbd> (`<complete>`) twice
**Expected**:
- No crash
- No change to text
=> fix label completion crash

.cirrus.yml, .github/workflows/build-and-test-freebsd.yml
The FreeBSD Cirrus jobs are currently failing due to a bug in the pkg manager which fails to correctly install xmlcatmgr before docbook-xsl. See https://github.com/freebsd/pkg/issues/2464. As a workaround, I'm explicitly installing xmlcatmgr before installing anything else.
=> Update FreeBSD CI and workaround `pkg` bug

bcache/bcache.c
The code was previously requiring `message_cache_dir` to exist *and* be a directory. We now only require that it is a directory *if* it exists. If it doesn't exist, we already take care of creating it at `mutt_bcache_put` time.
The check was introduced in #2661. @louis77, do you have an issue with the fix I propose?
Fixes #4583
=> Handle a non-existing message_cache_dir

mutt/logging.c, mutt/logging2.h
Fixes the build with `-Wignored-qualifiers`.
=> remove useless const qualifier from log_queue_get()

ncrypt/crypt.c
Cryptographically protect the Message-ID header field.
for that)
We still have pending some documentation for the entire set of crypto stuff.  It's still hidden as experimental, though, so we have time for that.
I did build neomutt from source, and tested sending myself some emails, one with message-id, and one without.  Both worked as expected. …
=> ncrypt/crypt.c: Protect Message-ID

mutt/ctype.c, mutt/ctype2.h
Change the return type of the ctype wrappers, to `bool`.
- `bool mutt_isalnum (int arg);`
- `bool mutt_isalpha (int arg);`
- `bool mutt_isdigit (int arg);`
- `bool mutt_ispunct (int arg);`
- `bool mutt_isspace (int arg);`
- `bool mutt_isxdigit(int arg);`
All the callers were using the functions in a `bool`-y way, so they didn't need to be changed.
=> convert the ctype wrappers to use bool

index/functions.c
After `<limit>`, send a notification so that the Index Bar (status) gets updated.
Fixes: #4664, #3662
**Test Steps**:
- Run NeoMutt with zero config:
`neomutt -n -F /dev/null -f /dev/null -e "set status_format=%V"`
- Apply a limit that matches zero emails: <kbd>l</kbd> <kbd>foo</kbd> <kbd>\<enter\></kbd>
**Expected Result**
- Index Bar shows the limit string 'foo'
----
Applying a limit normally causes an Index notification.
This isn't the case in two situations:
- The Index is empty
- One zero-matches limit is followed by another zero-matches limit
The fix is pretty simple: send a notification to simulate a change to the Index.
The fix isn't perfect for a couple of reasons:
- The Index Bar is independent of the Index.
We send a notification, but the Pattern code shows the "no matches" …
=> limit: force refresh of index bar
