pager.c
=> change pager to allow timehook-hook to fire

imap/auth_plain.c
=> Handle BAD as IMAP_AUTH_UNAVAIL

hcache-lmdb.c
Adopted from https://dev.mutt.org/hg/mutt/rev/fca7e504ab6a
Use mdb_txn_abort() to free up readonly/reset transactions, and avoid
leaking memory.
Use dprint, not fprintf, for debugging messages.
Remove strange blending of enum and bitfield logic for the txn_mode
state.
Closes #359
=> Import hcache-lmdb fixes from upstream

thread.c
@neomutt/reviewers Please review. :)
=> improve readability of find_subject()

pager.c
=> Unicode 0x202F is a non-break space too

doc/manual.xml.head
@neomutt/reviewers please review
=> doc: fix confusing description of notmuch operators

alias.c, browser.c, color.c, curs_main.c, hash.c, init.c, lib.c, mutt.h, mutt_sasl.c, mutt_tunnel.c, muttlib.c, pgppubring.c, protos.h, regex.c, smime.c
=> Do not cast return values from malloc (et similia)

pager.c
=> Advance by the correct number of position even for unknown characters

imap/util.c, init.c, parse.c
=> Fix latest Coverity issues

browser.c, buffy.c, compose.c, handler.c, imap/util.c, init.c, menu.c, mutt_notmuch.c, mutt_socket.c, mutt_ssl.c, mutt_ssl_gnutls.c, pager.c, query.c, recvattach.c, rfc1524.c, smime.c
=> Do not cast or check returns from safe_calloc

browser.c, compose.c
Closes #336 
@neomutt/reviewers Please review. This Works For Me (tm) but I'm not 100% confident that it doesn't fallout in some strange ways.
@P-EB I'd like to have your opinion on this, too.
=> Avoid browsing the remote spoolfile by setting MUTT_SELECT_MULTI attach

Makefile.am
=> Remove snprintf.c from EXTRA_DIST

alias.c, getdomain.c, group.c, hash.c, hash.h, headers.c, imap/message.c, init.c, mh.c, mutt_ssl.c, mx.c, newsrc.c, nntp.c, pop.c, thread.c
Merge the latest code changes from upstream (in preparation for mutt-1.8.0)
The translations will be handled separated.
@neomutt/reviewers Please Review.
=> merge: upstream fixes (mutt/default)

charset.c
this PR fixes just two minor style issues observed by [@gahr](https://github.com/neomutt/neomutt/pull/392#discussion_r102072729)
=> fix comment reflow

imap/imap.c
@neomutt/reviewers please review/merge.
=> imap: remove #if 1

doc/manual.xml.head
See: https://github.com/neomutt/neomutt/issues/361 @neomutt/reviewers please review
=> add blocking fmemopen bug on debian to manual

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
Followup PR to https://github.com/neomutt/neomutt/pull/312 - which i have accidentally closed.
@guyzmo @flatcap 
Maybe http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html is also worth to include into the PR tempalte?
=> github: added template for Pull Requests, issues and a CONTRIBUTION.md

.github/ISSUE_TEMPLATE.md
See: 
This fixes a small typo spotted by @gahr in [this commit](https://github.com/neomutt/neomutt/commit/8824bf52030edc60871ca8a91e47d228b159cf67#commitcomment-21082952). Sorry.
* Are there points in the code the reviewer needs to double check?
No.
* Why was this PR needed?
The ISSUE_TEMPLATE.md doesn't look very consistent at the moment.
* Screenshots (if relevant)
* Does this PR meet the acceptance criteria?
[doc/manual.xml.head](https://www.neomutt.org/guide/) for that)
* What are the relevant issue numbers?
#339
=> fix github issue template

handler.c
=> Get the correct buffer size under fmemopen/torify

lib.c
=> Fix inbox-first functionality when using mutt_pretty_mailbox

CONTRIBUTING.md, README.neomutt
@neomutt/reviewers Please review. (this PR touches only markdown files)
=> add note to be patient in IRC and elimante compiler warnings

configure.ac, crypt_gpgme.c, crypt_mod_pgp_gpgme.c
=> Don't fail if gpgme is neither installed nor requested

README.neomutt
Fix typo.
* Are there points in the code the reviewer needs to double check?
No.
* Does this PR meet the acceptance criteria?
Yes.
=> Fix typo in README.neomutt

Makefile.am, configure.ac, version.c
* **What does this PR do?** it makes the sidebar persistent in every compilation, as it doesn't rely on external libraries. 
* **Are there points in the code the reviewer needs to double check?** `configure.ac`, because i didn't knew where i should place the line to include `sidebar.o`.
* **Why was this PR needed?** This reduces the amount of builds we have to run for travis and coverity, which is desired because those services limit the amount of builds per week.
* **What are the relevant issue numbers?** #389
=> make sidebar persistent

main.c
Fixes #599
At startup, if Maildir (the `folder` setting) does not exists, mutt tries to create it. A pre-existing check skips this logic if Maildir is an IMAP URI. This PR extends this skip logic to NNTP URIs.
=> Do not try to create Maildir if it is an NNTP URI

.github/PULL_REQUEST_TEMPLATE.md
In a lot of PR's, either the question "Why is this PR needed" is removed
or answered very similar to "What does this PR do?". Therefore, i think
this can be removed.
=> github: simplify PR template

Makefile.am, README.md, po/da.po
Delete trailing whitespaces. Fix comment in `po/da.po`.
=> Fix trailing whitespaces

doc/manual.xml.head, init.c, init.h
allows the `source` command to take multiple arguments.
Issue #616
=> allow source command to load multiple files at once

CODE_OF_CONDUCT.md
=> CODE_OF_CONDUCT: remove jekyll code

doc/manual.xml.head
This is a follow up to #602, documenting the new
behavior.
@flatcap  @neomutt/reviewers
=> Update documentation for modify-labels-then-hide

configure.ac, curs_main.c, m4/gssapi.m4, mutt_sasl.h, resize.c
Signed-off-by: Thomas Klausner <wiz@NetBSD.org>
=> Handle native Solaris GSSAPI.

configure.ac
=> Fix the configure check for S-Lang

curs_main.c
=> No need to strdup the result of tigetstr

hcache/bdb.c, hcache/gdbm.c, hcache/hcache.c, hcache/hcache.h, hcache/kc.c, hcache/lmdb.c, hcache/qdbm.c, hcache/tc.c
=> Consistency check on hcache implementations' return codes

sendlib.c
=> Fix empty In-Reply-To generation

mutt_sasl.h
=> time_t requires time.h

mutt_notmuch.c
nm_normalize_uri re-builds notmuch queries, but `nm_uri_from_query` doesn't set `query_type` back again, so fix that.
Also, use the `NmQueryType` `enum` where possible instead of `int`.
Fixes #484.
=> mutt_notmuch: fix setting custom query_type in notmuch query

init.c
=> Do not pop from MuttrcStack what wasn't pushed

queue.h
=> Do not include sys/cdefs.h

ncrypt/crypt_gpgme.c
=> Remove spurious error message

recvattach.c
A recent upstream change stopped $digest_collapse from working.
The outer mime container wasn't being checked for type 'multipart/digest'.
A digest nested within another mime container should also be collapsed.
Fixes #789
=> fix: digest_collapse was broken

color.c, curs_main.c, menu.c, mutt_curses.h, pager.c
Continuous work on removing custom lists in favour of macros from queue.h
=> STAILQify struct ColorLine

color.c, curs_main.c, imap/imap.c, imap/util.c, menu.c, mutt_curses.h, mutt_socket.c, mutt_socket.h, pager.c
Continuous work on removing custom lists in favour of macros from queue.h
=> TAILQify struct Connection

auto.def
Issue #828
More background here: https://dev.mutt.org/trac/ticket/2303
=> Do not fail if deflate is not in libz

ncrypt/crypt_gpgme.c, ncrypt/pgpkey.c, ncrypt/smime.c
=> Prefer a helpful error message over a BEEP

auto.def
=> Allow enabling of fmemopen

auto.def
=> Allow to specify --docdir at configure time

doc/Makefile.autosetup
=> Generate neomuttrc even if configured with --disable-doc

Makefile.autosetup, auto.def
=> Let autosetup define PWD, do not unnecessarily try to create hcache dir

doc/manual.xml.head
Add some documentation about Notmuch and Imap Tags feature.
#861
=> imap/notmuch tags: Add some documentation

compose.c, lib/file.c, lib/file.h, rfc1524.c, rfc1524.h
Move stuff out of dedicated files into lib
=> Move mutt_rename_file to lib/file.[hc]

imap/imap.c
changes the imap mailbox flags logging to be more readable
no
#888
=> Issue 888: Fix imap mailbox flag logging

browser.c, imap/util.c, mutt_notmuch.c, newsrc.c, nntp.c, pop_lib.c, smtp.c, url.c, url.h
notmuch: remove custom UriTag linked list
url: make notmuch query string parser generic
=> url: make notmuch query string parser generic

init.c
=> Enhance ifdef feature to support my_ vars

url.c
=> Make sure Url is initialized even when u->scheme == U_UNKNOWN

conn/conn_globals.c, conn/conn_globals.h, globals.h
=>  Fix wrong extern declaration of globals in conn/conn_globals.h

auto.def
=> Respect --with-ssl path

hcache/hcachever.sh
=> Check that OpenSSL md5 supports -r before using it

init.c, sendlib.c
Currently, we support reading from /etc/mailname and /etc/mail/mailname.
Adding support for more files is trivial. Reading these files is only
done if NeoMutt was configured without the --with-domain option.
Issue #974
=> Support reading FQDN from mailname files

doc/neomutt.man, doc/neomuttrc.man.head, doc/neomuttrc.man.tail
renaming mutt-related things in the manpage to the corresponding neomutt things. (including website and mailinglist).
No.
=> man: "mutt" --> "neomutt"

sendlib.c
=> Context might be NULL - avoid dereferencing it

help.c
=> Fix line split logic in help

hcache/hcache.c, imap/auth_cram.c, mutt/md5.c, mutt/md5.h, pop_auth.c, test/Makefile.autosetup, test/main.c, test/md5.c
Simplify and reorder a bit the MD5 API. Add tests.
=> Enhance MD5 API, add tests

browser.c, functions.h, muttlib.c, opcodes.h, protos.h
This PR is an ongoing solution to #1028.
Part 2 is not yet completed. It will add a `<goto-parent>` function.
=> [browser] resolve dir on <change-dir> using realpath()

mutt/string.c
=> Fix out-of-bounds read in mutt_str_lws_len

auto.def
=> Allow choosing a particular version of BerkeleyDB via --with-bdb-version

autosetup/system.tcl
=> Update to latest autosetup

bcache.c, hcache/hcache.c, muttlib.c, newsrc.c
Issue #1073
Please double check and test - I have tested it with my configuration, but header cache is subtle.
=> Make sure paths created by header/body/news cache are POSIX-compliant

Makefile.autosetup, auto.def
=> Support —with-sysroot configure arg

README.md
Fixes a discrepancy between the website and this README on the topic of "is it a fork?".
No.
N/A
None.
[ci skip]
=> Clarify the relation between NeoMutt and Mutt

Makefile.autosetup, auto.def, doc/Makefile.autosetup, doc/neomutt.man, doc/neomuttrc.man.head
In case we want a simpler solution by which the dates in man pages is always consistent with the release date...
=>  Simplify generation of man date

doc/manual.xml.head, init.c, init.h, main.c
=> Let config file have precedence over environment

init.c
=> init.c: convert MyVars to use TAILQ

sendlib.c
=> Avoid trailing white space on header lines with no value

po/zh_CN.po
Update Chinese(Simplified) translate
for that)
- Added [doxygen code documentation](https://www.neomutt.org/dev/doxygen)
- Code follows the [style guide](https://www.neomutt.org/dev/coding-style)
Sorry, i just try it again
=> Update Chinese(Simplified) translate

imap/auth.c
=> Do not stop trying to log into an IMAP server at the first NO

curs_main.c
Hi @flatcap,
I push this for an easier review and just as a reminder for my patch
starting at neomutt-devel mailing list thread [1].
References:
[1] <http://mailman.neomutt.org/pipermail/neomutt-devel-neomutt.org/2018-March/000583.html>
=> Alternative OP_JUMP

po/zh_CN.po
Fix some Chinese (Simplified) translation.
@flatcap Should translation PRs be made on the translate branch?
for that)
* **What are the relevant issue …
=> Update zh_CN translation

attach.c, editmsg.c, mutt/file.c, mutt/file.h
I'm exploring solutions to #1165.  This introduces my proposals from that issue 
in mutt/file.c, and moves both attach.c and editmsg.c from mutt_mktemp to
mutt_file_mkstemp.
=> Partial solution to #1165

addrbook.c, alias.c, alias.h, globals.h, init.c, protos.h
Convert Aliases to use TAILQ
Fixes #1153.
=> Convert Aliases to use TAILQ

conn/sasl_plain.c, imap/auth_plain.c
=> Honour SASL-IR IMAP capability in SASL PLAIN

curs_main.c
=> Don't let info messages reset error messages' timeouts

po/ja.po
Adapted from translation of "Mail not sent." and "Mail sent.".
=> Update ja translation

resize.c
Splits up mutt_resize_screen() into its separate function to improve readability.
https://github.com/neomutt/neomutt/issues/1149
=> Refactor resize.c into separate functions.

bcache.c, mutt/address.c, mutt_notmuch.c, url.h
Arrgh! I deleted the old branch, and the pull request was closed automatically.
This is the continuation of #1259.
=> Fixes in style 

browser.h, hcache/hcache.c, mutt/address.h, mutt_menu.h
I don't know whether you plan to keep the bit fields at all. But if you do, they should be arranged so that they make sense.
=> Put bit fields together

doc/makedoc.c, init.c, init.h, mutt/file.c, mutt_lua.c, mutt_options.h
Allow variables such as alias_file to be relative and point to the correct locations
#1182
=> Allow variables that represent filenames to be relative

email/address.c, test/Makefile.autosetup, test/address.c, test/main.c
Remove static function variable from function.
Fixes #1150
=> Fix static addr mbox to udomain

test/address.c
Remove duplicated include from test/address.c
=> test/address.c: remove duplicated include

alias.c, email/email_globals.c, email/email_globals.h, email/parse.c, globals.h, group.c, hcache/hcache.c, hdrline.c, init.c, mutt/regex.c, mutt/regex3.h
This is my lastest version of the task,i do not want let it alone.
Signed-off-by: Bo YU <yuzibode@126.com>
Convert regexlist to use stailq
for that)
#1222
=> Easy task: convert-regexlist-stailq

po/de.po
Fix a translation error in the german translation.
for that)
=> Fix translation error in de.po

curs_main.c
make `<entire-thread>` work when not in a virtual folder
#1345
=> notmuch: reconstruct thread on-the-fly upon <entire-thread> w/o vfolder

flags.c, mailbox.c, mailbox.h, mbox/mbox.c, mx.c, nntp/nntp.c
=> move Context.new

imap/imap_private.h
This change removes a unused ImapAccountData attribute
=> Remove unused ImapAccountData->account

browser.c, context.h, flags.c, imap/imap.c, mailbox.h, maildir/mh.c, mbox/mbox.c, mx.c, nntp/nntp.c, postpone.c, sidebar.c, status.c
=> move Context.deleted

account.c, account.h
I just removed the API for two functions that were just called once and were supposed to be called one after the other.
=> Simplify account cleanup

browser.c, imap/imap.c
imap: Attempt to fix subscription issue.
=> imap: fix imap list subscribe

commands.c, mx.c
fix some msg_new update
This changes fixes some case where mailboxe->msg_unread is ++/-- without
changing mailbox->msg_new.
=> fix some msg_new update

browser.c
imap: ensure we can't delete the current selected mailbox
Closes #1417
=> imap: ensure we can't delete the current selected mailbox

browser.c, email/url.c, email/url.h, imap/browse.c, imap/imap.c, imap/util.c, mutt_account.c, mutt_account.h, nntp/newsrc.c, nntp/nntp.c, notmuch/mutt_notmuch.c, notmuch/nm_db.c, notmuch/notmuch_private.h, pop/pop.c, pop/pop_lib.c, smtp.c, test/Makefile.autosetup, test/main.c, test/url.c
Simplify (imho) the URL API so that memory is allocated by `url_parse` and released by `url_free`.
=> Simplify URLs API

imap/command.c, imap/imap.c, imap/imap_private.h, imap/message.c, imap/util.c
This moves all mailboxes related data to ImapMboxData.
=>  imap: move some ImapAccountData attributes to ImapMboxData

conn/ssl.c
=> ssl: don't shutdown broken connection

doc/manual.xml.head
Addition is based on issue https://github.com/neomutt/neomutt/issues/1353
* Added a single paragraph to the documentation of global hooks
* Should make it simpler for anyone with a similar issue.
* The basic task (disappearing temp files in attachments) has been solved already.
This is my first pull request here. I hope the contribution helps…
=> How to run shell commands in global-hooks

mutt/file.c, mutt/file.h, test/Makefile.autosetup, test/file.c, test/main.c
Adds a couple more convenient functions to read lines from a file.
This should help with addressing the review comments in #devel/extenal-search.
=> Add more convenient functions to map file lines

postpone.c
If the selected Mailbox is already the Postponed one, no need to open a
new context.
This change reuse the current context.
=> postpone: Don't reopen Postponed context

mailbox.c
=> Fix unsub from the selected mailbox by just hiding it

auto.def, ncrypt/crypt_gpgme.c
Merge in the lastest GPGME enhancements by Werner Koch.
=> Upstream gpgme

imap/command.c, imap/imap.c, imap/imap_private.h, imap/message.c, imap/util.c
imap: imap_expunge_mailbox should take Mailbox as argument
imap: always use mdata/adata getter
=> Pull request for devel/sileht-imap-cleanup

imap/imap.c, maildir/shared.c, mbox/mbox.c, mx.c, nntp/nntp.c, notmuch/mutt_notmuch.c, pop/pop.c
mx: share code between ac_find implementations
mx: Ensure mailbox is always added to Account->mailboxes
Fixes #1486
=> mx: ensure Mailbox is always added to Account->mailboxes

doc/manual.xml.head
Nothing fancy, just a small typo.
=> manual: Fix small typo

README.md
I thought it might help to have a pointer to the installation instructions in README.md.
=> +install instructions in README.md

browser.c, compress.c, config/bool.c, config/quad.c, flags.c, imap/command.c, imap/imap_private.h, imap/message.c, mutt/logging.c, muttlib.c, ncrypt/crypt_gpgme.c, ncrypt/pgp.c, ncrypt/pgpkey.c, ncrypt/pgppacket.c, pattern.c, score.c, send.c
A bunch of trivial fixes and a test of LGTM integration.
=> Trivial fixes

icommands.c, keymap.c, keymap.h
Implement the :bind and :macro command to the set of summary commands.
Issue #162
=> Implemented summary :bind/:macro commands

mutt/history.c
=> Disable all history operations if history is not enabled

browser.c, hdrline.c, mutt/date.c, mutt/date.h, mutt/logging.c, ncrypt/crypt.c, ncrypt/crypt_gpgme.c, ncrypt/pgpkey.c, nntp/nntp.c, pattern.c, sendlib.c
Provides a wrapper around common uses of localtime/gmtime
Fixes #1571
=> Encapsulate gmtime() and localtime()

po/zh_CN.po
Complete zh_CN translation on current master.
=> po/zh_CN: complete translation

globals.h, imap/imap.c, imap/imap_private.h, imap/message.c, imap/util.c, maildir/lib.h, maildir/maildir.c, maildir/shared.c, mx.h, nntp/newsrc.c, nntp/nntp.c, nntp/nntp_private.h, notmuch/mutt_notmuch.c, pop/pop.c
=> Make NotMuch hcache-aware

po/fi.po
I contacted the Finnish translator for Mutt and NeoMutt and he had finished the translations for NeoMutt, however he never merged them and uploaded them. I got the file from him, made the necessary merges, and fixed a few typos that I noticed. There are still 16 fuzzy translations left, but I'll leave it to either him or anyone else who is qualified to make those changes.
=> Update Finnish translation

color.c, curs_lib.c, doc/manual.xml.head, mutt_curses.h, mutt_window.c, mutt_window.h, ncrypt/smime.c
Please review the code.
Thanks.
Closes: #1181
=> Style Menu Options

index.c
=> Support group-chat-reply in the index

doc/manual.xml.head
Closes: #1668
Does the wording look OK?
=> docs: add note about line continuation

editmsg.c
=> Fix getting back to index after saving an edited message

browser.c
=> Fix nullptr dereference

index.c
=> Respect collapse_all after limit

color.c, curs_lib.c, handler.c, hook.c, mutt/file.c, mutt/file.h, mutt_attach.c, mutt_attach.h, mutt_body.c, muttlib.c, muttlib.h, ncrypt/pgpinvoke.c, ncrypt/smime.c, pattern.c, pattern.h, postpone.c, query.c, remailer.c, rfc1524.c, rfc1524.h, sendlib.c, test/Makefile.autosetup, test/file/main.c, test/file/mutt_buffer_file_expand_fmt_quote.c, test/file/mutt_buffer_quote_filename.c
Use `struct Buffer` rather than `char *` in lots more places.
These are fairly small, safe, changes.
=> Upstream Buffer changes

init.c, mx.c
=> Do not link in a new Account after a failed login 

email/rfc2047.c
glibc's implementation of the regex engine is a DFA which creates nodes on the fly under the regex_t object. This will cause leakes if we keep the compiled regular expression around, as it was the case before.
See also https://sourceware.org/bugzilla/show_bug.cgi?id=12567
=> Do not cache a compiled regex to avoid leaks

send.c
=> Fix list-reply regression introduced when converting Address to TAILQ

smtp.c
=> Fix segfault on bounce

po/ja.po
Modified some Japanese translation.
=> modified some Japanese translations

help/help.c, help/help.h
Modernize directory traversal with nftw() to replace readdir()
for that)
#1627
=> help: Modernize directory traversal with nftw()

imap/browse.c
=> Fix browsing an IMAP backend

ncrypt/pgpkey.c
=> Fix segfault in PGP key selection

smtp.c
=> Fix segfault in bounce

sendlib.c
This PR does two things:
* It changes the order of emission of headers to dump user headers (`my_hdr`) before hard-coded ones. This allows user headers to take precedence in case of unique headers (e.g., `Content-Type`, see #1792)
* It adds functionality to keep track of which user headers have been emitted, so unique headers emitted by user headers are not emitted again in the hard-coded path. This generalizes the ad-hoc machinery that was in place to keep track of the unique header User-Agent (see `has_agent` variable).
=> Prioritize my_hdr over default ones and keep track of unique headers

alias.c
This fixes two bugs when expanding aliases, of the form "alias1, alias1" in compose.
- only the first alias was expanded
- alias address was leaked
This bug was introduced when we converted the `Address` to use `TAILQ`.
---
The problem can be seen, and the fix tested, using the config file below.
Run:
- `./neomutt -n -f /dev/null -F alias.rc`
Then use <kbd>F1</kbd> .. <kbd>F10</kbd> to compose emails.
Each should result in fully-qualified addresses to `@example.com`, with zero duplicates.
**alias.rc**
```sh
set abort_unmodified = no
set editor           = cat
set postpone         = no
set record           = ""
alias person \
Adam Apple <apple@example.com>
alias people \
Barry Banana <banana@example.com>, \
Cat Cherry <cherry@exmaple.com>, \
Doug Damson <damson@example.com>
alias nested \ …
```
=> fix: alias expansion in compose

index.c, maildir/shared.c, mbox/mbox.c, notmuch/mutt_notmuch.c, progress.c, progress.h
=> Fix struct Progress ownership of its msg

autocrypt/autocrypt.c, conn/conn_raw.c, hcache/hcache.c, hcache/hcache.h, hcache/hcachever.sh, hcache/serialize.c, hcache/serialize.h, imap/util.c, maildir/shared.c, mutt/date.c, mutt/date.h, mutt_logging.c, notmuch/nm_db.c
Also, convert nanosleeps into usleep, which has a simpler API.
Edit: I haven't touched `progress.c`, which will come in #1822
=> Add mutt_date_epoch_ms API, convert gettimeofdays to use the new API

Makefile.autosetup, auto.def, contrib/Makefile.autosetup, doc/Makefile.autosetup, po/Makefile.autosetup, test/Makefile.autosetup
Alphabetizes and wraps lists in the files listed in issue #1835.
for that)
=> Release: Makefiles: Alphabetize and wrap

autocrypt/autocrypt.c, browser.c, conn/ssl_gnutls.c, email/parse.c, handler.c, hdrline.c, imap/command.c, imap/imap.c, imap/util.c, init.c, maildir/maildir.c, maildir/shared.c, mutt/date.c, mutt/date.h, mutt/file.c, mutt/logging.c, mutt_mailbox.c, mx.c, ncrypt/pgp.c, ncrypt/smime.c, nntp/nntp.c, notmuch/mutt_notmuch.c, pop/pop.c, progress.c, send.c, sendlib.c, test/date/mutt_date_add_timeout.c
=> Add mutt_date_epoch() API, use it instead of time()

curs_lib.c
Originally, `mutt_any_key_to_continue()` relied on `fflush(stdin)` to clear the input buffer, but that isn't portable.
This version changes the terminal settings, temporarily, so that it can read single characters without blocking, or line-buffering.
**To test**:
- Add an error to your `.neomuttrc`
- Start NeoMutt
- See error message and prompt: 'Press any key to continue...'
**Expected behaviour**:
- <kbd>q</kbd>  exits NeoMutt
**Actual behaviour**:
- <kbd>q</kbd><kbd>Enter</kbd> is required
=> fix: mutt_any_key_to_continue()

curs_lib.c, mutt/date.c, mutt_lua.c, mutt_thread.c
=> Fix some LGTM warnings

globals.h, init.c, mutt.h, mutt_parse.c, mutt_parse.h
=> Recurse into subparts when counting attachments

send.c
When replying to an email with `Reply-To` set that was sent by self, honour `Reply-To` over the `C_ReplySelf` setting. 
Thoughts?
=> Let reply_to take precedence over C_ReplySelf

mbox/mbox.c
If an mbox Mailbox doesn't have write privs, try opening it read-only.
---
Before the architectural changes, there could be multiple open Mailbox
objects representing a single folder.
By default a folder would be given a read-only Mailbox.  When the folder
needed to be written to, another Mailbox would be opened read-write.
This lead to synchronisation problems between the two Mailboxes.
=> fix read-only mbox

sendlib.c
I can only get lgtm to analyse this change if I create a PR :-)
=> lgtm: fix warning

conn/ssl.c
The code freed the ssl data using a local pointer.
This mean that Connection was left with a dangling pointer.
(and remove a couple of redundant lines)
=> fix: crash on failed ssl negotiation

index.c
This is a bit of a hack.
It fixes the immediate problem where a Mailbox pointer was being invalidated by some long chain of events.
Before we perform the `folder-hook`, we set up an observer on the Mailbox.
The observer's data is the Mailbox pointer.
**If** the Mailbox is closed, then the pointer is `NULL`'d.
If not, we remove the observer before its data goes out of scope.
=> NULL Mailbox pointer if it's deleted

hook.c
The account- and folder-hooks now log when they're triggered.
The two lines are logged at different levels:
- `LL_DEBUG1` for the hook match
- `LL_DEBUG2` for the command to be executed
As the command may contain private info, it's tempting to raise the level to `LL_DEBUG5`.
```
account-hook 'apple' matches 'imap://apple@example.com/'
set imap_user="apple"  imap_pass="AAAAAAAAAAAAAAAA"
```
```
folder-hook '.' matches 'imaps://example.com/neo.github'
exec collapse-all
```
=> hooks: add logging

curs_lib.c, enter.c, index.c, menu.c, mutt_window.c, mutt_window.h, pager.c
A couple of months back I did some refactoring of the gui code.
Of the 18 commits, I think this is the only problematic one.
@thomergil @protist @thecsw
Please can you give [[devel/release]](https://github.com/neomutt/neomutt/tree/devel/refresh) another try.
=> Revert the gui refactoring relating to clearing the screen.

mutt_mailbox.c
=> Do not check hidden mailboxes for new mail

conn/tunnel.c
=> Fix crash in tunnel's conn_close

doc/manual.xml.head
Fix some errors with the compile flags
=> Remove 'enable' from flags, fix sqlite3 flag

mx.c, notmuch/mutt_notmuch.c
=> fix: crash resizing notmuch mailbox

enriched.c
=> Avoid negative allocation

mutt_lua.c
Checks if the given variable in Lua maps to a DT_PATH type and if so,
expands the path to replace the "+" with the value of $folder
Closes: #2008
for that)
Not needed
Not sure. It works fine, locally for my own configuration
- Code follows the [style …
=> Fix setting of DT_MAILBOX type variables from Lua

imap/imap.c
hopefully fixes https://github.com/neomutt/neomutt/issues/2021
=> imap: empty cmdbuf before connecting

imap/imap.c
a band-aid solution; it's likely that some other IMAP states should
be restored on reconnection as well
hopefully fixes https://github.com/neomutt/neomutt/issues/1038
=> imap: select the mailbox on reconnect

index.c
=> Fix uncollapse_jump

index.c
Fixes #2030
@bremner please double check whether limiting this functionality to MH and MAILDIR makes sense.
=> Only try to perform entire-thread on maildir/mh mailboxes

mutt_thread.c
=> Do not recurse a non-threaded message

mx.c
=> Fix 'old append' trick in trash_append

index.c
To provide a consistent experience for those who want human-readable
names, set the 'vfolder-from-query' mailbox's name to the user's query.
The previous behavior for 'vfolder-from-query' delegated mailbox
creation to lower-level backend-agnostic code, which lacks the ability
to set a name. As such, 'vfolder-from-query' mailboxes displayed the
encoded notmuch URI when the user wanted a human readable name.
Since we know a Mailbox will be always created from a valid
'vfolder-from-query' execution, we can create it at a high-level and
pass it to the lower-level components, which obviates the need for the
lower-level component to create it.
Closes #2033
=> notmuch: use query as name for vfolder-from-query

CODEOWNERS
Create a CODEOWNERS file for setting the global code review group. The
CODEOWNERS file automates assigning reviewers for the pull request
process.
Syntax for CODEOWNERS is documented at:
https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners
=> improve: create CODEOWNERS file

conn/ssl.c
`RAND_status()` was added to OpenSSL 20 years ago.
https://github.com/openssl/openssl/blame/54a0d4ceb28d53f5b00a27fc5ca8ff8f0ddf9036/include/openssl/rand.h#L62
=> ssl: drop RAND_status() checks

imap/imap.c
The flag comparison code checks whether an IMAP server supports a given
flag. Because the check is run with substrings to be concatenated into a
final command to IMAP, the input flag to be checked can end with white
space, e.g., the function is called with "\\Seen " instead of "\\Seen".
I failed to notice this subtlety in ff57a18b and changed a
mutt_str_strncasecmp into a mutt_str_strcasecmp. This commit reverts the
change and makes it more explicit how we are comparing strings.
Fixes #2063
=> Fix IMAP flag comparison code

mx.c
The messages must both be copied into an EmailList **and** tagged,
because imap_exec_msgset works on tagged messages andignores the
EmailList.
Fixes #2081
=> Fix $move for IMAP mailboxes

test/date/mutt_date_localtime.c, test/date/mutt_date_localtime_format.c, test/date/mutt_date_make_imap.c, test/date/mutt_date_make_time.c
=> Make sure we use the correct timezone in tests

maildir/shared.c
https://github.com/neomutt/neomutt/issues/2103
=> maildir: sanitize filename before hashing

.cirrus.yml
I'd merge this and let Linux people add Linux to the matrix, if needed :)
=> Enable Cirrus CI for FreeBSD

hcache/gdbm.c
Just a very very small typo fix ;)
=> Fix typo in gdbm.c

.cirrus.yml, Makefile.autosetup, auto.def, doc/manual.xml.head, hcache/README.md, hcache/hcache.c, hcache/lib.h, hcache/tdb.c
TDB stands for "Trivial database" - most people may know it from samba ;-)
This backend is fast and gives good results together with the new compression functions.
=> Add new database backend to the header cache: TDB

command_parse.c
=> Handle variables inside backticks in sidebar_whitelist

email/email_globals.h, email/rfc2047.c, email/rfc2047.h, init.c, init.h, mutt/charset.c, mutt/charset.h, mutt_config.c, sendlib.c, sendlib.h, test/charset/mutt_ch_choose.c, test/rfc2047/rfc2047_encode.c
=> use SLIST for charsets

email/url.c, test/url/url_parse.c
Just some s/manual parsing/regex/ refactoring.
=> Use a regex instead of manual parsing to simplify parse_query_string

mutt/date.c, mutt/date.h, mutt/prex.c, mutt/prex.h, test/date/mutt_date_parse_date.c
Convert mutt_date_parse_date to use a regular expression for parsing.
=> Use a precompiled regular expression in mutt_date_parse_date

notmuch/mutt_notmuch.c
Fix: Using notmuch time window search updated query only for initial window and first change.
debug log https://pastebin.com/UThY2Yqk
for that)
=> Fix: notmuch time window search

browser.c
=> Only hide hidden mailboxes in Mailboxes view

.cirrus.yml
=> Stick to FreeBSD 12.1 in Cirrus

auto.def
=> build: tdb.h needs size_t, bring it in with stddef.h

mutt/prex.c, test/url/url_parse.c
=> Handle pretty much anything in a URL query part

maildir/maildir.c
=> maildir: handle deleted emails correctly

sidebar.c
Overhaul the sidebar indentation rules.
Fixes: #2272 
The diff isn't meaningful, so here's a summary.
Sidebar uses five config variables for indentation:
| Variable                | Description                                        |
| :---------------------- | :------------------------------------------------- |
| sidebar_short_path      | Abbreviate the paths using $folder                 |
| sidebar_folder_indent   | Indent nested folders                              |
| sidebar_delim_chars     | Characters that separate nested folders            |
| sidebar_component_depth | Strip leading path components from sidebar folders |
| sidebar_indent_string   | Indent nested folders using this string            |
1. Start with a Mailbox.
If it has a name, use that, goto step 4)
2. Is …
=> fix sidebar indentation

email/parse.c, test/url/url_check_scheme.c
Note that this will require a flush of the header cache.
Fixes #2320
=> Fix list-reply by correct parsing of List-Post headers

imap/imap.c
Fixes #2349
By using SLIST and friends we give up the possibility to treat a whole list
and a sub-chunk of the whole list as equal types. Because we now have a
dedicated "head" type for lists, 6edb2a71426f239dbbb0 had to change the pattern
```c
a = a->next;
```
into
```c
SLIST_REMOVE_HEAD(a, entries);
```
The two are different in that the second actually changes `a` for the
caller.
The fix here is to make a copy of the original list. It is hackish, but
I don't see a better way right now.
=> Don't mess with the original pattern when running IMAP searches

Makefile.autosetup, compress/compress_private.h, compress/lib.h, compress/lz4.c, compress/zlib.c, compress/zstd.c, init.c, init.h, mutt_config.c, test/Makefile.autosetup, test/compress/common.c, test/compress/common.h, test/compress/lz4.c, test/compress/zlib.c, test/compress/zstd.c, test/main.c
Add tests for lz4, zlib and zstd compression.
=> test: add compression tests

hcache/hcache.c
=> hcache: fix keylen not being considered when building the full key

mx.c
Fixes #2379
I'm totally not convinced this is the best way to approach it :/
See https://github.com/neomutt/neomutt/issues/2379#issuecomment-647482328 for the reasons.
=> Use the URL structure to compare the current mailbox with C_Spoolfile

index.c
Work around the case where a `folder-hook` performs `unmailboxes *`.
Recreate the Mailbox that the user is trying to open.
Fixes: #2382 
This isn't ideal, but the code is still much cleaner than `main_change_folder()` that came before.
=> re-open Mailbox after folder-hook

context.c, context.h, index.c, pager.c
=> Teach link-thread to link all tagged emails

command_parse.c, sidebar.c, sidebar.h
This allows renaming an existing mailbox.
=> Allow renaming existing mailboxes

sidebar.c
There are two issues with the current implementation of the sidebar
drawing algorithm in presence of named-mailboxes:
1. The `%B` expando shows an abbreviated mailbox name. This causes
`named-mailboxes "My Inbox @ server.com" +Inbox` to be abbreviated as
`com` (possibly indented).
2. The `%D` expando shows an unindented mailbox name. This causes
`named-mailboxes "My subfolder" +Inbox.Lists.Neomutt-devel` to be
displayed more to the left wrt its siblings.
This commit modifies the sidebar rendering algorithm as follows.
1. The `%B` expando always shows the mailbox path
2. The `%D` expando shows the mailbox name for named-mailboxes and the
mailbox path for regular ones.
3. Indentation is always applied.
4. Abbreviation is only ever applied to paths.
=> Fix sidebar abbreviation / indentation for named-mailboxes

docs/config.c
Update RFC2047-related documentation with the things that I'd looked for but didn't find. May be useful for others communicating with Outlook users in a.d. 2020
#2539
=> Add RFC2047 =?utf-8 example and the fact that Outlook makes it

index.c, menu.c, mutt_menu.h, pattern/lib.h, pattern/pattern.c, postpone.c
Implements index-style searching in postpone menu
#2428
=> Allow index-style searching in postpone menu

commands.c
=> Fix logic in checking an empty From address

gui/mutt_curses.c
This was broken by 2f9087322269a11adde76468a6b6f22de56667ba.
Fixes #2561
=> Fix setting attributes with S-Lang

address/address.c, address/address.h, test/address/mutt_addrlist_parse.c
=> Fix handling of empty address groups

imap/util.c
=> Use our own string APIs

help.c, icommands.c, keymap.c, keymap.h
Converts Keymaps and its functions to use STAILQ structures instead of being a simple array of linked lists.
Issue #1179
=> Convert Keymaps to use STAILQ

command_parse.c
Fixes #2575
@flatcap I am not too familiar with how windows are organized or notifications are sent. Please double check if this makes sense.
=> Do not assume that the sidebar window is a sibling of the current window

compmbox/compress.c, imap/imap.c, maildir/lib.h, maildir/maildir.c, maildir/mh.c, mbox/mbox.c, mx.c, mx.h
=> Make sure edata is not used by a backend of a different type

command_parse.c
Made changes to `parse_setenv()` in `command_parse.c` so that `:setenv VAR?` queries for environment variable `VAR`.
[2604](https://github.com/neomutt/neomutt/issues/2604)
=> `:setenv ENV_NAME?` now queries for `ENV_NAME` variable, like `:set`

Makefile.autosetup, alias/dlgalias.c, alias/dlgquery.c, alias/gui.c, alias/gui.h, browser.c, browser.h, copy.c, imap/browse.c, imap/command.c, imap/imap.c, imap/lib.h, imap/message.c, imap/msn.c, imap/msn.h, imap/private.h, imap/util.c, menu.c, mutt_menu.h, send/sendmail.c, test/array/mutt_array_api.c
This adds a macro-based linear array API, similar in spirit to the stuff in `mutt/queue.h`, and converts some manually-managed arrays to the new API.
=> Implement ARRAY API

compose.c
Allows displaying customer headers under a "Headers: " prompt in the compose screen
Appearance with no custom headers (unchanged):
```
From: 
To: 
Cc:
Bcc:
Subject: 
Reply-To:
Fcc: 
```
Appearance with a single custom header:
```
From:
To:
Cc:
Bcc:
Subject:
Reply-To:
Fcc:
Headers: X-First-Header: 1
```
Appearance with five custom headers:
```
From:
To:
Cc:
Bcc:
Subject:
Reply-To:
Fcc:
Headers: X-First-Header: 1
X-Second-Header: 2
X-Third-Header: 3
X-Fouth-Header: 4
X-Fifth-Header: 5
```
Appearance with more than 5 custom headers:
```
From:
To:
Cc:
Bcc:
Subject:
Reply-To:
Fcc:
Headers: X-First-Header: 1
X-Second-Header: 2
X-Third-Header: 3
X-Fouth-Header: 4
...
```
- Documentation …
=> Display custom headers in compose

index.c
Fixes #2631
**DO NOT MERGE** - I want to investigate a bit further.
=> Make sure all mail gets applied the index limit

alias/commands.c
=> Prevent half-parsing an alias

alias/commands.c, config/string.c, docs/manual.xml.head, docs/neomuttrc.man.head, test/config/string.c
implements string_string_plus_equals()
for that)
#243, #202 ?
=> implement string_string_plus_equals()

context.c, context.h
Moves a function from API to static space.
=> Make ctx_update_tables private

hcache/hcachever.sh
Tidy the `hcachever.sh` build script.
The output is unchanged.
- Replace ` `` `s with `$()`
- Tidy `while`, `if`, `case` layout
- Quote variables to prevent globbing
- Add `-r` to `read`
~One check has been disabled: SC2181.~
~It allows us to check `$?` separately from the command.~
~https://github.com/koalaman/shellcheck/wiki/SC2181~
=> build: run shellcheck on hcachever.sh

alias/dlgalias.c, alias/dlgquery.c, alias/gui.c, alias/gui.h, functions.c, pattern/lib.h, pattern/pattern.c
The purpose of this PR is to present a working and complete `<limit>` function in the Alias/Query menus.
The final version of the PR will take everything into account regarding Documentation, Formatting, etc.
#2621
=> Add <limit> function to Alias/Query dialogs

auto.def
=> Build with SASL and SSL when configuring with --everything

compmbox/compress.c, imap/imap.c, imap/message.c, maildir/maildir.c, maildir/mh.c, maildir/shared.c, mbox/mbox.c, mx.c, mx.h, nntp/nntp.c, notmuch/notmuch.c, pop/pop.c
Implements #2665 
For some of the functions I've added the guard all the backends were doing anyhow at the api call site so that we can enforce a stricter contract.
=> Add a Contract to the Mailbox API

alias/alias.c, alias/config.c, alias/dlgalias.c, alias/dlgquery.c, alias/gui.c, alias/gui.h, alias/lib.h, alias/sort.c, enter.c, index.c, pager.c
This PR eliminates Alias configuration global variables.
#2621
=> Remove Address Book Global Variables

browser.c, browser.h, config/sort2.h, core/mailbox.c, core/mailbox.h, docs/config.c, mutt_config.c, sidebar/config.c, sidebar/sort.c, test/config/dump.c, test/config/helpers.c, test/config/sort.c
=> Respect "unsorted" order for mailboxes

send/smtp.c
This is used for example by Outlook.com.
=> Implement SMTP LOGIN auth mech

index.c
Fixes #2679
Disclaimer: I am unsure of the potential fallout :)
=> Do not implicitly unlimit emails

docs/manual.xml.head, docs/neomuttrc.head
=> Adjust doc to explicitely mention $count_alternative

po/sk.po
Please review the translation. 
Please forgive me mistakes, there are surely many of them. I'm not native speaker. But this should improve sk translation from 49 % to 100 %.
=> Update sk_SK translations

browser.c, command_parse.c, gui/color.c, index.c, main.c, menu.c, monitor.c, pager.c, pattern/compile.c, pattern/pattern.c, send/sendlib.c, sidebar/window.c, sort.c, test/pattern/dummy.c
* Refactor (Context && Context->mailbox) to ctx_mailbox(Context)
* Resolves #2762
=> Refactor: use ctx_mailbox(Context)

conn/getdomain.c, conn/lib.h
=> asan: fix leaking addrinfo for non-canonical domain names

imap/message.c
If it fails, force a redownload without qresync, to set the uid_seqset
to a correct state.
Note the headers should almost all be in the header cache, so this
isn't a huge penalty, but ensures no duplicates occur (the most common
issue if something goes wrong).
Upstream-commit: https://gitlab.com/muttmua/mutt/commit/1598baa2ffd1a62053fea10bf2550d6cfbd91694
https://gist.github.com/flatcap/9d701d2ec21057dd77c6f685c56647c6#file-0012-add-a-sanity-check-for-qresync-patch
=>  Add a sanity check for qresync

sidebar/config.c, sidebar/functions.c, sidebar/observer.c, sidebar/private.h, sidebar/sidebar.c, sidebar/window.c
* **What does this PR do?***
Fixes #2819.
=> Removed C_* config definitions

notmuch/notmuch.c
The 'nm_record' functionality doesn't work in non-notmuch mailboxes
because 'nm_record_message()' requires notmuch-specific account data.
Other mailbox types lack the data so 'nm_record_message()' fails.
NeoMutt's documentation does not limit this functionality to notmuch
mailboxes.
To improve behavior consistency and user experience, modify
'nm_record_message()' to access a default notmuch mailbox.
When a user sends an email from a non-notmuch mailbox, the notmuch
backend uses the default mailbox for database access to append the
message.
The backend does not FREE the default mailbox for two reasons:
1) The user may define it in their configuration.
2) For future calls to prevent repeated allocations/deallocations.
The code contains inline warnings repeating the above rationale for …
=> notmuch: allow nm_record in non-notmuch mailboxes

pager.c
Add a commend explaining macro use
=> pager: add comment about macros

pager.c
CHECK_ATTACH macro was obscuring the execution flow by hiding break
keyword;
New function that replaces the macro is better named and does not
obscure the flow;
=>  pager: remove CHECK_ATTACH macro

pager.c
* 
Kills an evil CHECK_MODE macro
=> pager: replace CHECK_MODE macro

pager.c
=> pager: Contex2 removal

Makefile.autosetup, auto.def
=> Use the tail of --libdir

pager.c
Minor readability and type improvements
=> pager: check_sig minor improvements

context.c, core/mailbox.c, core/mailbox.h, index/index.c
=> Handle email deletion using a two-phase GC mechanism

docs/Makefile.autosetup
=> Skip installing empty manual.txt if lynx/w3m/elinks is not available

postpone.c
=> Fix crash in failure to decrypt a postponed message

auto.def
=> Refuse to build without pcre2 when the pcre2-posix library is linked in

gui/color.c, gui/color.h, gui/curs_lib.c, gui/mutt_curses.c, index/index.c, init.c, main.c, menu.c, mutt_globals.h, pager/pager.c, progress.c, sidebar/window.c
=> Get rid of the Colors global variable

email/email.c, gui/curs_lib.c, index/shared_data.c, mutt_attach.c, pager/pbar.c
=> [devel/refactor] fix attach crash

index/index.c
=> Escape message-ids in search macros generated with <mark-message>

po/el.po
=> el.po: started improving Greek translations

imap/message.c
No idea how we get there, but it's best not to crash
=> Handle emails without edata

postpone.c
This a botch introduced in 87b38b55f.
Fixes #2959
=> Fix cleanup logic after resuming a draft

pattern/exec.c, pattern/lib.h
=> Don't try to use an invalid message in mutt_pattern_exec

send/send.c
=> Kill GreetingInfo (refactor)

copy.c, maildir/maildir.c, maildir/mh.c
Fixes #3040
I introduced this bug in #2908.
=> Do not attempt to copy from a FILE* onto itself

mbox/mbox.c
=> Only try to open non-readonly mailboxes in read/write mode

docs/neomuttrc.man.head
Fixes the formatting errors in the neomuttrc man page. There are problems with both formatting and the table size.
#3131
=> Fix broken formatting and split tables to avoid formatting and length man errors

alias/alias.c, attach/mutt_attach.c, copy.c, email/parse.c, handler.c, mbox/mbox.c, mutt/file.c, mutt/file.h, ncrypt/crypt.c, ncrypt/crypt_gpgme.c, ncrypt/pgp.c, ncrypt/pgpmicalg.c, ncrypt/pgppacket.c, ncrypt/smime.c, nntp/nntp.c, pager/display.c, pattern/exec.c, postpone.c, send/send.c, send/sendlib.c
Make it simpler to seek and handle its results.
=> Expose mutt_file_seek API

docs/config.c
=> Explain how timezones and bangs work inside %{}, %[], and %()

docs/config.c
=> Document changed default for ssl_force_tls

pattern/compile.c
Fixes: #3184
Test config:
```
color index red default "~v~(~N)~(~F)"
```
=> pattern: fix leak

Makefile.autosetup, auto.def, keymap.c, main.c, mutt/string.c, mutt/string2.h, muttlib.c, mx.c, ncrypt/crypt_gpgme.c, nntp/nntp.c, pattern/exec.c, po/POTFILES.in, rfc3676.c, test/parse/mutt_parse_mailto.c, timegm.c
* Add support compiling under Solaris 10
Add compatibility functions and use existing wrappers to get neomutt running under Solaris 10.
=> Support compiling under Solaris 10

Makefile.autosetup, gui/global.c, gui/global.h, gui/lib.h, po/POTFILES.in
**Update**: scaled back to just:
- e754f5249 global: add functions dispatcher
---
---
- fbfa75824 window: add function dispatcher
- 65f6a435d global: add functions dispatcher
- f932f309e window: attach global,sidebar dispatchers
- 0d54c13b2 convert functions to use window dispatcher
For the abstract tree (to the right), imagine starting at **Node 7**.
We start with a recursive search of the children, from there, looking for a handler for our op.
If that fails, we climb the tree to **Node 1** and repeat the search.
We ignore nodes that we've already searched.
**State**: Pager is focused
**Event**: `OP_SIDEBAR_NEXT`
Search starts at the Pager Window
Continue until the function is handled,
or until we've tried all the windows.
- Pager's dispatcher has no match
- Pager has no children
- Climb …
=> Create global functions dispatcher

color/command.c, color/regex.c, color/simple.c, index/dlg_index.c, index/index.c, sidebar/functions.c
- 66210c3f7 color: fix index list updates
- 5ea8a51d0 color: fix regex_colors_parse_uncolor() retval
- 0589bca25 color: fix duplicate notification
- aa916f739 color: fix priority order of index colours
- 9c3ad5af8 color: fully-populate EventColor
- 5890611a5 sidebar: fix \<sidebar-toggle-visible\>
Fixes: #3262
=> Fix a handful of small GUI problems

docs/config.c, docs/manual.xml.head
=> docs: Improve description of some notmuch variables.

pattern/compile.c, test/Makefile.autosetup, test/main.c, test/pattern/leak.c
=> Plug a leak in mutt_pattern_comp

imap/message.c
I don't know why this happens, but let's be on the safe side
=> Make sure we have enough memory for a new email

index/functions.c
Refactor all the resolve code (advancing the cursor after a function).
- 8623759f1 create resolve_email()
- 29a43813b index: refactor resolve
This reduces the code duplication and gives us a central point to send notifications.
=> Index: refactor resolve

attach/mutt_attach.c, handler.c, mutt/state.h, options.h
Trade a new flag into State.flags for OptViewAttach
=> Kill global and Propagate display attach status through State

index/index.c
After checking for new mail the Mailbox size may be different,
so update the Menu's size and force a repaint of the Index.
Before this fix, the Index's size wasn't updated, so the user couldn't navigate to the new mail.
Fixes: #3375 
---
**Steps**:
- Open mailbox
- Open pager
- Wait for new mail in the current folder
- Message: "New mail in this folder"
- Status bar updated
- Sidebar updated
- Hit `<tab>` (`<next-new-then-unread>`)
**Results**
- Focus is moved to the new mail
- Pager displays the new mail
=> index: fix menu size on new mail

mbox/mbox.c
Running <sync-mailbox> when use_threads=reverse caused duplicate emails.
When you sync a mailbox, the backend, in this case `mbox_mbox_sync()`,
sorts the mailbox into its original order before writing it to disk.
The fix, is to ensure that both `$use_threads` and `$sort` are reset before sorting.
Fixes: #3374 
---
**Steps**:
- Create an mbox file with a few emails in it
- Open the mailbox `neomutt -n -F /dev/null -f MBOX -e 'set use_threads = reverse'`
- Flag some emails as new
- Quit NeoMutt
- Re-run NeoMutt
**Results**:
- Mailbox has the same number of emails as before
- The emails that were marked new are still new
=> mbox: fix sync duplicates

send/config.c
Add a check that $sendmail does not contain any shell metacharacters before using it.
The manual entry states that $sendmail is a "program and arguments" but people can mistake this and think that it can be an arbitrary shell command. The presence of shell metacharacters indicates that the user is attempting something that won't work. The existing result is whatever error message comes out of the program in $sendmail. This patch makes neomutt give the user a higher-level error message that indicates the cause of the problem, rather than running a command that won't work, and hoping they figure it out for themselves.
- Documentation created/updated
No documentation needed to be updated.
There is a new error message, and I've added …
=> Add error when $sendmail has shell metachars

main.c
=> Fix debug_file ignored #3394

email/rfc2047.c
=> Fix a leak on failure to decode a RFC2047 header

contrib/oauth2/mutt_oauth2.py
Makes `mutt_oauth2.py` store / fetch client ID and secret into / from token file.
for that)
This tries to fix #3477
=> Store client_{id,secret} in token file #3477

contrib/oauth2/mutt_oauth2.py.README
Updates docs for changes made in 7decc96c7ccabae4cb940927665783fe6ba81761
This should have been added then, I just noticed they were missed.
=> mutt_oauth2.py: Update usage docs

auto.def
=> Make it easier to account for different Berkeley DB names

mutt/prex.c, mutt/prex.h, test/from/is_from.c
=> Acces mbox From lines with a timezone offset

mutt/buffer.c, test/string/mutt_str_next_word.c
See https://reviews.llvm.org/D67122
=> Offsetting a NULL, even by 0, is UB

color/command.c
=> Restore special handling of status color

hcache/hcache.c
This might be related to #3546
=> Make sure we close compress operations on a failure path

bcache/bcache.c, browser/browser.c, complete/complete.c, maildir/maildir.c, maildir/mh.c, mutt/file.c, mutt/file.h, nntp/newsrc.c
=> Try to create cur/new on access

docs/config.c
Document the history mechanism a little more thorough.  There seems to be no dedicated place to talk about how the history works, so I added two paragraphs to `$history`.
=> Document the history mechanism a little more

docs/manual.xml.head, store/kc.c, store/lib.h, store/qdbm.c, store/tc.c
=> Update Homepage URLs of QDBM, Tokyo Cabinet, Kyoto Cabinet 

docs/manual.xml.head, docs/neomuttrc.man.head
* Document the subscribe-to and unsubscribe-from commands for IMAP
* Document the subscription feature of IMAP and how NeoMutt uses it
* Document that NeoMutt can speak NNTP / interact with newsgroups
Closes: #3654
=> Document the subscribe-to and unsubscribe-from commands

copy.c, recvcmd.c, send/send.c
While tracking down the usage sides of $date_format (cf #3718), I also fixed the issue #3716.
Closes: #3716
=> Let $indent_string, $post_indent_string respect $attribution_locale

docs/config.c
$resolve not only applies to messages but also to attachments and potentially others.
=> Document $resolve a little more

postpone/dlg_postpone.c
The Postponed Email list is almost identical to the Index, so we can colour it in the same way.
Fixes: #3704 
---
To test:
- Postpone some emails
- Set some index colours (below)
- Open postponed emails `<recall-message>` (<kbd>R</kbd>)
```
color index         blue    yellow
color index_author  red     green
color index_subject magenta cyan
```
=> colour postponed email

init.c
Allows querying `$my_var` via `neomutt -Q my_var`
It's not optimal that the output format for the `my_var` case has a different code path than built-in ones, so we must remember to keep this and the syntax for built-in variables coherent.
Fixes: #3731
=> Allow querying user-defined variables ($my_var) via -Q

send/sendlib.c
Implement the $message_id_format config variable which lets the user specify a template for the Message-ID header.  This functionality is already present in Mutt [0].
The patches try to mimic these commits though the last four are combined into a single commit as they are are essentially bugfixes to the first commit.
Mutt seems to be base64 focused while NeoMutt is base32 focused.  To be faithful to the Mutt expandos these preserve their base64 meaning.  However, we also introduce the `%R` expando (which mutt does not have) which expands to base32 encoded random bytes.
Mutt has also a completely different default Message-ID format.  This is also mimicked in this patch set as the `%z` expando.
However, the default of $message_id_format is NeoMutts old message-id …
=> Use random string as Message-ID

docs/manual.xml.head
Documents the command unbind which was only mentioned in a note.
=> Document command unbind

mutt_lua.c
Fix a mistake introduced in aa279814ad.
Fixes: #3784
=> lua: fix command registration

imap/message.c
=> Chase warning, tidy code

address/address.c
This avoids repeated strchr() calls; on platforms with 64-bit shifts (including all 64-bit platforms), it makes for very cheap testing.
Speeds up opening a large Maildir by about 1.5%.
for that)
* **What are the relevant issue …
=> address: use bitmasks to detect special characters

po/nb_NO.po
=> trans: update nb_NO

mutt/charset.c
A caching layer for iconv conversion descriptors was introduced in https://github.com/neomutt/neomutt/pull/3816.
There are two issues, which are both triggered when `iconv_open` returns an invalid conversion descriptor (e.g., because iconv doesn't understand the charsets being passed).
1. descriptors are [cached without checking their validity](https://github.com/sesse/neomutt/blob/27cf28e8b6f16af7a011e646cc3e88a53d6185e3/mutt/charset.c#L638-L664).  A subsequent use of an invalid cached descriptor will [trigger a reset](https://github.com/sesse/neomutt/blob/27cf28e8b6f16af7a011e646cc3e88a53d6185e3/mutt/charset.c#L616), which is needed for valid descriptor, but which causes a crash on invalid ones.
2. the code assumes that [an invalid descriptor is a descriptor not found in the …
=> Fix crash with the iconv cache

docs/manual.xml.head
Touches up a couple typos in the Feature pages.
=> manual: Feature page typos

imap/imap.c
=> Do not sort an empty mailbox

po/pt_BR.po
Improve and fix some typos in pt_BR translation file.
Not applicable.
for that)
Not applicable.
=> trans: improve and fix typos in pt_BR translation

index/functions.c
=> Select the first email when coming from an empty limit

pattern/exec.c
This is a mitigation for #3828.
=> Read body in bigger chunks

color/command.c
Prefixes "bright", "alert", "light" can also be applied to `colorNNN` colours.
=> color: fix handling of bright

color/command.c
Allow the prefixes 'alert', 'bright', 'light' not only for named colours (like "red") but also for colorNNN, e.g. color123.  This restores backwards compatibility with Mutt.
Also move parsing of '#RRGGBB' colors to the front, so named colours and colorNNN, which both allow prefixes, are grouped together.
This should fix #3855.
=> color: Allow 'alert', 'bright', 'light' prefix for colorNNN

test/convert/mutt_convert_file_to.c
=> Fix tests to respect iconv's return value

conn/gnutls.c
=> fix "certificate saved" message

imap/command.c
=> Truncate large UIDVALIDITYs to support non-conforming IMAP servers

enter/functions.c
See https://mailman.neomutt.org/pipermail/neomutt-users-neomutt.org/2023-June/001298.html
=> Treat complete-query as complete where it makes sense

index/dlg_index.c, index/functions.c, index/lib.h, mx.c, mx.h
This makes changing `MxOps.path_canon()` (https://github.com/neomutt/neomutt/discussions/3902) easier.
=> mx_path_canon() and change_folder_string() take a Buffer

hdrline.c, hdrline.h, help.c
Add explanation of message flags to the help screen of index.
=> help: Add message flags.

hdrline.c, hdrline.h, help.c
An enum for `$to_chars` to sort out  constanst.
=> hdrline: Add enum for $to_chars.

alias/dlg_alias.c, alias/lib.h, browser/dlg_browser.c, browser/lib.h, complete/complete.c, complete/helpers.c, complete/lib.h, enter/functions.c, enter/wdata.h, enter/window.c, imap/imap.c, imap/lib.h, imap/private.h, imap/util.c, mutt/buffer.c, mutt/buffer.h, mutt/mbyte.c, mutt/mbyte.h, nntp/complete.c, nntp/lib.h, test/Makefile.autosetup, test/common.c, test/enter/editor_case_word.c, test/main.c, test/mbyte/buf_mb_wcstombs.c
Converts the autocompletion functions to use struct Buffer's
See: #3899
=> Buffer convert: autocomplete

address/idna.c, gui/curs_lib.c, init.c, send/send.c
This replaces a couple more `sprintf()`s with `mutt_str_asprintf()`.
=> change sprintf() to mutt_str_asprintf() where possible

index/shared_data.c
=> bring IndexSharedData notifications back

browser/config.c, browser/dlg_browser.c, browser/sort.c, docs/config.c
Closes: #3948
partition-alpha:
=> Add bool browser_sort_dirs_first, always putting directories first

.gitignore
`asan.*` - Address Sanitizer log files
`.env`- direnv configuration file (https://github.com/direnv/direnv)
=> tweak .gitignore

Makefile.autosetup, config/lib.h, convert/content_info.c, core/config_cache.c, core/config_cache.h, core/lib.h, imap/utf7.c, test/Makefile.autosetup, test/core/config_cache.c, test/main.c
See this discussion: https://github.com/neomutt/neomutt/discussions/3968
=> move config/cache to core library

conn/openssl.c
If a signal interrupts an SSL read/write continue if possible.
Fixes: #4014
=> openssl: continue on signal

pager/functions.c
When showing an information screen, such as `:set`, `:bind`, etc
allow the user to save the text to a file using <kbd>s</kbd> (`<save-message>`).
---
**Updates**:
- Fix auto-completion
- Abort on empty filename
=> pager: add save function

mutt/memory.h
Code simplification in regards to `CLAMP` definition.
=> simplify CLAMP by expressing it with MIN/MAX

po/es.po
Completed not translated strings, and changed fuzzy messages!
for that)
=> Spanish translation finished, fuzzy words and changed

browser/functions.c, color/command.c, complete/helpers.c, config/dump.c, config/set.c, handler.c, hcache/hcache.c, key/dump.c, main.c, parse/set.c
This should be slightly better because we do less small allocations by reusing the buffers.
=> switch some buffers to use the buffer pool

compose/functions.c
I'm not sure when they disappeared, but...
Restore `<view-mailcap>`, `<view-pager>` and `<view-text>` to the Compose Dialog. 
**test.rc**
```
macro compose <f5> "<view-attach><enter-command>echo view-attach<enter>"
macro compose <f6> "<view-mailcap><enter-command>echo view-mailcap<enter>"
macro compose <f7> "<view-pager><enter-command>echo view-pager<enter>"
macro compose <f8> "<view-text><enter-command>echo view-text<enter>"
```
<kbd>\<f5\></kbd> performs the "standard" behaviour that <kbd>\<enter\></kbd> does.
=> compose: restore view-text/pager/mailcap

.github/unused.sh, .github/workflows/xunused.yml
As discussed here: https://github.com/neomutt/neomutt/discussions/4118
Sample job run: https://github.com/neomutt/neomutt/actions/runs/7223904797/job/19683982035?pr=4122
=> add github action to check for unused functions (xunused)

.github/unused.sh, conn/socket.c, conn/socket.h
Also add `mutt_str_upper()` and `log_multiline_full()` to the unused ignore list for now.
=> remove unused function mutt_socket_write()

docs/manual.xml.head, docs/neomutt.man
Fixes: b8f48720478c ("docs: -C: Document new flag")
Fixes: f11baccf09d3 ("docs: -C: Add feature page")
Cc: @flatcap
=> docs: -C: Fix some accidents

.cirrus.yml
This fixes the recent build failures.
=> use FreeBSD 14.0 in Cirrus CI

expando/config_type.c
Implement `+=` for the Expando config type.
Before the recent Expando changes, the format strings, e.g. `$index_format`, were represented as strings.
The Config string type supports `+=`
This PR adds `expando_string_plus_equals()` so that Expandos can `+=` too.
Fixes: #4209
=> config: implement expando plus-equals

mutt_mailbox.c
This was introduced in 10ab30cece451122d1c30a344d89eb2baeae5071.
=> Fix "New mail in..." messages

.github/workflows/macos.yml
This allows us to enable more features in the macOS build.
=> use homebrew in macOS build

autosetup/jimsh0.c
This updates the bundled jim from 0.78 to 0.82
=> Update autosetup (bundled jim)

docs/config.c, docs/manual.xml.head, ncrypt/config.c, ncrypt/crypt_gpgme.c
Show a block of information about the encryption of a message, which includes the recipients that can decrypt the message.
This info isn't necessarily complete: the sender could hide some recipients, so that they are able to decrypt the message, but aren't listed.  See gpg(1) options --recipient and --hidden-recipient.  I'm not sure, but I suspect a malicious sender could also add fake recipients, which are listed, but cannot really decrypt the message.
Therefore, this should be taken only as an informative block, and with a pinch of salt.
Closes: <https://github.com/neomutt/neomutt/issues/4163>
Cc: @flatcap
Cc: @dd9jn
Show encryption information about a message.
Unencrypted mail:
```
Message-ID: <ZgU0xhvp82jUPsy1@debian>
[-- …
```
=> ncrypt/crypt_gpgme.c: Show encryption information

mutt/memory.c
=> free(NULL) is valid C; it's a no-op

po/es.po
Spanish translation now finished 
for that)
=> Spanish translation finished

auto.def
=> Support BerkeleyDB 18.1

pattern/exec.c
=> Let ~Y match each tag individually

.cirrus.yml
=> Use FreeBSD 14.1 in Cirrus CI

docs/manual.xml.head
This PR changes documentation for `unmacro` command
#4431
=> fix unmacro docs

notmuch/notmuch.c
In notmuch, there can be multiple files with the same `Message-Id`.
e.g. Email addressed to two different addresses that you own.
If they arrive at different times notmuch will give NeoMutt the name of the newer file.
If NeoMutt has already parsed the file into `Email`/`Envelope`/`Body`, then the arrival of the second Email will invalidate this.
When we detect a change of filename, reparse the file to be sure.
**Note:** The `Message-Id` is cached in a `HashTable`, so that must be preserved.
Fixes: #4474
=> notmuch: refresh the Email if the filename changes

compmbox/compress.c, core/mxapi.h, editmsg.c, external.c, maildir/mailbox.c, mbox/mbox.c, mh/mh.c, mx.c
See https://github.com/neomutt/neomutt/issues/4541#issuecomment-2586418290 and subsequent comments.
Fixes #4541
=> Remove MUTT_NEWFOLDER, fix appending to mbox

copy.c
=> Respect Ignore when modifying an email's headers

auto.def
While at it, alphasort the deprecated options
=> Deprecate some configure options that aren't used anymore

notmuch/notmuch.c
Try to cope if a message disappears.
---
Fixes: #4594 
This fixes a problem introduced by f5d55b4b7f which was a fix for #4474 
The fix is crude but I don't understand the situation that causes the problem.
=> notmuch: check for parse failure

help.c
Fix memory leaks from <help>.
**Steps**:
- Build NeoMutt with ASAN
- Open NeoMutt
- Hit <kbd>h</kbd> (`<help>`)
- Quit Help and NeoMutt
**Expected**:
- No leaks :-)
=> help: fix leaks

auto.def
=> Check for DocBook XSL

.github/workflows/build-and-test-freebsd.yml, .github/workflows/build-and-test.yml
Use https://github.com/vmactions/freebsd-vm/ to build & test on FreeBSD
=> Build and test on FreeBSD

test/pattern/dummy.c
=> Update types in test dummy code
